"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated Kimi-K3 AttnRes programs.
# ``MODULES``: one record per generated program (role, translation units
# relative to this package's ``csrc``, compile flags, FFI entry, argument plan,
# closure identity, CTA size, and the architectures the one source is compiled
# for).  ``KERNELS``: per architecture, the logical kernel key the host planner
# resolves (``cake_backend.plan_route(...).kernel_key``) -> module name.  Both
# literals are populated verbatim by the generated-program export; do not edit
# by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_attn_res_028503fd0961d55b7765": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_028503fd0961d55b7765_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_028503fd0961d55b7765_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "e0011b044847d344061ee6d12175b2ac69949ce24a26a57bacab8cc195e61e66",
    },
    "cake_kimi_k3_attn_res_03bedd980b7a2200bf61": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_03bedd980b7a2200bf61_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_03bedd980b7a2200bf61_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "320e6f8d46acd0495d22163b87955ba559756abdee175d4e2bc96e0d367d3258",
    },
    "cake_kimi_k3_attn_res_04179092271f793576fd": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_04179092271f793576fd_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_04179092271f793576fd_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "c1e6022b4d5d8974008a33de32554390db985acac8e45b372358082462a0389a",
    },
    "cake_kimi_k3_attn_res_05f4833fcaebced8982a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_05f4833fcaebced8982a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_05f4833fcaebced8982a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "4b413c90b28f60be9f5aa5a9d49611cdf47fb4cca46ea540ca5dea1891a142e2",
    },
    "cake_kimi_k3_attn_res_06a4152cb4621c4b09f2": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a4152cb4621c4b09f2_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a4152cb4621c4b09f2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "8c3fdb6b18f55662b209c388a6fe53170580ac5da46a076cfc8236fe3498a169",
    },
    "cake_kimi_k3_attn_res_1fbd16a1745563095baf": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1fbd16a1745563095baf_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1fbd16a1745563095baf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "dffd9a2ba55ffae614338e6f084d07d82799069dc587beeecc93929a9a8ad297",
    },
    "cake_kimi_k3_attn_res_291d118f0d9137e82482": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "7d8e46398e1d05e079091c3991d20c4b7670b803c618d871d46b2dc6ccdb3568",
    },
    "cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "3259e9170d830458c2f27d4e4216ecb62ad6a45c35a4c6272adc1d23c47f79e1",
    },
    "cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "0f4f69ae4401fb4463296c5632fbf0aae72d98ecea40d0e1db2ebae86ba9ce04",
    },
    "cake_kimi_k3_attn_res_32f85df97de777defe91": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "a4893aa2404b064dae6a36a5faffbd2cd9a85429a23108f6bde9ba0b06011679",
    },
    "cake_kimi_k3_attn_res_34163a739700379987b9": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_34163a739700379987b9_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_34163a739700379987b9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "94dfe145aacc495e26e643af5766f750e53db50e7aa7bf2a5eab09e9b50a631f",
    },
    "cake_kimi_k3_attn_res_3899a43dd652e8333bce": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3899a43dd652e8333bce_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3899a43dd652e8333bce_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b93d330bd9e62706f5b68661ccd0d8f3469d888d0fc6fd70a15c3b61f15888c9",
    },
    "cake_kimi_k3_attn_res_39bea7db7ae295dced4f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_39bea7db7ae295dced4f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_39bea7db7ae295dced4f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "f0ae1194711119e80083b9982aa14226585f3fa76531de899f0a12d06f74549c",
    },
    "cake_kimi_k3_attn_res_42db4f4b8216ab6fcd8f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_42db4f4b8216ab6fcd8f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_42db4f4b8216ab6fcd8f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "a073b257972a5f6a09bbae61c82da993f94375cff036dd92dfd11e696bda94b5",
    },
    "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "output_norm_weight"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ec4c7934704b939ce55706c7ac94d709f80bb2810ce6a84deff005f28b3e6fe3",
    },
    "cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "43698c564cadd1eb07f91d232a5d39e43acdef3d9b7505f83f5b0fe94f61f056",
    },
    "cake_kimi_k3_attn_res_50393c0dec14fafed1ab": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_50393c0dec14fafed1ab_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_50393c0dec14fafed1ab_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "0247de8842ae94ccd518812235325afd3239e032def54bdf45ef35c911fb0b10",
    },
    "cake_kimi_k3_attn_res_5935d32598c8940b29b6": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5935d32598c8940b29b6_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5935d32598c8940b29b6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "d289138e49fbbf204a26fc57ab83980c8d0ab11bb1e41c80b828cdee58e102fe",
    },
    "cake_kimi_k3_attn_res_5f8b1731faaafb050910": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5f8b1731faaafb050910_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5f8b1731faaafb050910_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "2ce4a834d03af2d6cc07275618a8708742f84fe75f20fa8983f7243a9b743db4",
    },
    "cake_kimi_k3_attn_res_62234b7d691bf3392986": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62234b7d691bf3392986_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62234b7d691bf3392986_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "1a822f6961a56d80d621e9ba533672d01f098a7c98c59d2490593c92dec7bba9",
    },
    "cake_kimi_k3_attn_res_6c023a0cead93de42945": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6c023a0cead93de42945_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6c023a0cead93de42945_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "cb670acf0192cbceb21b1989d92fbab19512b6058e8935d94988cfbbde3fb1e6",
    },
    "cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "cfdda1609f6991372e974580bbc0ca26630ed30ee56811ee72daa7cf69690752",
    },
    "cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "93306c20ac0636619faee353ce78b38fb8330a5870570753b9747c4d9df96afc",
    },
    "cake_kimi_k3_attn_res_7194f290d641ae888abc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ac2b949c773e6faf346a63f3932992691467405b456ee0803ac3d64600bbc6b5",
    },
    "cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "8cec519ec92f0bfb8d5c13b5aaa3e4cb912593d8b2e73c218e296bb0b9eb806b",
    },
    "cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "2c13f679e9496a50659d891ae5871ff010e438d55e849b5fcf1b1c8afde8e9a8",
    },
    "cake_kimi_k3_attn_res_8dbbd3a31f2077a46155": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8dbbd3a31f2077a46155_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8dbbd3a31f2077a46155_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "d0ddbc5e1e695173c5a2f0726f6e6aeb65443b11a66d928cf69270a2346baa22",
    },
    "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "22b8ec501b91134866a4d7d69f8abdf662793eb85c4cd79fef9f35ed112a9d2b",
    },
    "cake_kimi_k3_attn_res_95af0f97dee8674c05f0": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95af0f97dee8674c05f0_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95af0f97dee8674c05f0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "3e495d592ebec32f9406f112d7f5ba3827a0e426c5784b25909c1d3ee7610049",
    },
    "cake_kimi_k3_attn_res_95daeeb4211b8860263c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95daeeb4211b8860263c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95daeeb4211b8860263c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "b2c73128fb9504b9ac125b962ff968fd792d2dc3cbff4af20f74eacc6ec58c80",
    },
    "cake_kimi_k3_attn_res_9a08b05661314c984c9c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9a08b05661314c984c9c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9a08b05661314c984c9c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ca53f80372bfe82a4927bc3bc2e754c120f8e5837183cde987d9d0776bc983e8",
    },
    "cake_kimi_k3_attn_res_a6741a83caf8cd798e00": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a6741a83caf8cd798e00_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a6741a83caf8cd798e00_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "0f74aa447f06bad7bce6a91fbbe7b797c5edcc6476ecd94376ddd46e47134abe",
    },
    "cake_kimi_k3_attn_res_a858be9f148c77834881": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a858be9f148c77834881_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a858be9f148c77834881_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "c958c90eba554513c9b912e47d63e86669b836e1e4d1840fb3834f96499d5a38",
    },
    "cake_kimi_k3_attn_res_a891298f0acbfc7661a5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a891298f0acbfc7661a5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a891298f0acbfc7661a5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "a7a90199aa534b60da0bd81ad6bb0906f1995c9dab6346b0bacf44aab3ddeea2",
    },
    "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_aa857192cd56bffd3e5d_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_aa857192cd56bffd3e5d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "7bc34948d283e5cd95299f68e711477dbd0af4480a461ef9293236e31d7a7374",
    },
    "cake_kimi_k3_attn_res_af4218928933d4553a6f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af4218928933d4553a6f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af4218928933d4553a6f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "2a3d034ce6b291686e7bcd7a96b394dac4ee28dba2da2fe3cd198084a4dfa68a",
    },
    "cake_kimi_k3_attn_res_bea505d472b29401f431": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_bea505d472b29401f431_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_bea505d472b29401f431_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "446d68942bc2177736fd7ace6006d2d47f5cbd52618ee4c471522e357f72377e",
    },
    "cake_kimi_k3_attn_res_c2e471b0412a3611b184": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c2e471b0412a3611b184_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c2e471b0412a3611b184_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "918d3258eb312f59b1c041ff9fda77961f6ac5683df231834353ac82cef6e162",
    },
    "cake_kimi_k3_attn_res_c84b13f3de176fff0611": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c84b13f3de176fff0611_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c84b13f3de176fff0611_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "f4608a1e5fb4d538fd7171bd38ef93c848980603815cc1475985a4774faf6292",
    },
    "cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "3c21be271a155047ada8377a599eb9ee7524a5e305dabb6b2f6d5bc038d39e37",
    },
    "cake_kimi_k3_attn_res_cadf0285c87dabe05863": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cadf0285c87dabe05863_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cadf0285c87dabe05863_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "6293863e05756d0ce80b90d56ced3c1f5d41a1e112a955e9896f797d71ec078d",
    },
    "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "dcf840bb50b5fd0eaac20703731c9fce04cf49c451e08fb0a815828313c68abe",
    },
    "cake_kimi_k3_attn_res_ea241ac152498469bdd1": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ea241ac152498469bdd1_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ea241ac152498469bdd1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "bc08419a8f861e228db815a932e1969344786d2ec7581c2cca43f8dfb63a6016",
    },
    "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ec4df9c22e0215ef7821_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ec4df9c22e0215ef7821_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "e0adcd21c32f593717d3f83da624622888e36ae39433f1a6d7e2b150b214c7d8",
    },
    "cake_kimi_k3_attn_res_ef66c031286a305c1104": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef66c031286a305c1104_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef66c031286a305c1104_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "0f8c24a1c2a322e8821f67d183b201521663b95437ce3c2ea7b15b1cd48621ca",
    },
    "cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "fb0435e2d8b3da3e3695feee2a07ee7fdd14c12f564bcc8d25527027b33b8ab8",
    },
    "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "b8791fb0a68565e6076ebab858823f09ceb1ef71c2b36e24cdf6345ed299df94",
    },
    "cake_kimi_k3_attn_res_fdbbeba136f2d7ede961": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fdbbeba136f2d7ede961_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fdbbeba136f2d7ede961_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "f3be900e2974ea46621ce218be41d2c817d493e27c0d94be36524ceb1113d5ca",
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746",
        "native_k8": "cake_kimi_k3_attn_res_5935d32598c8940b29b6",
        "native_m128": "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821",
        "persistent:k1_nc2_d2_f110000000000000": "cake_kimi_k3_attn_res_50393c0dec14fafed1ab",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_028503fd0961d55b7765",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_95daeeb4211b8860263c",
        "persistent:k3_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc",
        "persistent:k4_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_ef66c031286a305c1104",
        "persistent:k5_nc3_d3_f010000000000000": "cake_kimi_k3_attn_res_95af0f97dee8674c05f0",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_04179092271f793576fd",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_a6741a83caf8cd798e00",
        "small_m_cluster2:k4": "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d",
        "small_m_cluster2:k8": "cake_kimi_k3_attn_res_c84b13f3de176fff0611",
        "small_m_cluster4:k4": "cake_kimi_k3_attn_res_af4218928933d4553a6f",
        "small_m_cluster4:k5": "cake_kimi_k3_attn_res_cadf0285c87dabe05863",
        "small_m_cluster4:k6": "cake_kimi_k3_attn_res_34163a739700379987b9",
        "small_m_cluster4:k7": "cake_kimi_k3_attn_res_8dbbd3a31f2077a46155",
        "small_m_cluster4:k8": "cake_kimi_k3_attn_res_1fbd16a1745563095baf",
        "small_m_direct:k0": "cake_kimi_k3_attn_res_39bea7db7ae295dced4f",
        "small_m_direct:k1": "cake_kimi_k3_attn_res_6c023a0cead93de42945",
        "small_m_direct:k2": "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18",
        "small_m_direct:k3": "cake_kimi_k3_attn_res_9a08b05661314c984c9c",
        "small_m_direct:k4": "cake_kimi_k3_attn_res_42db4f4b8216ab6fcd8f",
    },
    "sm_103a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746",
        "native_k8": "cake_kimi_k3_attn_res_5935d32598c8940b29b6",
        "native_m128": "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b",
        "persistent:k1_nc4_d2_f110000000000010": "cake_kimi_k3_attn_res_5f8b1731faaafb050910",
        "persistent:k1_nc4_d2_f110000000100000": "cake_kimi_k3_attn_res_a858be9f148c77834881",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_3899a43dd652e8333bce",
        "persistent:k3_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_62234b7d691bf3392986",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca",
        "persistent:k4_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_c2e471b0412a3611b184",
        "persistent:k4_nc5_d2_f010001000000000": "cake_kimi_k3_attn_res_05f4833fcaebced8982a",
        "persistent:k5_nc4_d3_f100000000000000": "cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_bea505d472b29401f431",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_06a4152cb4621c4b09f2",
        "persistent:k8_nc3_d2_f011100000000001": "cake_kimi_k3_attn_res_a891298f0acbfc7661a5",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_fdbbeba136f2d7ede961",
        "small_m_cluster2:k4": "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d",
        "small_m_cluster2:k5": "cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7",
        "small_m_cluster2:k6": "cake_kimi_k3_attn_res_ea241ac152498469bdd1",
        "small_m_cluster2:k7": "cake_kimi_k3_attn_res_03bedd980b7a2200bf61",
        "small_m_cluster2:k8": "cake_kimi_k3_attn_res_c84b13f3de176fff0611",
        "small_m_direct:k0": "cake_kimi_k3_attn_res_39bea7db7ae295dced4f",
        "small_m_direct:k1": "cake_kimi_k3_attn_res_6c023a0cead93de42945",
        "small_m_direct:k2": "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18",
        "small_m_direct:k3": "cake_kimi_k3_attn_res_9a08b05661314c984c9c",
        "small_m_direct:k4": "cake_kimi_k3_attn_res_42db4f4b8216ab6fcd8f",
    },
}

# The programs use tcgen05 TMEM (the persistent and native ports) and are
# exact-architecture payloads: one source, compiled once per listed target.
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def _nvcc_flags(arches: list[str]) -> list[str]:
    """The target code-generation flags of ``arches`` followed by the common flags, each once."""
    flags: list[str] = []
    for arch in arches:
        for flag in ARCH_NVCC_FLAGS[arch]:
            if flag not in flags:
                flags.append(flag)
    return flags


def registered_kernel_keys(arch: str) -> tuple[str, ...]:
    """Every logical kernel key registered for ``arch`` (empty without programs)."""
    return tuple(sorted(KERNELS.get(arch, {})))


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    table = KERNELS.get(arch)
    if not table:
        return False
    return all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """The registered module of logical kernel ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if not table:
        raise NotImplementedError(
            f"No generated Kimi-K3 AttnRes programs are registered for {arch} in this checkout"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 AttnRes kernel {key!r} for {arch} is not registered in this "
            "checkout (the export covers the contract's token counts / block counts; see the package README)"
        )
    record = MODULES[name]
    if arch not in record["arches"]:
        raise RuntimeError(
            f"registered module {name!r} is not built for {arch} (arches: {record['arches']})"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_attn_res_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[*_nvcc_flags(record["arches"]), *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_attn_res_module(name: str):
    return gen_cake_kimi_k3_attn_res_module(name).build_and_load()
