"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated Kimi-K3 AttnRes programs.
# ``MODULES``: one record per generated program (role, translation units
# relative to this package's ``csrc``, compile flags, FFI entry, argument plan,
# closure identity, CTA size, and the architectures the one source is compiled
# for).  ``KERNELS``: per architecture, the logical kernel key the host planner
# resolves (``cake_backend.plan_route(...).kernel_key``) -> module name.  Both
# literals are populated verbatim by the generated-program export; do not edit
# by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_attn_res_0613f9587c9d96eee05c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0613f9587c9d96eee05c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0613f9587c9d96eee05c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "e32a9f9af1297a127c8d8fffddc3e7223f3402d1d24a635f406fd18b2fcf075b",
    },
    "cake_kimi_k3_attn_res_06a8275b6f52f79734b7": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a8275b6f52f79734b7_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a8275b6f52f79734b7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "4ad5273eb275af3c1aa0dd442f790afd258ff685562c4eb8d11164155dfa6fd8",
    },
    "cake_kimi_k3_attn_res_0bd21d5155f0320d64a5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0bd21d5155f0320d64a5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0bd21d5155f0320d64a5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b8e449755f9fdebe5acc38c9042c6058272d6e877abbe9e87ab2a5f8ba070c17",
    },
    "cake_kimi_k3_attn_res_0c8ecee3ce2b2f1d0e28": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0c8ecee3ce2b2f1d0e28_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0c8ecee3ce2b2f1d0e28_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "4cc98394852e50aa4060c2399479c78ab42dd7c8713958f96dcfdb7add534898",
    },
    "cake_kimi_k3_attn_res_0dbff4fe0f17de108eb5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0dbff4fe0f17de108eb5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_0dbff4fe0f17de108eb5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "84ebf8bf4c626307c75b6be0faa1d4531dc95e7067e802e32a634939d68b4fc0",
    },
    "cake_kimi_k3_attn_res_16777111e5c607a4cdea": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_16777111e5c607a4cdea_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_16777111e5c607a4cdea_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "d04fc45472753c40476640f9dd2114b66e4290209d4699fcd39aa653f6585818",
    },
    "cake_kimi_k3_attn_res_1680bc1d469acbcf595c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1680bc1d469acbcf595c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1680bc1d469acbcf595c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "e4c444cee2af2b202ece53888b65953cb821bc330c7558fe6bb848f5d499d63b",
    },
    "cake_kimi_k3_attn_res_1a738a436124fc36a688": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1a738a436124fc36a688_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1a738a436124fc36a688_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "fa25da0158ddbefde28a784635f1fe0904781afaf6075c8adb5b0ade322790c9",
    },
    "cake_kimi_k3_attn_res_249db59271f285d249d2": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_249db59271f285d249d2_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_249db59271f285d249d2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "302073db665762d03897b08a972473d4d4442ff5e97ba3e805fd6c2098bdaaab",
    },
    "cake_kimi_k3_attn_res_291d118f0d9137e82482": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "7d8e46398e1d05e079091c3991d20c4b7670b803c618d871d46b2dc6ccdb3568",
    },
    "cake_kimi_k3_attn_res_2d76ccc542c6b2948a50": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2d76ccc542c6b2948a50_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2d76ccc542c6b2948a50_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "c4e432703247348459b2c4e8fd485fa431785c51aba81bec6b98f559acb3f3d0",
    },
    "cake_kimi_k3_attn_res_32f85df97de777defe91": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "a4893aa2404b064dae6a36a5faffbd2cd9a85429a23108f6bde9ba0b06011679",
    },
    "cake_kimi_k3_attn_res_33adf525e31d9cf4f2fc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_33adf525e31d9cf4f2fc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_33adf525e31d9cf4f2fc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "cb5659f36d769971f3ef01b8c817492d355db7d7523adcec5df724446e0559ff",
    },
    "cake_kimi_k3_attn_res_3616bc15a73fc404a992": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3616bc15a73fc404a992_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3616bc15a73fc404a992_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "output_norm_weight"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "2feed29ad8a01cef7aa86867a9ca62a15cef79f479a295a74cc63c4a259b1484",
    },
    "cake_kimi_k3_attn_res_399136164142f7ab68d6": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_399136164142f7ab68d6_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_399136164142f7ab68d6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "52b34095298eecdecacac4ac25bb4b86b33378572bbcf2c9df876ce500a2a07b",
    },
    "cake_kimi_k3_attn_res_3b8133289c94eb4c1dbc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3b8133289c94eb4c1dbc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3b8133289c94eb4c1dbc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "4f2670396f54de1defb5cc74b9160c5527b6175523b04978c25fe7aa56268315",
    },
    "cake_kimi_k3_attn_res_4e9814cb1eb4905d19a9": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4e9814cb1eb4905d19a9_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4e9814cb1eb4905d19a9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "162953a9ca55508e92a262bcdedb4c87dddddee518977ebbf9e77a20240531b5",
    },
    "cake_kimi_k3_attn_res_5a14664e183b9205dc6a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5a14664e183b9205dc6a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5a14664e183b9205dc6a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "output_norm_weight"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "6fefe22a78d6931723a3fc27f6048a60da1304224ec848b4bafa7d30890e3ecd",
    },
    "cake_kimi_k3_attn_res_5fab147e878bdb4ece6d": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5fab147e878bdb4ece6d_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5fab147e878bdb4ece6d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "1aa674867d63f42f7c97c1a5267b1a1ecd886aa6d06f762a2ac8cd64e6abcd55",
    },
    "cake_kimi_k3_attn_res_62c0f39a13c38f083ce4": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62c0f39a13c38f083ce4_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62c0f39a13c38f083ce4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "ad349b677316843fe10eabbbc39ed0708962b54445e44a2219fb033da9cf92f0",
    },
    "cake_kimi_k3_attn_res_636fdc85aca73401a4de": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_636fdc85aca73401a4de_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_636fdc85aca73401a4de_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "7a2c0fd895a8a1ab82f98e73821dee95d99aa51fd6975645a599a202ed27a63e",
    },
    "cake_kimi_k3_attn_res_6b5f60c0ce722144a2af": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6b5f60c0ce722144a2af_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6b5f60c0ce722144a2af_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "49e2224de4b1bebc92c842b908c114e11c3c386f6ac262d4518652332c388de7",
    },
    "cake_kimi_k3_attn_res_7194f290d641ae888abc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ac2b949c773e6faf346a63f3932992691467405b456ee0803ac3d64600bbc6b5",
    },
    "cake_kimi_k3_attn_res_7968d0086ec8918847a1": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7968d0086ec8918847a1_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7968d0086ec8918847a1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "3d4289c440fa44c110e752cd2504b329006a9bf3e9f93328116d5af664a56712",
    },
    "cake_kimi_k3_attn_res_7bafbb336c9c3aaf3e47": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7bafbb336c9c3aaf3e47_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7bafbb336c9c3aaf3e47_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "f926808a31761374ef95c56151935ca61e1d32182718fcdeaa575c1a11d31182",
    },
    "cake_kimi_k3_attn_res_7fd82d46ca8e76bc9d14": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7fd82d46ca8e76bc9d14_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7fd82d46ca8e76bc9d14_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "37c777bc96db53154ac48c9a7aa6fc8d99fcfc7b327d8046dd527718bd7f27c1",
    },
    "cake_kimi_k3_attn_res_8e7b2312711e12e91f9b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e7b2312711e12e91f9b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e7b2312711e12e91f9b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "47f5d45c25bfa57cc0cf440bb58f3a236ef3798e1e0ef1ab38155d33821ed996",
    },
    "cake_kimi_k3_attn_res_902be300489120e507d2": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_902be300489120e507d2_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_902be300489120e507d2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "cd85b1afcd15f6c5fd674d834f514a51dd970b66ddb4e0cfd65e57b365e38238",
    },
    "cake_kimi_k3_attn_res_9093aefb373e348fc9b5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9093aefb373e348fc9b5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9093aefb373e348fc9b5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "55eef129b1f8c53b50f8fb915718debf8feae09d7c4608d0cf95008489b2cdce",
    },
    "cake_kimi_k3_attn_res_92481bc2cc7b890d9d7f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_92481bc2cc7b890d9d7f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_92481bc2cc7b890d9d7f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "ffa60553b6a80d0e97a50a2a579515e7edf73b686fb8022bc49a3b1c125e6bc0",
    },
    "cake_kimi_k3_attn_res_ab386393d568fcfa76b5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ab386393d568fcfa76b5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ab386393d568fcfa76b5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "2427df6c72b04f33a7069c3bb9ba87ba30900ec1c900b20cd800f0c882eefb4d",
    },
    "cake_kimi_k3_attn_res_ad1d2aabe3efd9434196": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ad1d2aabe3efd9434196_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ad1d2aabe3efd9434196_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "48ba794cb6b0bde8d2fa8b6e38e9274892c4f71b2f6d72cbaff3e63fb64312c0",
    },
    "cake_kimi_k3_attn_res_ad263eb0915275158a97": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ad263eb0915275158a97_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ad263eb0915275158a97_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "eddba25633e4982c159ee3e8aa28cd5f732aa1267d6c3d4169f2723dfd07e1ac",
    },
    "cake_kimi_k3_attn_res_af36d54521e19453b4fe": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af36d54521e19453b4fe_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af36d54521e19453b4fe_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "0d9c461c0b30acb6f881045843883f92e35dfce7916cce86eeb735c5f2b36b35",
    },
    "cake_kimi_k3_attn_res_b2ba94ef1fa658c4f00d": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_b2ba94ef1fa658c4f00d_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_b2ba94ef1fa658c4f00d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "21a12cde03c1e98ccc5be0467b9531f97dac5e4fa36ad6db5e1cf6c16b6e1a22",
    },
    "cake_kimi_k3_attn_res_b818e428163a66b0b5c5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_b818e428163a66b0b5c5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_b818e428163a66b0b5c5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "a66b9a994d4aa18e504c5050269823a27d21a7a223ce060221dc607067a90a73",
    },
    "cake_kimi_k3_attn_res_be6b54034c2c1b3afd3b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_be6b54034c2c1b3afd3b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_be6b54034c2c1b3afd3b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "60c77433740c0bc70d747f02688efad5a9c6081819d4628300f1a6ec97f5be09",
    },
    "cake_kimi_k3_attn_res_c348a5cf82bbbfe1f5f6": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c348a5cf82bbbfe1f5f6_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c348a5cf82bbbfe1f5f6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b944aa105af48bfd7eda8618c18dd4d20aae4be61eaad3cd1c9d1197afed37bf",
    },
    "cake_kimi_k3_attn_res_ceb5af1449319b8b9b62": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ceb5af1449319b8b9b62_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ceb5af1449319b8b9b62_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "9996cd6e1fb6a051898eaa8cab002a9aee12db44b9db357beffc3dda05521983",
    },
    "cake_kimi_k3_attn_res_d08b47079ac20e1d6d47": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d08b47079ac20e1d6d47_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d08b47079ac20e1d6d47_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "f82b653f4a2affb5c148908515cebf9d66b9e5be5024c32118ab448a02957a08",
    },
    "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "dcf840bb50b5fd0eaac20703731c9fce04cf49c451e08fb0a815828313c68abe",
    },
    "cake_kimi_k3_attn_res_d9a1778fa47d02bf1d8e": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d9a1778fa47d02bf1d8e_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d9a1778fa47d02bf1d8e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "0930d52042cfc7a31c459c81b30ac820498327be0cc8ace298c52f0a0f777a54",
    },
    "cake_kimi_k3_attn_res_e4487f79940addc13a35": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_e4487f79940addc13a35_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_e4487f79940addc13a35_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b6bc6a091b8cd5914199ef062edff06b20d57bdfd5e2bbbd3b886d362b10c5e0",
    },
    "cake_kimi_k3_attn_res_edfc466c7334b921d3bf": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_edfc466c7334b921d3bf_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_edfc466c7334b921d3bf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "c3f26256241b213fbd45fe223fbde25b01770238ad37e215b8974f876b73203c",
    },
    "cake_kimi_k3_attn_res_ef98060834a4c6db2fff": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef98060834a4c6db2fff_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef98060834a4c6db2fff_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "0f02dbdd2bace6443314c2c2630e665d62282bc0a0bdf37e08c773c1ae2ee5aa",
    },
    "cake_kimi_k3_attn_res_efd5a74e440e7e5fc81d": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_efd5a74e440e7e5fc81d_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_efd5a74e440e7e5fc81d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "35bc554f929770469c999b97a7ac1e9b12891b84ff7263a7b82015cf79277ee4",
    },
    "cake_kimi_k3_attn_res_fadda3356c152cbc919c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fadda3356c152cbc919c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fadda3356c152cbc919c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "582d71cc6b2f768776bb721d6d74a7c7e5525417cdec748fee1ce8e86d4577b9",
    },
    "cake_kimi_k3_attn_res_fb4f9275d678fa80d479": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fb4f9275d678fa80d479_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fb4f9275d678fa80d479_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "6b539bdc871d5a21c8543f9031abeec5f66f0f1d57b4fe892815cfa469efd069",
    },
    "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "b8791fb0a68565e6076ebab858823f09ceb1ef71c2b36e24cdf6345ed299df94",
    },
    "cake_kimi_k3_attn_res_fc543ec76ffc003dca2a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc543ec76ffc003dca2a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc543ec76ffc003dca2a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "1af8a5242f953a933dfdbe609dd8f61f480e87d68fa455e1c96e7a9ab659db58",
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_5a14664e183b9205dc6a",
        "native_k5": "cake_kimi_k3_attn_res_fb4f9275d678fa80d479",
        "native_k6": "cake_kimi_k3_attn_res_902be300489120e507d2",
        "native_k7": "cake_kimi_k3_attn_res_92481bc2cc7b890d9d7f",
        "native_k8": "cake_kimi_k3_attn_res_0c8ecee3ce2b2f1d0e28",
        "native_m128": "cake_kimi_k3_attn_res_1a738a436124fc36a688",
        "persistent:k1_nc2_d2_f110000000000000": "cake_kimi_k3_attn_res_d08b47079ac20e1d6d47",
        "persistent:k1_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_b2ba94ef1fa658c4f00d",
        "persistent:k1_nc4_d2_f100000000000000": "cake_kimi_k3_attn_res_fc543ec76ffc003dca2a",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_5fab147e878bdb4ece6d",
        "persistent:k2_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_9093aefb373e348fc9b5",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_ad1d2aabe3efd9434196",
        "persistent:k3_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_7fd82d46ca8e76bc9d14",
        "persistent:k3_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_fadda3356c152cbc919c",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_16777111e5c607a4cdea",
        "persistent:k4_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_4e9814cb1eb4905d19a9",
        "persistent:k5_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_d9a1778fa47d02bf1d8e",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_7bafbb336c9c3aaf3e47",
        "persistent:k7_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_1680bc1d469acbcf595c",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_62c0f39a13c38f083ce4",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_be6b54034c2c1b3afd3b",
        "persistent:k8_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_ad263eb0915275158a97",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_7968d0086ec8918847a1",
    },
    "sm_103a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_3616bc15a73fc404a992",
        "native_k5": "cake_kimi_k3_attn_res_fb4f9275d678fa80d479",
        "native_k6": "cake_kimi_k3_attn_res_902be300489120e507d2",
        "native_k8": "cake_kimi_k3_attn_res_0c8ecee3ce2b2f1d0e28",
        "native_m128": "cake_kimi_k3_attn_res_1a738a436124fc36a688",
        "persistent:k1_nc2_d2_f010000000000000": "cake_kimi_k3_attn_res_c348a5cf82bbbfe1f5f6",
        "persistent:k1_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_efd5a74e440e7e5fc81d",
        "persistent:k1_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_0bd21d5155f0320d64a5",
        "persistent:k1_nc4_d2_f011010000010000": "cake_kimi_k3_attn_res_06a8275b6f52f79734b7",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_0613f9587c9d96eee05c",
        "persistent:k1_nc4_d2_f110000000000010": "cake_kimi_k3_attn_res_af36d54521e19453b4fe",
        "persistent:k1_nc4_d2_f110000000100000": "cake_kimi_k3_attn_res_399136164142f7ab68d6",
        "persistent:k2_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_6b5f60c0ce722144a2af",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_8e7b2312711e12e91f9b",
        "persistent:k3_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_33adf525e31d9cf4f2fc",
        "persistent:k3_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_0dbff4fe0f17de108eb5",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_b818e428163a66b0b5c5",
        "persistent:k4_nc5_d2_f010001000000000": "cake_kimi_k3_attn_res_ef98060834a4c6db2fff",
        "persistent:k4_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_249db59271f285d249d2",
        "persistent:k5_nc4_d3_f100000000000000": "cake_kimi_k3_attn_res_ceb5af1449319b8b9b62",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_e4487f79940addc13a35",
        "persistent:k7_nc4_d2_f010000000000000": "cake_kimi_k3_attn_res_edfc466c7334b921d3bf",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_ab386393d568fcfa76b5",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_636fdc85aca73401a4de",
        "persistent:k8_nc3_d2_f011100000000001": "cake_kimi_k3_attn_res_2d76ccc542c6b2948a50",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_3b8133289c94eb4c1dbc",
    },
}

# The programs use tcgen05 TMEM (the persistent and native ports) and are
# exact-architecture payloads: one source, compiled once per listed target.
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def _nvcc_flags(arches: list[str]) -> list[str]:
    """The target code-generation flags of ``arches`` followed by the common flags, each once."""
    flags: list[str] = []
    for arch in arches:
        for flag in ARCH_NVCC_FLAGS[arch]:
            if flag not in flags:
                flags.append(flag)
    return flags


def registered_kernel_keys(arch: str) -> tuple[str, ...]:
    """Every logical kernel key registered for ``arch`` (empty without programs)."""
    return tuple(sorted(KERNELS.get(arch, {})))


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    table = KERNELS.get(arch)
    if not table:
        return False
    return all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """The registered module of logical kernel ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if not table:
        raise NotImplementedError(
            f"No generated Kimi-K3 AttnRes programs are registered for {arch} in this checkout"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 AttnRes kernel {key!r} for {arch} is not registered in this "
            "checkout (the export covers the contract's token counts / block counts; see the package README)"
        )
    record = MODULES[name]
    if arch not in record["arches"]:
        raise RuntimeError(
            f"registered module {name!r} is not built for {arch} (arches: {record['arches']})"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_attn_res_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[*_nvcc_flags(record["arches"]), *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_attn_res_module(name: str):
    return gen_cake_kimi_k3_attn_res_module(name).build_and_load()
