"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated Kimi-K3 AttnRes programs.
# ``MODULES``: one record per generated program (role, translation units
# relative to this package's ``csrc``, compile flags, FFI entry, argument plan,
# closure identity, CTA size, and the architectures the one source is compiled
# for).  ``KERNELS``: per architecture, the logical kernel key the host planner
# resolves (``cake_backend.plan_route(...).kernel_key``) -> module name.  Both
# literals are populated verbatim by the generated-program export; do not edit
# by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_attn_res_028503fd0961d55b7765": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_028503fd0961d55b7765_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_028503fd0961d55b7765_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "2675300c04a1351f7f3675eac75c633ef5504faa758a4630158d3f16c903b78c",
    },
    "cake_kimi_k3_attn_res_03bedd980b7a2200bf61": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_03bedd980b7a2200bf61_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_03bedd980b7a2200bf61_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "31dbd8b2e99bb5aa032c6d6f2de6a27f4a74aa3e4620cca24d5d44a06f2e07dd",
    },
    "cake_kimi_k3_attn_res_04179092271f793576fd": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_04179092271f793576fd_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_04179092271f793576fd_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "098ff9e35154f812fd2d81c65ecb526760039af08367e76ab407505f86d5fa24",
    },
    "cake_kimi_k3_attn_res_05f4833fcaebced8982a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_05f4833fcaebced8982a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_05f4833fcaebced8982a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b232d179f47c5025631d9e6a8331776cf0576272004eafc80e262a14ed3ebaca",
    },
    "cake_kimi_k3_attn_res_06a4152cb4621c4b09f2": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a4152cb4621c4b09f2_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_06a4152cb4621c4b09f2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "51816dd391a53dc71fe40e66c4efae41b427523b84c0a7a0426f576f14d10a50",
    },
    "cake_kimi_k3_attn_res_1fbd16a1745563095baf": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1fbd16a1745563095baf_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_1fbd16a1745563095baf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "b41b37d84f036fe1b5344f2a58ef7875c19dfd88d845118af3e913e08f8a9425",
    },
    "cake_kimi_k3_attn_res_291d118f0d9137e82482": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_291d118f0d9137e82482_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "7d8e46398e1d05e079091c3991d20c4b7670b803c618d871d46b2dc6ccdb3568",
    },
    "cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "030ff2d01df4e04395a4fe226c4f830097b05543c2b2d40921b37f9ee6c02358",
    },
    "cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "2bbb710f299c48cb3ae5a854fe2bb116b9c148307a1fc5386b9a4da69e97d606",
    },
    "cake_kimi_k3_attn_res_320ac84d68e18ee084ed": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_320ac84d68e18ee084ed_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_320ac84d68e18ee084ed_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "8bcf8d50f91fb66ffe3eb764b1a7c10587a7e5988bbc2538f6d95f99fc813537",
    },
    "cake_kimi_k3_attn_res_32f85df97de777defe91": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_32f85df97de777defe91_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "a4893aa2404b064dae6a36a5faffbd2cd9a85429a23108f6bde9ba0b06011679",
    },
    "cake_kimi_k3_attn_res_34163a739700379987b9": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_34163a739700379987b9_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_34163a739700379987b9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "42bb3fab497088075b2defdd5ed5c875fa650afbc2d3e1e02312dcd42803d631",
    },
    "cake_kimi_k3_attn_res_3899a43dd652e8333bce": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3899a43dd652e8333bce_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3899a43dd652e8333bce_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "912f09d0fcb62fc9bf3c839d07ed9a987764a40c995b0eda27ed6fe258c7de3f",
    },
    "cake_kimi_k3_attn_res_39bea7db7ae295dced4f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_39bea7db7ae295dced4f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_39bea7db7ae295dced4f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "f0ae1194711119e80083b9982aa14226585f3fa76531de899f0a12d06f74549c",
    },
    "cake_kimi_k3_attn_res_3ba9e82486ba3a8e744a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3ba9e82486ba3a8e744a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_3ba9e82486ba3a8e744a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "de4a8b674bd198c440f103934fbc705364edf8bc0a0b2675024413ddf2d0f9c1",
    },
    "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "output_norm_weight"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ec4c7934704b939ce55706c7ac94d709f80bb2810ce6a84deff005f28b3e6fe3",
    },
    "cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "238f26658077b664a77a9d3562f7d11bbe621b671a58d5ff07662bdb2c20fc4f",
    },
    "cake_kimi_k3_attn_res_50393c0dec14fafed1ab": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_50393c0dec14fafed1ab_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_50393c0dec14fafed1ab_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "d85a69222ce38fe84045830faf4f8f795abf16f976160c6c5a9f4ce3ce5dab86",
    },
    "cake_kimi_k3_attn_res_5935d32598c8940b29b6": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5935d32598c8940b29b6_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5935d32598c8940b29b6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "89c72a7e0dcf2a66f8dee667620fc9c0609ed1d136e2afaba59de2fb518cc8fa",
    },
    "cake_kimi_k3_attn_res_5f8b1731faaafb050910": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5f8b1731faaafb050910_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_5f8b1731faaafb050910_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "40e6962da005cce95e400edd90e01fdb14897587b3f26ecc3d45c34ee64de05e",
    },
    "cake_kimi_k3_attn_res_62234b7d691bf3392986": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62234b7d691bf3392986_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_62234b7d691bf3392986_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "966fca9419a85db0c6d5499b24bfb86f8bcc91f1dba9d0d5cabeeec8f81561f9",
    },
    "cake_kimi_k3_attn_res_6c023a0cead93de42945": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6c023a0cead93de42945_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6c023a0cead93de42945_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "4eac3ed0cdb5807313f8c652d49662ccec1f0da0dae8895b901157ed7f17c3aa",
    },
    "cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "785beb8e2523dc4a3114f4339f8224addaf656f241573a3e72b180a535c83ee4",
    },
    "cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "c5c071c4cebc9d83c23fb3f8bb22e0e26f8ede4316fa204d93baf0e278e6453f",
    },
    "cake_kimi_k3_attn_res_7194f290d641ae888abc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_7194f290d641ae888abc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "ac2b949c773e6faf346a63f3932992691467405b456ee0803ac3d64600bbc6b5",
    },
    "cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "102712700d42c64b291e35fdd7e939cb811c0969d0db60eca432ca688681f7fb",
    },
    "cake_kimi_k3_attn_res_78b0ba290a4ef1298d15": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_78b0ba290a4ef1298d15_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_78b0ba290a4ef1298d15_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "18da6ccbc47da34e37ace1fb31ab0ff5b187ac087cd6d6e7203ef743112673c6",
    },
    "cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "9b27c3c5ff9324599396956285eac98ae4bef707122e4a0615a8c0c5e0c8ef97",
    },
    "cake_kimi_k3_attn_res_8dbbd3a31f2077a46155": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8dbbd3a31f2077a46155_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8dbbd3a31f2077a46155_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "b043739600bb18720d1e9d0f06aefe46cb3c02694557e624a49580e5ad29d0ec",
    },
    "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "8056bcf8247079abf7c2b72724ee2db4bf92e8446184551792ca94c1c0cd93cd",
    },
    "cake_kimi_k3_attn_res_95af0f97dee8674c05f0": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95af0f97dee8674c05f0_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95af0f97dee8674c05f0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "681c2379049239528d617c95dc8e8c28d5eb43a091b07624c7ba58c2c4df1df8",
    },
    "cake_kimi_k3_attn_res_95daeeb4211b8860263c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95daeeb4211b8860263c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_95daeeb4211b8860263c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "f561da269af9c75d58b556b491976d810c5efb760a7fed713be84cf68f792e44",
    },
    "cake_kimi_k3_attn_res_9a08b05661314c984c9c": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9a08b05661314c984c9c_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_9a08b05661314c984c9c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "0cb158c811613fc37488cc027bdf8937c73b1c0ad6cf4afe2318d4f9f58603a1",
    },
    "cake_kimi_k3_attn_res_a6741a83caf8cd798e00": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a6741a83caf8cd798e00_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a6741a83caf8cd798e00_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "45fdd440552b964734450436db9a930579d5b035d2b56dec0e1d2532dbe55757",
    },
    "cake_kimi_k3_attn_res_a858be9f148c77834881": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a858be9f148c77834881_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a858be9f148c77834881_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "0c6e1e160a4cfb86a8cadd050cfa9462343d8934778e216630227eb93acf1bc8",
    },
    "cake_kimi_k3_attn_res_a891298f0acbfc7661a5": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a891298f0acbfc7661a5_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_a891298f0acbfc7661a5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "ec1f10392613e696d3bf3666b1bdf0b1475ec0bdefa8eee5724d199b5c33438f",
    },
    "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_aa857192cd56bffd3e5d_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_aa857192cd56bffd3e5d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "b02bcd30128c3efb8917679ece1dd63ddae22c90535efca3c139b9978472d56c",
    },
    "cake_kimi_k3_attn_res_af4218928933d4553a6f": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af4218928933d4553a6f_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_af4218928933d4553a6f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "080f664c3fcba3839150c1790ef925c3e94c406de71e197007a67fdd068d7a22",
    },
    "cake_kimi_k3_attn_res_bea505d472b29401f431": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_bea505d472b29401f431_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_bea505d472b29401f431_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "ada14dcea1cd18e9eab5a36d007eeb2534df11b80f89ac681e662b56bc7a059f",
    },
    "cake_kimi_k3_attn_res_c2e471b0412a3611b184": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c2e471b0412a3611b184_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c2e471b0412a3611b184_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "b085c1c1665c3c38603dbd9db2e3cfd86c60f9eeb8d8f151b93feefc288db326",
    },
    "cake_kimi_k3_attn_res_c84b13f3de176fff0611": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c84b13f3de176fff0611_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c84b13f3de176fff0611_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "9d0edb158d08a44a302581ebf69ec62e65c9829d43e7bb225b97990bac40588d",
    },
    "cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "e7caba64d6e28e6d266acd175ca23852cbe245caf14b3fb9bb8c0b2e418afd2f",
    },
    "cake_kimi_k3_attn_res_cadf0285c87dabe05863": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cadf0285c87dabe05863_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cadf0285c87dabe05863_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 64,
        "arches": ["sm_100a"],
        "closure_sha256": "e4f7ce7222698425042e46d3d2bcb63c9d5266ad25b947c735bc1fdcdd27ef68",
    },
    "cake_kimi_k3_attn_res_cb5b0c965ed8dc97130b": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cb5b0c965ed8dc97130b_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_cb5b0c965ed8dc97130b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "3ad739f42f867143ccaaa49368516d1662d507c957851400601993886817d67f",
    },
    "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "dcf840bb50b5fd0eaac20703731c9fce04cf49c451e08fb0a815828313c68abe",
    },
    "cake_kimi_k3_attn_res_ea241ac152498469bdd1": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ea241ac152498469bdd1_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ea241ac152498469bdd1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 128,
        "arches": ["sm_103a"],
        "closure_sha256": "637e23728a8cd8d281762897d07884e5772051abfc113c0da29658df5a358ac9",
    },
    "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ec4df9c22e0215ef7821_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ec4df9c22e0215ef7821_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "70e91757a875c88d8bbefae4cfd36afb85cd55831ae673d530fbc26ea526ccf6",
    },
    "cake_kimi_k3_attn_res_ef66c031286a305c1104": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef66c031286a305c1104_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_ef66c031286a305c1104_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "5a819ff9070bce8c2f6493b5996fb0c6390015fc98319ebec070ee5517b24d1f",
    },
    "cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_100a"],
        "closure_sha256": "759995a01f019812333550d468c74f8ddfdd67bde760a4abed8a31620e3f2272",
    },
    "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "out_stride"],
            ["parameter", "prefix_stride"],
            ["parameter", "delta_stride"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "block_write_idx"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 256,
        "arches": ["sm_100a", "sm_103a"],
        "closure_sha256": "b8791fb0a68565e6076ebab858823f09ceb1ef71c2b36e24cdf6345ed299df94",
    },
    "cake_kimi_k3_attn_res_fdbbeba136f2d7ede961": {
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fdbbeba136f2d7ede961_kernel.cu",
            "cake_kimi_k3_attn_res/cake_kimi_k3_attn_res_fdbbeba136f2d7ede961_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "out"],
            ["buffer", "prefix"],
            ["buffer", "delta"],
            ["buffer", "blocks"],
            ["buffer", "norm_weight"],
            ["buffer", "qk_weight"],
            ["buffer", "output_norm_weight"],
            ["parameter", "blocks_m_stride"],
            ["parameter", "blocks_k_stride"],
            ["parameter", "eps"],
            ["parameter", "output_norm_eps"],
            ["parameter", "M"],
            ["launch", "enable_pdl"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 0,
        "threads": 288,
        "arches": ["sm_103a"],
        "closure_sha256": "dab18481abb28a69ce1101310b9f8edcb29e425f8582fee9f6c398ecc271fda7",
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746",
        "native_k8": "cake_kimi_k3_attn_res_5935d32598c8940b29b6",
        "native_m128": "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821",
        "persistent:k1_nc2_d2_f110000000000000": "cake_kimi_k3_attn_res_50393c0dec14fafed1ab",
        "persistent:k1_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_cb5b0c965ed8dc97130b",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_028503fd0961d55b7765",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_95daeeb4211b8860263c",
        "persistent:k3_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_4cd66ac7fb3a3c76776a",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_f6d43c3667f5ea30b6cc",
        "persistent:k4_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_ef66c031286a305c1104",
        "persistent:k5_nc3_d3_f010000000000000": "cake_kimi_k3_attn_res_95af0f97dee8674c05f0",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_c9e9692ff7ae13af4d99",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_750dc67cc8bcf73ad8db",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_04179092271f793576fd",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_a6741a83caf8cd798e00",
        "small_m_cluster2:k4": "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d",
        "small_m_cluster4:k4": "cake_kimi_k3_attn_res_af4218928933d4553a6f",
        "small_m_cluster4:k5": "cake_kimi_k3_attn_res_cadf0285c87dabe05863",
        "small_m_cluster4:k6": "cake_kimi_k3_attn_res_34163a739700379987b9",
        "small_m_cluster4:k7": "cake_kimi_k3_attn_res_8dbbd3a31f2077a46155",
        "small_m_cluster4:k8": "cake_kimi_k3_attn_res_1fbd16a1745563095baf",
        "small_m_direct:k0": "cake_kimi_k3_attn_res_39bea7db7ae295dced4f",
        "small_m_direct:k1": "cake_kimi_k3_attn_res_6c023a0cead93de42945",
        "small_m_direct:k2": "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18",
        "small_m_direct:k3": "cake_kimi_k3_attn_res_9a08b05661314c984c9c",
    },
    "sm_103a": {
        "direct:k0_d0_w1_n1": "cake_kimi_k3_attn_res_fc09e868f74b8c6fdf0e",
        "direct:k4_d0_w0_n1": "cake_kimi_k3_attn_res_291d118f0d9137e82482",
        "direct:k4_d1_w1_n1": "cake_kimi_k3_attn_res_32f85df97de777defe91",
        "direct:k7_d1_w1_n1": "cake_kimi_k3_attn_res_7194f290d641ae888abc",
        "direct:k8_d1_w0_n0": "cake_kimi_k3_attn_res_d6c48b9566d909d3e0b8",
        "k0_tma": "cake_kimi_k3_attn_res_4c2c0a5a9ea5a9093746",
        "native_k8": "cake_kimi_k3_attn_res_5935d32598c8940b29b6",
        "native_m128": "cake_kimi_k3_attn_res_ec4df9c22e0215ef7821",
        "persistent:k1_nc2_d2_f010000000000000": "cake_kimi_k3_attn_res_3ba9e82486ba3a8e744a",
        "persistent:k1_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_320ac84d68e18ee084ed",
        "persistent:k1_nc4_d2_f011010000000000": "cake_kimi_k3_attn_res_78b0ba290a4ef1298d15",
        "persistent:k1_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_6d78f70ca0fc22e4d64b",
        "persistent:k1_nc4_d2_f110000000000010": "cake_kimi_k3_attn_res_5f8b1731faaafb050910",
        "persistent:k1_nc4_d2_f110000000100000": "cake_kimi_k3_attn_res_a858be9f148c77834881",
        "persistent:k2_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_3899a43dd652e8333bce",
        "persistent:k3_nc4_d2_f011000000000000": "cake_kimi_k3_attn_res_62234b7d691bf3392986",
        "persistent:k4_nc3_d2_f110000000000000": "cake_kimi_k3_attn_res_7050d9bcb8abed5bbeca",
        "persistent:k4_nc3_d3_f110000000000000": "cake_kimi_k3_attn_res_c2e471b0412a3611b184",
        "persistent:k4_nc5_d2_f010001000000000": "cake_kimi_k3_attn_res_05f4833fcaebced8982a",
        "persistent:k5_nc4_d3_f100000000000000": "cake_kimi_k3_attn_res_2bd6bc4d74544b1fcb6b",
        "persistent:k6_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_2ddeb0485677f92cd8b4",
        "persistent:k7_nc4_d2_f110000000000000": "cake_kimi_k3_attn_res_bea505d472b29401f431",
        "persistent:k8_nc3_d2_f011100000000000": "cake_kimi_k3_attn_res_06a4152cb4621c4b09f2",
        "persistent:k8_nc3_d2_f011100000000001": "cake_kimi_k3_attn_res_a891298f0acbfc7661a5",
        "persistent:k8_nc5_d2_f110000000000000": "cake_kimi_k3_attn_res_fdbbeba136f2d7ede961",
        "small_m_cluster2:k4": "cake_kimi_k3_attn_res_aa857192cd56bffd3e5d",
        "small_m_cluster2:k5": "cake_kimi_k3_attn_res_79b4ed02ddce5423fbb7",
        "small_m_cluster2:k6": "cake_kimi_k3_attn_res_ea241ac152498469bdd1",
        "small_m_cluster2:k7": "cake_kimi_k3_attn_res_03bedd980b7a2200bf61",
        "small_m_cluster2:k8": "cake_kimi_k3_attn_res_c84b13f3de176fff0611",
        "small_m_direct:k0": "cake_kimi_k3_attn_res_39bea7db7ae295dced4f",
        "small_m_direct:k1": "cake_kimi_k3_attn_res_6c023a0cead93de42945",
        "small_m_direct:k2": "cake_kimi_k3_attn_res_8e39ccd7a53d0d6dba18",
        "small_m_direct:k3": "cake_kimi_k3_attn_res_9a08b05661314c984c9c",
    },
}

# The programs use tcgen05 TMEM (the persistent and native ports) and are
# exact-architecture payloads: one source, compiled once per listed target.
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def _nvcc_flags(arches: list[str]) -> list[str]:
    """The target code-generation flags of ``arches`` followed by the common flags, each once."""
    flags: list[str] = []
    for arch in arches:
        for flag in ARCH_NVCC_FLAGS[arch]:
            if flag not in flags:
                flags.append(flag)
    return flags


def registered_kernel_keys(arch: str) -> tuple[str, ...]:
    """Every logical kernel key registered for ``arch`` (empty without programs)."""
    return tuple(sorted(KERNELS.get(arch, {})))


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    table = KERNELS.get(arch)
    if not table:
        return False
    return all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """The registered module of logical kernel ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if not table:
        raise NotImplementedError(
            f"No generated Kimi-K3 AttnRes programs are registered for {arch} in this checkout"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 AttnRes kernel {key!r} for {arch} is not registered in this "
            "checkout (the export covers the contract's token counts / block counts; see the package README)"
        )
    record = MODULES[name]
    if arch not in record["arches"]:
        raise RuntimeError(
            f"registered module {name!r} is not built for {arch} (arches: {record['arches']})"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_attn_res_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[*_nvcc_flags(record["arches"]), *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_attn_res_module(name: str):
    return gen_cake_kimi_k3_attn_res_module(name).build_and_load()
