"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the
# Kimi-K3 Stable LatentMoE front / tail projections (SM100 / SM103).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host planner resolves at preparation:
#
# * ``decode:<symbol>``  one weight-streaming swapped-AB tcgen05 instance per
#   decode plan (T <= 128: N padding, ring depth, cluster pairs, fused norm,
#   resident B operand, staged rows, issue gate are baked into the symbol);
# * ``front:i<I_local>`` the persistent 2-CTA prefill front GEMM (T > 128) per
#   shared-intermediate width (TP1 6144, TP8 768);
# * ``tail_norm:e<0|1>`` the one-pass RMSNorm kernel with the late / early
#   ``griddepcontrol.launch_dependents`` trigger the host plan selects;
# * ``tail_gemm:tp<1|8>e<0|1>f<0|1>`` the persistent 2-CTA prefill tail GEMM (PDL
#   launch, trailing-wave stream-K) per tensor-parallel degree; ``e1`` loads the
#   weight boxes with the ``evict_first`` L2 policy (single-wave grids); ``f1``
#   fuses the RMSNorm into the launch (the epilogue warps normalise the latent
#   rows, no ``tail_norm`` launch; TP1 T = 256 / 512).
#
# Every module is an exact-architecture program (tcgen05 / TMEM / TMA).  Both
# literals are populated verbatim by the generated-program export; do not
# edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_latent_moe_04b7802a48d2cb654059": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_04b7802a48d2cb654059_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_04b7802a48d2cb654059_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bdc8108fb14523b6c1cd1072b393cacc6a920aab0432b4cf01d16086f55ee115",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_0cab4920389a7dbc994f": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_0cab4920389a7dbc994f_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_0cab4920389a7dbc994f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "32f56e35532b03d7d14c0eeeda5c716b81385fd7ef8392b42064fed81b5cd92d",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 211968,
        },
    },
    "cake_kimi_k3_latent_moe_1a07149fda6f32837a5d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_1a07149fda6f32837a5d_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_1a07149fda6f32837a5d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ebb549f4f2d8b4c21d7e3eebb2c8ad429a52f0b430a308ec313d935eb77091a2",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_1be3103a935cf7a1e309": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1be3103a935cf7a1e309_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1be3103a935cf7a1e309_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7f481992aeed70c51986d1530f9939cc581cd669654bbf51320a73d1ef764e63",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 224256,
        },
    },
    "cake_kimi_k3_latent_moe_1c8ec1f6d247e9f47928": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1c8ec1f6d247e9f47928_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1c8ec1f6d247e9f47928_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fe7f162c9d86c69a13fb87791517581ffef4943364a4b8d43d81f877a098d307",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_1e1a2d332efcb061ee59": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1e1a2d332efcb061ee59_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_1e1a2d332efcb061ee59_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["parameter", "M"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fecad5068ccee888018ad19be34bcc2a0d30357168815dcf95a314ddc148359a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [128, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
        },
    },
    "cake_kimi_k3_latent_moe_2d1017bf8110b8557c82": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_2d1017bf8110b8557c82_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_2d1017bf8110b8557c82_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c6f45f61bd230e3c750ff75d16fe551c13695ec5372f45ecdfc3b8530e98286e",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_2e23d9e9673f1f13c837": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_2e23d9e9673f1f13c837_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_2e23d9e9673f1f13c837_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "afc2ff25a5eac808c711f16d1036268fe71d4788534ba711843b091496d96bd8",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 199680,
        },
    },
    "cake_kimi_k3_latent_moe_2fc8595c9156169efb6a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_2fc8595c9156169efb6a_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_2fc8595c9156169efb6a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0a2c48428411f296bdc8b43b32457ef5dc6e1f936f2c1e7792cff3689390c95a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 211968,
        },
    },
    "cake_kimi_k3_latent_moe_3dcbae5c1206f76ff7b7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_3dcbae5c1206f76ff7b7_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_3dcbae5c1206f76ff7b7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["parameter", "M"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "14a8b30b8dc687d6caef7b93c6d9461c782b079d2485c714061d95e9db0c7fff",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [128, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
        },
    },
    "cake_kimi_k3_latent_moe_43e508f7d2c7fab8a61f": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_43e508f7d2c7fab8a61f_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_43e508f7d2c7fab8a61f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a4e129917fc48f702807597f96e749459890921c2425da504b64f85791b2cee8",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 208896,
        },
    },
    "cake_kimi_k3_latent_moe_50d173da21802ac2fc8e": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_50d173da21802ac2fc8e_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_50d173da21802ac2fc8e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["parameter", "M"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b750b9b909e008655eb07f5740947ce6b3c79b32b0bf219d09f9f668e84c4d3f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [128, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
        },
    },
    "cake_kimi_k3_latent_moe_585cd1d9ed9505c38ccd": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_585cd1d9ed9505c38ccd_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_585cd1d9ed9505c38ccd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ad014eadc8ccc00c78043fc752508e678bc80005e6031d4e1514d9e6d217644b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_66a583fa8fce7a147412": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_66a583fa8fce7a147412_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_66a583fa8fce7a147412_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8b049e377de0f2e3f7cfb7c13b44ad3e5ef3a1f7fa5b8b142fd54c3764539f65",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_693a2c08cdc4a10ac480": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_693a2c08cdc4a10ac480_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_693a2c08cdc4a10ac480_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bced4b764720ec568c784f1095d7cd261616e5db08accaab99f34b0f9058a5bf",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_6eda257b29eab0cc590b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_6eda257b29eab0cc590b_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_6eda257b29eab0cc590b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2052ea921b948b005e475043599232e2e3128d16bb78286e0d181edaf9251d97",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_718ea490369f0ba79dc6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_718ea490369f0ba79dc6_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_718ea490369f0ba79dc6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6cea61fdb4f8c23b5ad745cf81bff7d69a607f42410dcba6d1276b70bfa332b9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 197760,
        },
    },
    "cake_kimi_k3_latent_moe_723fd0e64d35abe82b04": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_723fd0e64d35abe82b04_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_723fd0e64d35abe82b04_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7101cdf27aa2c70b25893e1c012de0c9cd5a84e3099b75d1542b1bba98bd0a07",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_726c7a11073ae2dc7264": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_726c7a11073ae2dc7264_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_726c7a11073ae2dc7264_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9c7baa649f3e32f35043684d67c748a6db51b7a582d80c07d125e3205d87c77f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 232448,
        },
    },
    "cake_kimi_k3_latent_moe_7998b9241646c7141eb1": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_7998b9241646c7141eb1_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_7998b9241646c7141eb1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1bf73d3a0d6f16652f6e3281af34c8b3d24328c8ea0ccadeaf8bc4454e112794",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 232448,
        },
    },
    "cake_kimi_k3_latent_moe_849b71c5342b7322b3ce": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_849b71c5342b7322b3ce_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_849b71c5342b7322b3ce_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fbbeb627b70486fe18ac0e299e027678acc02643520ce8460159966c534a811d",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 208896,
        },
    },
    "cake_kimi_k3_latent_moe_875e482c08c10315b0ce": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_875e482c08c10315b0ce_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_875e482c08c10315b0ce_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4ef2da552c38844f3dc2426fbdb24838892e0fba15174c49a65ad996a60ab5b9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_8a8f2a4cb044f782a635": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_8a8f2a4cb044f782a635_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_8a8f2a4cb044f782a635_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "337811f6fae979f80497dc1a51942de9fd944bafedc7f259818cab6c4a069c10",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 215040,
        },
    },
    "cake_kimi_k3_latent_moe_93daad03d5c8600716b3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_93daad03d5c8600716b3_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_93daad03d5c8600716b3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "661ec8478186032fb824b450a25c4b90a23d207627eb4fadbe5f6083459377b8",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_95554d8a7c79cf385b53": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_95554d8a7c79cf385b53_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_95554d8a7c79cf385b53_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "dfd6339ba6c0f0d6226fe6676b67bd0cf9b652a9879dd7808396485e36fb0c8a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 232448,
        },
    },
    "cake_kimi_k3_latent_moe_9a45e8eebda92f27f3de": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_9a45e8eebda92f27f3de_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_9a45e8eebda92f27f3de_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "048c99c01b631311bc895c4b2da87135a5be3c1da2ca480938f0116094eed379",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_9bd228462b4119320e1d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9bd228462b4119320e1d_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9bd228462b4119320e1d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7e10cf0a5694286b0c32f90f72eb13a8273aefd0b2f6c28e77e7d1ae467a8d3c",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 232448,
        },
    },
    "cake_kimi_k3_latent_moe_9bff19f8b33efea96887": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_9bff19f8b33efea96887_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_9bff19f8b33efea96887_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "94b025ee81af3c63897f2001861b6b1be639dcfebc7b67762c41098439338fec",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 197760,
        },
    },
    "cake_kimi_k3_latent_moe_9c1d14c06aa04e63ae85": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9c1d14c06aa04e63ae85_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9c1d14c06aa04e63ae85_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fb5c1b0683e91916ff0e886560c1d9d57de70898810feb20e2d36472969865ee",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 207872,
        },
    },
    "cake_kimi_k3_latent_moe_9c91a686804124a3199a": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9c91a686804124a3199a_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_9c91a686804124a3199a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["parameter", "M"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d69337ddd49e8139b5b49707dbf412e79e6351c3acee11e6d612ce569924fc0a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [128, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
        },
    },
    "cake_kimi_k3_latent_moe_a78b1f86a6900ef211b0": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_a78b1f86a6900ef211b0_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_a78b1f86a6900ef211b0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "08419e8a47ca24f96a61090e9107d7c8873bd3e011cb0cc9a2e9701928d9697a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_a7fb14cbc0a7e058870d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_a7fb14cbc0a7e058870d_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_a7fb14cbc0a7e058870d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ef42ec4697a11389f9da443120888fba7e3ae4cf442b0c64de86088c5bbf5678",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_adc52ee688a34bb929c3": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_adc52ee688a34bb929c3_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_adc52ee688a34bb929c3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "15b3d57065646b13e198064e782ab614868586d14c6aeb1b33bffc975d7659df",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_b0340a44d6ce9c208a0c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_b0340a44d6ce9c208a0c_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_b0340a44d6ce9c208a0c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d67265cdcbdae9b7154b5af3013689cddb27762fe737468897f5082cf9b087bb",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_b0bea74bdade1d5e4a1d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_b0bea74bdade1d5e4a1d_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_b0bea74bdade1d5e4a1d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bc93ef4a3ffed139257b13b1da35b82375c9be4e5c0a18a9527c5efe1cf776b7",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_b3518b4e4dfbdddf6b76": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_b3518b4e4dfbdddf6b76_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_b3518b4e4dfbdddf6b76_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "WG"],
            ["tma_buffer", "WD"],
            ["tma_buffer", "WS"],
            ["buffer", "logits"],
            ["buffer", "latent"],
            ["buffer", "shared_act"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a2283fbac176e42dc52a221366351c51806111bcf984f05f236463edef57722b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_ba8e19ca764ca0b5fb24": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_ba8e19ca764ca0b5fb24_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_ba8e19ca764ca0b5fb24_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f4bfc0433e03539235925030202740e227ee73567f0c3ef07d193429c30518fe",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_bb6028a533136505c652": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_bb6028a533136505c652_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_bb6028a533136505c652_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "3746c4c14ecd14f747f972417f73ed34a1c5699e5397a3633a96c69e32036138",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 199680,
        },
    },
    "cake_kimi_k3_latent_moe_bc102c266fb64a7ee4f3": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_bc102c266fb64a7ee4f3_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_bc102c266fb64a7ee4f3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "eed769431db300197ed08d7d2deabfd674e8d0389bb48d75b2868bb63745ed86",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_c15d90ffab06230b71a8": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_c15d90ffab06230b71a8_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_c15d90ffab06230b71a8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "372d61700d45d884f19a6095bb230f31917e5b207eb97dbbacbb91eb9144814e",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_c4900dec782af4802034": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_c4900dec782af4802034_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_c4900dec782af4802034_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "eb2547d4d1e4129fa19181021abf3f4259f7e3e76625027a766b6b9489d9105c",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_c961e9e410fe47042188": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_c961e9e410fe47042188_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_c961e9e410fe47042188_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1dc895ca8910fda88bb65cc2f279e0accfc1de8a23999da7c4bbd1af7419d6e7",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 215040,
        },
    },
    "cake_kimi_k3_latent_moe_cde89356488216968b16": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_cde89356488216968b16_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_cde89356488216968b16_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "201debdfac095ba813aaa81cecbc5cd3bf77af020b40edc788a5760fe906a53e",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 214016,
        },
    },
    "cake_kimi_k3_latent_moe_d1d722ccb1c7b4820ed0": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d1d722ccb1c7b4820ed0_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d1d722ccb1c7b4820ed0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "338e1c26f1adda6778227d2aca9dd2b972ecd62325c4611717ac261e148c0047",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_d54266e6944378998070": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_d54266e6944378998070_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_d54266e6944378998070_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "974d2ae9947503cf854e912780d7d6b313d2102b184e4ca0fefb37e74a52903a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_d56a5728110e874edb3e": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d56a5728110e874edb3e_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d56a5728110e874edb3e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "29432bae26e027c67c9c5a6bce1c430ce67ea495f5955110089369cd650fdef0",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 224256,
        },
    },
    "cake_kimi_k3_latent_moe_d6a47019f480e9ca2386": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d6a47019f480e9ca2386_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d6a47019f480e9ca2386_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "91c86f1fa46e3a282b841ac0ade62b965e49f90c0b3013bc6a6633f3f556ec00",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 214016,
        },
    },
    "cake_kimi_k3_latent_moe_d9e130e08329f83812b9": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d9e130e08329f83812b9_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_d9e130e08329f83812b9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d22bb430a2b32f3524690c57783a358a8310b6e649d77e2eb16e4de653bdf242",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_e1a706235b71a9f592eb": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_e1a706235b71a9f592eb_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_e1a706235b71a9f592eb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "de73225cee66691a2128d948fbe7ee373294cb2fbd6c8310facadb0bdc53a3c3",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_e6f991269ee9aa5a689b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_e6f991269ee9aa5a689b_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_e6f991269ee9aa5a689b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "WG"],
            ["tma_buffer", "WD"],
            ["tma_buffer", "WS"],
            ["buffer", "logits"],
            ["buffer", "latent"],
            ["buffer", "shared_act"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "633c3304552ac47b3278b4614a77acbae86ea4a3270f33cd620833eb73ef2271",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_edd88f8b8fde76bc5c48": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_edd88f8b8fde76bc5c48_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_edd88f8b8fde76bc5c48_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a3401d7f0ed3ed21016709a5b88a33eda067a75118ed9a14233e9c0b2b690508",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_f067f093cb0a158a0646": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f067f093cb0a158a0646_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f067f093cb0a158a0646_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "246c328f5b298ef10637ab919cacc247107ad92660791fa530a798f1bc8696ff",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
    "cake_kimi_k3_latent_moe_f072dbd29974a9db2e79": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f072dbd29974a9db2e79_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f072dbd29974a9db2e79_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A1"],
            ["tma_buffer", "B1"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B2"],
            ["buffer", "out"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "k0_blocks"],
            ["parameter", "num_items"],
            ["parameter", "full_items"],
            ["parameter", "sk_ipc"],
            ["parameter", "sk_max_seg"],
            ["parameter", "sk_total"],
            ["buffer", "routed"],
            ["buffer", "norm_weight"],
            ["buffer", "y_out"],
            ["buffer", "norm_counter"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "94b46f4f7d37c8387a246f22bacb36bd18c55f3cecd28138471d306053247967",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_f420c4bbfda366c98201": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f420c4bbfda366c98201_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f420c4bbfda366c98201_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6e900056417d750dceb33d90f418b0b4dab3534d0f0e4d89f71669ac54429caa",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 223232,
        },
    },
    "cake_kimi_k3_latent_moe_f59420f8cee8f4c16ec3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f59420f8cee8f4c16ec3_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f59420f8cee8f4c16ec3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "WG"],
            ["tma_buffer", "WD"],
            ["tma_buffer", "WS"],
            ["buffer", "logits"],
            ["buffer", "latent"],
            ["buffer", "shared_act"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a299dccc1d01f59bf8bcd821f9079f5dcafbb8835a2a38cd7cd63fe538379bc4",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_f64acd7a5c3c5e815321": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f64acd7a5c3c5e815321_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_100a/cake_kimi_k3_latent_moe_f64acd7a5c3c5e815321_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f50f0dec73d9730cffa6efca783c110cb4db14daa5aa7558185b09d6b91d8cdb",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 207872,
        },
    },
    "cake_kimi_k3_latent_moe_f9c11cd4b4fcd7ffc546": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f9c11cd4b4fcd7ffc546_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_f9c11cd4b4fcd7ffc546_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "WG"],
            ["tma_buffer", "WD"],
            ["tma_buffer", "WS"],
            ["buffer", "logits"],
            ["buffer", "latent"],
            ["buffer", "shared_act"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "94aa913cdc91d0b65976860ad47ea8fb9003054f4ccf96221c37a4170aa50959",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [320, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 230528,
        },
    },
    "cake_kimi_k3_latent_moe_fbb22f2cc231ae6bece5": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_fbb22f2cc231ae6bece5_kernel.cu",
            "cake_kimi_k3_latent_moe/sm_103a/cake_kimi_k3_latent_moe_fbb22f2cc231ae6bece5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A_R"],
            ["tma_buffer", "A_L"],
            ["tma_buffer", "A_S"],
            ["tma_buffer", "A_2"],
            ["tma_buffer", "B_1"],
            ["tma_buffer", "B_2"],
            ["buffer", "out_r"],
            ["buffer", "out_l"],
            ["buffer", "out_s"],
            ["buffer", "counters"],
            ["buffer", "routed"],
            ["buffer", "norm_w"],
            ["buffer", "y_out"],
            ["buffer", "tl"],
            ["parameter", "num_tokens"],
            ["parameter", "k1_off"],
            ["parameter", "num_partials"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d683e74f02058ab4f024da83c8c5359d5b2dd20c8bf9cfd566ba0fd0c3dcaf77",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [192, 1, 1],
            "cluster": [2, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 231424,
        },
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "decode:kimi_k3_latent_moe_decode_g112_n128_r5_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_693a2c08cdc4a10ac480",
        "decode:kimi_k3_latent_moe_decode_g112_n128_r5_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_9a45e8eebda92f27f3de",
        "decode:kimi_k3_latent_moe_decode_g112_n16_r12_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_1a07149fda6f32837a5d",
        "decode:kimi_k3_latent_moe_decode_g112_n16_r5_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_sb_rs_np": "cake_kimi_k3_latent_moe_726c7a11073ae2dc7264",
        "decode:kimi_k3_latent_moe_decode_g112_n32_r10_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_e1a706235b71a9f592eb",
        "decode:kimi_k3_latent_moe_decode_g112_n32_r10_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_b0bea74bdade1d5e4a1d",
        "decode:kimi_k3_latent_moe_decode_g112_n64_r8_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_a7fb14cbc0a7e058870d",
        "decode:kimi_k3_latent_moe_decode_g112_n64_r8_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_d1d722ccb1c7b4820ed0",
        "decode:kimi_k3_latent_moe_decode_g112_n8_r10_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f_sb": "cake_kimi_k3_latent_moe_849b71c5342b7322b3ce",
        "decode:kimi_k3_latent_moe_decode_g112_n8_r8_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_sb_rs": "cake_kimi_k3_latent_moe_d6a47019f480e9ca2386",
        "decode:kimi_k3_latent_moe_decode_g131_n128_r7_d1_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_7998b9241646c7141eb1",
        "decode:kimi_k3_latent_moe_decode_g131_n16_r6_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_d56a5728110e874edb3e",
        "decode:kimi_k3_latent_moe_decode_g131_n32_r5_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_f64acd7a5c3c5e815321",
        "decode:kimi_k3_latent_moe_decode_g131_n64_r4_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_bb6028a533136505c652",
        "decode:kimi_k3_latent_moe_decode_g131_n8_r6_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_2fc8595c9156169efb6a",
        "decode:kimi_k3_latent_moe_decode_g94_n128_r5_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_585cd1d9ed9505c38ccd",
        "decode:kimi_k3_latent_moe_decode_g94_n16_r6_d2_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_edd88f8b8fde76bc5c48",
        "decode:kimi_k3_latent_moe_decode_g94_n32_r10_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_a78b1f86a6900ef211b0",
        "decode:kimi_k3_latent_moe_decode_g94_n64_r8_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_2d1017bf8110b8557c82",
        "decode:kimi_k3_latent_moe_decode_g94_n8_r6_d2_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_8a8f2a4cb044f782a635",
        "front:i6144": "cake_kimi_k3_latent_moe_e6f991269ee9aa5a689b",
        "front:i768": "cake_kimi_k3_latent_moe_f59420f8cee8f4c16ec3",
        "tail_gemm:tp1e0f0": "cake_kimi_k3_latent_moe_d9e130e08329f83812b9",
        "tail_gemm:tp1e1f1": "cake_kimi_k3_latent_moe_c15d90ffab06230b71a8",
        "tail_gemm:tp1e1f1s6": "cake_kimi_k3_latent_moe_9bff19f8b33efea96887",
        "tail_gemm:tp8e0f0": "cake_kimi_k3_latent_moe_93daad03d5c8600716b3",
        "tail_gemm:tp8e1f0": "cake_kimi_k3_latent_moe_f072dbd29974a9db2e79",
        "tail_norm:e0": "cake_kimi_k3_latent_moe_50d173da21802ac2fc8e",
        "tail_norm:e1": "cake_kimi_k3_latent_moe_3dcbae5c1206f76ff7b7",
    },
    "sm_103a": {
        "decode:kimi_k3_latent_moe_decode_g112_n128_r5_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_6eda257b29eab0cc590b",
        "decode:kimi_k3_latent_moe_decode_g112_n128_r5_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_f067f093cb0a158a0646",
        "decode:kimi_k3_latent_moe_decode_g112_n16_r12_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_723fd0e64d35abe82b04",
        "decode:kimi_k3_latent_moe_decode_g112_n16_r5_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_sb_rs_np": "cake_kimi_k3_latent_moe_9bd228462b4119320e1d",
        "decode:kimi_k3_latent_moe_decode_g112_n32_r10_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_f420c4bbfda366c98201",
        "decode:kimi_k3_latent_moe_decode_g112_n32_r10_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_875e482c08c10315b0ce",
        "decode:kimi_k3_latent_moe_decode_g112_n64_r8_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f": "cake_kimi_k3_latent_moe_1c8ec1f6d247e9f47928",
        "decode:kimi_k3_latent_moe_decode_g112_n64_r8_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_g3": "cake_kimi_k3_latent_moe_b0340a44d6ce9c208a0c",
        "decode:kimi_k3_latent_moe_decode_g112_n8_r10_d1_p0_w0_t0_56_0_k56_96_o7168_c2_f_sb": "cake_kimi_k3_latent_moe_43e508f7d2c7fab8a61f",
        "decode:kimi_k3_latent_moe_decode_g112_n8_r8_d1_p0_w0_t0_56_0_k7_12_o7168_c2_f_sb_rs": "cake_kimi_k3_latent_moe_cde89356488216968b16",
        "decode:kimi_k3_latent_moe_decode_g131_n128_r7_d1_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_95554d8a7c79cf385b53",
        "decode:kimi_k3_latent_moe_decode_g131_n16_r6_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_1be3103a935cf7a1e309",
        "decode:kimi_k3_latent_moe_decode_g131_n32_r5_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_9c1d14c06aa04e63ae85",
        "decode:kimi_k3_latent_moe_decode_g131_n64_r4_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_2e23d9e9673f1f13c837",
        "decode:kimi_k3_latent_moe_decode_g131_n8_r6_d2_p0_w0_t7_28_96_k112_0_o3584_c1": "cake_kimi_k3_latent_moe_0cab4920389a7dbc994f",
        "decode:kimi_k3_latent_moe_decode_g94_n128_r5_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_d54266e6944378998070",
        "decode:kimi_k3_latent_moe_decode_g94_n16_r6_d2_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_fbb22f2cc231ae6bece5",
        "decode:kimi_k3_latent_moe_decode_g94_n32_r10_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_bc102c266fb64a7ee4f3",
        "decode:kimi_k3_latent_moe_decode_g94_n64_r8_d1_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_c4900dec782af4802034",
        "decode:kimi_k3_latent_moe_decode_g94_n8_r6_d2_p0_w0_t7_28_12_k112_0_o3584_c2": "cake_kimi_k3_latent_moe_c961e9e410fe47042188",
        "front:i6144": "cake_kimi_k3_latent_moe_b3518b4e4dfbdddf6b76",
        "front:i768": "cake_kimi_k3_latent_moe_f9c11cd4b4fcd7ffc546",
        "tail_gemm:tp1e0f0": "cake_kimi_k3_latent_moe_adc52ee688a34bb929c3",
        "tail_gemm:tp1e1f1": "cake_kimi_k3_latent_moe_66a583fa8fce7a147412",
        "tail_gemm:tp1e1f1s6": "cake_kimi_k3_latent_moe_718ea490369f0ba79dc6",
        "tail_gemm:tp8e0f0": "cake_kimi_k3_latent_moe_04b7802a48d2cb654059",
        "tail_gemm:tp8e1f0": "cake_kimi_k3_latent_moe_ba8e19ca764ca0b5fb24",
        "tail_norm:e0": "cake_kimi_k3_latent_moe_1e1a2d332efcb061ee59",
        "tail_norm:e1": "cake_kimi_k3_latent_moe_9c91a686804124a3199a",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 LatentMoE front/tail programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4568)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 LatentMoE kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4568)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_latent_moe_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_latent_moe_module(name: str):
    return gen_cake_kimi_k3_latent_moe_module(name).build_and_load()
