"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import (
    gen_jit_spec,
    sm100a_nvcc_flags,
    sm103a_nvcc_flags,
    sm107a_nvcc_flags,
)

# Registry of the generated Cake DSA indexer programs (written by the
# generated-program export; do not edit by hand).
#
# Every program is one device translation unit plus its host binding, shared
# by the architectures listed in its record; the loader compiles it with the
# exact flag set of the device it runs on.  ``ARG_PLANS`` holds the one
# argument order per stage role (``scan``: a persistent fused scoring /
# selection program; ``merge``: the split-range merge; ``finalize``: the
# ascending-id row sort by CUB block radix sort; ``finalize_rank``: the same
# sort as a prefix-popcount rank scatter), ``COMPILE_FLAGS`` the extra nvcc
# flags per role,
# ``PROGRAMS`` every program once with its role, sources, architectures and
# launch geometry, ``PROGRAM_KEYS`` the program of every host dispatch key per
# architecture (see ``cake_policy``), ``PROGRAM_LEVERS`` the program-text
# levers of every scan key per architecture, ``POLICY`` the per-architecture
# host dispatch record and ``NUMERICS`` the documented numerics of the
# programs.
ARCHES = ("sm_100a", "sm_103a", "sm_107a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
    "sm_107a": sm107a_nvcc_flags,
}
STAGES: list[str] = ["scan", "merge", "finalize", "finalize_rank"]
ABI: str = "dsa_indexer_v2"
NUMERICS: dict[str, str] = {"zero_sign_policy": "positive_accumulator"}
COMPILE_FLAGS: dict[str, list[str]] = {
    "scan": ["--ptxas-options=--register-usage-level=10"],
    "merge": [],
    "finalize": [],
    "finalize_rank": [],
}
FFI_ENTRY: str = "run"
ARG_PLANS: dict[str, list[list[str]]] = {
    "scan": [
        ["tma_buffer", "Q"],
        ["tma_buffer", "K"],
        ["tma_buffer", "W"],
        ["buffer", "cu_seqlens_q"],
        ["buffer", "cu_seqlens_k"],
        ["buffer", "q_offsets"],
        ["buffer", "Indices"],
        ["buffer", "Scores"],
        ["buffer", "Cand"],
        ["parameter", "num_segments"],
        ["parameter", "top_k"],
        ["parameter", "ratio"],
        ["parameter", "has_offsets"],
        ["parameter", "cand_cap"],
        ["parameter", "first_cap"],
        ["parameter", "sample_tiles_max"],
        ["parameter", "sample_shift_permille"],
        ["parameter", "check_period"],
        ["parameter", "grid_ctas"],
        ["parameter", "softmax_scale"],
        ["parameter", "n_split"],
        ["grid", "grid_x"],
        ["grid", "grid_y"],
        ["grid", "grid_z"],
    ],
    "merge": [
        ["buffer", "Staging"],
        ["buffer", "Indices"],
        ["buffer", "Scores"],
        ["parameter", "top_k"],
        ["parameter", "n_split"],
        ["grid", "grid_x"],
        ["grid", "grid_y"],
        ["grid", "grid_z"],
    ],
    "finalize": [
        ["buffer", "Indices"],
        ["buffer", "Scores"],
        ["parameter", "top_k"],
        ["parameter", "key_bits"],
        ["grid", "grid_x"],
        ["grid", "grid_y"],
        ["grid", "grid_z"],
    ],
    "finalize_rank": [
        ["buffer", "Indices"],
        ["buffer", "Scores"],
        ["buffer", "cu_seqlens_q"],
        ["buffer", "cu_seqlens_k"],
        ["parameter", "top_k"],
        ["parameter", "num_segments"],
        ["grid", "grid_x"],
        ["grid", "grid_y"],
        ["grid", "grid_z"],
    ],
}
PROGRAMS: dict[str, dict[str, Any]] = {
    "cake_dsa_indexer_topk_0adc4d67e5b5d40575e4": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0adc4d67e5b5d40575e4_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0adc4d67e5b5d40575e4_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_0c52296aaacdeb3a81d5": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0c52296aaacdeb3a81d5_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0c52296aaacdeb3a81d5_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_0ef78428a247cd3ba657": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0ef78428a247cd3ba657_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0ef78428a247cd3ba657_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_0f1681cc69326ab5a544": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0f1681cc69326ab5a544_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_0f1681cc69326ab5a544_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_1492170b20fc47c7d428": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_1492170b20fc47c7d428_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_1492170b20fc47c7d428_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_1cc6df0c6146aeb97456": {
        "role": "finalize",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_1cc6df0c6146aeb97456_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_1cc6df0c6146aeb97456_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [32, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_21522e95c423bab66e17": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_21522e95c423bab66e17_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_21522e95c423bab66e17_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_22bbbf84360f9c05f67d": {
        "role": "finalize",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_22bbbf84360f9c05f67d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_22bbbf84360f9c05f67d_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [128, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_24d8d107b3bb1f008f4b": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_24d8d107b3bb1f008f4b_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_24d8d107b3bb1f008f4b_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_257aca02c3800c5469a8": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_257aca02c3800c5469a8_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_257aca02c3800c5469a8_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_2ef8c86ca54f53ae1307": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_2ef8c86ca54f53ae1307_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_2ef8c86ca54f53ae1307_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [512, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_2fe0126b892ee4987459": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_2fe0126b892ee4987459_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_2fe0126b892ee4987459_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_3a0c2aa0cb0d211be224": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_3a0c2aa0cb0d211be224_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_3a0c2aa0cb0d211be224_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_3bfc784be769cddd720f": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_3bfc784be769cddd720f_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_3bfc784be769cddd720f_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_494100c6d43499dbddcc": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_494100c6d43499dbddcc_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_494100c6d43499dbddcc_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_50b07189c2e1f00b629d": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_50b07189c2e1f00b629d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_50b07189c2e1f00b629d_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_527ae037f0e9c06f3847": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_527ae037f0e9c06f3847_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_527ae037f0e9c06f3847_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_5c899d28c62e56c0ccd1": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_5c899d28c62e56c0ccd1_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_5c899d28c62e56c0ccd1_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_5d4378586ed6bf9bb17a": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_5d4378586ed6bf9bb17a_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_5d4378586ed6bf9bb17a_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_61fd207f5fdf731d82a4": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_61fd207f5fdf731d82a4_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_61fd207f5fdf731d82a4_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_6305f5d2a16f282edad3": {
        "role": "finalize",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6305f5d2a16f282edad3_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6305f5d2a16f282edad3_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_67fd57e228a2fe642ca3": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_67fd57e228a2fe642ca3_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_67fd57e228a2fe642ca3_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_6823255efa8aa892c05d": {
        "role": "finalize",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6823255efa8aa892c05d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6823255efa8aa892c05d_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_6badf6136e1372ff9d50": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6badf6136e1372ff9d50_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_6badf6136e1372ff9d50_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_807bcb6d08d4e426c891": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_807bcb6d08d4e426c891_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_807bcb6d08d4e426c891_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_846ae05af378bd9da2f3": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_846ae05af378bd9da2f3_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_846ae05af378bd9da2f3_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_907988957778b590b911": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_907988957778b590b911_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_907988957778b590b911_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_92beb5486c687e181dbe": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_92beb5486c687e181dbe_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_92beb5486c687e181dbe_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_94058e01cb2bb832c14c": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_94058e01cb2bb832c14c_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_94058e01cb2bb832c14c_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_9ba274dc5baac2da59af": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_9ba274dc5baac2da59af_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_9ba274dc5baac2da59af_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_9e0874a172ec9dd93510": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_9e0874a172ec9dd93510_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_9e0874a172ec9dd93510_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_a44e80f15a3c7450b738": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_a44e80f15a3c7450b738_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_a44e80f15a3c7450b738_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_a758aa5c76e516973076": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_a758aa5c76e516973076_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_a758aa5c76e516973076_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_ac0da5fc30fa2ca76207": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ac0da5fc30fa2ca76207_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ac0da5fc30fa2ca76207_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_add377e1a841e5fd9542": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_add377e1a841e5fd9542_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_add377e1a841e5fd9542_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_be0774ab4354eaac13d7": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_be0774ab4354eaac13d7_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_be0774ab4354eaac13d7_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [512, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_bf275e87a17938257f90": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_bf275e87a17938257f90_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_bf275e87a17938257f90_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_bf847a5d9a963b6de4c6": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_bf847a5d9a963b6de4c6_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_bf847a5d9a963b6de4c6_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_c1d286d05aaf35d58099": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c1d286d05aaf35d58099_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c1d286d05aaf35d58099_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_c273f97a1ad2e57d28cc": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c273f97a1ad2e57d28cc_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c273f97a1ad2e57d28cc_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_c3e981db728d64f7d74b": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c3e981db728d64f7d74b_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c3e981db728d64f7d74b_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_c5ecb2ad77c166575be9": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c5ecb2ad77c166575be9_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c5ecb2ad77c166575be9_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_c64313dd4e72fd45145b": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c64313dd4e72fd45145b_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c64313dd4e72fd45145b_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_c684babcb42d963a375e": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c684babcb42d963a375e_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_c684babcb42d963a375e_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_ca94e732693c821ec98f": {
        "role": "finalize",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ca94e732693c821ec98f_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ca94e732693c821ec98f_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [64, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_cb21dbc97e7c39162e1d": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_cb21dbc97e7c39162e1d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_cb21dbc97e7c39162e1d_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_cf83ea703f77cb925b27": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_cf83ea703f77cb925b27_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_cf83ea703f77cb925b27_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_d15778229395ec43d0ad": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d15778229395ec43d0ad_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d15778229395ec43d0ad_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_d194cadc957412227f47": {
        "role": "merge",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d194cadc957412227f47_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d194cadc957412227f47_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_d31b85899f533d6fddd6": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d31b85899f533d6fddd6_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d31b85899f533d6fddd6_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_d75923fd5232beceacf9": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d75923fd5232beceacf9_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d75923fd5232beceacf9_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_d883964564367b7ef09d": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d883964564367b7ef09d_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_d883964564367b7ef09d_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_dabd609a7901c33aaf43": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_dabd609a7901c33aaf43_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_dabd609a7901c33aaf43_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_e28f007fd6e60c0fbf19": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e28f007fd6e60c0fbf19_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e28f007fd6e60c0fbf19_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_e300f4f160ba24e6f870": {
        "role": "finalize_rank",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e300f4f160ba24e6f870_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e300f4f160ba24e6f870_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a", "sm_107a"],
        "launch": {"block": [256, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_e5489676e22f51e98967": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e5489676e22f51e98967_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e5489676e22f51e98967_binding.cu",
        ],
        "arches": ["sm_100a", "sm_103a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_e5a04a058759c5b52879": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e5a04a058759c5b52879_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_e5a04a058759c5b52879_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_ea599e082d17699a4c6e": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ea599e082d17699a4c6e_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ea599e082d17699a4c6e_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_ed6c69268e6a2c9f46e6": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ed6c69268e6a2c9f46e6_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ed6c69268e6a2c9f46e6_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
    "cake_dsa_indexer_topk_fe1d393e6a5e24ee258a": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_fe1d393e6a5e24ee258a_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_fe1d393e6a5e24ee258a_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [512, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dsa_indexer_topk_ffe34a2b30f7d233be44": {
        "role": "scan",
        "sources": [
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ffe34a2b30f7d233be44_kernel.cu",
            "cake_dsa_indexer_topk/cake_dsa_indexer_topk_ffe34a2b30f7d233be44_binding.cu",
        ],
        "arches": ["sm_107a"],
        "launch": {"block": [384, 1, 1], "cluster": [1, 1, 1]},
    },
}
PROGRAM_KEYS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "finalize:t128": "cake_dsa_indexer_topk_22bbbf84360f9c05f67d",
        "finalize:t256": "cake_dsa_indexer_topk_6823255efa8aa892c05d",
        "finalize:t32": "cake_dsa_indexer_topk_1cc6df0c6146aeb97456",
        "finalize:t512": "cake_dsa_indexer_topk_6305f5d2a16f282edad3",
        "finalize:t64": "cake_dsa_indexer_topk_ca94e732693c821ec98f",
        "finalize_rank:t256:w131072:two:staged": "cake_dsa_indexer_topk_527ae037f0e9c06f3847",
        "finalize_rank:t256:w131072:two:staged:bulk": "cake_dsa_indexer_topk_807bcb6d08d4e426c891",
        "finalize_rank:t256:w131072:two:staged:i16": "cake_dsa_indexer_topk_cf83ea703f77cb925b27",
        "finalize_rank:t256:w131072:two:staged:i16:bulk": "cake_dsa_indexer_topk_0adc4d67e5b5d40575e4",
        "finalize_rank:t256:w16384:staged": "cake_dsa_indexer_topk_dabd609a7901c33aaf43",
        "finalize_rank:t256:w16384:staged:bulk": "cake_dsa_indexer_topk_0f1681cc69326ab5a544",
        "finalize_rank:t256:w16384:staged:i16": "cake_dsa_indexer_topk_bf275e87a17938257f90",
        "finalize_rank:t256:w16384:staged:i16:bulk": "cake_dsa_indexer_topk_a758aa5c76e516973076",
        "finalize_rank:t256:w262144:two:staged": "cake_dsa_indexer_topk_e300f4f160ba24e6f870",
        "finalize_rank:t256:w262144:two:staged:bulk": "cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66",
        "finalize_rank:t256:w262144:two:staged:i16": "cake_dsa_indexer_topk_d75923fd5232beceacf9",
        "finalize_rank:t256:w262144:two:staged:i16:bulk": "cake_dsa_indexer_topk_e28f007fd6e60c0fbf19",
        "finalize_rank:t256:w524288:two:staged": "cake_dsa_indexer_topk_50b07189c2e1f00b629d",
        "finalize_rank:t256:w524288:two:staged:bulk": "cake_dsa_indexer_topk_3bfc784be769cddd720f",
        "finalize_rank:t256:w524288:two:staged:i16": "cake_dsa_indexer_topk_c1d286d05aaf35d58099",
        "finalize_rank:t256:w524288:two:staged:i16:bulk": "cake_dsa_indexer_topk_257aca02c3800c5469a8",
        "finalize_rank:t256:w65536:staged": "cake_dsa_indexer_topk_907988957778b590b911",
        "finalize_rank:t256:w65536:staged:bulk": "cake_dsa_indexer_topk_6badf6136e1372ff9d50",
        "finalize_rank:t256:w65536:staged:i16": "cake_dsa_indexer_topk_94058e01cb2bb832c14c",
        "finalize_rank:t256:w65536:staged:i16:bulk": "cake_dsa_indexer_topk_0ef78428a247cd3ba657",
        "finalize_rank:t256:w8192:staged": "cake_dsa_indexer_topk_9e0874a172ec9dd93510",
        "finalize_rank:t256:w8192:staged:bulk": "cake_dsa_indexer_topk_c64313dd4e72fd45145b",
        "merge": "cake_dsa_indexer_topk_d194cadc957412227f47",
        "scan:l6:u1:s0:f0": "cake_dsa_indexer_topk_61fd207f5fdf731d82a4",
        "scan:l6:u1:s0:f1": "cake_dsa_indexer_topk_494100c6d43499dbddcc",
        "scan:narrow:u1:s0:f0": "cake_dsa_indexer_topk_d31b85899f533d6fddd6",
        "scan:narrow:u1:s0:f1": "cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d",
        "scan:pair_l6:u1:s0:f0": "cake_dsa_indexer_topk_2ef8c86ca54f53ae1307",
        "scan:pair_l6:u1:s0:f1": "cake_dsa_indexer_topk_be0774ab4354eaac13d7",
        "scan:split_l6:u1:s0:f0": "cake_dsa_indexer_topk_0c52296aaacdeb3a81d5",
        "scan:split_narrow:u1:s0:f0": "cake_dsa_indexer_topk_a44e80f15a3c7450b738",
        "scan:wide:u1:s0:f0": "cake_dsa_indexer_topk_e5489676e22f51e98967",
        "scan:wide:u1:s0:f1": "cake_dsa_indexer_topk_92beb5486c687e181dbe",
    },
    "sm_103a": {
        "finalize:t128": "cake_dsa_indexer_topk_22bbbf84360f9c05f67d",
        "finalize:t256": "cake_dsa_indexer_topk_6823255efa8aa892c05d",
        "finalize:t32": "cake_dsa_indexer_topk_1cc6df0c6146aeb97456",
        "finalize:t512": "cake_dsa_indexer_topk_6305f5d2a16f282edad3",
        "finalize:t64": "cake_dsa_indexer_topk_ca94e732693c821ec98f",
        "finalize_rank:t256:w131072:two:staged": "cake_dsa_indexer_topk_527ae037f0e9c06f3847",
        "finalize_rank:t256:w131072:two:staged:bulk": "cake_dsa_indexer_topk_807bcb6d08d4e426c891",
        "finalize_rank:t256:w131072:two:staged:i16": "cake_dsa_indexer_topk_cf83ea703f77cb925b27",
        "finalize_rank:t256:w131072:two:staged:i16:bulk": "cake_dsa_indexer_topk_0adc4d67e5b5d40575e4",
        "finalize_rank:t256:w16384:staged": "cake_dsa_indexer_topk_dabd609a7901c33aaf43",
        "finalize_rank:t256:w16384:staged:bulk": "cake_dsa_indexer_topk_0f1681cc69326ab5a544",
        "finalize_rank:t256:w16384:staged:i16": "cake_dsa_indexer_topk_bf275e87a17938257f90",
        "finalize_rank:t256:w16384:staged:i16:bulk": "cake_dsa_indexer_topk_a758aa5c76e516973076",
        "finalize_rank:t256:w262144:two:staged": "cake_dsa_indexer_topk_e300f4f160ba24e6f870",
        "finalize_rank:t256:w262144:two:staged:bulk": "cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66",
        "finalize_rank:t256:w262144:two:staged:i16": "cake_dsa_indexer_topk_d75923fd5232beceacf9",
        "finalize_rank:t256:w262144:two:staged:i16:bulk": "cake_dsa_indexer_topk_e28f007fd6e60c0fbf19",
        "finalize_rank:t256:w524288:two:staged": "cake_dsa_indexer_topk_50b07189c2e1f00b629d",
        "finalize_rank:t256:w524288:two:staged:bulk": "cake_dsa_indexer_topk_3bfc784be769cddd720f",
        "finalize_rank:t256:w524288:two:staged:i16": "cake_dsa_indexer_topk_c1d286d05aaf35d58099",
        "finalize_rank:t256:w524288:two:staged:i16:bulk": "cake_dsa_indexer_topk_257aca02c3800c5469a8",
        "finalize_rank:t256:w65536:staged": "cake_dsa_indexer_topk_907988957778b590b911",
        "finalize_rank:t256:w65536:staged:bulk": "cake_dsa_indexer_topk_6badf6136e1372ff9d50",
        "finalize_rank:t256:w65536:staged:i16": "cake_dsa_indexer_topk_94058e01cb2bb832c14c",
        "finalize_rank:t256:w65536:staged:i16:bulk": "cake_dsa_indexer_topk_0ef78428a247cd3ba657",
        "finalize_rank:t256:w8192:staged": "cake_dsa_indexer_topk_9e0874a172ec9dd93510",
        "finalize_rank:t256:w8192:staged:bulk": "cake_dsa_indexer_topk_c64313dd4e72fd45145b",
        "merge": "cake_dsa_indexer_topk_d194cadc957412227f47",
        "scan:l6:u1:s0:f0": "cake_dsa_indexer_topk_61fd207f5fdf731d82a4",
        "scan:l6:u1:s0:f1": "cake_dsa_indexer_topk_494100c6d43499dbddcc",
        "scan:narrow:u1:s0:f0": "cake_dsa_indexer_topk_d31b85899f533d6fddd6",
        "scan:narrow:u1:s0:f1": "cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d",
        "scan:pair_l6:u1:s0:f0": "cake_dsa_indexer_topk_2ef8c86ca54f53ae1307",
        "scan:pair_l6:u1:s0:f1": "cake_dsa_indexer_topk_be0774ab4354eaac13d7",
        "scan:split_l6:u1:s0:f0": "cake_dsa_indexer_topk_0c52296aaacdeb3a81d5",
        "scan:split_narrow:u1:s0:f0": "cake_dsa_indexer_topk_a44e80f15a3c7450b738",
        "scan:wide:u1:s0:f0": "cake_dsa_indexer_topk_e5489676e22f51e98967",
        "scan:wide:u1:s0:f1": "cake_dsa_indexer_topk_92beb5486c687e181dbe",
    },
    "sm_107a": {
        "finalize:t128": "cake_dsa_indexer_topk_22bbbf84360f9c05f67d",
        "finalize:t256": "cake_dsa_indexer_topk_6823255efa8aa892c05d",
        "finalize:t32": "cake_dsa_indexer_topk_1cc6df0c6146aeb97456",
        "finalize:t512": "cake_dsa_indexer_topk_6305f5d2a16f282edad3",
        "finalize:t64": "cake_dsa_indexer_topk_ca94e732693c821ec98f",
        "finalize_rank:t256:w131072:two:staged": "cake_dsa_indexer_topk_527ae037f0e9c06f3847",
        "finalize_rank:t256:w131072:two:staged:bulk": "cake_dsa_indexer_topk_807bcb6d08d4e426c891",
        "finalize_rank:t256:w131072:two:staged:i16": "cake_dsa_indexer_topk_cf83ea703f77cb925b27",
        "finalize_rank:t256:w131072:two:staged:i16:bulk": "cake_dsa_indexer_topk_0adc4d67e5b5d40575e4",
        "finalize_rank:t256:w16384:staged": "cake_dsa_indexer_topk_dabd609a7901c33aaf43",
        "finalize_rank:t256:w16384:staged:bulk:persist": "cake_dsa_indexer_topk_3a0c2aa0cb0d211be224",
        "finalize_rank:t256:w16384:staged:i16": "cake_dsa_indexer_topk_bf275e87a17938257f90",
        "finalize_rank:t256:w16384:staged:i16:bulk": "cake_dsa_indexer_topk_a758aa5c76e516973076",
        "finalize_rank:t256:w262144:two:staged": "cake_dsa_indexer_topk_e300f4f160ba24e6f870",
        "finalize_rank:t256:w262144:two:staged:bulk": "cake_dsa_indexer_topk_ae78ae8b0d4a793aaf66",
        "finalize_rank:t256:w262144:two:staged:i16": "cake_dsa_indexer_topk_d75923fd5232beceacf9",
        "finalize_rank:t256:w262144:two:staged:i16:bulk": "cake_dsa_indexer_topk_e28f007fd6e60c0fbf19",
        "finalize_rank:t256:w524288:two:staged": "cake_dsa_indexer_topk_50b07189c2e1f00b629d",
        "finalize_rank:t256:w524288:two:staged:bulk": "cake_dsa_indexer_topk_3bfc784be769cddd720f",
        "finalize_rank:t256:w524288:two:staged:i16": "cake_dsa_indexer_topk_c1d286d05aaf35d58099",
        "finalize_rank:t256:w524288:two:staged:i16:bulk": "cake_dsa_indexer_topk_257aca02c3800c5469a8",
        "finalize_rank:t256:w65536:staged": "cake_dsa_indexer_topk_907988957778b590b911",
        "finalize_rank:t256:w65536:staged:bulk:persist": "cake_dsa_indexer_topk_67fd57e228a2fe642ca3",
        "finalize_rank:t256:w65536:staged:i16": "cake_dsa_indexer_topk_94058e01cb2bb832c14c",
        "finalize_rank:t256:w65536:staged:i16:bulk": "cake_dsa_indexer_topk_0ef78428a247cd3ba657",
        "finalize_rank:t256:w8192:staged": "cake_dsa_indexer_topk_9e0874a172ec9dd93510",
        "finalize_rank:t256:w8192:staged:bulk:persist": "cake_dsa_indexer_topk_9ba274dc5baac2da59af",
        "merge": "cake_dsa_indexer_topk_d194cadc957412227f47",
        "scan:l6:u1:s0:f0": "cake_dsa_indexer_topk_c3e981db728d64f7d74b",
        "scan:l6:u1:s0:f1": "cake_dsa_indexer_topk_add377e1a841e5fd9542",
        "scan:l6:u1:s1:f1": "cake_dsa_indexer_topk_c684babcb42d963a375e",
        "scan:narrow:u1:s0:f0": "cake_dsa_indexer_topk_d31b85899f533d6fddd6",
        "scan:narrow:u1:s0:f1": "cake_dsa_indexer_topk_b6aafd22b9c6a9e0c96d",
        "scan:narrow:u1:s1:f1": "cake_dsa_indexer_topk_846ae05af378bd9da2f3",
        "scan:narrow:u2:s0:f0": "cake_dsa_indexer_topk_ed6c69268e6a2c9f46e6",
        "scan:pair_l6:u1:s0:f0": "cake_dsa_indexer_topk_fe1d393e6a5e24ee258a",
        "scan:pair_l6:u1:s0:f1": "cake_dsa_indexer_topk_ac0da5fc30fa2ca76207",
        "scan:pair_l6:u1:s1:f1": "cake_dsa_indexer_topk_1492170b20fc47c7d428",
        "scan:pair_narrow:u1:s1:f1": "cake_dsa_indexer_topk_bf847a5d9a963b6de4c6",
        "scan:pair_narrow:u2:s0:f0": "cake_dsa_indexer_topk_c273f97a1ad2e57d28cc",
        "scan:pair_narrow:u2:s0:f1": "cake_dsa_indexer_topk_21522e95c423bab66e17",
        "scan:pair_wide:u1:s1:f0": "cake_dsa_indexer_topk_5c899d28c62e56c0ccd1",
        "scan:pair_wide:u1:s1:f1": "cake_dsa_indexer_topk_24d8d107b3bb1f008f4b",
        "scan:pair_wide:u2:s0:f0": "cake_dsa_indexer_topk_5d4378586ed6bf9bb17a",
        "scan:pair_wide:u2:s0:f1": "cake_dsa_indexer_topk_ea599e082d17699a4c6e",
        "scan:split_narrow:u1:s0:f0": "cake_dsa_indexer_topk_a44e80f15a3c7450b738",
        "scan:split_wide:u1:s0:f0": "cake_dsa_indexer_topk_d15778229395ec43d0ad",
        "scan:split_wide:u2:s0:f0": "cake_dsa_indexer_topk_c5ecb2ad77c166575be9",
        "scan:wide:u1:s0:f0": "cake_dsa_indexer_topk_cb21dbc97e7c39162e1d",
        "scan:wide:u1:s0:f1": "cake_dsa_indexer_topk_e5a04a058759c5b52879",
        "scan:wide:u1:s1:f0": "cake_dsa_indexer_topk_2fe0126b892ee4987459",
        "scan:wide:u1:s1:f1": "cake_dsa_indexer_topk_ffe34a2b30f7d233be44",
        "scan:wide:u2:s0:f0": "cake_dsa_indexer_topk_d883964564367b7ef09d",
    },
}
PROGRAM_LEVERS: dict[str, dict[str, dict[str, Any]]] = {
    "sm_100a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": True,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": True,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
    },
    "sm_103a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
    },
    "sm_107a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:l6:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:narrow:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_narrow:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_narrow:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_narrow:u2:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_wide:u1:s1:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": [10, 10],
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": False,
        },
        "scan:pair_wide:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": [10, 10],
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_wide:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_wide:u2:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_wide:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_wide:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:wide:u1:s1:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": False,
        },
        "scan:wide:u1:s1:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:wide:u2:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
    },
}
POLICY: dict[str, dict[str, Any]] = {
    "sm_100a": {
        "tile_keys": 128,
        "block_q_narrow": 4,
        "block_q_wide": 8,
        "block_q_l6": 6,
        "candidate_entry_bytes": 8,
        "candidate_multiplier": 4,
        "candidate_slack": 128,
        "cand_mult_rule": [384.0, 8],
        "cand_cap_floor": 8192,
        "l6_rule": [256.0, 512],
        "wide_rule": [6.0, 300.0],
        "split_max": 32,
        "split_min_range_tiles": 64,
        "split_wave_rule": None,
        "pair_rule": [128.0, 256.0, 512],
        "snake_default": False,
        "snake_rule": None,
        "tile_unroll_default": 1,
        "tile_unroll_factor": 1,
        "tile_unroll_rule": None,
        "sample_fit_max_mean_tiles": 512.0,
        "sample_tiles_max": 32,
        "sample_tiles_short_units": 16,
        "sample_dispatch_mean_tiles_max": 640.0,
        "sample_tiles_tiny_units": 8,
        "sample_dispatch_tiny_tiles_max": 128.0,
        "sample_shift_permille": 250,
        "check_period_max": 32,
        "check_period_knob_max": 64,
        "check_period_cap_divisor": 512,
        "check_period_kind_overrides": {},
        "finalize_items": 8,
        "finalize_threads_fit": [32, 64, 128],
        "finalize_threads_small": 256,
        "finalize_top_k_small": 2048,
        "finalize_threads": 512,
        "finalize_fit": True,
        "finalize_exact_key_bits": True,
        "rank_finalize": True,
        "rank_window_variants": [8192, 16384, 65536, 131072, 262144, 524288],
        "rank_top_k_min": 1025,
        "rank_rule": [524288, 262144],
        "rank_staged": True,
        "rank_staged_rule": [262144],
        "rank_seg_window": True,
        "rank_window_variants_seg_only": [131072],
        "rank_two_level": True,
        "rank_two_level_window_variants": [131072, 262144, 524288, 1048576],
        "rank_slab_window_max": 65536,
        "rank_two_level_rule": [524288],
        "rank_two_level_staged_rule": [524288],
        "rank_bulk_io": True,
        "rank_bulk_align_bytes": 16,
        "rank_t16": True,
        "rank_t16_slots": [4096],
        "rank_persist_max_k": 0,
        "rank_persist_ctas_per_sm": 4,
    },
    "sm_103a": {
        "tile_keys": 128,
        "block_q_narrow": 4,
        "block_q_wide": 8,
        "block_q_l6": 6,
        "candidate_entry_bytes": 8,
        "candidate_multiplier": 4,
        "candidate_slack": 128,
        "cand_mult_rule": [384.0, 8],
        "cand_cap_floor": 8192,
        "l6_rule": [1024.0, 512],
        "wide_rule": [6.0, 300.0],
        "split_max": 32,
        "split_min_range_tiles": 64,
        "split_wave_rule": None,
        "pair_rule": [64.0, 1024.0, 512],
        "snake_default": False,
        "snake_rule": None,
        "tile_unroll_default": 1,
        "tile_unroll_factor": 1,
        "tile_unroll_rule": None,
        "sample_fit_max_mean_tiles": 512.0,
        "sample_tiles_max": 32,
        "sample_tiles_short_units": 16,
        "sample_dispatch_mean_tiles_max": 640.0,
        "sample_tiles_tiny_units": 8,
        "sample_dispatch_tiny_tiles_max": 128.0,
        "sample_shift_permille": 250,
        "check_period_max": 32,
        "check_period_knob_max": 64,
        "check_period_cap_divisor": 512,
        "check_period_kind_overrides": {"wide": 32},
        "finalize_items": 8,
        "finalize_threads_fit": [32, 64, 128],
        "finalize_threads_small": 256,
        "finalize_top_k_small": 2048,
        "finalize_threads": 512,
        "finalize_fit": True,
        "finalize_exact_key_bits": True,
        "rank_finalize": True,
        "rank_window_variants": [8192, 16384, 65536, 131072, 262144, 524288],
        "rank_top_k_min": 1025,
        "rank_rule": [524288, 262144],
        "rank_staged": True,
        "rank_staged_rule": [262144],
        "rank_seg_window": True,
        "rank_window_variants_seg_only": [131072],
        "rank_two_level": True,
        "rank_two_level_window_variants": [131072, 262144, 524288, 1048576],
        "rank_slab_window_max": 65536,
        "rank_two_level_rule": [524288],
        "rank_two_level_staged_rule": [524288],
        "rank_bulk_io": True,
        "rank_bulk_align_bytes": 16,
        "rank_t16": True,
        "rank_t16_slots": [4096],
        "rank_persist_max_k": 0,
        "rank_persist_ctas_per_sm": 4,
    },
    "sm_107a": {
        "tile_keys": 128,
        "block_q_narrow": 4,
        "block_q_wide": 8,
        "block_q_l6": 6,
        "candidate_entry_bytes": 8,
        "candidate_multiplier": 4,
        "candidate_slack": 128,
        "cand_mult_rule": [384.0, 8],
        "cand_cap_floor": 8192,
        "l6_rule": [64.0, 0],
        "wide_rule": [2.0, 250.0],
        "split_max": 32,
        "split_min_range_tiles": 64,
        "split_wave_rule": [1000, 0.12],
        "pair_rule": [0.0, 4096.0, 512],
        "snake_default": False,
        "snake_rule": [
            ["l6", "narrow", "pair_l6", "pair_narrow", "pair_wide", "wide"],
            32.0,
            128.0,
            0.5,
        ],
        "tile_unroll_default": 1,
        "tile_unroll_factor": 2,
        "tile_unroll_rule": [
            ["narrow", "pair_narrow", "pair_wide", "split_wide", "wide"],
            512,
            True,
        ],
        "sample_fit_max_mean_tiles": 512.0,
        "sample_tiles_max": 32,
        "sample_tiles_short_units": 16,
        "sample_dispatch_mean_tiles_max": 640.0,
        "sample_tiles_tiny_units": 8,
        "sample_dispatch_tiny_tiles_max": 128.0,
        "sample_shift_permille": 250,
        "check_period_max": 32,
        "check_period_knob_max": 64,
        "check_period_cap_divisor": 512,
        "check_period_kind_overrides": {},
        "finalize_items": 8,
        "finalize_threads_fit": [32, 64, 128],
        "finalize_threads_small": 256,
        "finalize_top_k_small": 2048,
        "finalize_threads": 512,
        "finalize_fit": True,
        "finalize_exact_key_bits": True,
        "rank_finalize": True,
        "rank_window_variants": [8192, 16384, 65536, 131072, 262144, 524288],
        "rank_top_k_min": 1025,
        "rank_rule": [524288, 262144],
        "rank_staged": True,
        "rank_staged_rule": [262144],
        "rank_seg_window": True,
        "rank_window_variants_seg_only": [131072],
        "rank_two_level": True,
        "rank_two_level_window_variants": [131072, 262144, 524288, 1048576],
        "rank_slab_window_max": 65536,
        "rank_two_level_rule": [524288],
        "rank_two_level_staged_rule": [524288],
        "rank_bulk_io": True,
        "rank_bulk_align_bytes": 16,
        "rank_t16": True,
        "rank_t16_slots": [4096],
        "rank_persist_max_k": 2048,
        "rank_persist_ctas_per_sm": 4,
    },
}
TRACKING_ISSUE = "flashinfer-ai/flashinfer#5676"


@functools.cache
def toolchain_supports(arch: str) -> bool:
    """Can the nvcc this checkout invokes emit ``arch``?

    ``compute_107a`` needs a CUDA toolkit that lists it; a toolkit without it
    declines the sm_107a builds up front instead of failing inside the JIT
    build, so a checkout that registers sm_107a programs stays importable and
    testable on a toolkit that only knows 10.0 / 10.3.
    """
    if arch not in ARCH_NVCC_FLAGS:
        return False
    if arch == "sm_107a":
        from ...compilation_context import _nvcc_supports_sm107

        return bool(_nvcc_supports_sm107())
    return True


def registered_archs() -> tuple[str, ...]:
    """Architectures with registered programs, in ``ARCHES`` order."""
    return tuple(arch for arch in ARCHES if arch in PROGRAM_KEYS and arch in POLICY)


def program_available(arch: str) -> bool:
    """True when ``arch`` registers a scan, the merge and a finalize program (CUB or rank)."""
    keys = PROGRAM_KEYS.get(arch, {})
    return (
        arch in POLICY
        and any(key.startswith("scan:") for key in keys)
        and "merge" in keys
        and any(key.startswith(("finalize:", "finalize_rank:")) for key in keys)
    )


def select_program(arch: str, key: str) -> str:
    """Return the registered program of dispatch ``key`` on ``arch``."""
    keys = PROGRAM_KEYS.get(arch)
    if keys is None:
        raise NotImplementedError(
            f"The generated DSA indexer top-k programs for {arch} are not registered "
            f"in this checkout (registered: {sorted(PROGRAM_KEYS)}; see {TRACKING_ISSUE})"
        )
    program = keys.get(key)
    if program is None:
        raise NotImplementedError(
            f"The DSA indexer top-k program {key!r} is not registered for {arch} "
            f"(registered on {arch}: {sorted(keys)}; see {TRACKING_ISSUE})"
        )
    return program


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_program(program: str, arch: str):
    """JIT spec of ``program`` compiled for ``arch`` (one cached library per pair)."""
    record = PROGRAMS[program]
    if arch not in record["arches"]:
        raise ValueError(f"program {program!r} is not built for {arch!r}")
    if not toolchain_supports(arch):
        raise RuntimeError(f"this checkout cannot compile {arch}")
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{program}_{arch}",
        sources=sources,
        extra_cuda_cflags=[*ARCH_NVCC_FLAGS[arch], *COMPILE_FLAGS[record["role"]]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *{p.parent for p in sources}, *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_program(program: str, arch: str):
    return gen_program(program, arch).build_and_load()
