/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "../include/cake_fmha.h"

extern "C" __global__ void kernel_cake_fmha_compat_v1(const void* q, const void* k, const void* v, const void* k_scales, const void* v_scales, void* o, void* o_scales, float* lse, const int* page_table_k, const int* page_table_v, const int* q_indptr, const int* seq_lens_kv, const float* sinks, int batch_size, int num_q_heads, int num_kv_heads, int head_dim, int page_size, int kv_layout, int q_dtype, int kv_dtype, int o_dtype, int causal, int window_left, int enable_sink, int return_lse, float q_scale, float k_scale, float v_scale, float o_scale, float sm_scale, float o_sf_scale, int o_sf_start, int o_sf_columns, long long q_s0, long long q_s1, long long k_s0, long long k_s1, long long k_s2, long long k_s3, long long v_s0, long long v_s1, long long v_s2, long long v_s3, long long ksf_s0, long long ksf_s1, long long ksf_s2, long long ksf_s3, long long vsf_s0, long long vsf_s1, long long vsf_s2, long long vsf_s3, long long table_k_s0, long long table_v_s0, long long o_s0, long long o_s1);

extern "C" cudaError_t cake_fmha_launch_compat_v1(
    const void* q,
    const void* k,
    const void* v,
    const void* k_scales,
    const void* v_scales,
    void* o,
    void* o_scales,
    float* lse,
    const int* page_table_k,
    const int* page_table_v,
    const int* q_indptr,
    const int* seq_lens_kv,
    const float* sinks,
    int batch_size,
    int num_q_heads,
    int num_kv_heads,
    int head_dim,
    int page_size,
    int kv_layout,
    int q_dtype,
    int kv_dtype,
    int o_dtype,
    int causal,
    int window_left,
    int enable_sink,
    int return_lse,
    float q_scale,
    float k_scale,
    float v_scale,
    float o_scale,
    float sm_scale,
    float o_sf_scale,
    int o_sf_start,
    int o_sf_columns,
    long long q_s0,
    long long q_s1,
    long long k_s0,
    long long k_s1,
    long long k_s2,
    long long k_s3,
    long long v_s0,
    long long v_s1,
    long long v_s2,
    long long v_s3,
    long long ksf_s0,
    long long ksf_s1,
    long long ksf_s2,
    long long ksf_s3,
    long long vsf_s0,
    long long vsf_s1,
    long long vsf_s2,
    long long vsf_s3,
    long long table_k_s0,
    long long table_v_s0,
    long long o_s0,
    long long o_s1,
    unsigned int grid_x,
    unsigned int grid_y,
    unsigned int grid_z,
    cudaStream_t stream) {
    cudaError_t status = cudaFuncSetAttribute(
        reinterpret_cast<const void*>(kernel_cake_fmha_compat_v1),
        cudaFuncAttributeMaxDynamicSharedMemorySize,
        0);
    if (status != cudaSuccess) {
        return status;
    }
    void* kernel_args[] = {
        const_cast<void*>(reinterpret_cast<const void*>(&q)),
        const_cast<void*>(reinterpret_cast<const void*>(&k)),
        const_cast<void*>(reinterpret_cast<const void*>(&v)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_scales)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_scales)),
        const_cast<void*>(reinterpret_cast<const void*>(&o)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_scales)),
        const_cast<void*>(reinterpret_cast<const void*>(&lse)),
        const_cast<void*>(reinterpret_cast<const void*>(&page_table_k)),
        const_cast<void*>(reinterpret_cast<const void*>(&page_table_v)),
        const_cast<void*>(reinterpret_cast<const void*>(&q_indptr)),
        const_cast<void*>(reinterpret_cast<const void*>(&seq_lens_kv)),
        const_cast<void*>(reinterpret_cast<const void*>(&sinks)),
        const_cast<void*>(reinterpret_cast<const void*>(&batch_size)),
        const_cast<void*>(reinterpret_cast<const void*>(&num_q_heads)),
        const_cast<void*>(reinterpret_cast<const void*>(&num_kv_heads)),
        const_cast<void*>(reinterpret_cast<const void*>(&head_dim)),
        const_cast<void*>(reinterpret_cast<const void*>(&page_size)),
        const_cast<void*>(reinterpret_cast<const void*>(&kv_layout)),
        const_cast<void*>(reinterpret_cast<const void*>(&q_dtype)),
        const_cast<void*>(reinterpret_cast<const void*>(&kv_dtype)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_dtype)),
        const_cast<void*>(reinterpret_cast<const void*>(&causal)),
        const_cast<void*>(reinterpret_cast<const void*>(&window_left)),
        const_cast<void*>(reinterpret_cast<const void*>(&enable_sink)),
        const_cast<void*>(reinterpret_cast<const void*>(&return_lse)),
        const_cast<void*>(reinterpret_cast<const void*>(&q_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&sm_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_sf_scale)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_sf_start)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_sf_columns)),
        const_cast<void*>(reinterpret_cast<const void*>(&q_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&q_s1)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_s1)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_s2)),
        const_cast<void*>(reinterpret_cast<const void*>(&k_s3)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_s1)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_s2)),
        const_cast<void*>(reinterpret_cast<const void*>(&v_s3)),
        const_cast<void*>(reinterpret_cast<const void*>(&ksf_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&ksf_s1)),
        const_cast<void*>(reinterpret_cast<const void*>(&ksf_s2)),
        const_cast<void*>(reinterpret_cast<const void*>(&ksf_s3)),
        const_cast<void*>(reinterpret_cast<const void*>(&vsf_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&vsf_s1)),
        const_cast<void*>(reinterpret_cast<const void*>(&vsf_s2)),
        const_cast<void*>(reinterpret_cast<const void*>(&vsf_s3)),
        const_cast<void*>(reinterpret_cast<const void*>(&table_k_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&table_v_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_s0)),
        const_cast<void*>(reinterpret_cast<const void*>(&o_s1))
    };
    return cudaLaunchKernel(
        reinterpret_cast<const void*>(kernel_cake_fmha_compat_v1),
        dim3(grid_x, grid_y, grid_z),
        dim3(256, 1, 1),
        kernel_args,
        0,
        stream);
}
