/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_moe_grouped_gemm_e227d5245ddecad4cf5a'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_moe_grouped_gemm_e227d5245ddecad4cf5a(float* __restrict__ partials, __nv_bfloat16* __restrict__ C, int* __restrict__ offs, int num_groups, int N, int K, int ldc, int stride_e, int num_clusters_1, int tail_splits, int raster_rows);


namespace cake_host_shim_8dd01f75e45c3d4d {

using tvm::ffi::Optional;
using tvm::ffi::TensorView;

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  TVM_FFI_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  TVM_FFI_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  TVM_FFI_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  TVM_FFI_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  TVM_FFI_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

void Run(TensorView arg_partials, TensorView arg_C, TensorView arg_offs, int64_t arg_num_groups, int64_t arg_N, int64_t arg_K, int64_t arg_ldc, int64_t arg_stride_e, int64_t arg_num_clusters, int64_t arg_tail_splits, int64_t arg_raster_rows, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_partials.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_partials, "partials");
  CheckDtype(arg_partials, "partials", 2, 32, 1);
  CheckContiguous(arg_partials, "partials");
  CheckCudaTensor(arg_C, "C");
  CheckDtype(arg_C, "C", 4, 16, 1);
  CheckContiguous(arg_C, "C");
  CheckCudaTensor(arg_offs, "offs");
  CheckDtype(arg_offs, "offs", 0, 32, 1);
  CheckContiguous(arg_offs, "offs");
  TVM_FFI_CHECK(arg_num_groups >= -2147483648LL && arg_num_groups <= 2147483647LL, ValueError)
      << "scalar 'num_groups' value " << arg_num_groups
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_N >= -2147483648LL && arg_N <= 2147483647LL, ValueError)
      << "scalar 'N' value " << arg_N
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_K >= -2147483648LL && arg_K <= 2147483647LL, ValueError)
      << "scalar 'K' value " << arg_K
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_ldc >= -2147483648LL && arg_ldc <= 2147483647LL, ValueError)
      << "scalar 'ldc' value " << arg_ldc
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_stride_e >= -2147483648LL && arg_stride_e <= 2147483647LL, ValueError)
      << "scalar 'stride_e' value " << arg_stride_e
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_num_clusters >= -2147483648LL && arg_num_clusters <= 2147483647LL, ValueError)
      << "scalar 'num_clusters' value " << arg_num_clusters
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_tail_splits >= -2147483648LL && arg_tail_splits <= 2147483647LL, ValueError)
      << "scalar 'tail_splits' value " << arg_tail_splits
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_raster_rows >= -2147483648LL && arg_raster_rows <= 2147483647LL, ValueError)
      << "scalar 'raster_rows' value " << arg_raster_rows
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_C, arg_partials, "C", "partials");
  CheckSameCudaDevice(arg_offs, arg_partials, "offs", "partials");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  float* p_partials = static_cast<float*>(arg_partials.data_ptr());
  __nv_bfloat16* p_C = static_cast<__nv_bfloat16*>(arg_C.data_ptr());
  int* p_offs = static_cast<int*>(arg_offs.data_ptr());
  int32_t v_num_groups = (int32_t)arg_num_groups;
  int32_t v_N = (int32_t)arg_N;
  int32_t v_K = (int32_t)arg_K;
  int32_t v_ldc = (int32_t)arg_ldc;
  int32_t v_stride_e = (int32_t)arg_stride_e;
  int32_t v_num_clusters = (int32_t)arg_num_clusters;
  int32_t v_tail_splits = (int32_t)arg_tail_splits;
  int32_t v_raster_rows = (int32_t)arg_raster_rows;
  void* kargs[] = {&p_partials, &p_C, &p_offs, &v_num_groups, &v_N, &v_K, &v_ldc, &v_stride_e, &v_num_clusters, &v_tail_splits, &v_raster_rows};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaError_t launch_status = cudaLaunchKernel(
      reinterpret_cast<const void*>(kernel_cake_moe_grouped_gemm_e227d5245ddecad4cf5a), grid, block, kargs, 0u, stream);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernel for kernel_cake_moe_grouped_gemm_e227d5245ddecad4cf5a failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_8dd01f75e45c3d4d

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_8dd01f75e45c3d4d::Run);
