"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the
# Kimi-K3 TP12 fused LatentMoE communication tail (SM100 / SM103, twelve
# ranks in one multi-node NVLink domain).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host runtime resolves at preparation.
# Every route is two generated kernels, K1 and the tail, with cuBLAS between
# them for ``M > 4``:
#
# * ``k1_oneshot_ess:r<rank>``  the one-shot Lamport all-reduce of the routed
#   partial fused with KimiRMSNorm for ``M <= 16`` tokens with the early
#   shared scatter (ESS): the same CTAs also scatter this rank's columns of
#   the shared partial into the K3 workspace slots of their owner ranks (the
#   K3 workspace pointers and flags are extra arguments); the rank is a
#   trace-time specialisation (reduction order and local packet position), so
#   one module per rank;
# * ``k1_twoshot_ess:grouped``  the token-sliced two-shot form (owner reduce +
#   norm, multicast broadcast) with the early shared scatter for
#   ``16 < M < 256``; ``grouped`` issues all twelve remote loads of the owner
#   retry body before the first test;
# * ``k1_twoshot:<grouped|pinned>``  the two-shot form without the shared
#   scatter for ``M >= 256`` (the persistent tail scatters the shared partial
#   itself); ``grouped`` at ``M = 256``, ``pinned`` (the per-rank pinned retry
#   body) above;
# * ``k23:n<640|512>``  the fused up-projection + tail for ``M <= 4``: the
#   fp32 slice GEMM of the normalised latent with this rank's weight slice in
#   the K2-stream summation order, fused with the owner reduce of the
#   ESS-scattered shared columns, the add, one BF16 rounding and the multicast
#   all-gather of the output (the numerics of the round-4 K2-stream + fp32-add
#   K3 pair); one CTA per eight output columns, one module per column width of
#   the rank partition;
# * ``k3_ess:grouped``  the tail for ``4 < M < 256`` after an ESS K1: owner
#   reduce of the scattered shared columns, fused add of this rank's cuBLAS
#   up-projection slice, one BF16 rounding and the multicast all-gather of
#   the output row; one CTA per token and column half, no shared operand;
# * ``k3_persist:grouped``  the full K3 (own scatter of the shared partial,
#   owner reduce + add + rounding, all-gather) on a persistent grid of
#   ``min(M, SM count)`` CTAs per column half, each walking its tokens as a
#   three-stage pipeline (scatter ``t``, owner reduce + multicast ``t - P``,
#   gather ``t - 2P``) so the fabric hops of consecutive tokens overlap
#   (``M = 256``);
# * ``k3_persist_bulk:pinned``  the persistent K3 whose reduce-scatter stage
#   pushes the shared columns with ``cp.async.bulk``, pinned poll schedule
#   (``M > 256``).
#
# Every module is an exact-architecture program launched with programmatic
# dependent launch.  Both literals are populated verbatim by the
# generated-program export; do not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_tp12_tail_04635b5ae7ff6552933c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_04635b5ae7ff6552933c_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_04635b5ae7ff6552933c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4e17cd519773097468dbf99d12fd6aed61d6222ebf73644468516ab53e5d0682",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_048495176e2941f1abdf": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_048495176e2941f1abdf_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_048495176e2941f1abdf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "108e5346e3b8a86a6a83841108f34da66d0395a5114b81d85edef0313d51436c",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_06cd93c74e99e8d700fd": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_06cd93c74e99e8d700fd_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_06cd93c74e99e8d700fd_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e6d11b409f0dd2a7e2a512b731d7dbddc8f781824fc0a40e4ff9d4c271bc4cfb",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_0c09fb2c406fcc6485ea": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_0c09fb2c406fcc6485ea_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_0c09fb2c406fcc6485ea_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f2c269482faea91f9ce8ba51f0798e212ef6e76fda4c33f3055d92bbe40a4c6a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_14911f1d3d805719cf86": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_14911f1d3d805719cf86_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_14911f1d3d805719cf86_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2b54af53769d3842450d5a4e191753dfd2adae75d242c131dd44dec374a7d8a9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_15775f2d60624d8a832a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_15775f2d60624d8a832a_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_15775f2d60624d8a832a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ca3630ee120295d2feec5956d2dde747347ad79e19958bd2937dbec83035c7c9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_1917f5659b4fa4f177ed": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_1917f5659b4fa4f177ed_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_1917f5659b4fa4f177ed_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e9d5ce6577a9591bf3ebea971cec8d92203ab8529cd9d39acf9b9e4f5a19a630",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_26cb79a2c33c22471ef8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_26cb79a2c33c22471ef8_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_26cb79a2c33c22471ef8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d96f526fbb325d12c39b63c723d6fae81f5a652ed27c35443dfa7f8e74e79910",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_26f9d4709aa5d3939a86": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_26f9d4709aa5d3939a86_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_26f9d4709aa5d3939a86_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "97fb62e9a0aaff09cc99ff00b0e73e380eaeb127b52e3f0758031183339e0166",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_2bc7ad084d35a4607c2c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2bc7ad084d35a4607c2c_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2bc7ad084d35a4607c2c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "603e5a4645fe40b50b2d1223bccb171caabbece2206a60fc3f31e2a76aa612f2",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_3d57d4ec3ee0352b3935": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_3d57d4ec3ee0352b3935_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_3d57d4ec3ee0352b3935_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "62603fc228b5d6db12ad2589aef01055b99f2351a2445899fb694aa103c45f76",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_3e160b3c5575c120cba7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_3e160b3c5575c120cba7_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_3e160b3c5575c120cba7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "87defbd1c2fa2f6fb26ccc26595c30e73a278b046e2afa5f79a8a8b891892306",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_4a21a9e71a168414e4e2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_4a21a9e71a168414e4e2_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_4a21a9e71a168414e4e2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5ee9ad72199a0f5d718f69e08e1e1b8c92932208b900c530df7b823cb4ef29b4",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_4f1408f9961ce32e76d2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_4f1408f9961ce32e76d2_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_4f1408f9961ce32e76d2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c24ea7c2b97c6d869b026abdd19967634b12a47bf055cf157d5787c60c9616a5",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_556e701863c02611dca1": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_556e701863c02611dca1_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_556e701863c02611dca1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "80bc4e15b6ac0783540eece82ee4019b6b93b5adc961eb31757450902f50f260",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_56de0807d4bb3e361509": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_56de0807d4bb3e361509_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_56de0807d4bb3e361509_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "333d68990fafe992c1e71487ce8908fb315d0a7f51688453ba4d424fe1c31f8f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_58084e20a6795dab6546": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_58084e20a6795dab6546_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_58084e20a6795dab6546_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0f48073dd60c756776a3c7920d90287b652fdf18f3851c7bd10e9ae9c52aad69",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_6a43104c97d825a4abb2": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_6a43104c97d825a4abb2_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_6a43104c97d825a4abb2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f13b8bccd67eee1b29f57661dcf1d1c3704dcd26652d6f8dd5305532603b35fc",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_753e56f0ec38387d56bb": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_753e56f0ec38387d56bb_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_753e56f0ec38387d56bb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7bd364ab37ab90763b76aa938d20d8a6f272c13eff5936ec2c4a8e581acee79d",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 14336,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_77d2b6fd87d66a0cc1d3": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_77d2b6fd87d66a0cc1d3_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_77d2b6fd87d66a0cc1d3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "821b4fdeef7bca44d377d2fb2933b2028f1992987fd171483da3250b9ee80f5f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_795fb87562848e562cef": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_795fb87562848e562cef_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_795fb87562848e562cef_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6b6f15ed47713df50affacf9703b32b0d95052eaab4aaa2dc79e944bb9318a1f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_7b733bb4b07acfd39da3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_7b733bb4b07acfd39da3_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_7b733bb4b07acfd39da3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "241980e2d2ca02a32419b67ca59e787cf8dfbc0e7925ea970f8f88f7c043e557",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_80b99fbee3b113efb7dc": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_80b99fbee3b113efb7dc_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_80b99fbee3b113efb7dc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "76239db20e00a6e42600f29b6639f2674ef64faf1e534cad97501533937ed4e4",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_81f5a5ad6ee688e2ea30": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_81f5a5ad6ee688e2ea30_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_81f5a5ad6ee688e2ea30_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e4640953d1600674074d8e0de1019dbfc8183b4985d44b5a12b01bdd2e861910",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_86515964df4e45ecfabb": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_86515964df4e45ecfabb_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_86515964df4e45ecfabb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "902b4f21beace3b2f2b8894ab35021137df4e0474b848465fb894ca1188379c6",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_8928eedb7eccd54083f9": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_8928eedb7eccd54083f9_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_8928eedb7eccd54083f9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "148fda0ce942d0f5a39cfbe6ce88cb7fcd67fd6267fcd949b108b2d254de8f6b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_9058b6bd0d0f928ecd0a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9058b6bd0d0f928ecd0a_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9058b6bd0d0f928ecd0a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4f99c9b4017444905bb23d6df8dbf597d8f0a3f438902838b38ca83d65cb5b4c",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_9668692a24eb111869ba": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9668692a24eb111869ba_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9668692a24eb111869ba_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "48082b3bd30b4d3d07a2fa8e517e628e752b4c04bf17d9303a1de55aaad9decd",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_a49e8006e5a61a4a07d6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_a49e8006e5a61a4a07d6_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_a49e8006e5a61a4a07d6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e42474cf7d916b1aed97ef0deb2114c57ba03716b77e330e5a54d75596bfee4e",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_aee71a26c95620e90c3c": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_aee71a26c95620e90c3c_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_aee71a26c95620e90c3c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "675a027d93e2810096225d5690c2ccf2c258f98c50ad6e18ebb66d7a9e0324d2",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_b84b77e560868c438e28": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b84b77e560868c438e28_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b84b77e560868c438e28_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d5e8bb1b0340e92b74232f0dc323f908ac8b3ff61752e901d38b63962a6e82f9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_bbeb51c38372dce6e00a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_bbeb51c38372dce6e00a_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_bbeb51c38372dce6e00a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a2ef39e1d573cecb58539ed9480511efbbc2a3537ca5f0db431822d20f13bc19",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_bff01f9324308a06ae1e": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_bff01f9324308a06ae1e_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_bff01f9324308a06ae1e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "aa6fa30c0ce6abf44dc11179fe91d1cfa9a24a998a576f87631d480f471d55dd",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_cdf30244f1f8d753533c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_cdf30244f1f8d753533c_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_cdf30244f1f8d753533c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8db0ab4ca9ab1239c767bdebc3d7525d7b6eda312d0f1621410ee80236eec1c7",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_cf2e102aa8e3b7c170a8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_cf2e102aa8e3b7c170a8_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_cf2e102aa8e3b7c170a8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0d0cb467c9f8a3f41145681dd055cf0fcbe1ecd4aa51bce3f94470dcd8321170",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 14336,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_d72a1084bb6b17145aee": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_d72a1084bb6b17145aee_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_d72a1084bb6b17145aee_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b51c2539d3600b7336fc8a3ef78e633a9903097393e3bbb0e8d66bea69f9e03b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_dd0fb1d3b39505ad8e0e": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_dd0fb1d3b39505ad8e0e_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_dd0fb1d3b39505ad8e0e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "893a5e3e8c7e72985f73aa4887368c9ca95971c62a29da8b7cf72052c1464bb9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_e0875bb0a4f7fc3561e4": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e0875bb0a4f7fc3561e4_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e0875bb0a4f7fc3561e4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c4175cde0d46c7e1bff8231fa472b350a9559796198fd1cc9c133260bdc879af",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_e4ec3742ac4b0099aedb": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e4ec3742ac4b0099aedb_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e4ec3742ac4b0099aedb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "3eb639d3a1591bb5731e2362f9363d984010bf14d3ae0855aa40419c823a9924",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_e51f3a0073ea09771388": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e51f3a0073ea09771388_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e51f3a0073ea09771388_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "da287048cb91496ae9de018be6a0bc4eb5d7aaebbc2b8db4775485f7f089e5bd",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
}

KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "k1_oneshot_ess:r0": "cake_kimi_k3_tp12_tail_26f9d4709aa5d3939a86",
        "k1_oneshot_ess:r1": "cake_kimi_k3_tp12_tail_14911f1d3d805719cf86",
        "k1_oneshot_ess:r10": "cake_kimi_k3_tp12_tail_0c09fb2c406fcc6485ea",
        "k1_oneshot_ess:r11": "cake_kimi_k3_tp12_tail_15775f2d60624d8a832a",
        "k1_oneshot_ess:r2": "cake_kimi_k3_tp12_tail_06cd93c74e99e8d700fd",
        "k1_oneshot_ess:r3": "cake_kimi_k3_tp12_tail_1917f5659b4fa4f177ed",
        "k1_oneshot_ess:r4": "cake_kimi_k3_tp12_tail_aee71a26c95620e90c3c",
        "k1_oneshot_ess:r5": "cake_kimi_k3_tp12_tail_6a43104c97d825a4abb2",
        "k1_oneshot_ess:r6": "cake_kimi_k3_tp12_tail_dd0fb1d3b39505ad8e0e",
        "k1_oneshot_ess:r7": "cake_kimi_k3_tp12_tail_7b733bb4b07acfd39da3",
        "k1_oneshot_ess:r8": "cake_kimi_k3_tp12_tail_80b99fbee3b113efb7dc",
        "k1_oneshot_ess:r9": "cake_kimi_k3_tp12_tail_8928eedb7eccd54083f9",
        "k1_twoshot:grouped": "cake_kimi_k3_tp12_tail_58084e20a6795dab6546",
        "k1_twoshot:pinned": "cake_kimi_k3_tp12_tail_3e160b3c5575c120cba7",
        "k1_twoshot_ess:grouped": "cake_kimi_k3_tp12_tail_bbeb51c38372dce6e00a",
        "k23:n512": "cake_kimi_k3_tp12_tail_3d57d4ec3ee0352b3935",
        "k23:n640": "cake_kimi_k3_tp12_tail_81f5a5ad6ee688e2ea30",
        "k3_ess:grouped": "cake_kimi_k3_tp12_tail_9058b6bd0d0f928ecd0a",
        "k3_persist:grouped": "cake_kimi_k3_tp12_tail_9668692a24eb111869ba",
        "k3_persist_bulk:pinned": "cake_kimi_k3_tp12_tail_753e56f0ec38387d56bb",
    },
    "sm_103a": {
        "k1_oneshot_ess:r0": "cake_kimi_k3_tp12_tail_556e701863c02611dca1",
        "k1_oneshot_ess:r1": "cake_kimi_k3_tp12_tail_04635b5ae7ff6552933c",
        "k1_oneshot_ess:r10": "cake_kimi_k3_tp12_tail_56de0807d4bb3e361509",
        "k1_oneshot_ess:r11": "cake_kimi_k3_tp12_tail_e0875bb0a4f7fc3561e4",
        "k1_oneshot_ess:r2": "cake_kimi_k3_tp12_tail_e51f3a0073ea09771388",
        "k1_oneshot_ess:r3": "cake_kimi_k3_tp12_tail_cdf30244f1f8d753533c",
        "k1_oneshot_ess:r4": "cake_kimi_k3_tp12_tail_26cb79a2c33c22471ef8",
        "k1_oneshot_ess:r5": "cake_kimi_k3_tp12_tail_2bc7ad084d35a4607c2c",
        "k1_oneshot_ess:r6": "cake_kimi_k3_tp12_tail_e4ec3742ac4b0099aedb",
        "k1_oneshot_ess:r7": "cake_kimi_k3_tp12_tail_795fb87562848e562cef",
        "k1_oneshot_ess:r8": "cake_kimi_k3_tp12_tail_bff01f9324308a06ae1e",
        "k1_oneshot_ess:r9": "cake_kimi_k3_tp12_tail_b84b77e560868c438e28",
        "k1_twoshot:grouped": "cake_kimi_k3_tp12_tail_86515964df4e45ecfabb",
        "k1_twoshot:pinned": "cake_kimi_k3_tp12_tail_048495176e2941f1abdf",
        "k1_twoshot_ess:grouped": "cake_kimi_k3_tp12_tail_a49e8006e5a61a4a07d6",
        "k23:n512": "cake_kimi_k3_tp12_tail_4f1408f9961ce32e76d2",
        "k23:n640": "cake_kimi_k3_tp12_tail_4a21a9e71a168414e4e2",
        "k3_ess:grouped": "cake_kimi_k3_tp12_tail_d72a1084bb6b17145aee",
        "k3_persist:grouped": "cake_kimi_k3_tp12_tail_77d2b6fd87d66a0cc1d3",
        "k3_persist_bulk:pinned": "cake_kimi_k3_tp12_tail_cf2e102aa8e3b7c170a8",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}
WORLD_SIZE = 12
POLL_SCHEDULES = ("grouped", "pinned")


def required_kernel_keys() -> tuple[str, ...]:
    """Every logical kernel the runtime can select on one architecture (twenty-two keys)."""
    # Unreachable, hence not registered: ``k1_twoshot_ess:pinned`` and ``k3_ess:pinned``
    # (the ESS range ``M < 256`` is grouped-only), ``k3_persist:pinned`` and
    # ``k3_persist_bulk:grouped`` (the plain persistent K3 serves exactly 256 tokens,
    # the cp.async.bulk form the whole pinned range ``M > 256``).
    return (
        *(f"k1_oneshot_ess:r{rank}" for rank in range(WORLD_SIZE)),
        "k1_twoshot_ess:grouped",
        *(f"k1_twoshot:{schedule}" for schedule in POLL_SCHEDULES),
        # fused K23 per column width and accumulator capacity (round 6: the four-token module for M <= 4, the
        # eight-token module for 5 <= M <= 8)
        "k23:n640:c4",
        "k23:n512:c4",
        "k23:n640:c8",
        "k23:n512:c8",
        "k3_ess:grouped",
        "k3_persist:grouped",
        "k3_persist_bulk:pinned",
    )


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 TP12 tail programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4542)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 TP12 tail kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4542)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_tp12_tail_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_tp12_tail_module(name: str):
    return gen_cake_kimi_k3_tp12_tail_module(name).build_and_load()
