"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the
# Kimi-K3 TP12 fused LatentMoE communication tail (SM100 / SM103, twelve
# ranks in one multi-node NVLink domain).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host runtime resolves at preparation.
# Every route is two generated kernels, K1 and the tail, with cuBLAS between
# them for ``M > 4``:
#
# * ``k1_oneshot_ess:r<rank>``  the one-shot Lamport all-reduce of the routed
#   partial fused with KimiRMSNorm for ``M <= 16`` tokens with the early
#   shared scatter (ESS): the same CTAs also scatter this rank's columns of
#   the shared partial into the K3 workspace slots of their owner ranks (the
#   K3 workspace pointers and flags are extra arguments); the rank is a
#   trace-time specialisation (reduction order and local packet position), so
#   one module per rank;
# * ``k1_twoshot_ess:grouped``  the token-sliced two-shot form (owner reduce +
#   norm, multicast broadcast) with the early shared scatter for
#   ``16 < M < 256``; ``grouped`` issues all twelve remote loads of the owner
#   retry body before the first test;
# * ``k1_twoshot:<grouped|pinned>``  the two-shot form without the shared
#   scatter for ``M >= 256`` (the persistent tail scatters the shared partial
#   itself); ``grouped`` at ``M = 256``, ``pinned`` (the per-rank pinned retry
#   body) above;
# * ``k23:n<640|512>``  the fused up-projection + tail for ``M <= 4``: the
#   fp32 slice GEMM of the normalised latent with this rank's weight slice in
#   the K2-stream summation order, fused with the owner reduce of the
#   ESS-scattered shared columns, the add, one BF16 rounding and the multicast
#   all-gather of the output (the numerics of the round-4 K2-stream + fp32-add
#   K3 pair); one CTA per eight output columns, one module per column width of
#   the rank partition;
# * ``k3_ess:grouped``  the tail for ``4 < M < 256`` after an ESS K1: owner
#   reduce of the scattered shared columns, fused add of this rank's cuBLAS
#   up-projection slice, one BF16 rounding and the multicast all-gather of
#   the output row; one CTA per token and column half, no shared operand;
# * ``k3_persist:grouped``  the full K3 (own scatter of the shared partial,
#   owner reduce + add + rounding, all-gather) on a persistent grid of
#   ``min(M, SM count)`` CTAs per column half, each walking its tokens as a
#   three-stage pipeline (scatter ``t``, owner reduce + multicast ``t - P``,
#   gather ``t - 2P``) so the fabric hops of consecutive tokens overlap
#   (``M = 256``);
# * ``k3_persist_bulk:pinned``  the persistent K3 whose reduce-scatter stage
#   pushes the shared columns with ``cp.async.bulk``, pinned poll schedule
#   (``M > 256``).
#
# Every module is an exact-architecture program launched with programmatic
# dependent launch.  Both literals are populated verbatim by the
# generated-program export; do not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_tp12_tail_00d004fc2bed4cdeb4a6": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_00d004fc2bed4cdeb4a6_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_00d004fc2bed4cdeb4a6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6aba489d53bc72172754b8815d226ec0d8f3759aaa9fa405a698ff4533ca6e81",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_04ae4bf35674acf3b561": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_04ae4bf35674acf3b561_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_04ae4bf35674acf3b561_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7d0627ab74c1c2baa451e6bc774f660912316bbb7128cb732da9f8b0b6eac6ec",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_05162385eb034576cc45": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_05162385eb034576cc45_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_05162385eb034576cc45_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4dbcd28a770becee2645138298c250254f771308fff46b85d05ba41e695aea5a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 3840,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_07a5e20d9adb1e696225": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_07a5e20d9adb1e696225_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_07a5e20d9adb1e696225_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "cfbaec7c2d9b5bcf840e5f85020d28f1b84e16eadacf01e3ed9be85838f87686",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_07f1d91437f11a431b3b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_07f1d91437f11a431b3b_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_07f1d91437f11a431b3b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "59f12b1ea5beb81cfcb7d1a326a0ef086e643c62a011de76dc52d56cda8ab496",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_081678ba05dc43d7e036": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_081678ba05dc43d7e036_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_081678ba05dc43d7e036_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8683d718d477ae7c5470a0e7f7f33b82ccf19d4ed778bb07a368a8b9268ee89b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_0836e3058863eb4ab4a6": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_0836e3058863eb4ab4a6_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_0836e3058863eb4ab4a6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e61a5e8f2da46f4d10f49b6269aa8fed0a5f8a9cada02d28b6d2423e75e6bf24",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 3840,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_1adbe2e437df266f7a78": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_1adbe2e437df266f7a78_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_1adbe2e437df266f7a78_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a760d044e414d1369b71adee3a18dfdbbb2072a88a8d2bb99f8a10a6e4409b64",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_246b3f21c9b13696b874": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_246b3f21c9b13696b874_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_246b3f21c9b13696b874_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c961169c94dbe91e6a70281efeee8a71e51ce1836fb0216c9926fcfe15495e3c",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_24afccc394911e9de44c": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_24afccc394911e9de44c_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_24afccc394911e9de44c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "109186562c7b1499cd828bcbf13501e58dc51b107d24a5f28e9c7414c9000762",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 14336,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_2ab2bb8c8aeff910e28d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2ab2bb8c8aeff910e28d_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2ab2bb8c8aeff910e28d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bba3fb46f6fbeeb84d4e3a630a7b5c871eb0d1d7c557abe02d4e8b4e03bdd1d1",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_2ff34749029ad005f006": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2ff34749029ad005f006_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_2ff34749029ad005f006_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "26f6bbb6b5a2f0f47890746ae9dfca149cc5baa5f0c23444376931782e058dc8",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 3840,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_349bf037b46aecc0ae5d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_349bf037b46aecc0ae5d_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_349bf037b46aecc0ae5d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d4da9b8eeb350e66250b01d8a4dee9c9a3a4b9b090d67144dc58e978d7a5a47f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_45e687e01d30779a9728": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_45e687e01d30779a9728_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_45e687e01d30779a9728_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "702725301894bee57eb3bbdcf1c5d756990dd186d13def4e5bfc3ee4b1ae92f5",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_4940004b2ec7c345f8f1": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_4940004b2ec7c345f8f1_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_4940004b2ec7c345f8f1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a5fd67a38620986e3e76e0faf20ed86a5aed7ee088868548313b7df2f7de3c4b",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_4c4bffa3f4dc7eb5953e": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_4c4bffa3f4dc7eb5953e_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_4c4bffa3f4dc7eb5953e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1bd6c52f51af8caa9599ed9aa73731d5a0a8384eff87fbd4b6337296162fd9b5",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_501a33af9a5d4e0b6494": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_501a33af9a5d4e0b6494_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_501a33af9a5d4e0b6494_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7b28b4327e4490024b7f57268dfcffa2c7c0bc1cac8eff762e034dfcb0cd38a0",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_6669bef85bbd1e0e4000": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_6669bef85bbd1e0e4000_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_6669bef85bbd1e0e4000_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "3af36076be58375a449991a6575548fe31aa211fe90d4855d177a8e84f07effd",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_69f25f4193f2d1cfdbab": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_69f25f4193f2d1cfdbab_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_69f25f4193f2d1cfdbab_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "53574a95c6136c57c6582ac2310a71eb3cb36b0babd9833d8530975c938ee608",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_6f98ed61fd9063fb422b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_6f98ed61fd9063fb422b_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_6f98ed61fd9063fb422b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "28311ac4c723333aa7cdaf3874124b01bdefd614f4e577c85e7d66e794f952b3",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_75c27bd2d74dd5abeca4": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_75c27bd2d74dd5abeca4_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_75c27bd2d74dd5abeca4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1efff33e341424d2e55fd261bfebb01a97294177144a6c1668ee49c75db5c1a8",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_80c721c2e2138e7ee37e": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_80c721c2e2138e7ee37e_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_80c721c2e2138e7ee37e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d44a7867bbdf8c209d2d4e37a8bd2fa8c70e79df8419cd0c48a237e5b8d92e50",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_833b6eed638e6f2034a8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_833b6eed638e6f2034a8_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_833b6eed638e6f2034a8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a18c960adc2e5bb9139007c66269badc1b0913809e37e483762f3ccb1cc310cc",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_8c522891183caef25aa5": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_8c522891183caef25aa5_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_8c522891183caef25aa5_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "046ca9cfb6abadebb8f19fd800c35405d9060bd59d1e60fd603a754ff12ec43d",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_95229fc7f2e055c18803": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_95229fc7f2e055c18803_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_95229fc7f2e055c18803_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1802aaf4dabeae015bfc5d8f3b7d7726a81a82d32b7aa6e17e2c1e02b5532ba9",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_957ecb012270e1282bc7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_957ecb012270e1282bc7_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_957ecb012270e1282bc7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6187d76db876067c5f91b7704d13f2139f1aa96d0312914704652560f4e3fc6f",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_9b33c73cf4e5f0e447bc": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_9b33c73cf4e5f0e447bc_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_9b33c73cf4e5f0e447bc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1d2b127f4ed110e4de0649bd21540924aa47c0f6553000871b22d78134f090c5",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_9e011ee19c9fee6c6da8": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9e011ee19c9fee6c6da8_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_9e011ee19c9fee6c6da8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b4e4770bc0e32abfa406f9849cd84fe3828b8881850a0e1ff6db9e4650db40ec",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 1920,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_a197835d2fd98979c834": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_a197835d2fd98979c834_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_a197835d2fd98979c834_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9643f3d682c44d28638e3859b87a3c6dd6a451963566c9068efd08d98a99350a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_a3ae71b22b640947221d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_a3ae71b22b640947221d_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_a3ae71b22b640947221d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "033c4d6251b7cf57b610140f20cda58d536e561c83ffd542f06366c6e1a5a7fb",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_a4eda12e65769074b740": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_a4eda12e65769074b740_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_a4eda12e65769074b740_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b748a88ac1a7929f8b4134d6f4795182c1a343e27938e5a79b008b6ff266a296",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_b27004e66ef27b633109": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b27004e66ef27b633109_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b27004e66ef27b633109_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9c7a3c0b590cd4dbf5a9afd17413df61fc0dbdc7f0e29ef2f02d64ec58338b95",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_b3c06113921562d852f7": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b3c06113921562d852f7_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_b3c06113921562d852f7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "62ecfde37863efff316c698400756b2bef91a15b0dc107f352070dcb37ff7490",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 14336,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_bed7a2f179a620e77caa": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_bed7a2f179a620e77caa_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_bed7a2f179a620e77caa_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "325aba1ba8fb3e36cf11d7ab8956e0fadf62a8e172a82cd09a7817546b7dbdce",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_c263b39ffdf53979b8be": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_c263b39ffdf53979b8be_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_c263b39ffdf53979b8be_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2aa19b72ca68d2bdf7acbec926826c1387de65fa93dfc1400133e1c8ae0be12a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_c775895cc83cea1bf9e3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_c775895cc83cea1bf9e3_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_c775895cc83cea1bf9e3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "283b0f8f9913b31e66bb828fb97d3267055158145c5409e64c740078aa279c18",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_cc9210a8a5a8da9ac7b3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_cc9210a8a5a8da9ac7b3_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_cc9210a8a5a8da9ac7b3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b05559b488f3054bf7f6f298fed8256b21f622ad4e93aef761e203e060b3980a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_dbed6f66971dde1612d0": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_dbed6f66971dde1612d0_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_dbed6f66971dde1612d0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5bd2f2a0100349d40b9306d6d1cb59c9c0be770b0dbca2b295f1648ed40a9132",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_dc0b291169ee49e4337d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_dc0b291169ee49e4337d_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_dc0b291169ee49e4337d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "caf1a045a0a874c517522803bc331576d5a7b5be0e33f618aa340dc324a3b3e2",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_e6c3b60526335dc82bfb": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e6c3b60526335dc82bfb_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_e6c3b60526335dc82bfb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8219596737212d8b166dcd370f8be884544e0ea48939606042011c4ee7275c77",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_e909cd61302995e376d0": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_e909cd61302995e376d0_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_e909cd61302995e376d0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "859d05a4794ea1e78028cdc90e03035f15f3a4aeb3be76e461ba912cc1f8f54a",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_f01a6fa634bc356d5637": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_f01a6fa634bc356d5637_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_103a/cake_kimi_k3_tp12_tail_f01a6fa634bc356d5637_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "shared"],
            ["buffer", "gemm_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["parameter", "my_cols"],
            ["parameter", "gemm_plane_stride"],
            ["parameter", "num_gemm_splits"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7533fc9f0a7bdd6d3c40a17b82a66b475463c6ac0f16f42bcbdcc7a996f827cf",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 0,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_f2f940c37ecde40fbf95": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_f2f940c37ecde40fbf95_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_f2f940c37ecde40fbf95_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "w_slice"],
            ["buffer", "out"],
            ["buffer", "peer_ptrs"],
            ["raw_pointer", "mcast_ptr"],
            ["buffer", "buffer_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "rank"],
            ["parameter", "my_col_begin"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4279bf237e078e2f3699ea2881b47110a9d364aef8db49d326fc831d370b8227",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 3840,
            "use_pdl": True,
        },
    },
    "cake_kimi_k3_tp12_tail_f3da1f7b661ac254c860": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_f3da1f7b661ac254c860_kernel.cu",
            "cake_kimi_k3_tp12_tail/sm_100a/cake_kimi_k3_tp12_tail_f3da1f7b661ac254c860_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "routed"],
            ["buffer", "shared"],
            ["buffer", "y_out"],
            ["buffer", "gamma"],
            ["raw_pointer", "mcast_ptr"],
            ["raw_pointer", "local_unicast_ptr"],
            ["buffer", "buffer_flags"],
            ["buffer", "k3_peer_ptrs"],
            ["raw_pointer", "k3_mcast_ptr"],
            ["buffer", "k3_flags"],
            ["parameter", "num_tokens"],
            ["parameter", "epsilon"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1342561407e210c8ec2440fd2af94d16cb77c1a4119db5b8a2cfc2d3a4338893",
        "tma_workspace_bytes": 0,
        "launch": {
            "block": [448, 1, 1],
            "cluster": [1, 1, 1],
            "cooperative": False,
            "dynamic_smem_bytes": 128,
            "use_pdl": True,
        },
    },
}

KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "k1_oneshot_ess:r0": "cake_kimi_k3_tp12_tail_45e687e01d30779a9728",
        "k1_oneshot_ess:r1": "cake_kimi_k3_tp12_tail_f3da1f7b661ac254c860",
        "k1_oneshot_ess:r10": "cake_kimi_k3_tp12_tail_a3ae71b22b640947221d",
        "k1_oneshot_ess:r11": "cake_kimi_k3_tp12_tail_a197835d2fd98979c834",
        "k1_oneshot_ess:r2": "cake_kimi_k3_tp12_tail_69f25f4193f2d1cfdbab",
        "k1_oneshot_ess:r3": "cake_kimi_k3_tp12_tail_75c27bd2d74dd5abeca4",
        "k1_oneshot_ess:r4": "cake_kimi_k3_tp12_tail_cc9210a8a5a8da9ac7b3",
        "k1_oneshot_ess:r5": "cake_kimi_k3_tp12_tail_e909cd61302995e376d0",
        "k1_oneshot_ess:r6": "cake_kimi_k3_tp12_tail_4c4bffa3f4dc7eb5953e",
        "k1_oneshot_ess:r7": "cake_kimi_k3_tp12_tail_957ecb012270e1282bc7",
        "k1_oneshot_ess:r8": "cake_kimi_k3_tp12_tail_c263b39ffdf53979b8be",
        "k1_oneshot_ess:r9": "cake_kimi_k3_tp12_tail_501a33af9a5d4e0b6494",
        "k1_twoshot:grouped": "cake_kimi_k3_tp12_tail_081678ba05dc43d7e036",
        "k1_twoshot:pinned": "cake_kimi_k3_tp12_tail_00d004fc2bed4cdeb4a6",
        "k1_twoshot_ess:grouped": "cake_kimi_k3_tp12_tail_07a5e20d9adb1e696225",
        "k23:n512:c4": "cake_kimi_k3_tp12_tail_9e011ee19c9fee6c6da8",
        "k23:n512:c8": "cake_kimi_k3_tp12_tail_f2f940c37ecde40fbf95",
        "k23:n640:c4": "cake_kimi_k3_tp12_tail_4940004b2ec7c345f8f1",
        "k23:n640:c8": "cake_kimi_k3_tp12_tail_0836e3058863eb4ab4a6",
        "k3_ess:grouped": "cake_kimi_k3_tp12_tail_c775895cc83cea1bf9e3",
        "k3_persist:grouped": "cake_kimi_k3_tp12_tail_246b3f21c9b13696b874",
        "k3_persist_bulk:pinned": "cake_kimi_k3_tp12_tail_24afccc394911e9de44c",
    },
    "sm_103a": {
        "k1_oneshot_ess:r0": "cake_kimi_k3_tp12_tail_e6c3b60526335dc82bfb",
        "k1_oneshot_ess:r1": "cake_kimi_k3_tp12_tail_b27004e66ef27b633109",
        "k1_oneshot_ess:r10": "cake_kimi_k3_tp12_tail_04ae4bf35674acf3b561",
        "k1_oneshot_ess:r11": "cake_kimi_k3_tp12_tail_9b33c73cf4e5f0e447bc",
        "k1_oneshot_ess:r2": "cake_kimi_k3_tp12_tail_dbed6f66971dde1612d0",
        "k1_oneshot_ess:r3": "cake_kimi_k3_tp12_tail_6669bef85bbd1e0e4000",
        "k1_oneshot_ess:r4": "cake_kimi_k3_tp12_tail_07f1d91437f11a431b3b",
        "k1_oneshot_ess:r5": "cake_kimi_k3_tp12_tail_6f98ed61fd9063fb422b",
        "k1_oneshot_ess:r6": "cake_kimi_k3_tp12_tail_95229fc7f2e055c18803",
        "k1_oneshot_ess:r7": "cake_kimi_k3_tp12_tail_349bf037b46aecc0ae5d",
        "k1_oneshot_ess:r8": "cake_kimi_k3_tp12_tail_2ab2bb8c8aeff910e28d",
        "k1_oneshot_ess:r9": "cake_kimi_k3_tp12_tail_a4eda12e65769074b740",
        "k1_twoshot:grouped": "cake_kimi_k3_tp12_tail_80c721c2e2138e7ee37e",
        "k1_twoshot:pinned": "cake_kimi_k3_tp12_tail_1adbe2e437df266f7a78",
        "k1_twoshot_ess:grouped": "cake_kimi_k3_tp12_tail_bed7a2f179a620e77caa",
        "k23:n512:c4": "cake_kimi_k3_tp12_tail_8c522891183caef25aa5",
        "k23:n512:c8": "cake_kimi_k3_tp12_tail_2ff34749029ad005f006",
        "k23:n640:c4": "cake_kimi_k3_tp12_tail_833b6eed638e6f2034a8",
        "k23:n640:c8": "cake_kimi_k3_tp12_tail_05162385eb034576cc45",
        "k3_ess:grouped": "cake_kimi_k3_tp12_tail_dc0b291169ee49e4337d",
        "k3_persist:grouped": "cake_kimi_k3_tp12_tail_f01a6fa634bc356d5637",
        "k3_persist_bulk:pinned": "cake_kimi_k3_tp12_tail_b3c06113921562d852f7",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}
WORLD_SIZE = 12
POLL_SCHEDULES = ("grouped", "pinned")


def required_kernel_keys() -> tuple[str, ...]:
    """Every logical kernel the runtime can select on one architecture (twenty-two keys)."""
    # Unreachable, hence not registered: ``k1_twoshot_ess:pinned`` and ``k3_ess:pinned``
    # (the ESS range ``M < 256`` is grouped-only), ``k3_persist:pinned`` and
    # ``k3_persist_bulk:grouped`` (the plain persistent K3 serves exactly 256 tokens,
    # the cp.async.bulk form the whole pinned range ``M > 256``).
    return (
        *(f"k1_oneshot_ess:r{rank}" for rank in range(WORLD_SIZE)),
        "k1_twoshot_ess:grouped",
        *(f"k1_twoshot:{schedule}" for schedule in POLL_SCHEDULES),
        # fused K23 per column width and accumulator capacity (round 6: the four-token module for M <= 4, the
        # eight-token module for 5 <= M <= 8)
        "k23:n640:c4",
        "k23:n512:c4",
        "k23:n640:c8",
        "k23:n512:c8",
        "k3_ess:grouped",
        "k3_persist:grouped",
        "k3_persist_bulk:pinned",
    )


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 TP12 tail programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4542)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 TP12 tail kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4542)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_tp12_tail_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_tp12_tail_module(name: str):
    return gen_cake_kimi_k3_tp12_tail_module(name).build_and_load()
