"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the
# Kimi-K3 vision tower (MoonViT-3D encoder + PatchMergerV2; SM100 / SM103).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host launcher resolves at preparation:
#
# * ``gemm:<variant>:<tile>``   the fused tcgen05 BF16 GEMM family
#   (``pos``, ``norm_qkv_rope``, ``residual_wo``, ``norm_gelu``,
#   ``residual_fc1``, ``gelu_erf``, ``rmsnorm``) on the production tile
#   configuration ``select_tile_config`` picks for the token count;
# * ``attention:tiles2`` / ``attention:tiles1``   the packed-varlen BF16
#   attention kernel in its two-tile and SPLIT_KV unit layouts (the host plan
#   rule ``select_tiles_per_cta`` chooses per ``grid_thws`` batch);
# * ``merge``                     final RMSNorm + 2x2 spatial / temporal-mean merge;
# * ``rmsnorm_apply``             the post-projector RMSNorm apply pass.
#
# Every module is an exact-architecture program (tcgen05 / TMEM / 2-CTA MMA);
# the sm_103a attention additionally drains scores with ``tcgen05.ld.red``.
# Both literals are populated verbatim by the generated-program export; do
# not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_vision_tower_06ebbf8c1cbb463a324f": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_06ebbf8c1cbb463a324f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_06ebbf8c1cbb463a324f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ffadf712fc465b300e716feff35e81578c70ef08cbbb4f93bc2f767e9a56200d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_0af9477ad7b9f08efc52": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_0af9477ad7b9f08efc52_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_0af9477ad7b9f08efc52_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "89a6b2a4905de72a4be77c9352c274fbf05cff9a641a3bbdde5773044fdd9abc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_0f1dbb5852a0d5513d87": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_0f1dbb5852a0d5513d87_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_0f1dbb5852a0d5513d87_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "norm_weight"],
            ["buffer", "merge_table"],
            ["buffer", "m_out"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "476ff3da13a2174fa094b9374928f918d7ca2af147cb94a970bbbd6f1607a08c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_199198b854f1e3657b6f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_199198b854f1e3657b6f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_199198b854f1e3657b6f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ad07913329ff1ee0db96a083723f15b2f8be6e38bd38990ebb42a8008b9875e0",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_1bf640d943880236989f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_1bf640d943880236989f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_1bf640d943880236989f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7be6c9302af1282706bb9d5239e3a52e5ebc6823e9c34df3d6f70c781f663962",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_1db97bef963ed488dc72": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_1db97bef963ed488dc72_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_1db97bef963ed488dc72_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6174c023c4a0823a4e726ac4c9f6bce6236774e5672198520ac6fe7b07115e5d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_21792a093effefddce91": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_21792a093effefddce91_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_21792a093effefddce91_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8c387f23435644ba43f8334803c4dea80bd759cddd69d0cd3825279364418740",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_23b42f8b63924df28f98": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_23b42f8b63924df28f98_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_23b42f8b63924df28f98_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "159f5509b0728e7a4b979a6fd059b2f97805ae1d41ba80fef2098f5169170107",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_2c9410cb55e83813059b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_2c9410cb55e83813059b_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_2c9410cb55e83813059b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8eebe858a48cc908f1f1549a8f3ab0dfc6fe4574ba3b7ade4154fa23e1f6e55a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_307adc40d72f142a3ad7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_307adc40d72f142a3ad7_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_307adc40d72f142a3ad7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "337f61f00415023733c03d4bc13d6a5a2be61725f6efb64119a8dbf729fb8cbf",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_31d463c64e2f293e1549": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_31d463c64e2f293e1549_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_31d463c64e2f293e1549_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "747f27f60336b4ef21a650def39eefabe06b0b66107b8a868f370e182c356a95",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_3aed6956b7b08660a264": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_3aed6956b7b08660a264_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_3aed6956b7b08660a264_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "62c448d8cb9190125e529db388670df7eb419c9dbc2044e5cb5965f8c45d500c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_3b35275c99e1b9eaef93": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_3b35275c99e1b9eaef93_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_3b35275c99e1b9eaef93_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0e3a28f37439139c3b35cc2ae2a1c310ea172782316c9944c43794d79bba32e6",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_3cceb593ea9572a7910e": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_3cceb593ea9572a7910e_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_3cceb593ea9572a7910e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fe735701deabcd137aa9fd3f5403cfc740140619e1ebffbd34249d94ac2d90da",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_4617796171e3a15b7b01": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_4617796171e3a15b7b01_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_4617796171e3a15b7b01_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "85f7ae8835a288c9ae5cb760bc2ccb21ab3107a13717e7769f3c77b5f7b02d9d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_4a02ee8fb05b64907184": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4a02ee8fb05b64907184_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4a02ee8fb05b64907184_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "33c87326138dfcdbf5f277b1ab252d528bd8af6cdba17a977c033cd733355360",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_4b069de31665b36ac2c4": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4b069de31665b36ac2c4_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4b069de31665b36ac2c4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8b6e2ca558fca2b9d19b048c0ea2a47e68d07115d908e8881db35f7f29e319a3",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_5530ee096459f73333d8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_5530ee096459f73333d8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_5530ee096459f73333d8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f1dbd4f1fa82bdbbc6f0110fcbc2cc512b1cc974c7acb70df0be47ee53efcc3e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_6454095ab0c3891b3b41": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6454095ab0c3891b3b41_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6454095ab0c3891b3b41_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "057876e1687447acfedaa046dfe14abcf72f2d8ffb8b27cdf61c49d906944a6e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_64d5e9edc24052a323e8": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_64d5e9edc24052a323e8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_64d5e9edc24052a323e8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b7c8d2c6f87afe6d52bcbe7b4976d90392f0ea8d6de2a862040e9007f0af4d20",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_6a152899377da7f945f8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6a152899377da7f945f8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6a152899377da7f945f8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1e1970444de33d629b1d425c3d2fe5bcc4734928893d4a560cba8e6208fde10d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_759fd61ba107871b97df": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_759fd61ba107871b97df_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_759fd61ba107871b97df_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c066a16e57751c82d2b5779cac3cc4d5d5bf64685f6beb7e21a208b78a782616",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_7f0fd228059fee782a48": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7f0fd228059fee782a48_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7f0fd228059fee782a48_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1e01d99152d5c5fba613955e8bc690a93ab64f8a3ccf40a07f6d4abadc0d3867",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_7f35f9b1001151fb27d6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7f35f9b1001151fb27d6_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7f35f9b1001151fb27d6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "45279a7ea34ddb4d59f698038fe5fd8b9c078306f75217545863a35f2040f3e1",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_84efbca591a137244872": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_84efbca591a137244872_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_84efbca591a137244872_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "af79019411a5f8d83d3c092d9970a40d5bc85ea6d4d808b1e80ccaf2d07f8c5e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8e2e37692fb7955b2c92": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8e2e37692fb7955b2c92_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8e2e37692fb7955b2c92_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4766ca95a032b28c87d9f46e27584a717ec05fb041ac1b21bbb6382cfa919c5c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8fcad94948d1daa6296d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_8fcad94948d1daa6296d_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_8fcad94948d1daa6296d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "weight"],
            ["buffer", "rowsumsq"],
            ["parameter", "M"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7e86e7b20c76a026c5c959d08722dff269e0a27f69ef24f16665bf867c4b9860",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_960f3b2a869391cc6f07": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_960f3b2a869391cc6f07_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_960f3b2a869391cc6f07_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "05e0ead0a65933b5be528d9bef67d4400ee316a273ea3de4bfb1b2f25bd41ed4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_966a512a7c27fdba70f3": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_966a512a7c27fdba70f3_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_966a512a7c27fdba70f3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1fa3ee2017a7a42f6edfe9d6b80b6121f0d63d4677f266c22a00dac5a15986cf",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_97d6444430434e22e3ec": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_97d6444430434e22e3ec_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_97d6444430434e22e3ec_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "weight"],
            ["buffer", "rowsumsq"],
            ["parameter", "M"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b95066b27259d465d83ece54b80b78f60d5f4e03ccc2b824909fad58d8060547",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_a3d1f9bee37ff8e3d412": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_a3d1f9bee37ff8e3d412_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_a3d1f9bee37ff8e3d412_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "norm_weight"],
            ["buffer", "merge_table"],
            ["buffer", "m_out"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c2271d017b619dad1852ba471c16a549c4c567fa7b60ffbd217866ef0c9896c4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_a949de986a8248834488": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a949de986a8248834488_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a949de986a8248834488_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "86a87d45ae55825213f15b2933a5451be37c2604ddd281866f69dac05a3312ea",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_a97068df87c712231d20": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a97068df87c712231d20_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a97068df87c712231d20_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7f1b45ea1564271eb2b290b237844bbb7f9f859d69bc8edb0ee2cbcf875164a1",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_ac998a99b2f85bd88554": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ac998a99b2f85bd88554_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ac998a99b2f85bd88554_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2be0ffde060448e9642e2ca96ff7668a3545a826f3ef01a968ade09e11d03eca",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_acf234f3085cd986cfa3": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_acf234f3085cd986cfa3_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_acf234f3085cd986cfa3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1cadd55cd0f570f0ec97872df6ff4b2d42893cc03febad21254c94794190b98b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_afd394fbfa0eb200648f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_afd394fbfa0eb200648f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_afd394fbfa0eb200648f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "aa543c6d461eb5ba4218b05fe97ded53a03b4b7106478f7a3afffe9de51715cd",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b1544f648b66bf26b73a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b1544f648b66bf26b73a_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b1544f648b66bf26b73a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "20e98f2a69aa55640642f58218bf8b9d530e1822ae3304f64e5b08600bc537cf",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b3345647b85fe74adf64": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b3345647b85fe74adf64_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b3345647b85fe74adf64_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "250f73d3697a53e9bcdd3d34b9e08dbf7336a89fa710b1f3830269a8206d058c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b3b7b67f1a8424fa2807": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b3b7b67f1a8424fa2807_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b3b7b67f1a8424fa2807_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "49d36aca14a1c25d94a4dfa6c02353f936beb5eebe0738005784a1a335d1780f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b95a7c4862a651148ef7": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b95a7c4862a651148ef7_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b95a7c4862a651148ef7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1bd68d44572ad71b05fc519715b53dd70359f68d6ff58e4b9ea82bae5945bbd7",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_ba2009d871dd7a5205b4": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ba2009d871dd7a5205b4_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ba2009d871dd7a5205b4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "dbc5fcd6e53c11a7f81d7698420bcb9c0c6257409abb8032dc8ae2e0b52f0f0a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_bc8a78f82867c5725259": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_bc8a78f82867c5725259_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_bc8a78f82867c5725259_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4154d16b4797f65dff4c7d99c929de8345c638a8f4ecedb93be5fba83281c4d4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_be82b999ef0fa4a98337": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_be82b999ef0fa4a98337_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_be82b999ef0fa4a98337_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f922ec012a7da0d383d795c9aea30e6a5d9da9069b79cdfe5097363ab930e900",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_c0dc4ff7e000d80b8a53": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_c0dc4ff7e000d80b8a53_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_c0dc4ff7e000d80b8a53_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "3b4ba42f06830f7036fb033d19207c79f8c4d5c5f1a7bee033c35dafa5c40911",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_c91614dbbdcd9944ad85": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_c91614dbbdcd9944ad85_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_c91614dbbdcd9944ad85_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bdc6d865b6c26bdd1eea3612060aec462a13d0c5e79f59429f71a66beaff806a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_dbd633ecfe6f96292ea7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dbd633ecfe6f96292ea7_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dbd633ecfe6f96292ea7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0f8cab1e714ca35c8613a02c6b3c436ea241839f36914b589e92a7f6bae8f884",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_dd62e4b5eb4a13e1d5cd": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dd62e4b5eb4a13e1d5cd_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dd62e4b5eb4a13e1d5cd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6e5647939afe2251adcf6bb74ec8fbbd98723dd782fe6680666e6cfe4f9682a7",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_e8e58590c9f7da9fae6d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_e8e58590c9f7da9fae6d_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_e8e58590c9f7da9fae6d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d8c24d2f9251555e6c6f18901cb022429e7624c5e9785f55bd59880f0c372638",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_edb3f346fa6b95000db8": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_edb3f346fa6b95000db8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_edb3f346fa6b95000db8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4907e29db7ba37af39adb96c015fa81bc6e1302f9c5cab637843f65f0c9f4b17",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_f5fec367a9800dc604f9": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_f5fec367a9800dc604f9_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_f5fec367a9800dc604f9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2c125cd04a15fbe238615806dd214ff88ba177e68526d72a0d7952990d1b0001",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_f7b6a99bc33e171fe63b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_f7b6a99bc33e171fe63b_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_f7b6a99bc33e171fe63b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f44516d5dd6d8a5f62aa8e8da361fc0ec9f679e463904036b89653bb4cd7a41e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_f96e005506dad789b276": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_f96e005506dad789b276_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_f96e005506dad789b276_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0348d01057e332391d160addd4ab222a275a5d21f80826c6cadc684b139b2bc8",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_fcb0d9184a4784987429": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_fcb0d9184a4784987429_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_fcb0d9184a4784987429_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b2fcf642ee82124175aa97d5fac35590c160581ac9f20395b8cb86ab1780d8ff",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_ffe438870310472fe92b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ffe438870310472fe92b_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_ffe438870310472fe92b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b37321af17a28da39fe61bf1fa01393ec86c8be2e17d7be85c1079da3e005583",
        "tma_workspace_bytes": 0,
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "attention:tiles1": "cake_kimi_k3_vision_tower_307adc40d72f142a3ad7",
        "attention:tiles2": "cake_kimi_k3_vision_tower_e8e58590c9f7da9fae6d",
        "gemm:gelu_erf:l": "cake_kimi_k3_vision_tower_c0dc4ff7e000d80b8a53",
        "gemm:gelu_erf:s": "cake_kimi_k3_vision_tower_ac998a99b2f85bd88554",
        "gemm:gelu_erf:xs": "cake_kimi_k3_vision_tower_84efbca591a137244872",
        "gemm:norm_gelu:l_e8": "cake_kimi_k3_vision_tower_a949de986a8248834488",
        "gemm:norm_gelu:s": "cake_kimi_k3_vision_tower_8e2e37692fb7955b2c92",
        "gemm:norm_gelu:xs": "cake_kimi_k3_vision_tower_4b069de31665b36ac2c4",
        "gemm:norm_qkv_rope:l_e8": "cake_kimi_k3_vision_tower_1bf640d943880236989f",
        "gemm:norm_qkv_rope:s": "cake_kimi_k3_vision_tower_f5fec367a9800dc604f9",
        "gemm:norm_qkv_rope:xs": "cake_kimi_k3_vision_tower_4a02ee8fb05b64907184",
        "gemm:pos_sqxw:s_e8": "cake_kimi_k3_vision_tower_64d5e9edc24052a323e8",
        "gemm:pos_sqxw:xs": "cake_kimi_k3_vision_tower_0af9477ad7b9f08efc52",
        "gemm:residual_fc1:l_e8": "cake_kimi_k3_vision_tower_ffe438870310472fe92b",
        "gemm:residual_fc1:m": "cake_kimi_k3_vision_tower_3b35275c99e1b9eaef93",
        "gemm:residual_fc1:xs": "cake_kimi_k3_vision_tower_ba2009d871dd7a5205b4",
        "gemm:residual_fc1:xs_k4": "cake_kimi_k3_vision_tower_b3345647b85fe74adf64",
        "gemm:residual_fc1_sqxw:l_e8": "cake_kimi_k3_vision_tower_dbd633ecfe6f96292ea7",
        "gemm:residual_fc1_sqxw:m": "cake_kimi_k3_vision_tower_b1544f648b66bf26b73a",
        "gemm:residual_fc1_sqxw:xs": "cake_kimi_k3_vision_tower_a97068df87c712231d20",
        "gemm:residual_fc1_sqxw:xs_k4": "cake_kimi_k3_vision_tower_afd394fbfa0eb200648f",
        "gemm:residual_wo_sqxw:m": "cake_kimi_k3_vision_tower_edb3f346fa6b95000db8",
        "gemm:residual_wo_sqxw:xs": "cake_kimi_k3_vision_tower_dd62e4b5eb4a13e1d5cd",
        "gemm:rmsnorm:l": "cake_kimi_k3_vision_tower_199198b854f1e3657b6f",
        "gemm:rmsnorm:s": "cake_kimi_k3_vision_tower_2c9410cb55e83813059b",
        "merge": "cake_kimi_k3_vision_tower_0f1dbb5852a0d5513d87",
        "rmsnorm_apply": "cake_kimi_k3_vision_tower_97d6444430434e22e3ec",
    },
    "sm_103a": {
        "attention:tiles1": "cake_kimi_k3_vision_tower_b95a7c4862a651148ef7",
        "attention:tiles2": "cake_kimi_k3_vision_tower_3aed6956b7b08660a264",
        "gemm:gelu_erf:l": "cake_kimi_k3_vision_tower_fcb0d9184a4784987429",
        "gemm:gelu_erf:s": "cake_kimi_k3_vision_tower_31d463c64e2f293e1549",
        "gemm:gelu_erf:xs": "cake_kimi_k3_vision_tower_06ebbf8c1cbb463a324f",
        "gemm:norm_gelu:l_e8": "cake_kimi_k3_vision_tower_6454095ab0c3891b3b41",
        "gemm:norm_gelu:s": "cake_kimi_k3_vision_tower_6a152899377da7f945f8",
        "gemm:norm_gelu:xs": "cake_kimi_k3_vision_tower_960f3b2a869391cc6f07",
        "gemm:norm_qkv_rope:l_e8": "cake_kimi_k3_vision_tower_7f0fd228059fee782a48",
        "gemm:norm_qkv_rope:s": "cake_kimi_k3_vision_tower_4617796171e3a15b7b01",
        "gemm:norm_qkv_rope:xs": "cake_kimi_k3_vision_tower_f7b6a99bc33e171fe63b",
        "gemm:pos_sqxw:s_e8": "cake_kimi_k3_vision_tower_be82b999ef0fa4a98337",
        "gemm:pos_sqxw:xs": "cake_kimi_k3_vision_tower_23b42f8b63924df28f98",
        "gemm:residual_fc1:l_e8": "cake_kimi_k3_vision_tower_7f35f9b1001151fb27d6",
        "gemm:residual_fc1:m": "cake_kimi_k3_vision_tower_b3b7b67f1a8424fa2807",
        "gemm:residual_fc1:xs": "cake_kimi_k3_vision_tower_966a512a7c27fdba70f3",
        "gemm:residual_fc1:xs_k4": "cake_kimi_k3_vision_tower_c91614dbbdcd9944ad85",
        "gemm:residual_fc1_sqxw:l_e8": "cake_kimi_k3_vision_tower_5530ee096459f73333d8",
        "gemm:residual_fc1_sqxw:m": "cake_kimi_k3_vision_tower_bc8a78f82867c5725259",
        "gemm:residual_fc1_sqxw:xs": "cake_kimi_k3_vision_tower_759fd61ba107871b97df",
        "gemm:residual_fc1_sqxw:xs_k4": "cake_kimi_k3_vision_tower_21792a093effefddce91",
        "gemm:residual_wo_sqxw:m": "cake_kimi_k3_vision_tower_1db97bef963ed488dc72",
        "gemm:residual_wo_sqxw:xs": "cake_kimi_k3_vision_tower_acf234f3085cd986cfa3",
        "gemm:rmsnorm:l": "cake_kimi_k3_vision_tower_f96e005506dad789b276",
        "gemm:rmsnorm:s": "cake_kimi_k3_vision_tower_3cceb593ea9572a7910e",
        "merge": "cake_kimi_k3_vision_tower_a3d1f9bee37ff8e3d412",
        "rmsnorm_apply": "cake_kimi_k3_vision_tower_8fcad94948d1daa6296d",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def gemm_kernel_key(variant: str, tile: str) -> str:
    return f"gemm:{variant}:{tile}"


def attention_kernel_key(tiles_per_cta: int) -> str:
    return f"attention:tiles{int(tiles_per_cta)}"


MERGE_KERNEL_KEY = "merge"
RMSNORM_APPLY_KERNEL_KEY = "rmsnorm_apply"


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 vision tower programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4568)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 vision tower kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4568)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_vision_tower_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_vision_tower_module(name: str):
    return gen_cake_kimi_k3_vision_tower_module(name).build_and_load()
