"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the
# Kimi-K3 vision tower (MoonViT-3D encoder + PatchMergerV2; SM100 / SM103).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host launcher resolves at preparation:
#
# * ``gemm:<variant>:<tile>``   the fused tcgen05 BF16 GEMM family
#   (``pos``, ``norm_qkv_rope``, ``residual_wo``, ``norm_gelu``,
#   ``residual_fc1``, ``gelu_erf``, ``rmsnorm``) on the production tile
#   configuration ``select_tile_config`` picks for the token count;
# * ``attention:tiles2`` / ``attention:tiles1``   the packed-varlen BF16
#   attention kernel in its two-tile and SPLIT_KV unit layouts (the host plan
#   rule ``select_tiles_per_cta`` chooses per ``grid_thws`` batch);
# * ``merge``                     final RMSNorm + 2x2 spatial / temporal-mean merge;
# * ``rmsnorm_apply``             the post-projector RMSNorm apply pass.
#
# Every module is an exact-architecture program (tcgen05 / TMEM / 2-CTA MMA);
# the sm_103a attention additionally drains scores with ``tcgen05.ld.red``.
# Both literals are populated verbatim by the generated-program export; do
# not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_vision_tower_0412cee3db4a6cf0e44a": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0412cee3db4a6cf0e44a_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0412cee3db4a6cf0e44a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "34ca6fedfb29651c62c9bf4e9972078d46c2c7a7908479a257c00b8675f96ca5",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_0510597d848ab681b29a": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0510597d848ab681b29a_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0510597d848ab681b29a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "040dd2bf66fe692d7bffb223692dc1313e094f014135f6af2c12bd55f512a3fe",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_05798ab4f949721f1486": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_05798ab4f949721f1486_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_05798ab4f949721f1486_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4fe8c3f3528b231e472b7b836c8791a39d22dc34799e4f8f1d27a96e9624fc0c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_06967bebce6430b87a11": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_06967bebce6430b87a11_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_06967bebce6430b87a11_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d65ba0ba45eb77b73c79754cb3568272c1b96fa8b9c010e43304d193aebd13b4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_070f3e4fed51e9bcb2ff": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_070f3e4fed51e9bcb2ff_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_070f3e4fed51e9bcb2ff_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d06bce88a5d7f02f72103375034bff7405e862f7542b1ce7f87a031e32e3793d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_0a54c48e4360f09e32af": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0a54c48e4360f09e32af_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0a54c48e4360f09e32af_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "21b476395f1c2338790b0398767a5d02fe4c862fdcddd056a5c65396037abbfd",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_0b464a26bb0b01f5a1dc": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0b464a26bb0b01f5a1dc_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_0b464a26bb0b01f5a1dc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "be55e463c8e4e2521279532681943b5e295146de79b2505c906d4483139445d2",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_108065fc063a77a439ff": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_108065fc063a77a439ff_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_108065fc063a77a439ff_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5fc07ff987a09ef5efe8b8fb23a9a27b60c83fc8a6ac80c17f9c9e60a8d7231f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_166d723f9a1466854b55": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_166d723f9a1466854b55_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_166d723f9a1466854b55_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d2920a491d04bd1aeefa51d747d8b5905a6b6152632867c0efbe8e5001732558",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_1cb70bf9d01f255bb375": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_1cb70bf9d01f255bb375_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_1cb70bf9d01f255bb375_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5e1010d5bb0b91b59e50bbe33e2bdebe717c35d180459de008e07f18020736bd",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_205e18aed1faa07ca1a1": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_205e18aed1faa07ca1a1_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_205e18aed1faa07ca1a1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2ca10b3616ed4032be4f4c712bc3246e7827aceea810be5e74dfbea19397e68b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_21c97faae8373e3fa4b2": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_21c97faae8373e3fa4b2_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_21c97faae8373e3fa4b2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6154966c55411570b5989abb27683f76972327c7cdb96272d9c22439e15339ea",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_2b659f15e777ce4a0ac9": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_2b659f15e777ce4a0ac9_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_2b659f15e777ce4a0ac9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "22cb918057836156369525c235e66f87271338cb04fdcff5bdeadf47b9ff335b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_37a3f33ba08309a52dc4": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_37a3f33ba08309a52dc4_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_37a3f33ba08309a52dc4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "033d8ae197a547a81e9f4016ef41e11852b307df5cba160343ec523fbb359dbc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_394ddce48c70908dd421": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_394ddce48c70908dd421_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_394ddce48c70908dd421_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "186f0757316307cf6d9bcc6132e29797e86e36adead7074500a36bf36351ae51",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_43feaccd0cef4ee3c68a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_43feaccd0cef4ee3c68a_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_43feaccd0cef4ee3c68a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "53197b31f78b379326ecd259b07585a74269947d037f8408531574d3dee1cfbf",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_490785d9d81ac0cff316": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_490785d9d81ac0cff316_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_490785d9d81ac0cff316_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "norm_weight"],
            ["buffer", "merge_table"],
            ["buffer", "m_out"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0f0603f6a19b47307b19aa8664cfaa9c017bc4ab2d369a874959a499569da883",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_4948f45a76970693a137": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4948f45a76970693a137_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_4948f45a76970693a137_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "65f266d4d4b1358441cde5db3b089ac13c411c5796589512996722ebc70fda3f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_49f4284b6369c12b848c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_49f4284b6369c12b848c_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_49f4284b6369c12b848c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a4f3092f8c8ca6871f12a8da1b7db003baae23b0b53b27c1b1248a90c0781c46",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_4d3c93cbd1d4fcdd0d1f": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_4d3c93cbd1d4fcdd0d1f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_4d3c93cbd1d4fcdd0d1f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f837426ff733c872f127834d06360bfdc85a9e27365562f6d058c58e560ebeba",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_5b3fb2223cf6e81014d8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_5b3fb2223cf6e81014d8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_5b3fb2223cf6e81014d8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8a58c061ba5823f4e445ed96a7c69d4489176ab15311481dbfc31eaef0d2b0c0",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_625a2435628f973645d5": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_625a2435628f973645d5_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_625a2435628f973645d5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e924501cc2509d1cb77bf7a776ed9e7aa6a393c62388383ee2c225fb36b42b55",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_66d5db914b74a11f2ca8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_66d5db914b74a11f2ca8_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_66d5db914b74a11f2ca8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0992f7c0462ba1e219475483250fdca64a1af302b8730bfe70130c71b5c1d691",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_68703b18d9ed8bd395ab": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_68703b18d9ed8bd395ab_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_68703b18d9ed8bd395ab_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "weight"],
            ["buffer", "rowsumsq"],
            ["parameter", "M"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "aaf34bad30c3db1f6314446af349f90802142fe48f98d1c6e940e7598378598a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_6cdd5d63ae17746c33b7": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6cdd5d63ae17746c33b7_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_6cdd5d63ae17746c33b7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4d9f6fab5b343b24ffe5d70294596081a0e1cc3cff6067b8c02fa898e281e7d6",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_6f287fa965c3de28d091": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_6f287fa965c3de28d091_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_6f287fa965c3de28d091_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fa2af2e891faddaa22118d571c4d937d46c1f95b396eb442f9857d1e82738d77",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_7262f77479083cd892dd": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7262f77479083cd892dd_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_7262f77479083cd892dd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1805fb36727b3bcfc3a7d1d13d417bd875f28fdb4c83e050136d130b6a8744c9",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_818fd9be8f8d89dbc91b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_818fd9be8f8d89dbc91b_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_818fd9be8f8d89dbc91b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1ab8971126ee88c02b4f025042e3e9798aa435e2e6876c8eef0a4863bbb4b141",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_87112501e776709b45e9": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_87112501e776709b45e9_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_87112501e776709b45e9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2b48f15172788c763db0413c7c928dd427cedcc8d5bf8da04082faa7a7100061",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8a80269e13d6f0e3a1b2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_8a80269e13d6f0e3a1b2_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_8a80269e13d6f0e3a1b2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "946af4bf9b2f91dac28ba6b53f8e993b6062f461ae01f90dcbd7007c9b24d106",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8a9d596bcb18eb70d1f0": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8a9d596bcb18eb70d1f0_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8a9d596bcb18eb70d1f0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4d6ad5c060c80658113fd643033497befed0cf0b7e588f7d101a65dac844dde8",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8d3482326641c54c725a": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8d3482326641c54c725a_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8d3482326641c54c725a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0cb4d950f5477a9be2fa93d9752270f41cc1290186b8155a2288445199be8473",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_8eb8e53f87769b31fe96": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8eb8e53f87769b31fe96_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_8eb8e53f87769b31fe96_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4921893d8f8677b95771b7581ac6317bce253c7530e73d02a3614f455717be21",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_915b2ca02e4aad2a1673": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_915b2ca02e4aad2a1673_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_915b2ca02e4aad2a1673_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "297f9db6c538f2811d516e5a4e9d35b0848c2afd577bd40a03eb35e2d4f7fb18",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_91c98b33f9957920fa4c": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_91c98b33f9957920fa4c_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_91c98b33f9957920fa4c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6076c43f46e3283b61023d6469eef18962f670ba063b08ba110afb12b82e7273",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_9dab32b1df263885b207": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_9dab32b1df263885b207_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_9dab32b1df263885b207_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fae3850972cb4fa475373dda7d0a76381a30c9fdba1121af11ab3c3a17d73fb4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_9e9111cfadc59ea0ef6c": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_9e9111cfadc59ea0ef6c_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_9e9111cfadc59ea0ef6c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e12c7b6e233c92a439a00280734fe26e43e359a1645797a7d92021027e50133f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_a325b971de69565e5b1e": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a325b971de69565e5b1e_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_a325b971de69565e5b1e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "206f76dba06b1a2d974fceeaf477beee729c70f593392f97dc36aaf4580a262f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_a93555503f0e9c0b2833": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_a93555503f0e9c0b2833_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_a93555503f0e9c0b2833_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e1d5677dd491f91e1e4fa7fc378673f9ec05a2cbdb233b4235c6410cfcd27b75",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b08fc1d3d2ffc5fc6c94": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b08fc1d3d2ffc5fc6c94_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b08fc1d3d2ffc5fc6c94_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ae06270c71400b2dd4303f5bcbe2312a040dcdc48812cd00d26e86ac33711e34",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b25c45827e3f841871b9": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b25c45827e3f841871b9_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b25c45827e3f841871b9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math", "--ptxas-options=--opt-level=1"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["buffer", "Q_raw"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["tma_buffer", "O_tma"],
            ["buffer", "seg_begin"],
            ["buffer", "seg_len"],
            ["buffer", "unit_table"],
            ["buffer", "probe"],
            ["parameter", "total_tiles"],
            ["parameter", "num_heads"],
            ["parameter", "softmax_scale_log2"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "45c025d37efd0e1d89d2ce5b9f270d4da66fa8ad6a62a482922035a7621483c6",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b30dbd389f58654a05d2": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b30dbd389f58654a05d2_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_b30dbd389f58654a05d2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ff8d5dbb513b951087163ffd0ad95f6ac68ec3f423aee12d721731933f24ca82",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_b34f22a7310f0e9f98c0": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b34f22a7310f0e9f98c0_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_b34f22a7310f0e9f98c0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "64d0e36e128af7c1e0f9e1592d78095398db5cf2cd5aa24ecddbd73989869fb4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_bcff75feff930ae04377": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_bcff75feff930ae04377_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_bcff75feff930ae04377_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "909ca12256aab892afc38d2c32c840c6f41a604eda6f9ff7894e9e08144f9e60",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_c92fcc6b026469a4486e": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_c92fcc6b026469a4486e_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_c92fcc6b026469a4486e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "794a514610b24bcca847b12f5be2ebb2b04fc5ec1ff534e812da6455be10dd03",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_d2646625c7cd4e975045": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_d2646625c7cd4e975045_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_d2646625c7cd4e975045_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fc52b6368bde99b6cdcdb02d1713d7318273a61f2a59df304ebe879bf3fdccbd",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_d3f07fd30e607c90e120": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_d3f07fd30e607c90e120_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_d3f07fd30e607c90e120_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "y"],
            ["buffer", "weight"],
            ["buffer", "rowsumsq"],
            ["parameter", "M"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9d89a64e71dfbc7de070798484fcef6043db711305dd843d6315d37e8275b77d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_d96515fe262f77ad0e3b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_d96515fe262f77ad0e3b_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_d96515fe262f77ad0e3b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d065549997620dc54aee98fb156ce095146bdcb0995a7dc0611266f9505b90bb",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_dcb7e47bbc6ff3f35716": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dcb7e47bbc6ff3f35716_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_dcb7e47bbc6ff3f35716_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6852f5614991e2fc47aaed77fd5d99fb434c9a687f685f4f0071ae441dac2985",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_e53152ca1aff7904f79f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_e53152ca1aff7904f79f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_e53152ca1aff7904f79f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "798baa142ed891e62be1696d97a7c569150fcf709b074eafb639c1a6500e64af",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_e540c6015253f7d092f1": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_e540c6015253f7d092f1_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_e540c6015253f7d092f1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "norm_weight"],
            ["buffer", "merge_table"],
            ["buffer", "m_out"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "85f7ae0709bc26aeef39175dae846985f4b4e5b00a1d673244dcb9603b50f50d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_e6a3524123298177f1a6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_e6a3524123298177f1a6_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_103a/cake_kimi_k3_vision_tower_e6a3524123298177f1a6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "81871f0719a5e25d1394e0b77e84ee33fa97f1320a1b69f0a900b3fc0ba4c294",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_fb5098ba3b4866b810f3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_fb5098ba3b4866b810f3_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_fb5098ba3b4866b810f3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1da0379258d52bc0405b5f0f7897b6e1a35c25dc62ee0ad4a21c7e151ce99ef8",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_vision_tower_fbd5e5d2222acd44732f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_fbd5e5d2222acd44732f_kernel.cu",
            "cake_kimi_k3_vision_tower/sm_100a/cake_kimi_k3_vision_tower_fbd5e5d2222acd44732f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "A2"],
            ["tma_buffer", "B"],
            ["buffer", "C"],
            ["buffer", "C2"],
            ["buffer", "C3"],
            ["buffer", "R"],
            ["buffer", "COS"],
            ["buffer", "SIN"],
            ["buffer", "CS"],
            ["buffer", "SQ"],
            ["buffer", "XW"],
            ["buffer", "WN"],
            ["buffer", "WS"],
            ["buffer", "FLAGS"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "full_tiles"],
            ["parameter", "tail_split"],
            ["parameter", "eps"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "254edf5ae75d93f7e14ef1e3b7a1a95d4eda95cceb2b3e37d7c2cf66d5c91555",
        "tma_workspace_bytes": 0,
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "attention:tiles1": "cake_kimi_k3_vision_tower_8a9d596bcb18eb70d1f0",
        "attention:tiles2": "cake_kimi_k3_vision_tower_818fd9be8f8d89dbc91b",
        "gemm:gelu_erf:l": "cake_kimi_k3_vision_tower_1cb70bf9d01f255bb375",
        "gemm:gelu_erf:s": "cake_kimi_k3_vision_tower_8eb8e53f87769b31fe96",
        "gemm:gelu_erf:xs": "cake_kimi_k3_vision_tower_fbd5e5d2222acd44732f",
        "gemm:norm_gelu:l_e8": "cake_kimi_k3_vision_tower_a325b971de69565e5b1e",
        "gemm:norm_gelu:s": "cake_kimi_k3_vision_tower_166d723f9a1466854b55",
        "gemm:norm_gelu:xs": "cake_kimi_k3_vision_tower_9e9111cfadc59ea0ef6c",
        "gemm:norm_qkv_rope:l_e8_cs": "cake_kimi_k3_vision_tower_b08fc1d3d2ffc5fc6c94",
        "gemm:norm_qkv_rope:s_cs": "cake_kimi_k3_vision_tower_dcb7e47bbc6ff3f35716",
        "gemm:norm_qkv_rope:xs_cs_pf": "cake_kimi_k3_vision_tower_43feaccd0cef4ee3c68a",
        "gemm:pos_sqxw:s_e8_pf": "cake_kimi_k3_vision_tower_05798ab4f949721f1486",
        "gemm:pos_sqxw:xs_pf": "cake_kimi_k3_vision_tower_b30dbd389f58654a05d2",
        "gemm:residual_fc1:l_e8_pf": "cake_kimi_k3_vision_tower_d2646625c7cd4e975045",
        "gemm:residual_fc1:m_p": "cake_kimi_k3_vision_tower_8d3482326641c54c725a",
        "gemm:residual_fc1:xs_k4_pf": "cake_kimi_k3_vision_tower_4948f45a76970693a137",
        "gemm:residual_fc1:xs_pf": "cake_kimi_k3_vision_tower_070f3e4fed51e9bcb2ff",
        "gemm:residual_fc1_sqxw:l_e8_pf": "cake_kimi_k3_vision_tower_bcff75feff930ae04377",
        "gemm:residual_fc1_sqxw:m_p": "cake_kimi_k3_vision_tower_fb5098ba3b4866b810f3",
        "gemm:residual_fc1_sqxw:xs_k4_pf": "cake_kimi_k3_vision_tower_21c97faae8373e3fa4b2",
        "gemm:residual_fc1_sqxw:xs_pf": "cake_kimi_k3_vision_tower_6f287fa965c3de28d091",
        "gemm:residual_wo_sqxw:m_p": "cake_kimi_k3_vision_tower_108065fc063a77a439ff",
        "gemm:residual_wo_sqxw:xs_pf": "cake_kimi_k3_vision_tower_9dab32b1df263885b207",
        "gemm:rmsnorm:l": "cake_kimi_k3_vision_tower_e53152ca1aff7904f79f",
        "gemm:rmsnorm:s": "cake_kimi_k3_vision_tower_06967bebce6430b87a11",
        "merge": "cake_kimi_k3_vision_tower_490785d9d81ac0cff316",
        "rmsnorm_apply": "cake_kimi_k3_vision_tower_d3f07fd30e607c90e120",
    },
    "sm_103a": {
        "attention:tiles1": "cake_kimi_k3_vision_tower_b25c45827e3f841871b9",
        "attention:tiles2": "cake_kimi_k3_vision_tower_87112501e776709b45e9",
        "gemm:gelu_erf:l": "cake_kimi_k3_vision_tower_b34f22a7310f0e9f98c0",
        "gemm:gelu_erf:s": "cake_kimi_k3_vision_tower_394ddce48c70908dd421",
        "gemm:gelu_erf:xs": "cake_kimi_k3_vision_tower_625a2435628f973645d5",
        "gemm:norm_gelu:l_e8": "cake_kimi_k3_vision_tower_a93555503f0e9c0b2833",
        "gemm:norm_gelu:s": "cake_kimi_k3_vision_tower_0412cee3db4a6cf0e44a",
        "gemm:norm_gelu:xs": "cake_kimi_k3_vision_tower_915b2ca02e4aad2a1673",
        "gemm:norm_qkv_rope:l_e8_cs": "cake_kimi_k3_vision_tower_91c98b33f9957920fa4c",
        "gemm:norm_qkv_rope:s_cs": "cake_kimi_k3_vision_tower_d96515fe262f77ad0e3b",
        "gemm:norm_qkv_rope:xs_cs_pf": "cake_kimi_k3_vision_tower_37a3f33ba08309a52dc4",
        "gemm:pos_sqxw:s_e8_pf": "cake_kimi_k3_vision_tower_0510597d848ab681b29a",
        "gemm:pos_sqxw:xs_pf": "cake_kimi_k3_vision_tower_66d5db914b74a11f2ca8",
        "gemm:residual_fc1:l_e8_pf": "cake_kimi_k3_vision_tower_4d3c93cbd1d4fcdd0d1f",
        "gemm:residual_fc1:m_p": "cake_kimi_k3_vision_tower_2b659f15e777ce4a0ac9",
        "gemm:residual_fc1:xs_k4_pf": "cake_kimi_k3_vision_tower_0b464a26bb0b01f5a1dc",
        "gemm:residual_fc1:xs_pf": "cake_kimi_k3_vision_tower_7262f77479083cd892dd",
        "gemm:residual_fc1_sqxw:l_e8_pf": "cake_kimi_k3_vision_tower_8a80269e13d6f0e3a1b2",
        "gemm:residual_fc1_sqxw:m_p": "cake_kimi_k3_vision_tower_6cdd5d63ae17746c33b7",
        "gemm:residual_fc1_sqxw:xs_k4_pf": "cake_kimi_k3_vision_tower_0a54c48e4360f09e32af",
        "gemm:residual_fc1_sqxw:xs_pf": "cake_kimi_k3_vision_tower_e6a3524123298177f1a6",
        "gemm:residual_wo_sqxw:m_p": "cake_kimi_k3_vision_tower_205e18aed1faa07ca1a1",
        "gemm:residual_wo_sqxw:xs_pf": "cake_kimi_k3_vision_tower_5b3fb2223cf6e81014d8",
        "gemm:rmsnorm:l": "cake_kimi_k3_vision_tower_49f4284b6369c12b848c",
        "gemm:rmsnorm:s": "cake_kimi_k3_vision_tower_c92fcc6b026469a4486e",
        "merge": "cake_kimi_k3_vision_tower_e540c6015253f7d092f1",
        "rmsnorm_apply": "cake_kimi_k3_vision_tower_68703b18d9ed8bd395ab",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}


def gemm_kernel_key(variant: str, tile: str) -> str:
    return f"gemm:{variant}:{tile}"


def attention_kernel_key(tiles_per_cta: int) -> str:
    return f"attention:tiles{int(tiles_per_cta)}"


MERGE_KERNEL_KEY = "merge"
RMSNORM_APPLY_KERNEL_KEY = "rmsnorm_apply"


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 vision tower programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4568)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 vision tower kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4568)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_vision_tower_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_vision_tower_module(name: str):
    return gen_cake_kimi_k3_vision_tower_module(name).build_and_load()
