"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# JIT registration of the generated Blackwell BF16 x FP4 GEMM programs.
#
# ``MODULES`` lists every physical program once: its device and binding
# translation units under ``csrc/blackwell_bf16_fp4`` (one source for every
# architecture in ``arches``), the compile flags of the source build, the
# tvm-ffi entry, the positional argument plan and the launch geometry.
# ``ROUTES`` maps the logical kernel key selected by
# ``flashinfer.gemm.gemm_bf16_fp4_blackwell`` to its program.  Both tables are
# written by the generated-program export; do not edit them by hand.

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ..compilation_context import CompilationContext
from . import env as jit_env
from .core import JitSpec, gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

MODULES: dict[str, dict[str, Any]] = {
    "cake_blackwell_bf16_fp4_01269af369b6ca2f265f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_01269af369b6ca2f265f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_01269af369b6ca2f265f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_01269af369b6ca2f265f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_023d26416fc1b8b440e1": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_023d26416fc1b8b440e1",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_023d26416fc1b8b440e1_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_023d26416fc1b8b440e1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_04b3e10e4154d92341cd": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_04b3e10e4154d92341cd",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04b3e10e4154d92341cd_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04b3e10e4154d92341cd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partials"],
            ["buffer", "C"],
            ["parameter", "elements"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 0,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_04f102301a6caccf3ef9": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_04f102301a6caccf3ef9",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04f102301a6caccf3ef9_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04f102301a6caccf3ef9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0514be13a6625fe20da7": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0514be13a6625fe20da7",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0514be13a6625fe20da7_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0514be13a6625fe20da7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_074e904d4bd7b05012a2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_074e904d4bd7b05012a2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_074e904d4bd7b05012a2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_074e904d4bd7b05012a2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_077c32d6e2a6ebffe24d": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_077c32d6e2a6ebffe24d",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_077c32d6e2a6ebffe24d_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_077c32d6e2a6ebffe24d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_07d31eb2b3f974fdd286": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_07d31eb2b3f974fdd286",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_07d31eb2b3f974fdd286_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_07d31eb2b3f974fdd286_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0a51f9a8a3cd01c0c044": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0a51f9a8a3cd01c0c044",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0a51f9a8a3cd01c0c044_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0a51f9a8a3cd01c0c044_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_196ec120a64c2a35a799": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_196ec120a64c2a35a799",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_196ec120a64c2a35a799_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_196ec120a64c2a35a799_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1a6eeb1a7d41c0f12d54": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1a6eeb1a7d41c0f12d54",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1a6eeb1a7d41c0f12d54_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1a6eeb1a7d41c0f12d54_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1aa55bb38555446f68bb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1aa55bb38555446f68bb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1aa55bb38555446f68bb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1aa55bb38555446f68bb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1e94cb74c5ac5cb04075": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1e94cb74c5ac5cb04075",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e94cb74c5ac5cb04075_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e94cb74c5ac5cb04075_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_224bc9f41f99d1f03113": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_224bc9f41f99d1f03113",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_224bc9f41f99d1f03113_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_224bc9f41f99d1f03113_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_2617427744020a3b80b0": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_2617427744020a3b80b0",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2617427744020a3b80b0_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2617427744020a3b80b0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_26ffc7eed934ce15580e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_26ffc7eed934ce15580e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_26ffc7eed934ce15580e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_26ffc7eed934ce15580e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_279873110ddd9dd425f7": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_279873110ddd9dd425f7",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_279873110ddd9dd425f7_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_279873110ddd9dd425f7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_2b63457fafc3df49be1e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_2b63457fafc3df49be1e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2b63457fafc3df49be1e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2b63457fafc3df49be1e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_329b223fccd643796bdf": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_329b223fccd643796bdf",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_329b223fccd643796bdf_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_329b223fccd643796bdf_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_33a9fe1d576242d8ceba": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_33a9fe1d576242d8ceba",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_33a9fe1d576242d8ceba_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_33a9fe1d576242d8ceba_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_3ae9f6b031fb3a69e5a6": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_3ae9f6b031fb3a69e5a6",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae9f6b031fb3a69e5a6_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae9f6b031fb3a69e5a6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_411476304965559f0184": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_411476304965559f0184",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_411476304965559f0184_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_411476304965559f0184_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_4bc32d685db85f337918": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_4bc32d685db85f337918",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4bc32d685db85f337918_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4bc32d685db85f337918_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_4e45c544bae61d4e9100": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_4e45c544bae61d4e9100",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e45c544bae61d4e9100_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e45c544bae61d4e9100_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_57909bca7181725a705f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_57909bca7181725a705f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57909bca7181725a705f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57909bca7181725a705f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5a0565c42c3db0d80855": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5a0565c42c3db0d80855",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5a0565c42c3db0d80855_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5a0565c42c3db0d80855_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5b899e10c0ed7ada6750": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5b899e10c0ed7ada6750",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5b899e10c0ed7ada6750_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5b899e10c0ed7ada6750_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 34816,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5dc876fff2fe218138dc": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5dc876fff2fe218138dc",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5dc876fff2fe218138dc_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5dc876fff2fe218138dc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5e52e807e3d4acb51488": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5e52e807e3d4acb51488",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5e52e807e3d4acb51488_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5e52e807e3d4acb51488_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_66fcfef344a575a294b3": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_66fcfef344a575a294b3",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_66fcfef344a575a294b3_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_66fcfef344a575a294b3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_683e1beeb56cd3f6b934": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_683e1beeb56cd3f6b934",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_683e1beeb56cd3f6b934_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_683e1beeb56cd3f6b934_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6fa3e1498ab6fd355208": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6fa3e1498ab6fd355208",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6fa3e1498ab6fd355208_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6fa3e1498ab6fd355208_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_724adeb4733dc0926a7d": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_724adeb4733dc0926a7d",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_724adeb4733dc0926a7d_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_724adeb4733dc0926a7d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_752ccd10766586dcf810": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_752ccd10766586dcf810",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_752ccd10766586dcf810_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_752ccd10766586dcf810_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_796ca575d1ed975b3bbc": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_796ca575d1ed975b3bbc",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_796ca575d1ed975b3bbc_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_796ca575d1ed975b3bbc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_8145f9f74416b3eb7aee": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_8145f9f74416b3eb7aee",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8145f9f74416b3eb7aee_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8145f9f74416b3eb7aee_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_85ac8746ec0259191bbc": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_85ac8746ec0259191bbc",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_85ac8746ec0259191bbc_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_85ac8746ec0259191bbc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_8e48b9d706dcfc5d8c9b": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_8e48b9d706dcfc5d8c9b",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8e48b9d706dcfc5d8c9b_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8e48b9d706dcfc5d8c9b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_8f57f133866bb1662ce4": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_8f57f133866bb1662ce4",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8f57f133866bb1662ce4_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8f57f133866bb1662ce4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_99adc65489ad9e68f1ef": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_99adc65489ad9e68f1ef",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_99adc65489ad9e68f1ef_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_99adc65489ad9e68f1ef_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_9a0993a075e12c9d387c": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_9a0993a075e12c9d387c",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9a0993a075e12c9d387c_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9a0993a075e12c9d387c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partials"],
            ["buffer", "C"],
            ["parameter", "elements"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 0,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_a1629bab78bcec86ffe1": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_a1629bab78bcec86ffe1",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a1629bab78bcec86ffe1_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a1629bab78bcec86ffe1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_a37017557adc85f0b565": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_a37017557adc85f0b565",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a37017557adc85f0b565_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a37017557adc85f0b565_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b497302deade8c62e431": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b497302deade8c62e431",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b497302deade8c62e431_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b497302deade8c62e431_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b4dbbbe027ec244fb92c": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b4dbbbe027ec244fb92c",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b4dbbbe027ec244fb92c_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b4dbbbe027ec244fb92c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b8233fe48c0865e15d99": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b8233fe48c0865e15d99",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b8233fe48c0865e15d99_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b8233fe48c0865e15d99_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_bb755cae6e02179189cf": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_bb755cae6e02179189cf",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bb755cae6e02179189cf_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bb755cae6e02179189cf_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_cf6fbfa0e7a1839645a0": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_cf6fbfa0e7a1839645a0",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_cf6fbfa0e7a1839645a0_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_cf6fbfa0e7a1839645a0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d1a4e2326052bcab89c5": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d1a4e2326052bcab89c5",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d1a4e2326052bcab89c5_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d1a4e2326052bcab89c5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d34d61107cd5f931c7c1": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d34d61107cd5f931c7c1",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d34d61107cd5f931c7c1_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d34d61107cd5f931c7c1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d3cba069b2bde25e9f4a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d3cba069b2bde25e9f4a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d3cba069b2bde25e9f4a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d3cba069b2bde25e9f4a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d3e170ef65bec0a70875": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d3e170ef65bec0a70875",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d3e170ef65bec0a70875_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d3e170ef65bec0a70875_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d4f4d2965358824ae084": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d4f4d2965358824ae084",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d4f4d2965358824ae084_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d4f4d2965358824ae084_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d643d97e7c93e5c59f59": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d643d97e7c93e5c59f59",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d643d97e7c93e5c59f59_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d643d97e7c93e5c59f59_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d94284c438d593ab647e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d94284c438d593ab647e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d94284c438d593ab647e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d94284c438d593ab647e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e00999eb1dd350e31244": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e00999eb1dd350e31244",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e00999eb1dd350e31244_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e00999eb1dd350e31244_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e2f7102c868f46f7d864": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e2f7102c868f46f7d864",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e2f7102c868f46f7d864_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e2f7102c868f46f7d864_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e38e32cbb4b9777de8f4": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e38e32cbb4b9777de8f4",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e38e32cbb4b9777de8f4_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e38e32cbb4b9777de8f4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e73a5e8907c47202d9f4": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e73a5e8907c47202d9f4",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e73a5e8907c47202d9f4_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e73a5e8907c47202d9f4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ee8a40429fdaee6f8813": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ee8a40429fdaee6f8813",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ee8a40429fdaee6f8813_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ee8a40429fdaee6f8813_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f447e8d93c496a5f1c40": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f447e8d93c496a5f1c40",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f447e8d93c496a5f1c40_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f447e8d93c496a5f1c40_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f45fd3b04de230792191": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f45fd3b04de230792191",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f45fd3b04de230792191_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f45fd3b04de230792191_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f55a437b64a6c2bc3a8f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f55a437b64a6c2bc3a8f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f55a437b64a6c2bc3a8f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f55a437b64a6c2bc3a8f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_fa00b8f466ce285e2457": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_fa00b8f466ce285e2457",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fa00b8f466ce285e2457_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fa00b8f466ce285e2457_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ff2313eae4af393a456f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ff2313eae4af393a456f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff2313eae4af393a456f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff2313eae4af393a456f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
}

ROUTES: dict[str, str] = {
    "cudnn_cp_async_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_077c32d6e2a6ebffe24d",
    "cudnn_cp_async_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_d3cba069b2bde25e9f4a",
    "cudnn_cp_async_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_6fa3e1498ab6fd355208",
    "cudnn_cp_async_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_cf6fbfa0e7a1839645a0",
    "cudnn_cp_async_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_8145f9f74416b3eb7aee",
    "cudnn_cp_async_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_752ccd10766586dcf810",
    "cudnn_cp_async_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_04f102301a6caccf3ef9",
    "cudnn_cp_async_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_196ec120a64c2a35a799",
    "cudnn_cp_async_f16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_3ae9f6b031fb3a69e5a6",
    "cudnn_cp_async_f16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_5e52e807e3d4acb51488",
    "cudnn_cp_async_f16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_d1a4e2326052bcab89c5",
    "cudnn_cp_async_f16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_9a0993a075e12c9d387c",
    "cudnn_cp_async_f16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_26ffc7eed934ce15580e",
    "cudnn_cp_async_f16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_01269af369b6ca2f265f",
    "cudnn_cp_async_f16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_8e48b9d706dcfc5d8c9b",
    "cudnn_cp_async_f16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_a1629bab78bcec86ffe1",
    "cudnn_group_m128_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_2b63457fafc3df49be1e",
    "cudnn_group_m128_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_d643d97e7c93e5c59f59",
    "cudnn_group_m128_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_d4f4d2965358824ae084",
    "cudnn_group_m128_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_f55a437b64a6c2bc3a8f",
    "cudnn_split_k2_partial_f32:alpha0:pdl0": "cake_blackwell_bf16_fp4_1aa55bb38555446f68bb",
    "cudnn_split_k2_partial_f32:alpha0:pdl1": "cake_blackwell_bf16_fp4_f447e8d93c496a5f1c40",
    "cudnn_split_k2_partial_f32:alpha1:pdl0": "cake_blackwell_bf16_fp4_e73a5e8907c47202d9f4",
    "cudnn_split_k2_partial_f32:alpha1:pdl1": "cake_blackwell_bf16_fp4_0a51f9a8a3cd01c0c044",
    "cudnn_split_k2_reduce_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_04b3e10e4154d92341cd",
    "cudnn_split_k2_reduce_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a",
    "cudnn_tma_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_5b899e10c0ed7ada6750",
    "cudnn_tma_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_074e904d4bd7b05012a2",
    "cudnn_tma_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_85ac8746ec0259191bbc",
    "cudnn_tma_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_4bc32d685db85f337918",
    "cudnn_tma_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_e00999eb1dd350e31244",
    "cudnn_tma_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_411476304965559f0184",
    "cudnn_tma_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_d94284c438d593ab647e",
    "cudnn_tma_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_07d31eb2b3f974fdd286",
    "cudnn_tma_f16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_ee8a40429fdaee6f8813",
    "cudnn_tma_f16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_2617427744020a3b80b0",
    "cudnn_tma_f16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_796ca575d1ed975b3bbc",
    "cudnn_tma_f16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_5dc876fff2fe218138dc",
    "cudnn_tma_f16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_1a6eeb1a7d41c0f12d54",
    "cudnn_tma_f16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_bb755cae6e02179189cf",
    "cudnn_tma_f16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_224bc9f41f99d1f03113",
    "cudnn_tma_f16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_e38e32cbb4b9777de8f4",
    "cute_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_fa00b8f466ce285e2457",
    "cute_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_8f57f133866bb1662ce4",
    "cute_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_d34d61107cd5f931c7c1",
    "cute_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_f45fd3b04de230792191",
    "cute_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_b497302deade8c62e431",
    "cute_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_99adc65489ad9e68f1ef",
    "cute_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_279873110ddd9dd425f7",
    "cute_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_329b223fccd643796bdf",
    "cute_seed_exact_m17_n3072_k3072_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82",
    "cute_seed_exact_m768_n2112_k2048_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_b4dbbbe027ec244fb92c",
    "cute_seed_m16_k1024_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_ff2313eae4af393a456f",
    "cute_seed_m16_k1024_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632",
    "cute_seed_m16_k1024_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58",
    "cute_seed_m16_k1024_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_4e45c544bae61d4e9100",
    "cute_warp_mma_m16_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_57909bca7181725a705f",
    "cute_warp_mma_m16_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2",
    "cute_warp_mma_m16_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c",
    "cute_warp_mma_m16_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_724adeb4733dc0926a7d",
    "cute_warp_mma_m16_k16_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_5a0565c42c3db0d80855",
    "cute_warp_mma_m16_k16_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2",
    "cute_warp_mma_m16_k16_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_023d26416fc1b8b440e1",
    "cute_warp_mma_m16_k16_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_d3e170ef65bec0a70875",
    "cute_warp_mma_m16_k32_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42",
    "cute_warp_mma_m16_k32_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f",
    "cute_warp_mma_m16_k32_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5",
    "cute_warp_mma_m16_k32_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_a37017557adc85f0b565",
    "cute_warp_mma_m16_k48_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a",
    "cute_warp_mma_m16_k48_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_e2f7102c868f46f7d864",
    "cute_warp_mma_m16_k48_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_0514be13a6625fe20da7",
    "cute_warp_mma_m16_k48_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_1e94cb74c5ac5cb04075",
    "cute_warp_mma_m32_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_b8233fe48c0865e15d99",
    "cute_warp_mma_m32_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_66fcfef344a575a294b3",
    "cute_warp_mma_m32_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051",
    "cute_warp_mma_m32_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_683e1beeb56cd3f6b934",
    "cute_warp_mma_m64_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb",
    "cute_warp_mma_m64_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb",
    "cute_warp_mma_m64_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25",
    "cute_warp_mma_m64_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_33a9fe1d576242d8ceba",
}

# tcgen05 / TMEM programs: one exact-architecture module per target.
ARCH_NVCC_FLAGS = {"sm_100a": sm100a_nvcc_flags, "sm_103a": sm103a_nvcc_flags}
CAPABILITY_ARCH = {(10, 0): "sm_100a", (10, 3): "sm_103a"}


def _source_dirs() -> tuple[Path, Path]:
    checkout = Path(__file__).resolve().parents[2]
    source_root = checkout / "csrc"
    include_root = checkout / "include"
    if not (source_root / "tvm_ffi_utils.h").is_file():
        source_root = jit_env.FLASHINFER_CSRC_DIR
        include_root = jit_env.FLASHINFER_INCLUDE_DIR
    if not (source_root / "tvm_ffi_utils.h").is_file():
        raise FileNotFoundError("FlashInfer binding headers were not found")
    return source_root, include_root


@functools.cache
def target_capabilities() -> frozenset[tuple[int, int]]:
    """Exported capabilities this process builds for (``FLASHINFER_CUDA_ARCH_LIST`` or visible devices)."""

    capabilities = set()
    for major, minor in CompilationContext().TARGET_CUDA_ARCHS:
        capability = _capability(major, minor)
        if capability in CAPABILITY_ARCH:
            capabilities.add(capability)
    return frozenset(capabilities)


def _capability(major: int | str, minor: int | str) -> tuple[int, int]:
    """``CompilationContext`` keeps the nvcc suffix on the minor version (``"3a"``, ``"0f"``); drop it."""

    digits = str(minor).rstrip("abcdefghijklmnopqrstuvwxyz")
    if not str(major).isdigit() or not digits.isdigit():
        raise ValueError(
            f"malformed CUDA architecture entry {major}.{minor} in FLASHINFER_CUDA_ARCH_LIST"
        )
    return int(major), int(digits)


def supported_arch(capability: tuple[int, int]) -> str | None:
    """The exported architecture for a device capability, or ``None`` when it is not a build target."""

    capability = (int(capability[0]), int(capability[1]))
    if capability not in target_capabilities():
        return None
    return CAPABILITY_ARCH[capability]


@functools.cache
def module_spec(name: str, arch: str) -> JitSpec:
    record = MODULES[name]
    if arch not in record["arches"]:
        raise ValueError(f"program {name!r} is not delivered for {arch}")
    source_root, include_root = _source_dirs()
    sources = [source_root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_{arch}",
        sources=sources,
        extra_cuda_cflags=[*ARCH_NVCC_FLAGS[arch], *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[
            source_root,
            *sorted({p.parent for p in sources}),
            include_root,
        ],
        use_fast_math=False,
    )


@functools.cache
def load_module(name: str, arch: str):
    return module_spec(name, arch).build_and_load()


__all__ = [
    "ARCH_NVCC_FLAGS",
    "CAPABILITY_ARCH",
    "MODULES",
    "ROUTES",
    "load_module",
    "module_spec",
    "supported_arch",
    "target_capabilities",
]
