"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# JIT registration of the generated Blackwell BF16 x FP4 GEMM programs.
#
# ``MODULES`` lists every physical program once: its device and binding
# translation units under ``csrc/blackwell_bf16_fp4`` (one source for every
# architecture in ``arches``), the compile flags of the source build, the
# tvm-ffi entry, the positional argument plan and the launch geometry.
# ``ROUTES`` maps the logical kernel key selected by
# ``flashinfer.gemm.gemm_bf16_fp4_blackwell`` to its program.  Both tables are
# written by the generated-program export; do not edit them by hand.

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ..compilation_context import CompilationContext
from . import env as jit_env
from .core import JitSpec, gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

MODULES: dict[str, dict[str, Any]] = {
    "cake_blackwell_bf16_fp4_0230414401339c1d0410": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0230414401339c1d0410",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0230414401339c1d0410_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0230414401339c1d0410_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_023d26416fc1b8b440e1": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_023d26416fc1b8b440e1",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_023d26416fc1b8b440e1_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_023d26416fc1b8b440e1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_04b3e10e4154d92341cd": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_04b3e10e4154d92341cd",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04b3e10e4154d92341cd_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_04b3e10e4154d92341cd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partials"],
            ["buffer", "C"],
            ["parameter", "elements"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 0,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0514be13a6625fe20da7": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0514be13a6625fe20da7",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0514be13a6625fe20da7_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0514be13a6625fe20da7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0725119ff8055eba138e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0725119ff8055eba138e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0725119ff8055eba138e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0725119ff8055eba138e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_07b14bea4dcf2bf6e793": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_07b14bea4dcf2bf6e793",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_07b14bea4dcf2bf6e793_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_07b14bea4dcf2bf6e793_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0b395775bbc27234f45e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0b395775bbc27234f45e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0b395775bbc27234f45e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0b395775bbc27234f45e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0ea74a069244d05ff34d": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0ea74a069244d05ff34d",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0ea74a069244d05ff34d_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0ea74a069244d05ff34d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_0f9e562baf3ca817390c": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_0f9e562baf3ca817390c",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0f9e562baf3ca817390c_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_0f9e562baf3ca817390c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_15a5f50207e3baf94e49": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_15a5f50207e3baf94e49",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_15a5f50207e3baf94e49_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_15a5f50207e3baf94e49_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_188226f44f4650e55dc2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_188226f44f4650e55dc2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_188226f44f4650e55dc2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_188226f44f4650e55dc2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1b71766bc3036935b747": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1b71766bc3036935b747",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1b71766bc3036935b747_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1b71766bc3036935b747_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_2304cf19f4a19879549d": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_2304cf19f4a19879549d",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2304cf19f4a19879549d_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2304cf19f4a19879549d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_27fa031d0012b04f0742": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_27fa031d0012b04f0742",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_27fa031d0012b04f0742_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_27fa031d0012b04f0742_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_2ad19642455e0f07a0a6": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_2ad19642455e0f07a0a6",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2ad19642455e0f07a0a6_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_2ad19642455e0f07a0a6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_34dc301724af442a6290": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_34dc301724af442a6290",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_34dc301724af442a6290_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_34dc301724af442a6290_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_378e42a49496d4e175cb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_378e42a49496d4e175cb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_378e42a49496d4e175cb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_378e42a49496d4e175cb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_3a73df614427399210be": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_3a73df614427399210be",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3a73df614427399210be_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3a73df614427399210be_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_3bacdd704c0a3ba6c9e9": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_3bacdd704c0a3ba6c9e9",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3bacdd704c0a3ba6c9e9_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_3bacdd704c0a3ba6c9e9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_44a4424e779b208086ab": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_44a4424e779b208086ab",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_44a4424e779b208086ab_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_44a4424e779b208086ab_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_46c64cda9ea11ae00bcb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_46c64cda9ea11ae00bcb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_46c64cda9ea11ae00bcb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_46c64cda9ea11ae00bcb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_4e1b24bd6fccdb912992": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_4e1b24bd6fccdb912992",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e1b24bd6fccdb912992_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e1b24bd6fccdb912992_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_4e45c544bae61d4e9100": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_4e45c544bae61d4e9100",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e45c544bae61d4e9100_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e45c544bae61d4e9100_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_4e961d76c96c0735db42": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_4e961d76c96c0735db42",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e961d76c96c0735db42_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_4e961d76c96c0735db42_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_553aee87036d40228f9b": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_553aee87036d40228f9b",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_553aee87036d40228f9b_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_553aee87036d40228f9b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_57909bca7181725a705f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_57909bca7181725a705f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57909bca7181725a705f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57909bca7181725a705f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_59cc3d9c564129d1be31": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_59cc3d9c564129d1be31",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_59cc3d9c564129d1be31_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_59cc3d9c564129d1be31_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5a0565c42c3db0d80855": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5a0565c42c3db0d80855",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5a0565c42c3db0d80855_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5a0565c42c3db0d80855_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 34816,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_60df3d63bfe47236afd4": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_60df3d63bfe47236afd4",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_60df3d63bfe47236afd4_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_60df3d63bfe47236afd4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_643dbc9880d5dd6402bb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_643dbc9880d5dd6402bb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_643dbc9880d5dd6402bb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_643dbc9880d5dd6402bb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_66fcfef344a575a294b3": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_66fcfef344a575a294b3",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_66fcfef344a575a294b3_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_66fcfef344a575a294b3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6a731b5bbe7ea95c1ae9": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6a731b5bbe7ea95c1ae9",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6a731b5bbe7ea95c1ae9_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6a731b5bbe7ea95c1ae9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6de554584c414a73ad81": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6de554584c414a73ad81",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6de554584c414a73ad81_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6de554584c414a73ad81_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_74215ae16c2d85091ea2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_74215ae16c2d85091ea2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_74215ae16c2d85091ea2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_74215ae16c2d85091ea2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_750fbb6de8160762efdb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_750fbb6de8160762efdb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_750fbb6de8160762efdb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_750fbb6de8160762efdb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_866140668f306522b996": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_866140668f306522b996",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_866140668f306522b996_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_866140668f306522b996_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_8d5a0392779f7f83da76": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_8d5a0392779f7f83da76",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8d5a0392779f7f83da76_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_8d5a0392779f7f83da76_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partials"],
            ["buffer", "C"],
            ["parameter", "elements"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 0,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_9dfe31cc589f0763d332": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_9dfe31cc589f0763d332",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9dfe31cc589f0763d332_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_9dfe31cc589f0763d332_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_a472cfe22f8949bd3c44": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_a472cfe22f8949bd3c44",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a472cfe22f8949bd3c44_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a472cfe22f8949bd3c44_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_a5244de0e8109687c28f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_a5244de0e8109687c28f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a5244de0e8109687c28f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a5244de0e8109687c28f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_a96b2195bd513ebe1053": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_a96b2195bd513ebe1053",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a96b2195bd513ebe1053_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_a96b2195bd513ebe1053_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_aa6c886aa0ebfd3061b5": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_aa6c886aa0ebfd3061b5",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_aa6c886aa0ebfd3061b5_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_aa6c886aa0ebfd3061b5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ab2f6bf76fd35c015114": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ab2f6bf76fd35c015114",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ab2f6bf76fd35c015114_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ab2f6bf76fd35c015114_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_acb0e0ab2d22df35fab8": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_acb0e0ab2d22df35fab8",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_acb0e0ab2d22df35fab8_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_acb0e0ab2d22df35fab8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_af6010375484274af3b2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_af6010375484274af3b2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_af6010375484274af3b2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_af6010375484274af3b2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b4b97457f8892bd24307": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b4b97457f8892bd24307",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b4b97457f8892bd24307_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b4b97457f8892bd24307_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b8233fe48c0865e15d99": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b8233fe48c0865e15d99",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b8233fe48c0865e15d99_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b8233fe48c0865e15d99_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 218112,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b843dc623b0599fd39d6": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b843dc623b0599fd39d6",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b843dc623b0599fd39d6_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b843dc623b0599fd39d6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_b9d3518abd8ab26c38a9": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_b9d3518abd8ab26c38a9",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b9d3518abd8ab26c38a9_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_b9d3518abd8ab26c38a9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_baccfaef9e63b440c8ed": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_baccfaef9e63b440c8ed",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_baccfaef9e63b440c8ed_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_baccfaef9e63b440c8ed_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 160,
        "dynamic_smem_bytes": 73728,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_c802b99f06c3df59c86e": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_c802b99f06c3df59c86e",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c802b99f06c3df59c86e_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_c802b99f06c3df59c86e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_cbc8bf6e8da65032ebc1": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_cbc8bf6e8da65032ebc1",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_cbc8bf6e8da65032ebc1_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_cbc8bf6e8da65032ebc1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_d903275bc0b4475fa460": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_d903275bc0b4475fa460",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d903275bc0b4475fa460_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_d903275bc0b4475fa460_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_db8865fb1c3a9e8c55f5": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_db8865fb1c3a9e8c55f5",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_db8865fb1c3a9e8c55f5_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_db8865fb1c3a9e8c55f5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_dbf32c2beb4cb28ecc7a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_dbf32c2beb4cb28ecc7a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_dbf32c2beb4cb28ecc7a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_dbf32c2beb4cb28ecc7a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_df18a5a32a207d9b734f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_df18a5a32a207d9b734f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_df18a5a32a207d9b734f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_df18a5a32a207d9b734f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e1eb4069c0b094513220": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e1eb4069c0b094513220",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e1eb4069c0b094513220_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e1eb4069c0b094513220_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e2f7102c868f46f7d864": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e2f7102c868f46f7d864",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e2f7102c868f46f7d864_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e2f7102c868f46f7d864_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_e42f036bd80f10b5d075": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_e42f036bd80f10b5d075",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e42f036bd80f10b5d075_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_e42f036bd80f10b5d075_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ec1a76ad1967947516e3": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ec1a76ad1967947516e3",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ec1a76ad1967947516e3_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ec1a76ad1967947516e3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 139264,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_f8c3b5bd2be4b37e58a0": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_f8c3b5bd2be4b37e58a0",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f8c3b5bd2be4b37e58a0_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_f8c3b5bd2be4b37e58a0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_fa06a91c6b37614c897b": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_fa06a91c6b37614c897b",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fa06a91c6b37614c897b_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fa06a91c6b37614c897b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["tma_buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 96,
        "dynamic_smem_bytes": 150528,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_fea4e5ffd5ec902faebe": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_fea4e5ffd5ec902faebe",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fea4e5ffd5ec902faebe_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_fea4e5ffd5ec902faebe_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": True,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ff2313eae4af393a456f": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ff2313eae4af393a456f",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff2313eae4af393a456f_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff2313eae4af393a456f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "A"],
            ["buffer", "B"],
            ["buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 128,
        "dynamic_smem_bytes": 21504,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
    "cake_blackwell_bf16_fp4_ff8323c63435cdf57225": {
        "kernel": "kernel_cake_blackwell_bf16_fp4_ff8323c63435cdf57225",
        "sources": [
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff8323c63435cdf57225_kernel.cu",
            "blackwell_bf16_fp4/cake_blackwell_bf16_fp4_ff8323c63435cdf57225_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "B_descale"],
            ["buffer", "alpha"],
            ["buffer", "C"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "threads": 512,
        "dynamic_smem_bytes": 107520,
        "use_pdl": False,
        "arches": ["sm_100a", "sm_103a"],
    },
}

ROUTES: dict[str, str] = {
    "cudnn_cp_async_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_6de554584c414a73ad81",
    "cudnn_cp_async_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_acb0e0ab2d22df35fab8",
    "cudnn_cp_async_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_f8c3b5bd2be4b37e58a0",
    "cudnn_cp_async_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_af6010375484274af3b2",
    "cudnn_cp_async_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_e1eb4069c0b094513220",
    "cudnn_cp_async_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_aa6c886aa0ebfd3061b5",
    "cudnn_cp_async_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_b9d3518abd8ab26c38a9",
    "cudnn_cp_async_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_60df3d63bfe47236afd4",
    "cudnn_cp_async_f16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_b4b97457f8892bd24307",
    "cudnn_cp_async_f16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_07b14bea4dcf2bf6e793",
    "cudnn_cp_async_f16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_4e1b24bd6fccdb912992",
    "cudnn_cp_async_f16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_553aee87036d40228f9b",
    "cudnn_cp_async_f16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_643dbc9880d5dd6402bb",
    "cudnn_cp_async_f16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_0230414401339c1d0410",
    "cudnn_cp_async_f16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_1b71766bc3036935b747",
    "cudnn_cp_async_f16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_750fbb6de8160762efdb",
    "cudnn_group_m128_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_e42f036bd80f10b5d075",
    "cudnn_group_m128_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_9dfe31cc589f0763d332",
    "cudnn_group_m128_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_ec1a76ad1967947516e3",
    "cudnn_group_m128_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_df18a5a32a207d9b734f",
    "cudnn_split_k2_partial_f32:alpha0:pdl0": "cake_blackwell_bf16_fp4_44a4424e779b208086ab",
    "cudnn_split_k2_partial_f32:alpha0:pdl1": "cake_blackwell_bf16_fp4_0725119ff8055eba138e",
    "cudnn_split_k2_partial_f32:alpha1:pdl0": "cake_blackwell_bf16_fp4_6a731b5bbe7ea95c1ae9",
    "cudnn_split_k2_partial_f32:alpha1:pdl1": "cake_blackwell_bf16_fp4_d903275bc0b4475fa460",
    "cudnn_split_k2_reduce_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_04b3e10e4154d92341cd",
    "cudnn_split_k2_reduce_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_9cce8d1b5c41dd65980a",
    "cudnn_tma_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_baccfaef9e63b440c8ed",
    "cudnn_tma_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_dbf32c2beb4cb28ecc7a",
    "cudnn_tma_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_fea4e5ffd5ec902faebe",
    "cudnn_tma_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_a5244de0e8109687c28f",
    "cudnn_tma_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_c802b99f06c3df59c86e",
    "cudnn_tma_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_ff8323c63435cdf57225",
    "cudnn_tma_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_0ea74a069244d05ff34d",
    "cudnn_tma_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_3a73df614427399210be",
    "cudnn_tma_f16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_0b395775bbc27234f45e",
    "cudnn_tma_f16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_fa06a91c6b37614c897b",
    "cudnn_tma_f16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_27fa031d0012b04f0742",
    "cudnn_tma_f16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_2ad19642455e0f07a0a6",
    "cudnn_tma_f16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_15a5f50207e3baf94e49",
    "cudnn_tma_f16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_a96b2195bd513ebe1053",
    "cudnn_tma_f16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_ab2f6bf76fd35c015114",
    "cudnn_tma_f16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_3bacdd704c0a3ba6c9e9",
    "cute_bf16:alpha0:pdl0:flat": "cake_blackwell_bf16_fp4_74215ae16c2d85091ea2",
    "cute_bf16:alpha0:pdl0:grid2d": "cake_blackwell_bf16_fp4_db8865fb1c3a9e8c55f5",
    "cute_bf16:alpha0:pdl1:flat": "cake_blackwell_bf16_fp4_a472cfe22f8949bd3c44",
    "cute_bf16:alpha0:pdl1:grid2d": "cake_blackwell_bf16_fp4_2304cf19f4a19879549d",
    "cute_bf16:alpha1:pdl0:flat": "cake_blackwell_bf16_fp4_866140668f306522b996",
    "cute_bf16:alpha1:pdl0:grid2d": "cake_blackwell_bf16_fp4_8d5a0392779f7f83da76",
    "cute_bf16:alpha1:pdl1:flat": "cake_blackwell_bf16_fp4_cbc8bf6e8da65032ebc1",
    "cute_bf16:alpha1:pdl1:grid2d": "cake_blackwell_bf16_fp4_378e42a49496d4e175cb",
    "cute_seed_exact_m17_n3072_k3072_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_5d47a298f721f0fb3b82",
    "cute_seed_exact_m768_n2112_k2048_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_4e961d76c96c0735db42",
    "cute_seed_m16_k1024_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_ff2313eae4af393a456f",
    "cute_seed_m16_k1024_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_eb5a4ecd239e18bc2632",
    "cute_seed_m16_k1024_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_e185cb5ee44d7aff7f58",
    "cute_seed_m16_k1024_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_4e45c544bae61d4e9100",
    "cute_warp_mma_m16_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_57909bca7181725a705f",
    "cute_warp_mma_m16_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_3ae50a5d7f2883b9b9d2",
    "cute_warp_mma_m16_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_f26a9af8eb686dd9da6c",
    "cute_warp_mma_m16_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_b843dc623b0599fd39d6",
    "cute_warp_mma_m16_k16_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_5a0565c42c3db0d80855",
    "cute_warp_mma_m16_k16_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_bbf9b93d37a5c68670e2",
    "cute_warp_mma_m16_k16_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_023d26416fc1b8b440e1",
    "cute_warp_mma_m16_k16_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_46c64cda9ea11ae00bcb",
    "cute_warp_mma_m16_k32_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_1e0a2945528d7b8b4b42",
    "cute_warp_mma_m16_k32_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_14eddcc58f47c2d8435f",
    "cute_warp_mma_m16_k32_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_6773a7bb811b0bd669d5",
    "cute_warp_mma_m16_k32_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_59cc3d9c564129d1be31",
    "cute_warp_mma_m16_k48_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_fb26b846e5d1cf0f421a",
    "cute_warp_mma_m16_k48_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_e2f7102c868f46f7d864",
    "cute_warp_mma_m16_k48_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_0514be13a6625fe20da7",
    "cute_warp_mma_m16_k48_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_0f9e562baf3ca817390c",
    "cute_warp_mma_m32_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_b8233fe48c0865e15d99",
    "cute_warp_mma_m32_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_66fcfef344a575a294b3",
    "cute_warp_mma_m32_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_6ebf29f5fd2bf154a051",
    "cute_warp_mma_m32_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_34dc301724af442a6290",
    "cute_warp_mma_m64_bf16:alpha0:pdl0": "cake_blackwell_bf16_fp4_57ae63487a1f631aeaeb",
    "cute_warp_mma_m64_bf16:alpha0:pdl1": "cake_blackwell_bf16_fp4_c1f6887e0740c60b35cb",
    "cute_warp_mma_m64_bf16:alpha1:pdl0": "cake_blackwell_bf16_fp4_7c905c6ae908ea82eb25",
    "cute_warp_mma_m64_bf16:alpha1:pdl1": "cake_blackwell_bf16_fp4_188226f44f4650e55dc2",
}

# tcgen05 / TMEM programs: one exact-architecture module per target.
ARCH_NVCC_FLAGS = {"sm_100a": sm100a_nvcc_flags, "sm_103a": sm103a_nvcc_flags}
CAPABILITY_ARCH = {(10, 0): "sm_100a", (10, 3): "sm_103a"}


def _source_dirs() -> tuple[Path, Path]:
    checkout = Path(__file__).resolve().parents[2]
    source_root = checkout / "csrc"
    include_root = checkout / "include"
    if not (source_root / "tvm_ffi_utils.h").is_file():
        source_root = jit_env.FLASHINFER_CSRC_DIR
        include_root = jit_env.FLASHINFER_INCLUDE_DIR
    if not (source_root / "tvm_ffi_utils.h").is_file():
        raise FileNotFoundError("FlashInfer binding headers were not found")
    return source_root, include_root


@functools.cache
def target_capabilities() -> frozenset[tuple[int, int]]:
    """Exported capabilities this process builds for (``FLASHINFER_CUDA_ARCH_LIST`` or visible devices)."""

    capabilities = set()
    for major, minor in CompilationContext().TARGET_CUDA_ARCHS:
        capability = _capability(major, minor)
        if capability in CAPABILITY_ARCH:
            capabilities.add(capability)
    return frozenset(capabilities)


def _capability(major: int | str, minor: int | str) -> tuple[int, int]:
    """``CompilationContext`` keeps the nvcc suffix on the minor version (``"3a"``, ``"0f"``); drop it."""

    digits = str(minor).rstrip("abcdefghijklmnopqrstuvwxyz")
    if not str(major).isdigit() or not digits.isdigit():
        raise ValueError(
            f"malformed CUDA architecture entry {major}.{minor} in FLASHINFER_CUDA_ARCH_LIST"
        )
    return int(major), int(digits)


def supported_arch(capability: tuple[int, int]) -> str | None:
    """The exported architecture for a device capability, or ``None`` when it is not a build target."""

    capability = (int(capability[0]), int(capability[1]))
    if capability not in target_capabilities():
        return None
    return CAPABILITY_ARCH[capability]


@functools.cache
def module_spec(name: str, arch: str) -> JitSpec:
    record = MODULES[name]
    if arch not in record["arches"]:
        raise ValueError(f"program {name!r} is not delivered for {arch}")
    source_root, include_root = _source_dirs()
    sources = [source_root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_{arch}",
        sources=sources,
        extra_cuda_cflags=[*ARCH_NVCC_FLAGS[arch], *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[
            source_root,
            *sorted({p.parent for p in sources}),
            include_root,
        ],
        use_fast_math=False,
    )


@functools.cache
def load_module(name: str, arch: str):
    return module_spec(name, arch).build_and_load()


__all__ = [
    "ARCH_NVCC_FLAGS",
    "CAPABILITY_ARCH",
    "MODULES",
    "ROUTES",
    "load_module",
    "module_spec",
    "supported_arch",
    "target_capabilities",
]
