# Copyright (c) 2026 by FlashInfer team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generated runtime catalog for Cake NVFP4 SVDQuant. Do not edit."""

TARGET = "sm103a"

# fmt: off
MODULES = {'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735_binding.cu',
                                                                 'binding_sha256': 'da276b6058c9617a37aba291cfe7698776d693209e165a1018bc6c6d52639594',
                                                                 'closure_sha256': '42cdd51dca5a2cc4cfca2a9fb50e17c0c2ddbf1a3e45b931131b59fb95043235',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735_kernel.cu',
                                                                 'device_sha256': '5ec406a662dd107459caccfc46711455091b02c64ce5cd6e53188862607cc838',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'raster_along_m'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c_binding.cu',
                                                                 'binding_sha256': 'f5ec4ffbf24d079440a592967de98a466c28b3b9f17446bc6a72e4f275401e9e',
                                                                 'closure_sha256': '87cb6590d11c562838acd4875904d75259104323e5116776612bf41a09230942',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c_kernel.cu',
                                                                 'device_sha256': 'ce3dddf16157f36b6c5cc1709590ac48220450f9573bdac1fdefde0eff26e267',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7_binding.cu',
                                                                 'binding_sha256': '862a28f272fead6cb12dbe30e3d4ee3660dc37193136cf06d84a6060a6e0d4a7',
                                                                 'closure_sha256': '702e2e5f661a2a8b6bb2ddaef29d2bcaa9e1f312730d1c9fecf1b65b60deb4b1',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7_kernel.cu',
                                                                 'device_sha256': '4d2abcc141f0405eb8b3a21edea9df089360741be2601ca784039155d31d2ce1',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed_binding.cu',
                                                                 'binding_sha256': '7592092a01c18098dbe681950a7539a9927cfd21543ca904d20266f098a1b001',
                                                                 'closure_sha256': '5da0bb036d0ca2fe6e886b23026813a9a462f36eb5cd66d9b7adb26ae4591897',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed_kernel.cu',
                                                                 'device_sha256': '557861e877f15839522c87301a31bde8ae90a8be2b3ed662dc811fc142aa383f',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['tma_buffer',
                                                                               'D_tail'],
                                                                              ['tma_buffer',
                                                                               'L1_tail'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a_binding.cu',
                                                                 'binding_sha256': '681516a132f298471c2316e0a1d1c5658fed96e31cbd40948a9251592aef3773',
                                                                 'closure_sha256': '4acfbb70d70694321d5aa05dad1e451ec2311304ea54e0aa33b09f89cefb208e',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a_kernel.cu',
                                                                 'device_sha256': '2854228f650fd32b864bec3a95f5f2a2faaccd73c8924726b61450d061535429',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b_binding.cu',
                                                                 'binding_sha256': '670b5f43dbd774fc96a12d1eccd48c3eaf4137f05a838cc9df15210a347e558b',
                                                                 'closure_sha256': '5738296e33f8982cb33b768f95e56f313da892e3095a8401d4f246f249e0d6f9',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b_kernel.cu',
                                                                 'device_sha256': 'dd3c26e17a28b786158ddfac87568f7e21bf211739d9b2e771638a5a36cd4db4',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c:kernel': {'arch': 'sm_103a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c_binding.cu',
                                                                 'binding_sha256': '72322a00c64415fde597d6de2f39e2c9ca78d1daed2716bbc75e8da94ccb13e4',
                                                                 'closure_sha256': '96994d29d661108809fa99ce55e8c69be4a635da7851d957c20775b7125c5a82',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_103a/cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c_kernel.cu',
                                                                 'device_sha256': 'dd0469689de5788107f804d4b0aa183c3373d82b0494ff16a323f3cc1b75f5b3',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c_sm_103a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c',
                                                                 'role': 'kernel'}}

ROUTES = {'autotuned_m129_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'autotuned_replay',
                                                     'rank': 32,
                                                     'tactic': None},
                                            'shape': 'autotuned_m129_n3072_k3072_r32_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_n128_exact_epilogue',
                                                      'tma_workspace_bytes': 896}},
 'autotuned_m129_n3072_k3072_r96_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'autotuned_replay',
                                                     'rank': 96,
                                                     'tactic': None},
                                            'shape': 'autotuned_m129_n3072_k3072_r96_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'autotuned_m6912_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'autotuned_replay',
                                                      'rank': 32,
                                                      'tactic': None},
                                             'shape': 'autotuned_m6912_n3072_k3072_r32_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_n128_exact_epilogue',
                                                       'tma_workspace_bytes': 896}},
 'autotuned_m6912_n3072_k3072_r96_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'autotuned_replay',
                                                      'rank': 96,
                                                      'tactic': None},
                                             'shape': 'autotuned_m6912_n3072_k3072_r96_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'bench_m16384_n12288_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                    'M': 16384,
                                                    'N': 12288,
                                                    'bias': True,
                                                    'execution_profile': 'autotuned_benchmark',
                                                    'rank': 32,
                                                    'tactic': None},
                                           'shape': 'bench_m16384_n12288_k3072_r32_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_n128_exact_epilogue',
                                                     'tma_workspace_bytes': 896}},
 'bench_m16384_n3072_k12288_r32_sm_103a': {'args': {'K': 12288,
                                                    'M': 16384,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'autotuned_benchmark',
                                                    'rank': 32,
                                                    'tactic': None},
                                           'shape': 'bench_m16384_n3072_k12288_r32_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_k12288_r32',
                                                     'tma_workspace_bytes': 768}},
 'bench_m16384_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                   'M': 16384,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m16384_n3072_k3072_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m4096_n12288_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                   'M': 4096,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m4096_n12288_k3072_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m4096_n3072_k12288_r32_sm_103a': {'args': {'K': 12288,
                                                   'M': 4096,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m4096_n3072_k12288_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m4096_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                  'M': 4096,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m4096_n3072_k3072_r32_sm_103a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'bench_m6889_n12288_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                   'M': 6889,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m6889_n12288_k3072_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m6889_n3072_k12288_r32_sm_103a': {'args': {'K': 12288,
                                                   'M': 6889,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m6889_n3072_k12288_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m6889_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                  'M': 6889,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m6889_n3072_k3072_r32_sm_103a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'bench_m9216_n12288_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                   'M': 9216,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m9216_n12288_k3072_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m9216_n3072_k12288_r32_sm_103a': {'args': {'K': 12288,
                                                   'M': 9216,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m9216_n3072_k12288_r32_sm_103a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m9216_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                  'M': 9216,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m9216_n3072_k3072_r32_sm_103a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t0_sm_103a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 64,
                                                    'tactic': 0},
                                           'shape': 'chunk_m129_n3072_k3072_r64_t0_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_rank64_bias_smem',
                                                     'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t19_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 19},
                                            'shape': 'chunk_m129_n3072_k3072_r64_t19_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t1_sm_103a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 64,
                                                    'tactic': 1},
                                           'shape': 'chunk_m129_n3072_k3072_r64_t1_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_rank64_bias_smem',
                                                     'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t25_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 25},
                                            'shape': 'chunk_m129_n3072_k3072_r64_t25_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r96_t0_sm_103a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 96,
                                                    'tactic': 0},
                                           'shape': 'chunk_m129_n3072_k3072_r96_t0_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_rank96_compact_tail',
                                                     'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t19_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 19},
                                            'shape': 'chunk_m129_n3072_k3072_r96_t19_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t1_sm_103a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 96,
                                                    'tactic': 1},
                                           'shape': 'chunk_m129_n3072_k3072_r96_t1_sm_103a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_rank96_compact_tail',
                                                     'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t25_sm_103a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 25},
                                            'shape': 'chunk_m129_n3072_k3072_r96_t25_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_58f6567c70b0a643e02c',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': True,
                                                      'template': 'tactic25_rank96_persistent',
                                                      'tma_workspace_bytes': 0}},
 'chunk_m6912_n3072_k3072_r64_t0_sm_103a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 0},
                                            'shape': 'chunk_m6912_n3072_k3072_r64_t0_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t19_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 64,
                                                      'tactic': 19},
                                             'shape': 'chunk_m6912_n3072_k3072_r64_t19_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_rank64_bias_smem',
                                                       'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t1_sm_103a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 1},
                                            'shape': 'chunk_m6912_n3072_k3072_r64_t1_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t25_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 64,
                                                      'tactic': 25},
                                             'shape': 'chunk_m6912_n3072_k3072_r64_t25_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_3c3f5ad40f2109f9f735',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_rank64_bias_smem',
                                                       'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r96_t0_sm_103a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 0},
                                            'shape': 'chunk_m6912_n3072_k3072_r96_t0_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t19_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 96,
                                                      'tactic': 19},
                                             'shape': 'chunk_m6912_n3072_k3072_r96_t19_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t1_sm_103a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 1},
                                            'shape': 'chunk_m6912_n3072_k3072_r96_t1_sm_103a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t25_sm_103a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 96,
                                                      'tactic': 25},
                                             'shape': 'chunk_m6912_n3072_k3072_r96_t25_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f0bacd9b17fc740f0f6a',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'cuda_graph_m129_n3072_k3072_r128_sm_103a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': True,
                                                       'execution_profile': 'cuda_graph',
                                                       'rank': 128,
                                                       'tactic': None},
                                              'shape': 'cuda_graph_m129_n3072_k3072_r128_sm_103a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic0_n128_exact_epilogue',
                                                        'tma_workspace_bytes': 896}},
 'cuda_graph_m129_n3072_k3072_r32_sm_103a': {'args': {'K': 3072,
                                                      'M': 129,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'cuda_graph',
                                                      'rank': 32,
                                                      'tactic': None},
                                             'shape': 'cuda_graph_m129_n3072_k3072_r32_sm_103a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_n128_exact_epilogue',
                                                       'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r128_bias0_sm_103a': {'args': {'K': 12288,
                                                         'M': 129,
                                                         'N': 3072,
                                                         'bias': False,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m129_n3072_k12288_r128_bias0_sm_103a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r128_bias1_sm_103a': {'args': {'K': 12288,
                                                         'M': 129,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m129_n3072_k12288_r128_bias1_sm_103a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r32_bias0_sm_103a': {'args': {'K': 12288,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': False,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k12288_r32_bias0_sm_103a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_fb1cf657a9d1f48bdd5c',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic18_2sm_m256n128k256',
                                                         'tma_workspace_bytes': 0}},
 'fixed_m129_n3072_k12288_r32_bias1_sm_103a': {'args': {'K': 12288,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k12288_r32_bias1_sm_103a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic25_k12288_r32',
                                                         'tma_workspace_bytes': 768}},
 'fixed_m129_n3072_k3072_r128_bias0_sm_103a': {'args': {'K': 3072,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': False,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 128,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k3072_r128_bias0_sm_103a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k3072_r128_bias1_sm_103a': {'args': {'K': 3072,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 128,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k3072_r128_bias1_sm_103a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k3072_r32_bias0_sm_103a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': False,
                                                       'execution_profile': 'all_tactics',
                                                       'rank': 32,
                                                       'tactic': None},
                                              'shape': 'fixed_m129_n3072_k3072_r32_bias0_sm_103a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_f78640203ac9493fcc2b',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic14_m128n64k128_cluster1x2',
                                                        'tma_workspace_bytes': 0}},
 'fixed_m129_n3072_k3072_r32_bias1_sm_103a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': True,
                                                       'execution_profile': 'all_tactics',
                                                       'rank': 32,
                                                       'tactic': None},
                                              'shape': 'fixed_m129_n3072_k3072_r32_bias1_sm_103a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic0_n128_exact_epilogue',
                                                        'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k12288_r128_bias1_sm_103a': {'args': {'K': 12288,
                                                          'M': 6912,
                                                          'N': 3072,
                                                          'bias': True,
                                                          'execution_profile': 'all_tactics',
                                                          'rank': 128,
                                                          'tactic': None},
                                                 'shape': 'fixed_m6912_n3072_k12288_r128_bias1_sm_103a',
                                                 'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                      'role': 'kernel'},
                                                           'pdl_enabled': False,
                                                           'template': 'tactic0_n128_exact_epilogue',
                                                           'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k12288_r32_bias1_sm_103a': {'args': {'K': 12288,
                                                         'M': 6912,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 32,
                                                         'tactic': None},
                                                'shape': 'fixed_m6912_n3072_k12288_r32_bias1_sm_103a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_8f1364cc5fb82aad53ed',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic25_k12288_r32',
                                                          'tma_workspace_bytes': 768}},
 'fixed_m6912_n3072_k3072_r128_bias1_sm_103a': {'args': {'K': 3072,
                                                         'M': 6912,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m6912_n3072_k3072_r128_bias1_sm_103a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k3072_r32_bias1_sm_103a': {'args': {'K': 3072,
                                                        'M': 6912,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m6912_n3072_k3072_r32_bias1_sm_103a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm103a_79ffc2cf5c67377ecfb7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}}}
# fmt: on
