# Copyright (c) 2026 by FlashInfer team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generated runtime catalog for Cake NVFP4 SVDQuant. Do not edit."""

TARGET = "sm100a"

# fmt: off
MODULES = {'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b_binding.cu',
                                                                 'binding_sha256': 'e4691e1af36affdf49f7b2d6b300f0d3d3a59731312579aca4cb4a6617873094',
                                                                 'closure_sha256': 'a57cd1a1b9c1fce869705e68eb69ee27201b792381db7864cfe78fb35f204b90',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b_kernel.cu',
                                                                 'device_sha256': 'e26cadb88ff0c0594ef185cdab17f0c3da2a241b84d723ff6582621fe25b0350',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'raster_along_m'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0_binding.cu',
                                                                 'binding_sha256': '1aed85c9ab807a6ccb97eea3e4818f7025bbab93c4dd1c9fe2844f3fb15c571a',
                                                                 'closure_sha256': 'da6626cad64ffb011cdd6918d61deab31a5d07ad86f3ab64f0e2e70824840bed',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0_kernel.cu',
                                                                 'device_sha256': 'df5fd626514ce23aadab72b06b1613a521c055763786701ce914f46ac67c6fbd',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['tma_buffer',
                                                                               'D_tail'],
                                                                              ['tma_buffer',
                                                                               'L1_tail'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76_binding.cu',
                                                                 'binding_sha256': 'a8ff8c9a66edd617cc9c2e059666d6dd35da96473cf518cc31f92127271c2e76',
                                                                 'closure_sha256': '445bc459d8aea36b38f95fc4a501cfbdec9350e5999aa6d3c3cfbe3983f03be4',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76_kernel.cu',
                                                                 'device_sha256': 'e7247eb7962765028897b8a0cccc87d7df9b54ba64c17570e73a1f44a06ea99d',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7_binding.cu',
                                                                 'binding_sha256': '920c8922038970e117e31b138c2a2efefaac38c0280a053e9ca598ead50db6d4',
                                                                 'closure_sha256': '98d92b83a348d3a03d5fb7b0d44fe98e792082c6f7638c6de517f2c5829f4ed3',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7_kernel.cu',
                                                                 'device_sha256': 'd90bc4ff02f76721fcc88d94244d3c79500ea3f2b4cad255b1c6174a589f6890',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c_binding.cu',
                                                                 'binding_sha256': 'ad9283e19d1aca90b05002aa8dd800d62fe84dd9bbd0c51e384e7f31bbeea696',
                                                                 'closure_sha256': '88b2643bd30c5ee127620b58037d3f3003c857f4295aada171de699f9290e81e',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c_kernel.cu',
                                                                 'device_sha256': '228c38c8e53413e97f4ea26b09365e46d19b84550df9a293bde8fa8c01e3d61b',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['buffer', 'bias'],
                                                                              ['buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter', 'rank'],
                                                                              ['parameter',
                                                                               'rank_chunks'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['parameter',
                                                                               'has_bias'],
                                                                              ['workspace',
                                                                               'tma_descriptor_workspace'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34_binding.cu',
                                                                 'binding_sha256': '44a7c7f03bf974903b8e320d5a46e761104c17b1f3fe2144c4b69e2e91df7cc4',
                                                                 'closure_sha256': '3b318427bf05064a0a2fb81051582f3d89de323058c4f8c69a7ecffa5169a634',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34_kernel.cu',
                                                                 'device_sha256': 'bdb089577dd0b82252960ecdf4333bd628904b89daf2638e850e232f4aaa2a4f',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                                 'role': 'kernel'},
 'cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de:kernel': {'arch': 'sm_100a',
                                                                 'arg_plan': [['tma_buffer', 'A'],
                                                                              ['tma_buffer', 'B'],
                                                                              ['tma_buffer', 'SFA'],
                                                                              ['tma_buffer', 'SFB'],
                                                                              ['tma_buffer', 'D'],
                                                                              ['tma_buffer', 'L1'],
                                                                              ['buffer', 'alpha'],
                                                                              ['tma_buffer', 'out'],
                                                                              ['parameter', 'M'],
                                                                              ['parameter', 'N'],
                                                                              ['parameter',
                                                                               'K_tiles'],
                                                                              ['parameter',
                                                                               'rank_tiles'],
                                                                              ['parameter',
                                                                               'grid_n'],
                                                                              ['grid', 'grid_x'],
                                                                              ['grid', 'grid_y'],
                                                                              ['grid', 'grid_z']],
                                                                 'binding': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de_binding.cu',
                                                                 'binding_sha256': 'a8e15668d69ef1976a8d2dbca58c0afef3eb4f348ab8ffa0fce46c0ff365da31',
                                                                 'closure_sha256': '581d945c3d1d3875fee9926b430638b64feb9298659a9a79c991613e38209377',
                                                                 'compile_flags': ['--use_fast_math'],
                                                                 'device': 'sm_100a/cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de_kernel.cu',
                                                                 'device_sha256': '229cbac2cc7a6a21381c1fbaa40220f0c32bb48f83554ca9530e76d194e6b332',
                                                                 'ffi_entry': 'run',
                                                                 'module_ident': 'cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de_sm_100a',
                                                                 'name': 'cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de',
                                                                 'role': 'kernel'}}

ROUTES = {'autotuned_m129_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'autotuned_replay',
                                                     'rank': 32,
                                                     'tactic': None},
                                            'shape': 'autotuned_m129_n3072_k3072_r32_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_n128_exact_epilogue',
                                                      'tma_workspace_bytes': 896}},
 'autotuned_m129_n3072_k3072_r96_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'autotuned_replay',
                                                     'rank': 96,
                                                     'tactic': None},
                                            'shape': 'autotuned_m129_n3072_k3072_r96_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'autotuned_m6912_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'autotuned_replay',
                                                      'rank': 32,
                                                      'tactic': None},
                                             'shape': 'autotuned_m6912_n3072_k3072_r32_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_n128_exact_epilogue',
                                                       'tma_workspace_bytes': 896}},
 'autotuned_m6912_n3072_k3072_r96_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'autotuned_replay',
                                                      'rank': 96,
                                                      'tactic': None},
                                             'shape': 'autotuned_m6912_n3072_k3072_r96_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'bench_m16384_n12288_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                    'M': 16384,
                                                    'N': 12288,
                                                    'bias': True,
                                                    'execution_profile': 'autotuned_benchmark',
                                                    'rank': 32,
                                                    'tactic': None},
                                           'shape': 'bench_m16384_n12288_k3072_r32_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_n128_exact_epilogue',
                                                     'tma_workspace_bytes': 896}},
 'bench_m16384_n3072_k12288_r32_sm_100a': {'args': {'K': 12288,
                                                    'M': 16384,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'autotuned_benchmark',
                                                    'rank': 32,
                                                    'tactic': None},
                                           'shape': 'bench_m16384_n3072_k12288_r32_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_k12288_r32',
                                                     'tma_workspace_bytes': 768}},
 'bench_m16384_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                   'M': 16384,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m16384_n3072_k3072_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m4096_n12288_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                   'M': 4096,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m4096_n12288_k3072_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m4096_n3072_k12288_r32_sm_100a': {'args': {'K': 12288,
                                                   'M': 4096,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m4096_n3072_k12288_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m4096_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                  'M': 4096,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m4096_n3072_k3072_r32_sm_100a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'bench_m6889_n12288_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                   'M': 6889,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m6889_n12288_k3072_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m6889_n3072_k12288_r32_sm_100a': {'args': {'K': 12288,
                                                   'M': 6889,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m6889_n3072_k12288_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m6889_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                  'M': 6889,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m6889_n3072_k3072_r32_sm_100a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'bench_m9216_n12288_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                   'M': 9216,
                                                   'N': 12288,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m9216_n12288_k3072_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic0_n128_exact_epilogue',
                                                    'tma_workspace_bytes': 896}},
 'bench_m9216_n3072_k12288_r32_sm_100a': {'args': {'K': 12288,
                                                   'M': 9216,
                                                   'N': 3072,
                                                   'bias': True,
                                                   'execution_profile': 'autotuned_benchmark',
                                                   'rank': 32,
                                                   'tactic': None},
                                          'shape': 'bench_m9216_n3072_k12288_r32_sm_100a',
                                          'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                               'role': 'kernel'},
                                                    'pdl_enabled': False,
                                                    'template': 'tactic25_k12288_r32',
                                                    'tma_workspace_bytes': 768}},
 'bench_m9216_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                  'M': 9216,
                                                  'N': 3072,
                                                  'bias': True,
                                                  'execution_profile': 'autotuned_benchmark',
                                                  'rank': 32,
                                                  'tactic': None},
                                         'shape': 'bench_m9216_n3072_k3072_r32_sm_100a',
                                         'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                              'role': 'kernel'},
                                                   'pdl_enabled': False,
                                                   'template': 'tactic0_n128_exact_epilogue',
                                                   'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t0_sm_100a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 64,
                                                    'tactic': 0},
                                           'shape': 'chunk_m129_n3072_k3072_r64_t0_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_rank64_bias_smem',
                                                     'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t19_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 19},
                                            'shape': 'chunk_m129_n3072_k3072_r64_t19_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t1_sm_100a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 64,
                                                    'tactic': 1},
                                           'shape': 'chunk_m129_n3072_k3072_r64_t1_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic0_rank64_bias_smem',
                                                     'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r64_t25_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 25},
                                            'shape': 'chunk_m129_n3072_k3072_r64_t25_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m129_n3072_k3072_r96_t0_sm_100a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 96,
                                                    'tactic': 0},
                                           'shape': 'chunk_m129_n3072_k3072_r96_t0_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_rank96_compact_tail',
                                                     'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t19_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 19},
                                            'shape': 'chunk_m129_n3072_k3072_r96_t19_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t1_sm_100a': {'args': {'K': 3072,
                                                    'M': 129,
                                                    'N': 3072,
                                                    'bias': True,
                                                    'execution_profile': 'fixed_tactic',
                                                    'rank': 96,
                                                    'tactic': 1},
                                           'shape': 'chunk_m129_n3072_k3072_r96_t1_sm_100a',
                                           'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                'role': 'kernel'},
                                                     'pdl_enabled': False,
                                                     'template': 'tactic25_rank96_compact_tail',
                                                     'tma_workspace_bytes': 1152}},
 'chunk_m129_n3072_k3072_r96_t25_sm_100a': {'args': {'K': 3072,
                                                     'M': 129,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 25},
                                            'shape': 'chunk_m129_n3072_k3072_r96_t25_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_3bf71ff85153580a81d0',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': True,
                                                      'template': 'tactic25_rank96_persistent',
                                                      'tma_workspace_bytes': 0}},
 'chunk_m6912_n3072_k3072_r64_t0_sm_100a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 0},
                                            'shape': 'chunk_m6912_n3072_k3072_r64_t0_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t19_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 64,
                                                      'tactic': 19},
                                             'shape': 'chunk_m6912_n3072_k3072_r64_t19_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_rank64_bias_smem',
                                                       'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t1_sm_100a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 64,
                                                     'tactic': 1},
                                            'shape': 'chunk_m6912_n3072_k3072_r64_t1_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic0_rank64_bias_smem',
                                                      'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r64_t25_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 64,
                                                      'tactic': 25},
                                             'shape': 'chunk_m6912_n3072_k3072_r64_t25_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_39e687bcbf797014c49b',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_rank64_bias_smem',
                                                       'tma_workspace_bytes': 896}},
 'chunk_m6912_n3072_k3072_r96_t0_sm_100a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 0},
                                            'shape': 'chunk_m6912_n3072_k3072_r96_t0_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t19_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 96,
                                                      'tactic': 19},
                                             'shape': 'chunk_m6912_n3072_k3072_r96_t19_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t1_sm_100a': {'args': {'K': 3072,
                                                     'M': 6912,
                                                     'N': 3072,
                                                     'bias': True,
                                                     'execution_profile': 'fixed_tactic',
                                                     'rank': 96,
                                                     'tactic': 1},
                                            'shape': 'chunk_m6912_n3072_k3072_r96_t1_sm_100a',
                                            'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                 'role': 'kernel'},
                                                      'pdl_enabled': False,
                                                      'template': 'tactic25_rank96_compact_tail',
                                                      'tma_workspace_bytes': 1152}},
 'chunk_m6912_n3072_k3072_r96_t25_sm_100a': {'args': {'K': 3072,
                                                      'M': 6912,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'fixed_tactic',
                                                      'rank': 96,
                                                      'tactic': 25},
                                             'shape': 'chunk_m6912_n3072_k3072_r96_t25_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6a0748a3221d25bb5b76',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic25_rank96_compact_tail',
                                                       'tma_workspace_bytes': 1152}},
 'cuda_graph_m129_n3072_k3072_r128_sm_100a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': True,
                                                       'execution_profile': 'cuda_graph',
                                                       'rank': 128,
                                                       'tactic': None},
                                              'shape': 'cuda_graph_m129_n3072_k3072_r128_sm_100a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic0_n128_exact_epilogue',
                                                        'tma_workspace_bytes': 896}},
 'cuda_graph_m129_n3072_k3072_r32_sm_100a': {'args': {'K': 3072,
                                                      'M': 129,
                                                      'N': 3072,
                                                      'bias': True,
                                                      'execution_profile': 'cuda_graph',
                                                      'rank': 32,
                                                      'tactic': None},
                                             'shape': 'cuda_graph_m129_n3072_k3072_r32_sm_100a',
                                             'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                  'role': 'kernel'},
                                                       'pdl_enabled': False,
                                                       'template': 'tactic0_n128_exact_epilogue',
                                                       'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r128_bias0_sm_100a': {'args': {'K': 12288,
                                                         'M': 129,
                                                         'N': 3072,
                                                         'bias': False,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m129_n3072_k12288_r128_bias0_sm_100a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r128_bias1_sm_100a': {'args': {'K': 12288,
                                                         'M': 129,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m129_n3072_k12288_r128_bias1_sm_100a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k12288_r32_bias0_sm_100a': {'args': {'K': 12288,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': False,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k12288_r32_bias0_sm_100a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_83ad737b1da2b792d17c',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic18_2sm_m256n128k256',
                                                         'tma_workspace_bytes': 0}},
 'fixed_m129_n3072_k12288_r32_bias1_sm_100a': {'args': {'K': 12288,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k12288_r32_bias1_sm_100a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic25_k12288_r32',
                                                         'tma_workspace_bytes': 768}},
 'fixed_m129_n3072_k3072_r128_bias0_sm_100a': {'args': {'K': 3072,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': False,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 128,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k3072_r128_bias0_sm_100a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k3072_r128_bias1_sm_100a': {'args': {'K': 3072,
                                                        'M': 129,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 128,
                                                        'tactic': None},
                                               'shape': 'fixed_m129_n3072_k3072_r128_bias1_sm_100a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}},
 'fixed_m129_n3072_k3072_r32_bias0_sm_100a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': False,
                                                       'execution_profile': 'all_tactics',
                                                       'rank': 32,
                                                       'tactic': None},
                                              'shape': 'fixed_m129_n3072_k3072_r32_bias0_sm_100a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_9131a81cef113dbfc7de',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic14_m128n64k128_cluster1x2',
                                                        'tma_workspace_bytes': 0}},
 'fixed_m129_n3072_k3072_r32_bias1_sm_100a': {'args': {'K': 3072,
                                                       'M': 129,
                                                       'N': 3072,
                                                       'bias': True,
                                                       'execution_profile': 'all_tactics',
                                                       'rank': 32,
                                                       'tactic': None},
                                              'shape': 'fixed_m129_n3072_k3072_r32_bias1_sm_100a',
                                              'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                   'role': 'kernel'},
                                                        'pdl_enabled': False,
                                                        'template': 'tactic0_n128_exact_epilogue',
                                                        'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k12288_r128_bias1_sm_100a': {'args': {'K': 12288,
                                                          'M': 6912,
                                                          'N': 3072,
                                                          'bias': True,
                                                          'execution_profile': 'all_tactics',
                                                          'rank': 128,
                                                          'tactic': None},
                                                 'shape': 'fixed_m6912_n3072_k12288_r128_bias1_sm_100a',
                                                 'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                      'role': 'kernel'},
                                                           'pdl_enabled': False,
                                                           'template': 'tactic0_n128_exact_epilogue',
                                                           'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k12288_r32_bias1_sm_100a': {'args': {'K': 12288,
                                                         'M': 6912,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 32,
                                                         'tactic': None},
                                                'shape': 'fixed_m6912_n3072_k12288_r32_bias1_sm_100a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_8498b5f39012170f7e34',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic25_k12288_r32',
                                                          'tma_workspace_bytes': 768}},
 'fixed_m6912_n3072_k3072_r128_bias1_sm_100a': {'args': {'K': 3072,
                                                         'M': 6912,
                                                         'N': 3072,
                                                         'bias': True,
                                                         'execution_profile': 'all_tactics',
                                                         'rank': 128,
                                                         'tactic': None},
                                                'shape': 'fixed_m6912_n3072_k3072_r128_bias1_sm_100a',
                                                'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                     'role': 'kernel'},
                                                          'pdl_enabled': False,
                                                          'template': 'tactic0_n128_exact_epilogue',
                                                          'tma_workspace_bytes': 896}},
 'fixed_m6912_n3072_k3072_r32_bias1_sm_100a': {'args': {'K': 3072,
                                                        'M': 6912,
                                                        'N': 3072,
                                                        'bias': True,
                                                        'execution_profile': 'all_tactics',
                                                        'rank': 32,
                                                        'tactic': None},
                                               'shape': 'fixed_m6912_n3072_k3072_r32_bias1_sm_100a',
                                               'stage': {'module': {'name': 'cake_nvfp4_svdquant_gemm_sm100a_6f2f971f07cbfb1089f7',
                                                                    'role': 'kernel'},
                                                         'pdl_enabled': False,
                                                         'template': 'tactic0_n128_exact_epilogue',
                                                         'tma_workspace_bytes': 896}}}
# fmt: on
