"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

JIT registration of the Cake-generated Hopper (compute capability 9.0) MSA
programs.  One device / binding source pair per physical schedule, compiled
with FlashInfer's exact ``sm_90a`` flag set; ``ROUTES`` maps a logical route
(``<route key>:<stage>``) to the program that serves it and ``MODULES`` carries
each program's sources, neutral compile flags, FFI entry, argument order and
launch geometry.
"""

import functools
from pathlib import Path
from typing import Any

from . import env as jit_env
from .core import JitSpec, gen_jit_spec, sm90a_nvcc_flags

HopperMSAVariant = str
_ARCH = "sm_90a"
_TARGET = "sm90a"

MODULES: dict[str, dict[str, Any]] = {
    "cake_hopper_msa_003b5465e77b790a9114": {
        "sources": [
            "hopper_msa/cake_hopper_msa_003b5465e77b790a9114_kernel.cu",
            "hopper_msa/cake_hopper_msa_003b5465e77b790a9114_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "7be5fec020adf833bc13bbce6d5cecf450c315367849c7fdb957c884bcc38afd",
    },
    "cake_hopper_msa_0462a19ac588e6c8bd63": {
        "sources": [
            "hopper_msa/cake_hopper_msa_0462a19ac588e6c8bd63_kernel.cu",
            "hopper_msa/cake_hopper_msa_0462a19ac588e6c8bd63_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "ee708612ff725e810e84f309945b8b570d08a82fae5581ee1c161c4384633cb9",
    },
    "cake_hopper_msa_065a485700df577ebe10": {
        "sources": [
            "hopper_msa/cake_hopper_msa_065a485700df577ebe10_kernel.cu",
            "hopper_msa/cake_hopper_msa_065a485700df577ebe10_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "51e5363ffa513ef97488e0b1b2a574921f9fc9c7d7aa83a36e95d682a967aa48",
    },
    "cake_hopper_msa_0952589e2b34ea760d55": {
        "sources": [
            "hopper_msa/cake_hopper_msa_0952589e2b34ea760d55_kernel.cu",
            "hopper_msa/cake_hopper_msa_0952589e2b34ea760d55_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "56d30186e9be44d16ac7e5215fc970de8335685156520b67f5e987ab11dac150",
    },
    "cake_hopper_msa_162af71cdd4537102d9b": {
        "sources": [
            "hopper_msa/cake_hopper_msa_162af71cdd4537102d9b_kernel.cu",
            "hopper_msa/cake_hopper_msa_162af71cdd4537102d9b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "7e6091be4361a9eaa9b3c8931d29faeb7c6254e1d20e2757b84d532e76f198e4",
    },
    "cake_hopper_msa_1e9797726a19fa488072": {
        "sources": [
            "hopper_msa/cake_hopper_msa_1e9797726a19fa488072_kernel.cu",
            "hopper_msa/cake_hopper_msa_1e9797726a19fa488072_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 120576,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "44774ad1f6552a5cfd6806051e335041ca8818f9925c1c546d308abab1d02d8d",
    },
    "cake_hopper_msa_1fd27e38633d6ea82673": {
        "sources": [
            "hopper_msa/cake_hopper_msa_1fd27e38633d6ea82673_kernel.cu",
            "hopper_msa/cake_hopper_msa_1fd27e38633d6ea82673_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "74cccda1e0c4791c0e98534e78d04a50cff7cd43196cb5915e3b35714aa08a0a",
    },
    "cake_hopper_msa_21873273fae8a3c615a2": {
        "sources": [
            "hopper_msa/cake_hopper_msa_21873273fae8a3c615a2_kernel.cu",
            "hopper_msa/cake_hopper_msa_21873273fae8a3c615a2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "721e730c61eb77a79d8b1d4951f06735ec44dfe4a126a246ac9b24c25f1a718c",
    },
    "cake_hopper_msa_22ebc0f51af3d75f13dd": {
        "sources": [
            "hopper_msa/cake_hopper_msa_22ebc0f51af3d75f13dd_kernel.cu",
            "hopper_msa/cake_hopper_msa_22ebc0f51af3d75f13dd_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "77079b71ca7a4de2352f0adbd9e5ad95dab678c81a3a4ac2a302ce10e82b74fc",
    },
    "cake_hopper_msa_26344b48428342e063aa": {
        "sources": [
            "hopper_msa/cake_hopper_msa_26344b48428342e063aa_kernel.cu",
            "hopper_msa/cake_hopper_msa_26344b48428342e063aa_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "118e134acc02c7a0351445e57f6b86a990b94184c6bc141290aba29a2678201b",
    },
    "cake_hopper_msa_26ff947d109d665e2c4d": {
        "sources": [
            "hopper_msa/cake_hopper_msa_26ff947d109d665e2c4d_kernel.cu",
            "hopper_msa/cake_hopper_msa_26ff947d109d665e2c4d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 38144,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "91f00291a7abf7e62fe4407b9797eebb369f8f913d0b3f792ff00d9e90d7d212",
    },
    "cake_hopper_msa_2bd172db346f7133b82c": {
        "sources": [
            "hopper_msa/cake_hopper_msa_2bd172db346f7133b82c_kernel.cu",
            "hopper_msa/cake_hopper_msa_2bd172db346f7133b82c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 120576,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "43edfa950d9c4dfa5f5577dc2ebb8bde63e42ab63bb3c1ec33afd64b4d4477f2",
    },
    "cake_hopper_msa_2e1c5ebe73754bda4155": {
        "sources": [
            "hopper_msa/cake_hopper_msa_2e1c5ebe73754bda4155_kernel.cu",
            "hopper_msa/cake_hopper_msa_2e1c5ebe73754bda4155_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "5d5d2c4789e7d66e271212e683d168f78288c6e3f30c1650332128a41820e128",
    },
    "cake_hopper_msa_2fa3726f462d8c70ed4e": {
        "sources": [
            "hopper_msa/cake_hopper_msa_2fa3726f462d8c70ed4e_kernel.cu",
            "hopper_msa/cake_hopper_msa_2fa3726f462d8c70ed4e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 120576,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "230cb5669e75ddd3cc20ca7f9c91dd0cf4f5a442ecf33c9b7e672f0a59e1b403",
    },
    "cake_hopper_msa_34a2ca63ee1bd9b197e3": {
        "sources": [
            "hopper_msa/cake_hopper_msa_34a2ca63ee1bd9b197e3_kernel.cu",
            "hopper_msa/cake_hopper_msa_34a2ca63ee1bd9b197e3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "ba7312aa868b3c13db1da2209932bae435069a907c4dbcfe47d8298660e1dd0f",
    },
    "cake_hopper_msa_35bc38a12cf2bbf0e86f": {
        "sources": [
            "hopper_msa/cake_hopper_msa_35bc38a12cf2bbf0e86f_kernel.cu",
            "hopper_msa/cake_hopper_msa_35bc38a12cf2bbf0e86f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "e2cc9e90379394c7afa9f4bccf69f4c50da45aef0c19cb3c36f5c4cd9cd9a91a",
    },
    "cake_hopper_msa_43c3ad08016f1c2c561e": {
        "sources": [
            "hopper_msa/cake_hopper_msa_43c3ad08016f1c2c561e_kernel.cu",
            "hopper_msa/cake_hopper_msa_43c3ad08016f1c2c561e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "72f4c4784735d26dbf97bc0da160533efa256420bad14ab73242ac2de3ec49e9",
    },
    "cake_hopper_msa_4a357f5ea76dc72ceb44": {
        "sources": [
            "hopper_msa/cake_hopper_msa_4a357f5ea76dc72ceb44_kernel.cu",
            "hopper_msa/cake_hopper_msa_4a357f5ea76dc72ceb44_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "d2a6845b3dbd2e23f6840dc9015227227cd9d7e5b56529d55c6926f39d300ff9",
    },
    "cake_hopper_msa_542942520ec68077d62e": {
        "sources": [
            "hopper_msa/cake_hopper_msa_542942520ec68077d62e_kernel.cu",
            "hopper_msa/cake_hopper_msa_542942520ec68077d62e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "5ccdf3a16d2c039a77d062e054b5c485557ad48da31c3a248b8e057026be7dec",
    },
    "cake_hopper_msa_5deed3067b4b08970f90": {
        "sources": [
            "hopper_msa/cake_hopper_msa_5deed3067b4b08970f90_kernel.cu",
            "hopper_msa/cake_hopper_msa_5deed3067b4b08970f90_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "5aebcd91377a4246c87295cea13fa31c970f9f95c9839ced833a97ce58e8accf",
    },
    "cake_hopper_msa_5eb31e4eaf76b78fed57": {
        "sources": [
            "hopper_msa/cake_hopper_msa_5eb31e4eaf76b78fed57_kernel.cu",
            "hopper_msa/cake_hopper_msa_5eb31e4eaf76b78fed57_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "4241637df843036b74cc0d1662c7b74b7b5181560439feef56a22c97e8d2c0be",
    },
    "cake_hopper_msa_6f8e57b5fc1555236457": {
        "sources": [
            "hopper_msa/cake_hopper_msa_6f8e57b5fc1555236457_kernel.cu",
            "hopper_msa/cake_hopper_msa_6f8e57b5fc1555236457_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "d5fe8eec07130deb090ad4dbf80a96aac14a7cea300797ed9e65e2e489fcae72",
    },
    "cake_hopper_msa_70a72c8695dfcc520faf": {
        "sources": [
            "hopper_msa/cake_hopper_msa_70a72c8695dfcc520faf_kernel.cu",
            "hopper_msa/cake_hopper_msa_70a72c8695dfcc520faf_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "3a518c96b9d3a4c08e0468c0f6e84195a9aee81938e39940e1d3206452512348",
    },
    "cake_hopper_msa_7343e5b584e26ae2f7ac": {
        "sources": [
            "hopper_msa/cake_hopper_msa_7343e5b584e26ae2f7ac_kernel.cu",
            "hopper_msa/cake_hopper_msa_7343e5b584e26ae2f7ac_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "de38b148677bd768a2f2957a13107a8fa752dfb5fde2c97a3d4db32c1ab64c65",
    },
    "cake_hopper_msa_81f144a9f72d9671882d": {
        "sources": [
            "hopper_msa/cake_hopper_msa_81f144a9f72d9671882d_kernel.cu",
            "hopper_msa/cake_hopper_msa_81f144a9f72d9671882d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "23150dc33a77f90788c060e3e6cb8c6cfc7a5bfb7c53eb60ce2cea8c302d60fc",
    },
    "cake_hopper_msa_8877938a4daf6b5ee23f": {
        "sources": [
            "hopper_msa/cake_hopper_msa_8877938a4daf6b5ee23f_kernel.cu",
            "hopper_msa/cake_hopper_msa_8877938a4daf6b5ee23f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "41da0e0db4e37c3cce43bfc087764717857895f5ab44126cfac8d392acedffe7",
    },
    "cake_hopper_msa_8976e9c16261809fa7c4": {
        "sources": [
            "hopper_msa/cake_hopper_msa_8976e9c16261809fa7c4_kernel.cu",
            "hopper_msa/cake_hopper_msa_8976e9c16261809fa7c4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "e0a7584ce037fa30abfa4470ece279c4fb8cb23d147ec979dc5e52783f140e6d",
    },
    "cake_hopper_msa_9d46dd3b31f3a832a397": {
        "sources": [
            "hopper_msa/cake_hopper_msa_9d46dd3b31f3a832a397_kernel.cu",
            "hopper_msa/cake_hopper_msa_9d46dd3b31f3a832a397_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "c1047f8e8904e755fb9f33197bf8de8cb7631bd88beb4c5167e6d77034ccf069",
    },
    "cake_hopper_msa_9ff4175787ceb89dce8e": {
        "sources": [
            "hopper_msa/cake_hopper_msa_9ff4175787ceb89dce8e_kernel.cu",
            "hopper_msa/cake_hopper_msa_9ff4175787ceb89dce8e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "4fb80c0089b2b9839aeeb15208e0543d98c4fb796941df36773eb73583f72ec8",
    },
    "cake_hopper_msa_ab4a6608645a52682c56": {
        "sources": [
            "hopper_msa/cake_hopper_msa_ab4a6608645a52682c56_kernel.cu",
            "hopper_msa/cake_hopper_msa_ab4a6608645a52682c56_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "b41197f39211c43ec60268a3553497d174c07034ac72a7e8870d3502cb35fd4a",
    },
    "cake_hopper_msa_bfa992f26b7bc653a8ce": {
        "sources": [
            "hopper_msa/cake_hopper_msa_bfa992f26b7bc653a8ce_kernel.cu",
            "hopper_msa/cake_hopper_msa_bfa992f26b7bc653a8ce_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "d4b06d4a38b9add3ea6a8bf7f6a4c27b9edb8a75b1008e0795d3473f43e090d5",
    },
    "cake_hopper_msa_cd6d09a015115a110166": {
        "sources": [
            "hopper_msa/cake_hopper_msa_cd6d09a015115a110166_kernel.cu",
            "hopper_msa/cake_hopper_msa_cd6d09a015115a110166_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 87808,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "c1d72afbd52df328aba475e026f0fc497c709b23a276837d2be58fbf2b3a5585",
    },
    "cake_hopper_msa_d3fe04aefb6ffe2cdc14": {
        "sources": [
            "hopper_msa/cake_hopper_msa_d3fe04aefb6ffe2cdc14_kernel.cu",
            "hopper_msa/cake_hopper_msa_d3fe04aefb6ffe2cdc14_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "9ff1d122ae891fa18e9eb7ad6a7e138479ad5dcc8039e41fea6aca5a929d0f9c",
    },
    "cake_hopper_msa_d5130641114f60c91b14": {
        "sources": [
            "hopper_msa/cake_hopper_msa_d5130641114f60c91b14_kernel.cu",
            "hopper_msa/cake_hopper_msa_d5130641114f60c91b14_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "83de111bec9210c05507e881435601353e7a4e6fc137dc13ecd46558f1287859",
    },
    "cake_hopper_msa_d63df15e4090199b514c": {
        "sources": [
            "hopper_msa/cake_hopper_msa_d63df15e4090199b514c_kernel.cu",
            "hopper_msa/cake_hopper_msa_d63df15e4090199b514c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 120576,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "c16dea225fa807898fa50c71492ed298d9aa5da0957f38ff1b2a052dd4f0aa6a",
    },
    "cake_hopper_msa_ddfc82015c1436f34552": {
        "sources": [
            "hopper_msa/cake_hopper_msa_ddfc82015c1436f34552_kernel.cu",
            "hopper_msa/cake_hopper_msa_ddfc82015c1436f34552_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 18560,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "4bbb43c4607bff60cbf3ff9debfa9187993612aff61755a03adf6aa377173777",
    },
    "cake_hopper_msa_df30c37becd6d9edd3e0": {
        "sources": [
            "hopper_msa/cake_hopper_msa_df30c37becd6d9edd3e0_kernel.cu",
            "hopper_msa/cake_hopper_msa_df30c37becd6d9edd3e0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "351f4d9b57815b7260608a38b2764c44e555204fa5535c7b709a98084d274c2c",
    },
    "cake_hopper_msa_f0894a48315c8a3e9d8c": {
        "sources": [
            "hopper_msa/cake_hopper_msa_f0894a48315c8a3e9d8c_kernel.cu",
            "hopper_msa/cake_hopper_msa_f0894a48315c8a3e9d8c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 19712,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "43a1f3c5be3f6d64a1ddb9c20d3c3f3f47226326beaf4851d9fa158b71a82f1a",
    },
    "cake_hopper_msa_f4b5b279e07cb845206c": {
        "sources": [
            "hopper_msa/cake_hopper_msa_f4b5b279e07cb845206c_kernel.cu",
            "hopper_msa/cake_hopper_msa_f4b5b279e07cb845206c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "Q"],
            ["tma_buffer", "K"],
            ["buffer", "out"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "q_offset"],
            ["parameter", "has_qoff"],
            ["parameter", "pt_stride"],
            ["parameter", "max_k_tiles"],
            ["parameter", "total_q"],
            ["parameter", "batch_fast"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 35968,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "1ab0cdfd456fd607d76b3973d1f22dc749df0ce1399c475fa7dabf2668a8a09e",
    },
    "cake_hopper_msa_fb72a8bf9b9aff82b63f": {
        "sources": [
            "hopper_msa/cake_hopper_msa_fb72a8bf9b9aff82b63f_kernel.cu",
            "hopper_msa/cake_hopper_msa_fb72a8bf9b9aff82b63f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "Q32"],
            ["tma_buffer", "K"],
            ["tma_buffer", "V"],
            ["buffer", "O"],
            ["buffer", "q2k_indices"],
            ["buffer", "page_table"],
            ["buffer", "seqused_k"],
            ["buffer", "part_o"],
            ["buffer", "part_ml"],
            ["buffer", "counters"],
            ["buffer", "done"],
            ["parameter", "total_q"],
            ["parameter", "seqlen_q"],
            ["parameter", "num_q_heads"],
            ["parameter", "num_kv_heads"],
            ["parameter", "max_pages"],
            ["parameter", "num_chunks"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "zero_u32"],
            ["buffer", "trace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {
            "block": [128, 1, 1],
            "dynamic_smem_bytes": 81408,
            "cluster": [1, 1, 1],
            "cooperative": False,
            "use_pdl": False,
            "persistent_ctas_per_sm": 1,
            "max_persistent_clusters": None,
            "cluster_scheduling_policy": "spread",
        },
        "arches": ["sm_90a"],
        "closure_sha256": "01ea7dd44e91ad6f68ad07bbc3080a2e6181f28a333e04228db415e6b6e47475",
    },
}

ROUTES: dict[str, str] = {
    "decode_v5:nc16:s1:st2:evict_first:main": "cake_hopper_msa_35bc38a12cf2bbf0e86f",
    "decode_v5:nc16:s1:st2:none:main": "cake_hopper_msa_8877938a4daf6b5ee23f",
    "decode_v5:nc16:s1:st3:evict_first:main": "cake_hopper_msa_d63df15e4090199b514c",
    "decode_v5:nc16:s1:st3:none:main": "cake_hopper_msa_2fa3726f462d8c70ed4e",
    "decode_v5:nc16:s2:st2:evict_first:main": "cake_hopper_msa_43c3ad08016f1c2c561e",
    "decode_v5:nc16:s2:st2:none:main": "cake_hopper_msa_70a72c8695dfcc520faf",
    "decode_v5:nc16:s2:st3:evict_first:main": "cake_hopper_msa_2bd172db346f7133b82c",
    "decode_v5:nc16:s2:st3:none:main": "cake_hopper_msa_1e9797726a19fa488072",
    "decode_v5:nc16:s4:st2:evict_first:main": "cake_hopper_msa_2e1c5ebe73754bda4155",
    "decode_v5:nc16:s4:st2:none:main": "cake_hopper_msa_6f8e57b5fc1555236457",
    "decode_v5:nc16:s8:st2:evict_first:main": "cake_hopper_msa_003b5465e77b790a9114",
    "decode_v5:nc16:s8:st2:none:main": "cake_hopper_msa_cd6d09a015115a110166",
    "decode_v5:nc8:s16:st2:evict_first:main": "cake_hopper_msa_7343e5b584e26ae2f7ac",
    "decode_v5:nc8:s16:st2:none:main": "cake_hopper_msa_542942520ec68077d62e",
    "decode_v5:nc8:s1:st2:evict_first:main": "cake_hopper_msa_ab4a6608645a52682c56",
    "decode_v5:nc8:s1:st2:none:main": "cake_hopper_msa_1fd27e38633d6ea82673",
    "decode_v5:nc8:s2:st2:evict_first:main": "cake_hopper_msa_21873273fae8a3c615a2",
    "decode_v5:nc8:s2:st2:none:main": "cake_hopper_msa_9ff4175787ceb89dce8e",
    "decode_v5:nc8:s4:st2:evict_first:main": "cake_hopper_msa_81f144a9f72d9671882d",
    "decode_v5:nc8:s4:st2:none:main": "cake_hopper_msa_162af71cdd4537102d9b",
    "decode_v5:nc8:s8:st2:evict_first:main": "cake_hopper_msa_d5130641114f60c91b14",
    "decode_v5:nc8:s8:st2:none:main": "cake_hopper_msa_fb72a8bf9b9aff82b63f",
    "proxy_decode:bf16:hq1:sq1:main": "cake_hopper_msa_f4b5b279e07cb845206c",
    "proxy_decode:bf16:hq1:sq2:main": "cake_hopper_msa_065a485700df577ebe10",
    "proxy_decode:bf16:hq1:sq4:main": "cake_hopper_msa_d3fe04aefb6ffe2cdc14",
    "proxy_decode:bf16:hq2:sq1:main": "cake_hopper_msa_df30c37becd6d9edd3e0",
    "proxy_decode:bf16:hq2:sq2:main": "cake_hopper_msa_34a2ca63ee1bd9b197e3",
    "proxy_decode:bf16:hq2:sq4:main": "cake_hopper_msa_26344b48428342e063aa",
    "proxy_decode:bf16:hq4:sq1:main": "cake_hopper_msa_5deed3067b4b08970f90",
    "proxy_decode:bf16:hq4:sq2:main": "cake_hopper_msa_0462a19ac588e6c8bd63",
    "proxy_decode:bf16:hq4:sq4:main": "cake_hopper_msa_26ff947d109d665e2c4d",
    "proxy_decode:fp8:hq1:sq1:main": "cake_hopper_msa_4a357f5ea76dc72ceb44",
    "proxy_decode:fp8:hq1:sq2:main": "cake_hopper_msa_ddfc82015c1436f34552",
    "proxy_decode:fp8:hq1:sq4:main": "cake_hopper_msa_22ebc0f51af3d75f13dd",
    "proxy_decode:fp8:hq2:sq1:main": "cake_hopper_msa_bfa992f26b7bc653a8ce",
    "proxy_decode:fp8:hq2:sq2:main": "cake_hopper_msa_9d46dd3b31f3a832a397",
    "proxy_decode:fp8:hq2:sq4:main": "cake_hopper_msa_0952589e2b34ea760d55",
    "proxy_decode:fp8:hq4:sq1:main": "cake_hopper_msa_8976e9c16261809fa7c4",
    "proxy_decode:fp8:hq4:sq2:main": "cake_hopper_msa_5eb31e4eaf76b78fed57",
    "proxy_decode:fp8:hq4:sq4:main": "cake_hopper_msa_f0894a48315c8a3e9d8c",
}

HOPPER_MSA_VARIANTS: tuple[HopperMSAVariant, ...] = tuple(MODULES)


def _csrc_dir() -> Path:
    for root in (
        jit_env.FLASHINFER_CSRC_DIR,
        Path(__file__).resolve().parents[2] / "csrc",
    ):
        if (root / "hopper_msa").exists():
            return root
    raise FileNotFoundError(
        "Hopper MSA CUDA sources were not found under csrc/hopper_msa"
    )


def _include_dir() -> Path:
    if jit_env.FLASHINFER_INCLUDE_DIR.exists():
        return jit_env.FLASHINFER_INCLUDE_DIR
    return Path(__file__).resolve().parents[2] / "include"


def route_program(key: str) -> str:
    """Program name of one logical route (``<route key>:<stage>``)."""
    try:
        return ROUTES[key]
    except KeyError:
        raise KeyError(f"no Hopper MSA program for route {key!r}") from None


def get_hopper_msa_uri(name: HopperMSAVariant) -> str:
    """JIT / AOT key of one program."""
    record = MODULES.get(name)
    if record is None or _ARCH not in record["arches"]:
        raise ValueError(f"unsupported Hopper MSA program: {name}")
    return f"hopper_msa_{name}_{_TARGET}"


@functools.cache
def gen_hopper_msa_module(name: HopperMSAVariant) -> JitSpec:
    uri = get_hopper_msa_uri(name)
    record = MODULES[name]
    csrc = _csrc_dir()
    return gen_jit_spec(
        name=uri,
        sources=[csrc / path for path in record["sources"]],
        extra_cuda_cflags=[*sm90a_nvcc_flags, *record["compile_flags"]],
        extra_include_paths=[csrc / "hopper_msa", csrc, _include_dir()],
    )


@functools.cache
def load_hopper_msa_module(name: HopperMSAVariant):
    return gen_hopper_msa_module(name).build_and_load()


def get_hopper_msa_module(name: HopperMSAVariant):
    """The loaded module of one program."""
    return load_hopper_msa_module(name)


__all__ = [
    "HOPPER_MSA_VARIANTS",
    "MODULES",
    "ROUTES",
    "HopperMSAVariant",
    "gen_hopper_msa_module",
    "get_hopper_msa_module",
    "get_hopper_msa_uri",
    "load_hopper_msa_module",
    "route_program",
]
