"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Cake backend: fused DSA indexer scoring + deterministic exact top-k selection
for training on SM100 / SM103 / SM107 (flashinfer-ai/flashinfer#5676; GLM-5.2
geometry: 32 indexer heads, head dimension 128, top-k 2048).

Contract (the issue text is authoritative)
------------------------------------------
* ``q [T, 32, 128]`` BF16 indexer queries after RoPE (contiguous); ``k [Tkv,
  128]`` BF16 packed keys after normalization and RoPE -- a row-strided view
  (the trainer's ``[:, :128]`` view of a packed ``[Tkv, 704]`` tensor) is
  accepted without a copy; ``w [T, 32]`` FP32 signed head weights already
  scaled by ``32 ** -0.5``; ``cu_seqlens_q`` / ``cu_seqlens_k [S + 1]`` int32
  independent query / key segment boundaries on the device; optional
  ``q_causal_offsets [S]`` int64 on the device; ``top_k`` in ``[1, 4096]``
  (default 2048); ``softmax_scale > 0`` (default ``128 ** -0.5``); ``ratio
  >= 1``; ``max_seqlen_q`` is an accepted host mirror that no launch decision
  reads; ``max_seqlen_k`` (the caller's bound on every key segment, optional)
  sizes the rank finalize's bitmap pool and so selects its program variant
  (``rank_seg_window``) -- never a result; a value above ``Tkv`` or below
  ``ceil(Tkv / S)`` is rejected.
* Outputs ``indices [T, top_k]`` int32 segment-local key ids and ``scores [T,
  top_k]`` FP32, both in ascending id order with the tail padded by ``-1`` /
  ``-inf``; an entirely empty row holds only padding.
* Score ``s[t, j] = sum_h w[t, h] * relu(softmax_scale * sum_d q[t, h, d] *
  k[j, d])`` with FP32 products, accumulation and score arithmetic (no BF16
  intermediate rounding).  The FP32 reduction scheme of the generated program
  is documented in the package README and is fixed: the result does not depend
  on the internal query / key partition.
* Visibility: key ``j`` is visible to the query at segment-local position ``u``
  iff ``0 <= j < Lk`` and ``j < floor((offset + u + 1) / ratio)``; ``offset`` is
  ``q_causal_offsets[s]`` when supplied, else ``Lk - Lq`` for ``ratio == 1`` and
  ``0`` otherwise.  Keys of other segments or outside the visible prefix are
  never selected; negative offsets, empty segments and rows without visible
  keys are defined (all padding).
* Selection: the exact global top ``min(top_k, visible)`` keys per row, ranked
  by score descending then key id descending (``+0.0 == -0.0`` for ranking);
  the returned score bits are the computed FP32 bits.
* Repeatable: identical inputs give identical ids and score bits; the program
  the host dispatches (unit geometry, key-range split, CTA pair, unroll, unit
  order, sampled threshold; the CUB block radix sort or the prefix-popcount
  rank scatter as the finalize) and the partition knobs (``grid_ctas``,
  ``candidate_multiplier``, ``check_period``, the sampled-threshold knobs, the
  finalize program) never change a result.
* Memory: no ``[T, Tkv]`` score matrix.  The workspace is
  :func:`dsa_indexer_workspace_size` bytes for the call's geometry -- the
  persistent candidate buffers ``grid x queries_per_unit x
  candidate_capacity(top_k) x entry_bytes`` plus, when the dispatch splits the
  key ranges, the staging ``T x n_split x top_k x entry_bytes`` -- separate
  from the inputs and the two outputs; no host synchronization inside the
  operator.
* Non-finite inputs (NaN / inf / overflow) are outside the normal domain: the
  operator returns with the output structure intact and no loop bound depends
  on a score value, so the kernels cannot hang.

Every allocation happens in :func:`prepare_dsa_indexer_topk`; the returned
runner launches with no CUDA allocation and no host synchronization, so a
runner (or a CUDA graph capturing it) replays for new values written into the
bound tensors.  The host decides the program from host-known integers only
(:mod:`cake_policy`, the registry's ``POLICY`` record of the architecture) and
fails closed when the decided program is not registered for the device's
architecture.  Kernels are reached through the argument plans of the registry
(``cake_jit.ARG_PLANS``); ``cake_jit.ABI`` names the keyword set its kernels
expect (:data:`ABI_CONTRACT`).
"""
# Written by the Cake generated-program export (``exports/dsa_indexer_topk``); not edited by hand.
# ``PROGRAM_LEVERS[arch][key]`` documents the program-text levers of every scan dispatch key per
# architecture (tile order, bar_addr, agg_arrive, compact_select, pipe_write, cs_pipe, ordered_key,
# float_tau, select_wide, verdict_skip, reg_split, ...) with the kind, block_q, tile_unroll, snake and
# sample_fit of the program the key selects.  The test suite reads it; the runtime loader
# (``cake_jit``) does not.

from typing import Any

PROGRAM_LEVERS: dict[str, dict[str, dict[str, Any]]] = {
    "sm_100a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": True,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": True,
            "branchless_walk": True,
            "chunked_trigger": False,
            "peek": True,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": True,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": True,
            "branchless_walk": True,
            "chunked_trigger": False,
            "peek": True,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": True,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": True,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": True,
            "wide_wreg": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [232, 40],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": True,
            "wide_wreg": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [232, 40],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:wide:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": True,
            "wide_wreg": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [232, 40],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u2:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": True,
            "chunked_trigger": True,
            "peek": True,
            "wide_wreg": True,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [232, 40],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": True,
        },
    },
    "sm_103a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": True,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": True,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_l6:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": True,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
    },
    "sm_107a": {
        "scan:l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:l6:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:narrow:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:narrow:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:narrow:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_l6:u1:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_l6:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": True,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": True,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_l6",
            "block_q": 6,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_narrow:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_narrow:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_narrow:u2:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "pair_narrow",
            "block_q": 4,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": True,
        },
        "scan:pair_wide:u1:s1:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": [10, 10],
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": False,
        },
        "scan:pair_wide:u1:s1:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": [10, 10],
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:pair_wide:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:pair_wide:u2:s0:f1": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": True,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "pair_wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": True,
        },
        "scan:split_narrow:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 4,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_wide:u1:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:split_wide:u2:s0:f0": {
            "tile_order": "descending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": False,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "split",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": False,
        },
        "scan:wide:u1:s0:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": False,
            "sample_fit": True,
        },
        "scan:wide:u1:s1:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": False,
        },
        "scan:wide:u1:s1:f1": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": [240, 24],
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 1,
            "snake": True,
            "sample_fit": True,
        },
        "scan:wide:u2:s0:f0": {
            "tile_order": "ascending",
            "bar_addr": False,
            "agg_arrive": False,
            "compact_select": False,
            "pipe_write": False,
            "cs_pipe": False,
            "branchless_walk": False,
            "chunked_trigger": False,
            "peek": False,
            "wide_wreg": False,
            "ordered_key": False,
            "float_tau": True,
            "select_wide": None,
            "verdict_skip": False,
            "reg_split": None,
            "kind": "wide",
            "block_q": 8,
            "tile_unroll": 2,
            "snake": False,
            "sample_fit": False,
        },
    },
}
