/*
 * Copyright (c) 2026 by FlashInfer team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_sm90_bf16_megamoe_fc2'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <cstdint>

extern "C" __global__ void kernel_cake_sm90_bf16_megamoe_fc2(unsigned int num_experts, unsigned int shape_n, unsigned int shape_k, float clamp_limit, const __grid_constant__ CUtensorMap A, const __grid_constant__ CUtensorMap W, long long* __restrict__ offsets, __nv_bfloat16* __restrict__ D);


namespace cake_host_shim_98a953346792f799 {

using tvm::ffi::TensorView;

// Opt the linked kernel into its dynamic shared memory once for every device
// that accepts it. Function-local static initialization already serializes
// the first call; no lock or per-device cache is needed.
inline bool CakeSetMaxDynamicSmem(const void* symbol, int smem_bytes) {
  cudaKernel_t kernel = nullptr;
  TVM_FFI_CHECK_CUDA_ERROR(cudaGetKernel(&kernel, symbol));
  int device_count = 0;
  TVM_FFI_CHECK_CUDA_ERROR(cudaGetDeviceCount(&device_count));
  int configured = 0;
  for (int device = 0; device < device_count; ++device) {
    if (cudaKernelSetAttributeForDevice(
            kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_bytes, device) ==
        cudaSuccess) {
      ++configured;
    } else {
      (void)cudaGetLastError();
    }
  }
  TVM_FFI_CHECK(configured > 0, RuntimeError)
      << "no CUDA device accepts " << smem_bytes << " B of dynamic shared memory";
  return true;
}

// 2D TMA descriptor for buffer 'A' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_A(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'A' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'A' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  TVM_FFI_CHECK(d1 > 0, ValueError)
      << "TMA source 'A' trailing dims must be positive";
  int64_t outer1 = t.numel() / (d1);
  check_dense_leading_dims(t, 1, "A");
  int64_t s2 = t.stride(t.ndim() - 2) * 1;
  TVM_FFI_CHECK(s2 > 0, ValueError)
      << "TMA source 'A' physical strides must be positive";
  uint64_t global_dim[2] = {(uint64_t)(d1), (uint64_t)(outer1)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0, ValueError)
      << "TMA descriptor for 'A' resolved a non-positive global dim";
  uint32_t box_dim[2] = {64u, 128u};
  TVM_FFI_CHECK(box_dim[0] <= global_dim[0] && box_dim[1] <= global_dim[1], ValueError)
      << "TMA box (" << box_dim[0] << ", " << box_dim[1] << ") exceeds resolved global dims for 'A'";
  int64_t carrier_stride_0 = s2;
  TVM_FFI_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'A' resolved global stride 1 negative";
  TVM_FFI_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'A' resolved global stride 1 zero while global dimension 1 is not 1";
  TVM_FFI_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'A' resolved global stride 1 to a non-whole-byte offset";
  uint64_t global_strides[1] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
  };
  uint32_t elem_strides[2] = {1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 2, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_L2_256B,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (2D, 'A') failed: CUresult=" << (int)r;
  return tm;
}

// 2D TMA descriptor for buffer 'W' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_W(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'W' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'W' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  TVM_FFI_CHECK(d1 > 0, ValueError)
      << "TMA source 'W' trailing dims must be positive";
  int64_t outer1 = t.numel() / (d1);
  check_dense_leading_dims(t, 1, "W");
  int64_t s2 = t.stride(t.ndim() - 2) * 1;
  TVM_FFI_CHECK(s2 > 0, ValueError)
      << "TMA source 'W' physical strides must be positive";
  uint64_t global_dim[2] = {(uint64_t)(d1), (uint64_t)(outer1)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0, ValueError)
      << "TMA descriptor for 'W' resolved a non-positive global dim";
  uint32_t box_dim[2] = {64u, 256u};
  TVM_FFI_CHECK(box_dim[0] <= global_dim[0] && box_dim[1] <= global_dim[1], ValueError)
      << "TMA box (" << box_dim[0] << ", " << box_dim[1] << ") exceeds resolved global dims for 'W'";
  int64_t carrier_stride_0 = s2;
  TVM_FFI_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'W' resolved global stride 1 negative";
  TVM_FFI_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'W' resolved global stride 1 zero while global dimension 1 is not 1";
  TVM_FFI_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'W' resolved global stride 1 to a non-whole-byte offset";
  uint64_t global_strides[1] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
  };
  uint32_t elem_strides[2] = {1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 2, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_L2_256B,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (2D, 'W') failed: CUresult=" << (int)r;
  return tm;
}

void Run(int64_t arg_num_experts, int64_t arg_shape_n, int64_t arg_shape_k, double arg_clamp_limit, TensorView arg_A, TensorView arg_W, TensorView arg_offsets, TensorView arg_D, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_A.device();
  tvm::ffi::CUDADeviceGuard device_guard(dev.device_id);
  TVM_FFI_CHECK_CUDA_ERROR(cudaSetDevice(dev.device_id));  // binds the context for the encoders
  TVM_FFI_CHECK(arg_num_experts >= 0LL && arg_num_experts <= 4294967295LL, ValueError)
      << "scalar 'num_experts' value " << arg_num_experts
      << " is outside u32 range [0, 4294967295]";
  TVM_FFI_CHECK(arg_shape_n >= 0LL && arg_shape_n <= 4294967295LL, ValueError)
      << "scalar 'shape_n' value " << arg_shape_n
      << " is outside u32 range [0, 4294967295]";
  TVM_FFI_CHECK(arg_shape_k >= 0LL && arg_shape_k <= 4294967295LL, ValueError)
      << "scalar 'shape_k' value " << arg_shape_k
      << " is outside u32 range [0, 4294967295]";
  check_cuda_tensor(arg_A, "A");
  check_dtype(arg_A, DLDataType{kDLBfloat, 16, 1}, "A");
  check_cuda_tensor(arg_W, "W");
  check_dtype(arg_W, DLDataType{kDLBfloat, 16, 1}, "W");
  check_cuda_tensor(arg_offsets, "offsets");
  check_dtype(arg_offsets, DLDataType{kDLInt, 64, 1}, "offsets");
  check_contiguous(arg_offsets, "offsets");
  check_cuda_tensor(arg_D, "D");
  check_dtype(arg_D, DLDataType{kDLBfloat, 16, 1}, "D");
  check_contiguous(arg_D, "D");
  check_same_device(arg_W, arg_A, "W", "A");
  check_same_device(arg_offsets, arg_A, "offsets", "A");
  check_same_device(arg_D, arg_A, "D", "A");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";
  TVM_FFI_CHECK(grid_x % 2 == 0 && grid_y % 1 == 0 && grid_z % 1 == 0, ValueError)
      << "launch grid (" << grid_x << ", " << grid_y << ", " << grid_z
      << ") must be divisible by cluster dims (2, 1, 1)";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  uint32_t v_num_experts = (uint32_t)arg_num_experts;
  uint32_t v_shape_n = (uint32_t)arg_shape_n;
  uint32_t v_shape_k = (uint32_t)arg_shape_k;
  float v_clamp_limit = (float)arg_clamp_limit;
  CUtensorMap p_A = EncodeTma_A(arg_A);
  CUtensorMap p_W = EncodeTma_W(arg_W);
  long long* p_offsets = static_cast<long long*>(arg_offsets.data_ptr());
  __nv_bfloat16* p_D = static_cast<__nv_bfloat16*>(arg_D.data_ptr());
  void* kargs[] = {&v_num_experts, &v_shape_n, &v_shape_k, &v_clamp_limit, &p_A, &p_W, &p_offsets, &p_D};

  static const bool smem_ready = CakeSetMaxDynamicSmem(
      reinterpret_cast<const void*>(kernel_cake_sm90_bf16_megamoe_fc2), 196704);
  (void)smem_ready;
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(384u, 1u, 1u);

  // Extended direct-source launch for a linked CUDA kernel symbol.
  cudaLaunchAttribute attrs[2]{};
  int n = 0;
  attrs[n].id = cudaLaunchAttributeClusterDimension;
  attrs[n].val.clusterDim.x = 2u;
  attrs[n].val.clusterDim.y = 1u;
  attrs[n].val.clusterDim.z = 1u;
  ++n;
  attrs[n].id = cudaLaunchAttributeClusterSchedulingPolicyPreference;
  attrs[n].val.clusterSchedulingPolicyPreference = cudaClusterSchedulingPolicySpread;
  ++n;
  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 196704u;
  config.stream = stream;
  config.attrs = attrs;
  config.numAttrs = n;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_sm90_bf16_megamoe_fc2), kargs);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_sm90_bf16_megamoe_fc2 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_98a953346792f799

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_98a953346792f799::Run);
