/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_kimi_k3_tp12_tail_7919fc819bb5f04d4df0'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <cstdint>

#include "cake_kimi_k3_tp12_tail_host_common.cuh"

extern "C" __global__ void kernel_cake_kimi_k3_tp12_tail_7919fc819bb5f04d4df0(__nv_bfloat16* __restrict__ y, __nv_bfloat16* __restrict__ w_slice, __nv_bfloat16* __restrict__ out, long long* __restrict__ peer_ptrs, __nv_bfloat16* __restrict__ mcast_ptr, unsigned int* __restrict__ buffer_flags, int num_tokens, int rank, int my_col_begin);


namespace cake_host_shim_759a361f39991366 {

using namespace cake_host_shim_common;
using tvm::ffi::TensorView;

void Run(TensorView arg_y, TensorView arg_w_slice, TensorView arg_out, TensorView arg_peer_ptrs, int64_t arg_mcast_ptr, TensorView arg_buffer_flags, int64_t arg_num_tokens, int64_t arg_rank, int64_t arg_my_col_begin, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_y.device();
  tvm::ffi::CUDADeviceGuard device_guard(dev.device_id);
  check_cuda_tensor(arg_y, "y");
  check_dtype(arg_y, DLDataType{kDLBfloat, 16, 1}, "y");
  check_contiguous(arg_y, "y");
  check_cuda_tensor(arg_w_slice, "w_slice");
  check_dtype(arg_w_slice, DLDataType{kDLBfloat, 16, 1}, "w_slice");
  check_contiguous(arg_w_slice, "w_slice");
  check_cuda_tensor(arg_out, "out");
  check_dtype(arg_out, DLDataType{kDLBfloat, 16, 1}, "out");
  check_contiguous(arg_out, "out");
  check_cuda_tensor(arg_peer_ptrs, "peer_ptrs");
  check_dtype(arg_peer_ptrs, DLDataType{kDLInt, 64, 1}, "peer_ptrs");
  check_contiguous(arg_peer_ptrs, "peer_ptrs");
  TVM_FFI_CHECK(arg_mcast_ptr > 0, ValueError)
      << "raw pointer 'mcast_ptr' must be positive";
  check_cuda_tensor(arg_buffer_flags, "buffer_flags");
  check_dtype(arg_buffer_flags, DLDataType{kDLUInt, 32, 1}, "buffer_flags");
  check_contiguous(arg_buffer_flags, "buffer_flags");
  TVM_FFI_CHECK(arg_num_tokens >= -2147483648LL && arg_num_tokens <= 2147483647LL, ValueError)
      << "scalar 'num_tokens' value " << arg_num_tokens
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_rank >= -2147483648LL && arg_rank <= 2147483647LL, ValueError)
      << "scalar 'rank' value " << arg_rank
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_my_col_begin >= -2147483648LL && arg_my_col_begin <= 2147483647LL, ValueError)
      << "scalar 'my_col_begin' value " << arg_my_col_begin
      << " is outside i32 range [-2147483648, 2147483647]";
  check_same_device(arg_w_slice, arg_y, "w_slice", "y");
  check_same_device(arg_out, arg_y, "out", "y");
  check_same_device(arg_peer_ptrs, arg_y, "peer_ptrs", "y");
  check_same_device(arg_buffer_flags, arg_y, "buffer_flags", "y");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_y = static_cast<__nv_bfloat16*>(arg_y.data_ptr());
  __nv_bfloat16* p_w_slice = static_cast<__nv_bfloat16*>(arg_w_slice.data_ptr());
  __nv_bfloat16* p_out = static_cast<__nv_bfloat16*>(arg_out.data_ptr());
  long long* p_peer_ptrs = static_cast<long long*>(arg_peer_ptrs.data_ptr());
  void* p_mcast_ptr = reinterpret_cast<void*>(static_cast<uintptr_t>(arg_mcast_ptr));
  unsigned int* p_buffer_flags = static_cast<unsigned int*>(arg_buffer_flags.data_ptr());
  int32_t v_num_tokens = (int32_t)arg_num_tokens;
  int32_t v_rank = (int32_t)arg_rank;
  int32_t v_my_col_begin = (int32_t)arg_my_col_begin;
  void* kargs[] = {&p_y, &p_w_slice, &p_out, &p_peer_ptrs, &p_mcast_ptr, &p_buffer_flags, &v_num_tokens, &v_rank, &v_my_col_begin};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(448u, 1u, 1u);

  // Extended direct-source launch for a linked CUDA kernel symbol.
  cudaLaunchAttribute attrs[1]{};
  int n = 0;
  attrs[n].id = cudaLaunchAttributeProgrammaticStreamSerialization;
  attrs[n].val.programmaticStreamSerializationAllowed = 1;
  ++n;
  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 1920u;
  config.stream = stream;
  config.attrs = attrs;
  config.numAttrs = n;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kimi_k3_tp12_tail_7919fc819bb5f04d4df0), kargs);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kimi_k3_tp12_tail_7919fc819bb5f04d4df0 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_759a361f39991366

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_759a361f39991366::Run);
