/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel
// 'kernel_cake_selective_state_update_89c874c1541f71e37533'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include <cstdint>

#include "tvm_ffi_utils.h"

extern "C" __global__ void kernel_cake_selective_state_update_89c874c1541f71e37533(
    __nv_bfloat16* __restrict__ state, __nv_bfloat16* __restrict__ x, float* __restrict__ dt,
    float* __restrict__ A, __nv_bfloat16* __restrict__ B, __nv_bfloat16* __restrict__ C,
    float* __restrict__ D, float* __restrict__ dt_bias, __nv_bfloat16* __restrict__ output,
    long long* __restrict__ state_batch_indices, int batch_size, int nheads, int dim, int dstate,
    int ngroups, int token_steps, unsigned long long state_stride_slot, int dt_softplus,
    long long pad_slot_id);

namespace cake_host_shim_82cc0e4f2220795d {

using tvm::ffi::TensorView;

void Run(TensorView arg_state, TensorView arg_x, TensorView arg_dt, TensorView arg_A,
         TensorView arg_B, TensorView arg_C, TensorView arg_D, TensorView arg_dt_bias,
         TensorView arg_output, TensorView arg_state_batch_indices, int64_t arg_batch_size,
         int64_t arg_nheads, int64_t arg_dim, int64_t arg_dstate, int64_t arg_ngroups,
         int64_t arg_token_steps, int64_t arg_state_stride_slot, int64_t arg_dt_softplus,
         int64_t arg_pad_slot_id, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_state.device();
  tvm::ffi::CUDADeviceGuard device_guard(dev.device_id);
  check_cuda_tensor(arg_state, "state");
  check_dtype(arg_state, DLDataType{kDLBfloat, 16, 1}, "state");
  check_contiguous(arg_state, "state");
  check_cuda_tensor(arg_x, "x");
  check_dtype(arg_x, DLDataType{kDLBfloat, 16, 1}, "x");
  check_contiguous(arg_x, "x");
  check_cuda_tensor(arg_dt, "dt");
  check_dtype(arg_dt, DLDataType{kDLFloat, 32, 1}, "dt");
  check_contiguous(arg_dt, "dt");
  check_cuda_tensor(arg_A, "A");
  check_dtype(arg_A, DLDataType{kDLFloat, 32, 1}, "A");
  check_contiguous(arg_A, "A");
  check_cuda_tensor(arg_B, "B");
  check_dtype(arg_B, DLDataType{kDLBfloat, 16, 1}, "B");
  check_contiguous(arg_B, "B");
  check_cuda_tensor(arg_C, "C");
  check_dtype(arg_C, DLDataType{kDLBfloat, 16, 1}, "C");
  check_contiguous(arg_C, "C");
  check_cuda_tensor(arg_D, "D");
  check_dtype(arg_D, DLDataType{kDLFloat, 32, 1}, "D");
  check_contiguous(arg_D, "D");
  check_cuda_tensor(arg_dt_bias, "dt_bias");
  check_dtype(arg_dt_bias, DLDataType{kDLFloat, 32, 1}, "dt_bias");
  check_contiguous(arg_dt_bias, "dt_bias");
  check_cuda_tensor(arg_output, "output");
  check_dtype(arg_output, DLDataType{kDLBfloat, 16, 1}, "output");
  check_contiguous(arg_output, "output");
  check_cuda_tensor(arg_state_batch_indices, "state_batch_indices");
  check_dtype(arg_state_batch_indices, DLDataType{kDLInt, 64, 1}, "state_batch_indices");
  check_contiguous(arg_state_batch_indices, "state_batch_indices");
  TVM_FFI_CHECK(arg_batch_size >= -2147483648LL && arg_batch_size <= 2147483647LL, ValueError)
      << "scalar 'batch_size' value " << arg_batch_size
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_nheads >= -2147483648LL && arg_nheads <= 2147483647LL, ValueError)
      << "scalar 'nheads' value " << arg_nheads
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_dim >= -2147483648LL && arg_dim <= 2147483647LL, ValueError)
      << "scalar 'dim' value " << arg_dim << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_dstate >= -2147483648LL && arg_dstate <= 2147483647LL, ValueError)
      << "scalar 'dstate' value " << arg_dstate
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_ngroups >= -2147483648LL && arg_ngroups <= 2147483647LL, ValueError)
      << "scalar 'ngroups' value " << arg_ngroups
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_token_steps >= -2147483648LL && arg_token_steps <= 2147483647LL, ValueError)
      << "scalar 'token_steps' value " << arg_token_steps
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_state_stride_slot >= 0LL && arg_state_stride_slot <= 9223372036854775807LL,
                ValueError)
      << "scalar 'state_stride_slot' value " << arg_state_stride_slot
      << " is outside u64 range [0, 9223372036854775807]";
  TVM_FFI_CHECK(arg_dt_softplus >= -2147483648LL && arg_dt_softplus <= 2147483647LL, ValueError)
      << "scalar 'dt_softplus' value " << arg_dt_softplus
      << " is outside i32 range [-2147483648, 2147483647]";
  check_same_device(arg_x, arg_state, "x", "state");
  check_same_device(arg_dt, arg_state, "dt", "state");
  check_same_device(arg_A, arg_state, "A", "state");
  check_same_device(arg_B, arg_state, "B", "state");
  check_same_device(arg_C, arg_state, "C", "state");
  check_same_device(arg_D, arg_state, "D", "state");
  check_same_device(arg_dt_bias, arg_state, "dt_bias", "state");
  check_same_device(arg_output, arg_state, "output", "state");
  check_same_device(arg_state_batch_indices, arg_state, "state_batch_indices", "state");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y << ", "
      << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_state = static_cast<__nv_bfloat16*>(arg_state.data_ptr());
  __nv_bfloat16* p_x = static_cast<__nv_bfloat16*>(arg_x.data_ptr());
  float* p_dt = static_cast<float*>(arg_dt.data_ptr());
  float* p_A = static_cast<float*>(arg_A.data_ptr());
  __nv_bfloat16* p_B = static_cast<__nv_bfloat16*>(arg_B.data_ptr());
  __nv_bfloat16* p_C = static_cast<__nv_bfloat16*>(arg_C.data_ptr());
  float* p_D = static_cast<float*>(arg_D.data_ptr());
  float* p_dt_bias = static_cast<float*>(arg_dt_bias.data_ptr());
  __nv_bfloat16* p_output = static_cast<__nv_bfloat16*>(arg_output.data_ptr());
  long long* p_state_batch_indices = static_cast<long long*>(arg_state_batch_indices.data_ptr());
  int32_t v_batch_size = (int32_t)arg_batch_size;
  int32_t v_nheads = (int32_t)arg_nheads;
  int32_t v_dim = (int32_t)arg_dim;
  int32_t v_dstate = (int32_t)arg_dstate;
  int32_t v_ngroups = (int32_t)arg_ngroups;
  int32_t v_token_steps = (int32_t)arg_token_steps;
  uint64_t v_state_stride_slot = (uint64_t)arg_state_stride_slot;
  int32_t v_dt_softplus = (int32_t)arg_dt_softplus;
  int64_t v_pad_slot_id = (int64_t)arg_pad_slot_id;
  void* kargs[] = {&p_state,
                   &p_x,
                   &p_dt,
                   &p_A,
                   &p_B,
                   &p_C,
                   &p_D,
                   &p_dt_bias,
                   &p_output,
                   &p_state_batch_indices,
                   &v_batch_size,
                   &v_nheads,
                   &v_dim,
                   &v_dstate,
                   &v_ngroups,
                   &v_token_steps,
                   &v_state_stride_slot,
                   &v_dt_softplus,
                   &v_pad_slot_id};

  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 1664u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config,
      reinterpret_cast<const void*>(kernel_cake_selective_state_update_89c874c1541f71e37533),
      kargs);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_selective_state_update_89c874c1541f71e37533 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_82cc0e4f2220795d

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_82cc0e4f2220795d::Run);
