/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9'.
#include "cake_kda_prefill_host_shim.cuh"

struct CakeTensorMap;
extern "C" __global__ void kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9(int* __restrict__ items, int num_heads, __nv_bfloat16* __restrict__ pair, CakeTensorMap const* pair_tma, float* __restrict__ dpair, __nv_bfloat16* __restrict__ maps, CakeTensorMap const* maps_tma, __nv_bfloat16* __restrict__ map_final, CakeTensorMap const* map_final_tma);

namespace cake_host_shim_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9 {

using namespace cake_kda_prefill_shim;
using tvm::ffi::Optional;
using tvm::ffi::TensorView;

void RunWithDescriptors(TensorView arg_items, int64_t arg_num_heads, TensorView arg_pair, TensorView arg_pair_tma, TensorView arg_dpair, TensorView arg_maps, TensorView arg_maps_tma, TensorView arg_map_final, TensorView arg_map_final_tma, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z, int descriptor_action) {
  DLDevice dev = arg_items.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_items, "items");
  CheckDtype(arg_items, "items", 0, 32, 1);
  CheckContiguous(arg_items, "items");
  TVM_FFI_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckCudaTensor(arg_pair, "pair");
  CheckDtype(arg_pair, "pair", 4, 16, 1);
  CheckContiguous(arg_pair, "pair");
  CheckCudaTensor(arg_pair_tma, "pair_tma");
  CheckDtype(arg_pair_tma, "pair_tma", 4, 16, 1);
  CheckContiguous(arg_pair_tma, "pair_tma");
  CheckCudaTensor(arg_dpair, "dpair");
  CheckDtype(arg_dpair, "dpair", 2, 32, 1);
  CheckContiguous(arg_dpair, "dpair");
  CheckCudaTensor(arg_maps, "maps");
  CheckDtype(arg_maps, "maps", 4, 16, 1);
  CheckContiguous(arg_maps, "maps");
  CheckCudaTensor(arg_maps_tma, "maps_tma");
  CheckDtype(arg_maps_tma, "maps_tma", 4, 16, 1);
  CheckContiguous(arg_maps_tma, "maps_tma");
  CheckCudaTensor(arg_map_final, "map_final");
  CheckDtype(arg_map_final, "map_final", 4, 16, 1);
  CheckContiguous(arg_map_final, "map_final");
  CheckCudaTensor(arg_map_final_tma, "map_final_tma");
  CheckDtype(arg_map_final_tma, "map_final_tma", 4, 16, 1);
  CheckContiguous(arg_map_final_tma, "map_final_tma");
  CheckSameCudaDevice(arg_pair, arg_items, "pair", "items");
  CheckSameCudaDevice(arg_pair_tma, arg_items, "pair_tma", "items");
  CheckSameCudaDevice(arg_dpair, arg_items, "dpair", "items");
  CheckSameCudaDevice(arg_maps, arg_items, "maps", "items");
  CheckSameCudaDevice(arg_maps_tma, arg_items, "maps_tma", "items");
  CheckSameCudaDevice(arg_map_final, arg_items, "map_final", "items");
  CheckSameCudaDevice(arg_map_final_tma, arg_items, "map_final_tma", "items");
  CheckCudaTensor(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckSameCudaDevice(arg_tma_descriptor_workspace, arg_items, "tma_descriptor_workspace", "items");
  CheckContiguous(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckDtype(arg_tma_descriptor_workspace, "tma_descriptor_workspace", 1, 8, 1);
  TVM_FFI_CHECK(arg_tma_descriptor_workspace.numel() >= 384, ValueError)
      << "tma_descriptor_workspace requires at least 384 bytes";
  TVM_FFI_CHECK(
      reinterpret_cast<uintptr_t>(arg_tma_descriptor_workspace.data_ptr()) % 128 == 0,
      ValueError)
      << "tma_descriptor_workspace must be 128-byte aligned";
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  int* p_items = static_cast<int*>(arg_items.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  __nv_bfloat16* p_pair = static_cast<__nv_bfloat16*>(arg_pair.data_ptr());
  CUtensorMap h_pair_tma = EncodeTma_pair_tma_1(arg_pair_tma);
  CakeTensorMap const* p_pair_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 0u));
  float* p_dpair = static_cast<float*>(arg_dpair.data_ptr());
  __nv_bfloat16* p_maps = static_cast<__nv_bfloat16*>(arg_maps.data_ptr());
  CUtensorMap h_maps_tma = EncodeTma_maps_tma_1(arg_maps_tma);
  CakeTensorMap const* p_maps_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 1u));
  __nv_bfloat16* p_map_final = static_cast<__nv_bfloat16*>(arg_map_final.data_ptr());
  CUtensorMap h_map_final_tma = EncodeTma_map_final_tma_1(arg_map_final_tma);
  CakeTensorMap const* p_map_final_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 2u));
  void* kargs[] = {&p_items, &v_num_heads, &p_pair, &p_pair_tma, &p_dpair, &p_maps, &p_maps_tma, &p_map_final, &p_map_final_tma};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = EnsureMaxDynamicSharedMemory(
      smem_mu, *smem_status_by_device, dev.device_id,
      reinterpret_cast<const void*>(kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9), 118784);
  TVM_FFI_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(320u, 1u, 1u);
  if (descriptor_action != 0) {
  const CUtensorMap workspace_maps[] = {h_pair_tma, h_maps_tma, h_map_final_tma};
  UploadCallerTmaWorkspace(arg_tma_descriptor_workspace.data_ptr(), workspace_maps, stream);
  }
  if (descriptor_action == 1) return;

  cudaError_t launch_status = cudaLaunchKernel(
      reinterpret_cast<const void*>(kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9), grid, block, kargs, 118784u, stream);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernel for kernel_cake_kda_bf16_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9 failed: "
      << cudaGetErrorString(launch_status);
}

void Run(TensorView arg_items, int64_t arg_num_heads, TensorView arg_pair, TensorView arg_pair_tma, TensorView arg_dpair, TensorView arg_maps, TensorView arg_maps_tma, TensorView arg_map_final, TensorView arg_map_final_tma, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_items, arg_num_heads, arg_pair, arg_pair_tma, arg_dpair, arg_maps, arg_maps_tma, arg_map_final, arg_map_final_tma, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 2);
}

void PrepareTma(TensorView arg_items, int64_t arg_num_heads, TensorView arg_pair, TensorView arg_pair_tma, TensorView arg_dpair, TensorView arg_maps, TensorView arg_maps_tma, TensorView arg_map_final, TensorView arg_map_final_tma, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_items, arg_num_heads, arg_pair, arg_pair_tma, arg_dpair, arg_maps, arg_maps_tma, arg_map_final, arg_map_final_tma, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 1);
}

void RunPrepared(TensorView arg_items, int64_t arg_num_heads, TensorView arg_pair, TensorView arg_pair_tma, TensorView arg_dpair, TensorView arg_maps, TensorView arg_maps_tma, TensorView arg_map_final, TensorView arg_map_final_tma, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_items, arg_num_heads, arg_pair, arg_pair_tma, arg_dpair, arg_maps, arg_maps_tma, arg_map_final, arg_map_final_tma, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 0);
}

}  // namespace cake_host_shim_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9::Run);
TVM_FFI_DLL_EXPORT_TYPED_FUNC(run_prepare_tma, cake_host_shim_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9::PrepareTma);
TVM_FFI_DLL_EXPORT_TYPED_FUNC(run_prepared, cake_host_shim_d4ff22207792366eab60b789e452c65302005372ca900f47ed636c5332834dd9::RunPrepared);
