/*
 * Copyright (c) 2023 by FlashInfer team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "tvm_ffi_utils.h"
// Generated by cake.runtime.host_shim — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_dsv4_bf16_h64_fixed_q'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include <tvm/ffi/container/tensor.h>
#include <tvm/ffi/error.h>
#include <tvm/ffi/extra/c_env_api.h>
#include <tvm/ffi/function.h>

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

struct CakeTensorMap;
extern "C" __global__ void kernel_cake_dsv4_bf16_h64_fixed_q(CakeTensorMap const* tmap_q, CakeTensorMap const* tmap_swa_kv, CakeTensorMap const* tmap_compressed_kv, __nv_bfloat16* __restrict__ partial_O, float* __restrict__ partial_lse, int* __restrict__ sparse_indices, int* __restrict__ sparse_topk_lens, float* __restrict__ sinks, float* __restrict__ bmm1_scale, float* __restrict__ bmm2_scale, int num_heads, int sparse_topk, int num_splits, int has_sinks);


namespace cake_host_shim_bda296eb97c633f5 {

using tvm::ffi::Optional;
using tvm::ffi::TensorView;

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  TVM_FFI_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  TVM_FFI_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  TVM_FFI_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  TVM_FFI_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  TVM_FFI_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

// Upload one encoded tensor map into a caller-owned immutable slot. The
// caller supplies the CUDA storage; this helper never allocates device memory.
// Stable descriptor bytes are uploaded once before capture and reused by warm
// launches. A changed binding must be prepared outside CUDA Graph capture.
static inline void* CallerTmaWorkspaceSlot(
    const CUtensorMap& tm,
    const tvm::ffi::TensorView& workspace,
    size_t slot,
    cudaStream_t stream) {
  static std::mutex mu;
  static auto* descriptor_by_slot =
      new std::unordered_map<std::string, std::string>();

  CUcontext current_context = nullptr;
  CUresult result = cuCtxGetCurrent(&current_context);
  TVM_FFI_CHECK(result == CUDA_SUCCESS && current_context != nullptr, RuntimeError)
      << "caller-owned pointer TMA ABI requires an active CUDA context: "
      << "CUresult=" << static_cast<int>(result);

  const uintptr_t base = reinterpret_cast<uintptr_t>(workspace.data_ptr());
  const uintptr_t address = base + slot * sizeof(CUtensorMap);
  unsigned long long buffer_id = 0;
  result = cuPointerGetAttribute(
      &buffer_id,
      CU_POINTER_ATTRIBUTE_BUFFER_ID,
      static_cast<CUdeviceptr>(address));
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuPointerGetAttribute for caller-owned TMA workspace failed: "
      << "CUresult=" << static_cast<int>(result);
  std::string key =
      std::to_string(reinterpret_cast<uintptr_t>(current_context));
  key.push_back(':');
  key.append(std::to_string(base));
  key.push_back(':');
  key.append(std::to_string(slot));
  std::string binding(sizeof(buffer_id) + sizeof(CUtensorMap), '\0');
  std::memcpy(binding.data(), &buffer_id, sizeof(buffer_id));
  std::memcpy(binding.data() + sizeof(buffer_id), &tm, sizeof(CUtensorMap));

  std::lock_guard<std::mutex> lock(mu);
  auto it = descriptor_by_slot->find(key);
  if (it != descriptor_by_slot->end() && it->second == binding) {
    return reinterpret_cast<void*>(address);
  }

  cudaStreamCaptureStatus capture_status = cudaStreamCaptureStatusNone;
  cudaError_t capture_error = cudaStreamIsCapturing(stream, &capture_status);
  TVM_FFI_CHECK(capture_error == cudaSuccess, RuntimeError)
      << "cudaStreamIsCapturing for caller-owned TMA workspace failed: "
      << cudaGetErrorString(capture_error);
  TVM_FFI_CHECK(capture_status == cudaStreamCaptureStatusNone, RuntimeError)
      << "caller-owned pointer TMA workspace is not prepared for this tensor "
         "binding; warm the exact tensors before CUDA Graph capture";

  result = cuMemcpyHtoD(
      static_cast<CUdeviceptr>(address), &tm, sizeof(CUtensorMap));
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuMemcpyHtoD into caller-owned TMA workspace failed: CUresult="
      << static_cast<int>(result);
  (*descriptor_by_slot)[key] = binding;
  return reinterpret_cast<void*>(address);
}

// 4D TMA descriptor for buffer 'tmap_q' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_tmap_q(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 3, ValueError)
      << "TMA source 'tmap_q' must have at least 3 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'tmap_q' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0, ValueError)
      << "TMA source 'tmap_q' trailing dims must be positive";
  TVM_FFI_CHECK(d1 % 64 == 0, ValueError)
      << "TMA source 'tmap_q' extent " << d1
      << " must divide exactly by " << 64;
  uint64_t global_dim[4] = {(uint64_t)(64), (uint64_t)(d2), (uint64_t)((d1 / 64)), (uint64_t)(d3)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 1u <= global_dim[2] && 1u <= global_dim[3], ValueError)
      << "TMA box (64, 64, 1, 1) exceeds resolved global dims for 'tmap_q'";
  int64_t carrier_stride_0 = d1;
  TVM_FFI_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 1 negative";
  TVM_FFI_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 1 zero while global dimension 1 is not 1";
  TVM_FFI_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = 64;
  TVM_FFI_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 2 negative";
  TVM_FFI_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 2 zero while global dimension 2 is not 1";
  TVM_FFI_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 2 to a non-whole-byte offset";
  int64_t carrier_stride_2 = (d2 * d1);
  TVM_FFI_CHECK(carrier_stride_2 >= 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 3 negative";
  TVM_FFI_CHECK(carrier_stride_2 != 0 || global_dim[3] == 1, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 3 zero while global dimension 3 is not 1";
  TVM_FFI_CHECK((carrier_stride_2 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'tmap_q' resolved global stride 3 to a non-whole-byte offset";
  uint64_t global_strides[3] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
      (uint64_t)((carrier_stride_2 * 16) / 8),
  };
  uint32_t box_dim[4] = {64u, 64u, 1u, 1u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'tmap_q') failed: CUresult=" << (int)r;
  return tm;
}

// 2D TMA descriptor for buffer 'tmap_swa_kv' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_tmap_swa_kv(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'tmap_swa_kv' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'tmap_swa_kv' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  TVM_FFI_CHECK(d1 > 0, ValueError)
      << "TMA source 'tmap_swa_kv' trailing dims must be positive";
  int64_t outer1 = t.numel() / (d1);
  CheckDenseLeadingFold(t, 1, "tmap_swa_kv");
  int64_t s2 = t.stride(t.ndim() - 2) * 1;
  TVM_FFI_CHECK(s2 > 0, ValueError)
      << "TMA source 'tmap_swa_kv' physical strides must be positive";
  uint64_t global_dim[2] = {(uint64_t)(d1), (uint64_t)(outer1)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0, ValueError)
      << "TMA descriptor for 'tmap_swa_kv' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 1u <= global_dim[1], ValueError)
      << "TMA box (64, 1) exceeds resolved global dims for 'tmap_swa_kv'";
  int64_t carrier_stride_0 = s2;
  TVM_FFI_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'tmap_swa_kv' resolved global stride 1 negative";
  TVM_FFI_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'tmap_swa_kv' resolved global stride 1 zero while global dimension 1 is not 1";
  TVM_FFI_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'tmap_swa_kv' resolved global stride 1 to a non-whole-byte offset";
  uint64_t global_strides[1] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
  };
  uint32_t box_dim[2] = {64u, 1u};
  uint32_t elem_strides[2] = {1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 2, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (2D, 'tmap_swa_kv') failed: CUresult=" << (int)r;
  return tm;
}

// 2D TMA descriptor for buffer 'tmap_compressed_kv' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_tmap_compressed_kv(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'tmap_compressed_kv' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'tmap_compressed_kv' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  TVM_FFI_CHECK(d1 > 0, ValueError)
      << "TMA source 'tmap_compressed_kv' trailing dims must be positive";
  int64_t outer1 = t.numel() / (d1);
  CheckDenseLeadingFold(t, 1, "tmap_compressed_kv");
  int64_t s2 = t.stride(t.ndim() - 2) * 1;
  TVM_FFI_CHECK(s2 > 0, ValueError)
      << "TMA source 'tmap_compressed_kv' physical strides must be positive";
  uint64_t global_dim[2] = {(uint64_t)(d1), (uint64_t)(outer1)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0, ValueError)
      << "TMA descriptor for 'tmap_compressed_kv' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 1u <= global_dim[1], ValueError)
      << "TMA box (64, 1) exceeds resolved global dims for 'tmap_compressed_kv'";
  int64_t carrier_stride_0 = s2;
  TVM_FFI_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'tmap_compressed_kv' resolved global stride 1 negative";
  TVM_FFI_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'tmap_compressed_kv' resolved global stride 1 zero while global dimension 1 is not 1";
  TVM_FFI_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'tmap_compressed_kv' resolved global stride 1 to a non-whole-byte offset";
  uint64_t global_strides[1] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
  };
  uint32_t box_dim[2] = {64u, 1u};
  uint32_t elem_strides[2] = {1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 2, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (2D, 'tmap_compressed_kv') failed: CUresult=" << (int)r;
  return tm;
}

void Run(TensorView arg_tmap_q, TensorView arg_tmap_swa_kv, TensorView arg_tmap_compressed_kv, TensorView arg_partial_O, TensorView arg_partial_lse, TensorView arg_sparse_indices, TensorView arg_sparse_topk_lens, TensorView arg_sinks, TensorView arg_bmm1_scale, TensorView arg_bmm2_scale, int64_t arg_num_heads, int64_t arg_sparse_topk, int64_t arg_num_splits, int64_t arg_has_sinks, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_tmap_q.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_tmap_q, "tmap_q");
  CheckDtype(arg_tmap_q, "tmap_q", 4, 16, 1);
  CheckContiguous(arg_tmap_q, "tmap_q");
  CheckCudaTensor(arg_tmap_swa_kv, "tmap_swa_kv");
  CheckDtype(arg_tmap_swa_kv, "tmap_swa_kv", 4, 16, 1);
  CheckCudaTensor(arg_tmap_compressed_kv, "tmap_compressed_kv");
  CheckDtype(arg_tmap_compressed_kv, "tmap_compressed_kv", 4, 16, 1);
  CheckCudaTensor(arg_partial_O, "partial_O");
  CheckDtype(arg_partial_O, "partial_O", 4, 16, 1);
  CheckContiguous(arg_partial_O, "partial_O");
  CheckCudaTensor(arg_partial_lse, "partial_lse");
  CheckDtype(arg_partial_lse, "partial_lse", 2, 32, 1);
  CheckContiguous(arg_partial_lse, "partial_lse");
  CheckCudaTensor(arg_sparse_indices, "sparse_indices");
  CheckDtype(arg_sparse_indices, "sparse_indices", 0, 32, 1);
  CheckContiguous(arg_sparse_indices, "sparse_indices");
  CheckCudaTensor(arg_sparse_topk_lens, "sparse_topk_lens");
  CheckDtype(arg_sparse_topk_lens, "sparse_topk_lens", 0, 32, 1);
  CheckContiguous(arg_sparse_topk_lens, "sparse_topk_lens");
  CheckCudaTensor(arg_sinks, "sinks");
  CheckDtype(arg_sinks, "sinks", 2, 32, 1);
  CheckContiguous(arg_sinks, "sinks");
  CheckCudaTensor(arg_bmm1_scale, "bmm1_scale");
  CheckDtype(arg_bmm1_scale, "bmm1_scale", 2, 32, 1);
  CheckContiguous(arg_bmm1_scale, "bmm1_scale");
  CheckCudaTensor(arg_bmm2_scale, "bmm2_scale");
  CheckDtype(arg_bmm2_scale, "bmm2_scale", 2, 32, 1);
  CheckContiguous(arg_bmm2_scale, "bmm2_scale");
  TVM_FFI_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_sparse_topk >= -2147483648LL && arg_sparse_topk <= 2147483647LL, ValueError)
      << "scalar 'sparse_topk' value " << arg_sparse_topk
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_num_splits >= -2147483648LL && arg_num_splits <= 2147483647LL, ValueError)
      << "scalar 'num_splits' value " << arg_num_splits
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_has_sinks >= -2147483648LL && arg_has_sinks <= 2147483647LL, ValueError)
      << "scalar 'has_sinks' value " << arg_has_sinks
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_tmap_swa_kv, arg_tmap_q, "tmap_swa_kv", "tmap_q");
  CheckSameCudaDevice(arg_tmap_compressed_kv, arg_tmap_q, "tmap_compressed_kv", "tmap_q");
  CheckSameCudaDevice(arg_partial_O, arg_tmap_q, "partial_O", "tmap_q");
  CheckSameCudaDevice(arg_partial_lse, arg_tmap_q, "partial_lse", "tmap_q");
  CheckSameCudaDevice(arg_sparse_indices, arg_tmap_q, "sparse_indices", "tmap_q");
  CheckSameCudaDevice(arg_sparse_topk_lens, arg_tmap_q, "sparse_topk_lens", "tmap_q");
  CheckSameCudaDevice(arg_sinks, arg_tmap_q, "sinks", "tmap_q");
  CheckSameCudaDevice(arg_bmm1_scale, arg_tmap_q, "bmm1_scale", "tmap_q");
  CheckSameCudaDevice(arg_bmm2_scale, arg_tmap_q, "bmm2_scale", "tmap_q");
  CheckCurrentCudaDevice(arg_tmap_q, "tmap_q");
  CheckCudaTensor(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckSameCudaDevice(arg_tma_descriptor_workspace, arg_tmap_q, "tma_descriptor_workspace", "tmap_q");
  CheckContiguous(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckDtype(arg_tma_descriptor_workspace, "tma_descriptor_workspace", 1, 8, 1);
  TVM_FFI_CHECK(arg_tma_descriptor_workspace.numel() >= 384, ValueError)
      << "tma_descriptor_workspace requires at least 384 bytes";
  TVM_FFI_CHECK(
      reinterpret_cast<uintptr_t>(arg_tma_descriptor_workspace.data_ptr()) % 128 == 0,
      ValueError)
      << "tma_descriptor_workspace must be 128-byte aligned";
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";
  TVM_FFI_CHECK(grid_x % 2 == 0 && grid_y % 1 == 0 && grid_z % 1 == 0, ValueError)
      << "launch grid (" << grid_x << ", " << grid_y << ", " << grid_z
      << ") must be divisible by cluster dims (2, 1, 1)";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  CUtensorMap h_tmap_q = EncodeTma_tmap_q(arg_tmap_q);
  CakeTensorMap const* p_tmap_q = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(h_tmap_q, arg_tma_descriptor_workspace, 0u, stream));
  CUtensorMap h_tmap_swa_kv = EncodeTma_tmap_swa_kv(arg_tmap_swa_kv);
  CakeTensorMap const* p_tmap_swa_kv = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(h_tmap_swa_kv, arg_tma_descriptor_workspace, 1u, stream));
  CUtensorMap h_tmap_compressed_kv = EncodeTma_tmap_compressed_kv(arg_tmap_compressed_kv);
  CakeTensorMap const* p_tmap_compressed_kv = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(h_tmap_compressed_kv, arg_tma_descriptor_workspace, 2u, stream));
  __nv_bfloat16* p_partial_O = static_cast<__nv_bfloat16*>(arg_partial_O.data_ptr());
  float* p_partial_lse = static_cast<float*>(arg_partial_lse.data_ptr());
  int* p_sparse_indices = static_cast<int*>(arg_sparse_indices.data_ptr());
  int* p_sparse_topk_lens = static_cast<int*>(arg_sparse_topk_lens.data_ptr());
  float* p_sinks = static_cast<float*>(arg_sinks.data_ptr());
  float* p_bmm1_scale = static_cast<float*>(arg_bmm1_scale.data_ptr());
  float* p_bmm2_scale = static_cast<float*>(arg_bmm2_scale.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_sparse_topk = (int32_t)arg_sparse_topk;
  int32_t v_num_splits = (int32_t)arg_num_splits;
  int32_t v_has_sinks = (int32_t)arg_has_sinks;
  void* kargs[] = {&p_tmap_q, &p_tmap_swa_kv, &p_tmap_compressed_kv, &p_partial_O, &p_partial_lse, &p_sparse_indices, &p_sparse_topk_lens, &p_sinks, &p_bmm1_scale, &p_bmm2_scale, &v_num_heads, &v_sparse_topk, &v_num_splits, &v_has_sinks};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_dsv4_bf16_h64_fixed_q),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            215168);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  TVM_FFI_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_dsv4_bf16_h64_fixed_q failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(416u, 1u, 1u);

  cudaLaunchAttribute attrs[2]{};
  int n = 0;
  attrs[n].id = cudaLaunchAttributeClusterDimension;
  attrs[n].val.clusterDim.x = 2u;
  attrs[n].val.clusterDim.y = 1u;
  attrs[n].val.clusterDim.z = 1u;
  ++n;
  attrs[n].id = cudaLaunchAttributeClusterSchedulingPolicyPreference;
  attrs[n].val.clusterSchedulingPolicyPreference = cudaClusterSchedulingPolicySpread;
  ++n;
  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 215168u;
  config.stream = stream;
  config.attrs = attrs;
  config.numAttrs = n;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsv4_bf16_h64_fixed_q), kargs);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsv4_bf16_h64_fixed_q failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_bda296eb97c633f5

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run_bf16_h64_fixed_q, cake_host_shim_bda296eb97c633f5::Run);
