/*
 * Copyright (c) 2026 by FlashInfer team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_gdn_cp_182ccae8c184a6945d27'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <cstdint>

extern "C" __global__ void kernel_cake_gdn_cp_182ccae8c184a6945d27(float* __restrict__ packed, long long* __restrict__ state_indices, float* __restrict__ output, long long pool_stride0, long long pool_stride1, long long pool_stride2, long long pool_stride3, int num_heads, long long total_values, int use_indices);


namespace cake_host_shim_214b04dace936b52 {

using tvm::ffi::TensorView;

void Run(TensorView arg_packed, TensorView arg_state_indices, TensorView arg_output, int64_t arg_pool_stride0, int64_t arg_pool_stride1, int64_t arg_pool_stride2, int64_t arg_pool_stride3, int64_t arg_num_heads, int64_t arg_total_values, int64_t arg_use_indices, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_packed.device();
  tvm::ffi::CUDADeviceGuard device_guard(dev.device_id);
  check_cuda_tensor(arg_packed, "packed");
  check_dtype(arg_packed, DLDataType{kDLFloat, 32, 1}, "packed");
  check_contiguous(arg_packed, "packed");
  check_cuda_tensor(arg_state_indices, "state_indices");
  check_dtype(arg_state_indices, DLDataType{kDLInt, 64, 1}, "state_indices");
  check_contiguous(arg_state_indices, "state_indices");
  check_cuda_tensor(arg_output, "output");
  check_dtype(arg_output, DLDataType{kDLFloat, 32, 1}, "output");
  check_contiguous(arg_output, "output");
  TVM_FFI_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_use_indices >= -2147483648LL && arg_use_indices <= 2147483647LL, ValueError)
      << "scalar 'use_indices' value " << arg_use_indices
      << " is outside i32 range [-2147483648, 2147483647]";
  check_same_device(arg_state_indices, arg_packed, "state_indices", "packed");
  check_same_device(arg_output, arg_packed, "output", "packed");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  float* p_packed = static_cast<float*>(arg_packed.data_ptr());
  long long* p_state_indices = static_cast<long long*>(arg_state_indices.data_ptr());
  float* p_output = static_cast<float*>(arg_output.data_ptr());
  int64_t v_pool_stride0 = (int64_t)arg_pool_stride0;
  int64_t v_pool_stride1 = (int64_t)arg_pool_stride1;
  int64_t v_pool_stride2 = (int64_t)arg_pool_stride2;
  int64_t v_pool_stride3 = (int64_t)arg_pool_stride3;
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int64_t v_total_values = (int64_t)arg_total_values;
  int32_t v_use_indices = (int32_t)arg_use_indices;
  void* kargs[] = {&p_packed, &p_state_indices, &p_output, &v_pool_stride0, &v_pool_stride1, &v_pool_stride2, &v_pool_stride3, &v_num_heads, &v_total_values, &v_use_indices};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaError_t launch_status = cudaLaunchKernel(
      reinterpret_cast<const void*>(kernel_cake_gdn_cp_182ccae8c184a6945d27), grid, block, kargs, 0u, stream);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernel for kernel_cake_gdn_cp_182ccae8c184a6945d27 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_214b04dace936b52

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_214b04dace936b52::Run);
