#
# Copyright (c) 2026 by FlashInfer team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Generated by Cake's CuTe DSL backend.  Do not edit."""
from __future__ import annotations

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
from cutlass._mlir import ir as cutlass_ir
from cutlass._mlir.dialects import arith as cutlass_arith
from cutlass._mlir.dialects import llvm as cutlass_llvm
from cutlass._mlir.dialects import nvvm as cutlass_nvvm
from cutlass._mlir.dialects import cuda as cutlass_cuda
from cutlass.cute.runtime import make_fake_stream, make_fake_tensor
from cutlass.experimental import primitives as prims
from cutlass.experimental.primitives import nvvm_wrapper as prims_nvvm
from cutlass.utils import blackwell_helpers as cutlass_blackwell
from cutlass.utils.layout import LayoutEnum as CutlassLayout
from cutlass.utils import blockscaled_layout as cutlass_blockscaled
from cutlass.experimental.cuda.tensor_map import (
    TensorMap,
    TensorMapDataFormat,
    TensorMapFloatOOBFill,
    TensorMapL2Promotion,
    TensorMapSwizzle,
    create_tensor_map_tiled,
)
from cutlass._mlir.dialects.nvvm import CTAGroupKind as DialectCTAGroup
from cutlass._mlir.dialects.nvvm import TMALoadMode as DialectTMALoadMode

TMEM_NCOLS = 264
TMEM_ACC_OFFSET = 0
TMEM_SF_A_OFFSET = 256
TMEM_SF_B_OFFSET = 260
NUM_PAB_STAGES = 5
NUM_PACC_STAGES = 2
NUM_PTILE_STAGES = 2
NUM_PMETA_STAGES = 2
SMEM_A_OFF = 1024
SMEM_A_STAGE_BYTES = 16384
SMEM_A_STRIDE = 16384
SMEM_B_OFF = 82944
SMEM_B_STAGE_BYTES = 16384
SMEM_B_STRIDE = 16384
SMEM_SFA_OFF = 164864
SMEM_SFA_STAGE_BYTES = 512
SMEM_SFA_STRIDE = 512
SMEM_SFB_OFF = 167424
SMEM_SFB_STAGE_BYTES = 512
SMEM_SFB_STRIDE = 512
SMEM_SC_OFF = 169984
SMEM_SC_STAGE_BYTES = 34816
SMEM_SC_STRIDE = 34816
SMEM_SINFO_OFF = 204800
SMEM_SINFO_STAGE_BYTES = 40
SMEM_SINFO_STRIDE = 40
SMEM_SMETA_TOK_OFF = 204848
SMEM_SMETA_TOK_STAGE_BYTES = 1024
SMEM_SMETA_TOK_STRIDE = 1024
SMEM_SMETA_SCALE_OFF = 205872
SMEM_SMETA_SCALE_STAGE_BYTES = 1024
SMEM_SMETA_SCALE_STRIDE = 1024
SMEM_TOTAL = 206976
THREADS = 256
CAKE_TARGET_ARCH = 'sm_103a'
CAKE_SMEM_BYTES = 206976

def _cake_ldparam_b32(addr, ptx_type):
    return cutlass.Int32(cutlass_llvm.inline_asm(
        cutlass.Int32.mlir_type,
        [cutlass.Uint64(addr).ir_value()],
        '{ .reg .u64 %pa; cvta.to.param::entry.u64 %pa, $1; ld.param::entry.' + ptx_type + ' $0, [%pa]; }', '=r,l',
        has_side_effects=False, is_align_stack=False,
        asm_dialect=cutlass_llvm.AsmDialect.AD_ATT,
    ))

def _cake_ldparam_b64(addr, ptx_type):
    return cutlass.Uint64(cutlass_llvm.inline_asm(
        cutlass.Uint64.mlir_type,
        [cutlass.Uint64(addr).ir_value()],
        '{ .reg .u64 %pa; cvta.to.param::entry.u64 %pa, $1; ld.param::entry.' + ptx_type + ' $0, [%pa]; }', '=l,l',
        has_side_effects=False, is_align_stack=False,
        asm_dialect=cutlass_llvm.AsmDialect.AD_ATT,
    ))

@cute.kernel
def kernel_cake_mxfp4_situ_moe_4e29554c5f9311bd563c(A: cutlass.GridConstant[TensorMap], B: cutlass.GridConstant[TensorMap], SFA: cutlass.GridConstant[TensorMap], SFB: cutlass.GridConstant[TensorMap], out: cute.Pointer, tile_idx_to_expert_idx: cute.Pointer, tile_idx_to_mn_limit: cute.Pointer, num_non_exiting_tiles: cute.Pointer, alpha: cute.Pointer, permuted_idx_to_expanded_idx: cute.Pointer, token_final_scales: cute.Pointer, tile_idx_to_row_group: cute.Pointer, num_m_tiles: cutlass.Int32, num_n_tiles: cutlass.Int32, k_tiles: cutlass.Int32, out_cols: cutlass.Int32, top_k: cutlass.Int32, dbg: cute.Pointer):
    tid = cutlass.Int32(cute.arch.thread_idx()[0])
    warp = cutlass.Int32(cute.arch.warp_idx())
    lane = cutlass.Int32(cute.arch.lane_idx())
    bid = cutlass.Int32(cute.arch.block_idx()[0])
    num_bids = cutlass.Int32(cute.arch.grid_dim()[0])
    blockIdx = cute.arch.block_idx()
    gridDim = cute.arch.grid_dim()
    smem_raw = cute.arch.get_dyn_smem(cutlass.Uint8, alignment=1024)
    smem = smem_raw.toint()
    _flat_layout = cute.make_layout((2147483647,), stride=(1,))
    _out = cute.make_tensor(out, _flat_layout)
    _tile_idx_to_expert_idx = cute.make_tensor(tile_idx_to_expert_idx, _flat_layout)
    _tile_idx_to_mn_limit = cute.make_tensor(tile_idx_to_mn_limit, _flat_layout)
    _num_non_exiting_tiles = cute.make_tensor(num_non_exiting_tiles, _flat_layout)
    _alpha = cute.make_tensor(alpha, _flat_layout)
    _permuted_idx_to_expanded_idx = cute.make_tensor(permuted_idx_to_expanded_idx, _flat_layout)
    _token_final_scales = cute.make_tensor(token_final_scales, _flat_layout)
    _tile_idx_to_row_group = cute.make_tensor(tile_idx_to_row_group, _flat_layout)
    _dbg = cute.make_tensor(dbg, _flat_layout)
    a = cute.recast_ptr(smem_raw + 1024, swizzle_=cute.make_swizzle(4, 3, 3), dtype=cutlass.Uint8)
    _a = cute.make_tensor(a, _flat_layout)
    a_addr = smem + 1024
    b = cute.recast_ptr(smem_raw + 82944, swizzle_=cute.make_swizzle(4, 3, 3), dtype=cutlass.Uint8)
    _b = cute.make_tensor(b, _flat_layout)
    b_addr = smem + 82944
    sfa = cute.recast_ptr(smem_raw + 164864, dtype=cutlass.Uint8)
    _sfa = cute.make_tensor(sfa, _flat_layout)
    sfa_addr = smem + 164864
    sfb = cute.recast_ptr(smem_raw + 167424, dtype=cutlass.Uint8)
    _sfb = cute.make_tensor(sfb, _flat_layout)
    sfb_addr = smem + 167424
    sc = cute.recast_ptr(smem_raw + 169984, dtype=cutlass.Uint8)
    _sc = cute.make_tensor(sc, _flat_layout)
    sc_addr = smem + 169984
    sinfo = cute.recast_ptr(smem_raw + 204800, dtype=cutlass.Int32)
    _sinfo = cute.make_tensor(sinfo, _flat_layout)
    sinfo_addr = smem + 204800
    smeta_tok = cute.recast_ptr(smem_raw + 204848, dtype=cutlass.Int32)
    _smeta_tok = cute.make_tensor(smeta_tok, _flat_layout)
    smeta_tok_addr = smem + 204848
    smeta_scale = cute.recast_ptr(smem_raw + 205872, dtype=cutlass.Float32)
    _smeta_scale = cute.make_tensor(smeta_scale, _flat_layout)
    smeta_scale_addr = smem + 205872
    ab_full_addr = cute.recast_ptr(smem_raw, dtype=cutlass.Uint64)
    ab_free_addr = cute.recast_ptr(smem_raw + 40, dtype=cutlass.Uint64)
    acc_full_addr = cute.recast_ptr(smem_raw + 80, dtype=cutlass.Uint64)
    acc_free_addr = cute.recast_ptr(smem_raw + 96, dtype=cutlass.Uint64)
    tile_full_addr = cute.recast_ptr(smem_raw + 112, dtype=cutlass.Uint64)
    tile_free_addr = cute.recast_ptr(smem_raw + 128, dtype=cutlass.Uint64)
    meta_full_addr = cute.recast_ptr(smem_raw + 144, dtype=cutlass.Uint64)
    meta_free_addr = cute.recast_ptr(smem_raw + 160, dtype=cutlass.Uint64)
    if warp == 0:
        _mbarrier_init_run_0 = cute.recast_ptr(smem_raw, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_1 in cutlass.range(lane, 12, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_0 + _mbarrier_init_bar_1, 1)
        _mbarrier_init_run_2 = cute.recast_ptr(smem_raw + 96, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_3 in cutlass.range(lane, 2, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_2 + _mbarrier_init_bar_3, 128)
        _mbarrier_init_run_4 = cute.recast_ptr(smem_raw + 112, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_5 in cutlass.range(lane, 2, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_4 + _mbarrier_init_bar_5, 32)
        _mbarrier_init_run_6 = cute.recast_ptr(smem_raw + 128, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_7 in cutlass.range(lane, 2, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_6 + _mbarrier_init_bar_7, 224)
        _mbarrier_init_run_8 = cute.recast_ptr(smem_raw + 144, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_9 in cutlass.range(lane, 2, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_8 + _mbarrier_init_bar_9, 32)
        _mbarrier_init_run_10 = cute.recast_ptr(smem_raw + 160, dtype=cutlass.Uint64)
        for _mbarrier_init_bar_11 in cutlass.range(lane, 2, 32):
            cute.arch.mbarrier_init(_mbarrier_init_run_10 + _mbarrier_init_bar_11, 128)
    cute.arch.mbarrier_init_fence()
    cute.arch.sync_threads()
    _tmem_hold = cute.recast_ptr(smem_raw + 176, dtype=cutlass.Uint32)
    if warp == 0:
        cute.arch.alloc_tmem(512, _tmem_hold, is_two_cta=False, arch='sm_100')
    cute.arch.sync_threads()
    prims.tcgen05_fence('after_thread_sync')
    _tmem_base_ptr = cute.arch.retrieve_tmem_ptr(cutlass.Float32, 4, _tmem_hold)
    taddr = _tmem_base_ptr.toint()
    tmem_acc = cutlass.Int32(taddr)
    tmem_sf_a = cutlass.Int32(taddr + 256)
    tmem_sf_b = cutlass.Int32(taddr + 260)
    prims.griddepcontrol(kind=prims.GridDepAction.WAIT)
    if warp <= 3:
        acc_stage = cute.make_rmem_tensor((1,), cutlass.Uint32)
        tile_stage = cute.make_rmem_tensor((1,), cutlass.Uint32)
        meta_stage = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_tile_full = cute.make_rmem_tensor((1,), cutlass.Uint32)
        e_coord_m = cute.make_rmem_tensor((1,), cutlass.Int32)
        e_coord_n = cute.make_rmem_tensor((1,), cutlass.Int32)
        e_limit = cute.make_rmem_tensor((1,), cutlass.Int32)
        _phase_meta_full = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_acc_full = cute.make_rmem_tensor((1,), cutlass.Uint32)
        reduce_row = cute.make_rmem_tensor((1,), cutlass.Int32)
        epi_tidx = cutlass.Int32(tid)
        epi_warp = cutlass.Int32(warp)
        acc_stage[0] = cutlass.Uint32(0)
        tile_stage[0] = cutlass.Uint32(0)
        meta_stage[0] = cutlass.Uint32(0)
        info = cute.make_rmem_tensor((5,), cutlass.Int32)
        vals = cute.make_rmem_tensor((32,), cutlass.Float32)
        packed = cute.make_rmem_tensor((16,), cutlass.Uint32)
        _phase_tile_full[0] = cutlass.Uint32(0)
        while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage[0], _phase_tile_full[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
            pass
        info[0] = cutlass.Int32(_sinfo[(tile_stage[0] * 5)])
        info[1] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 1)])
        info[2] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 2)])
        info[3] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 3)])
        info[4] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 4)])
        e_coord_m[0] = cutlass.Int32(_sinfo[(tile_stage[0] * 5)])
        e_coord_n[0] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 1)])
        e_limit[0] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 4)])
        cute.arch.fence_proxy("async.shared", space="cta")
        cute.arch.mbarrier_arrive(tile_free_addr + tile_stage[0])
        _advanced_stage_12 = cutlass.Uint32(tile_stage[0] + 1)
        _stage_wrapped_13 = cutlass.Boolean(_advanced_stage_12 == 2)
        tile_stage[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_13, 0, _advanced_stage_12))
        _phase_tile_full[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_13, _phase_tile_full[0] ^ cutlass.Uint32(1), _phase_tile_full[0]))
        _phase_meta_full[0] = cutlass.Uint32(0)
        _phase_acc_full[0] = cutlass.Uint32(0)
        _loop_active_14 = cute.make_rmem_tensor((1,), cutlass.Boolean)
        _break_loop_counter_15 = cute.make_rmem_tensor((1,), cutlass.Int32)
        _break_loop_counter_15[0] = cutlass.Int32(cutlass.Int32(0))
        _loop_active_14[0] = cutlass.Boolean(_break_loop_counter_15[0] < cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)))
        while _loop_active_14[0]:
            _tile = cutlass.Int32(_break_loop_counter_15[0])
            if (info[3] == 0):
                _loop_active_14[0] = False
            if _loop_active_14[0]:
                row_base = cutlass.Int32((e_coord_m[0] * 128))
                col_base = cutlass.Int32((e_coord_n[0] * 128))
                prow = cutlass.Int32((row_base + epi_tidx))
                is_valid_row = cutlass.Int32(cutlass.Int32((prow < e_limit[0])))
                is_partial = cutlass.Int32(cutlass.Int32((e_limit[0] < (row_base + 128))))
                _min_0 = cutlass.min((out_cols - col_base), 128)
                valid_cols = cutlass.Int32(_min_0)
                while not prims.mbarrier_wait_parity(meta_full_addr + meta_stage[0], _phase_meta_full[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                meta_scale = cutlass.Float32(_smeta_scale[((meta_stage[0] * 128) + cutlass.Uint32(epi_tidx))])
                while not prims.mbarrier_wait_parity(acc_full_addr + acc_stage[0], _phase_acc_full[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                prims.tcgen05_fence('after_thread_sync')
                _tmem_load_0 = cute.make_rmem_tensor((32,), cutlass.Float32)
                _tmem_load_16_atom = cute.make_copy_atom(cute.nvgpu.tcgen05.Ld32x32bOp(cute.nvgpu.tcgen05.Repetition.x32), cutlass.Float32)
                _tmem_load_16_src = cute.make_tensor(cute.make_ptr(cutlass.Float32, cutlass.Uint32(((taddr + cutlass.Uint32(((epi_warp * 32) << 16))) + (acc_stage[0] * 128))), mem_space=cutlass.AddressSpace.tmem, assumed_align=1), cute.make_layout((32,), stride=(1,)))
                _tmem_load_16_dst = cute.make_tensor(_tmem_load_0.iterator + 0, cute.make_layout((32,), stride=(1,)))
                cute.copy(_tmem_load_16_atom, _tmem_load_16_src, _tmem_load_16_dst)
                cute.arch.fence_view_async_tmem_load()
                vals[0] = cutlass.Float32((_tmem_load_0[0] * meta_scale))
                vals[1] = cutlass.Float32((_tmem_load_0[1] * meta_scale))
                vals[2] = cutlass.Float32((_tmem_load_0[2] * meta_scale))
                vals[3] = cutlass.Float32((_tmem_load_0[3] * meta_scale))
                vals[4] = cutlass.Float32((_tmem_load_0[4] * meta_scale))
                vals[5] = cutlass.Float32((_tmem_load_0[5] * meta_scale))
                vals[6] = cutlass.Float32((_tmem_load_0[6] * meta_scale))
                vals[7] = cutlass.Float32((_tmem_load_0[7] * meta_scale))
                vals[8] = cutlass.Float32((_tmem_load_0[8] * meta_scale))
                vals[9] = cutlass.Float32((_tmem_load_0[9] * meta_scale))
                vals[10] = cutlass.Float32((_tmem_load_0[10] * meta_scale))
                vals[11] = cutlass.Float32((_tmem_load_0[11] * meta_scale))
                vals[12] = cutlass.Float32((_tmem_load_0[12] * meta_scale))
                vals[13] = cutlass.Float32((_tmem_load_0[13] * meta_scale))
                vals[14] = cutlass.Float32((_tmem_load_0[14] * meta_scale))
                vals[15] = cutlass.Float32((_tmem_load_0[15] * meta_scale))
                vals[16] = cutlass.Float32((_tmem_load_0[16] * meta_scale))
                vals[17] = cutlass.Float32((_tmem_load_0[17] * meta_scale))
                vals[18] = cutlass.Float32((_tmem_load_0[18] * meta_scale))
                vals[19] = cutlass.Float32((_tmem_load_0[19] * meta_scale))
                vals[20] = cutlass.Float32((_tmem_load_0[20] * meta_scale))
                vals[21] = cutlass.Float32((_tmem_load_0[21] * meta_scale))
                vals[22] = cutlass.Float32((_tmem_load_0[22] * meta_scale))
                vals[23] = cutlass.Float32((_tmem_load_0[23] * meta_scale))
                vals[24] = cutlass.Float32((_tmem_load_0[24] * meta_scale))
                vals[25] = cutlass.Float32((_tmem_load_0[25] * meta_scale))
                vals[26] = cutlass.Float32((_tmem_load_0[26] * meta_scale))
                vals[27] = cutlass.Float32((_tmem_load_0[27] * meta_scale))
                vals[28] = cutlass.Float32((_tmem_load_0[28] * meta_scale))
                vals[29] = cutlass.Float32((_tmem_load_0[29] * meta_scale))
                vals[30] = cutlass.Float32((_tmem_load_0[30] * meta_scale))
                vals[31] = cutlass.Float32((_tmem_load_0[31] * meta_scale))
                _bf16_pack_17 = prims.cvt_packfloat_f32(vals[1], vals[0], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[0] = cutlass.Uint32(_bf16_pack_17)
                _bf16_pack_18 = prims.cvt_packfloat_f32(vals[3], vals[2], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[1] = cutlass.Uint32(_bf16_pack_18)
                _bf16_pack_19 = prims.cvt_packfloat_f32(vals[5], vals[4], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[2] = cutlass.Uint32(_bf16_pack_19)
                _bf16_pack_20 = prims.cvt_packfloat_f32(vals[7], vals[6], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[3] = cutlass.Uint32(_bf16_pack_20)
                _bf16_pack_21 = prims.cvt_packfloat_f32(vals[9], vals[8], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[4] = cutlass.Uint32(_bf16_pack_21)
                _bf16_pack_22 = prims.cvt_packfloat_f32(vals[11], vals[10], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[5] = cutlass.Uint32(_bf16_pack_22)
                _bf16_pack_23 = prims.cvt_packfloat_f32(vals[13], vals[12], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[6] = cutlass.Uint32(_bf16_pack_23)
                _bf16_pack_24 = prims.cvt_packfloat_f32(vals[15], vals[14], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[7] = cutlass.Uint32(_bf16_pack_24)
                _bf16_pack_25 = prims.cvt_packfloat_f32(vals[17], vals[16], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[8] = cutlass.Uint32(_bf16_pack_25)
                _bf16_pack_26 = prims.cvt_packfloat_f32(vals[19], vals[18], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[9] = cutlass.Uint32(_bf16_pack_26)
                _bf16_pack_27 = prims.cvt_packfloat_f32(vals[21], vals[20], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[10] = cutlass.Uint32(_bf16_pack_27)
                _bf16_pack_28 = prims.cvt_packfloat_f32(vals[23], vals[22], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[11] = cutlass.Uint32(_bf16_pack_28)
                _bf16_pack_29 = prims.cvt_packfloat_f32(vals[25], vals[24], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[12] = cutlass.Uint32(_bf16_pack_29)
                _bf16_pack_30 = prims.cvt_packfloat_f32(vals[27], vals[26], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[13] = cutlass.Uint32(_bf16_pack_30)
                _bf16_pack_31 = prims.cvt_packfloat_f32(vals[29], vals[28], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[14] = cutlass.Uint32(_bf16_pack_31)
                _bf16_pack_32 = prims.cvt_packfloat_f32(vals[31], vals[30], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[15] = cutlass.Uint32(_bf16_pack_32)
                if (is_valid_row != 0):
                    _smem_store_vec_33 = cutlass.Vector.from_elements([cutlass.Uint32(packed[0]), cutlass.Uint32(packed[1]), cutlass.Uint32(packed[2]), cutlass.Uint32(packed[3])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_33.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32((epi_tidx * 272)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_34 = cutlass.Vector.from_elements([cutlass.Uint32(packed[4]), cutlass.Uint32(packed[5]), cutlass.Uint32(packed[6]), cutlass.Uint32(packed[7])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_34.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 16)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_35 = cutlass.Vector.from_elements([cutlass.Uint32(packed[8]), cutlass.Uint32(packed[9]), cutlass.Uint32(packed[10]), cutlass.Uint32(packed[11])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_35.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 32)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_36 = cutlass.Vector.from_elements([cutlass.Uint32(packed[12]), cutlass.Uint32(packed[13]), cutlass.Uint32(packed[14]), cutlass.Uint32(packed[15])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_36.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 48)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                _tmem_load_1 = cute.make_rmem_tensor((32,), cutlass.Float32)
                _tmem_load_37_atom = cute.make_copy_atom(cute.nvgpu.tcgen05.Ld32x32bOp(cute.nvgpu.tcgen05.Repetition.x32), cutlass.Float32)
                _tmem_load_37_src = cute.make_tensor(cute.make_ptr(cutlass.Float32, cutlass.Uint32((((taddr + cutlass.Uint32(((epi_warp * 32) << 16))) + (acc_stage[0] * 128)) + 32)), mem_space=cutlass.AddressSpace.tmem, assumed_align=1), cute.make_layout((32,), stride=(1,)))
                _tmem_load_37_dst = cute.make_tensor(_tmem_load_1.iterator + 0, cute.make_layout((32,), stride=(1,)))
                cute.copy(_tmem_load_37_atom, _tmem_load_37_src, _tmem_load_37_dst)
                cute.arch.fence_view_async_tmem_load()
                vals[0] = cutlass.Float32((_tmem_load_1[0] * meta_scale))
                vals[1] = cutlass.Float32((_tmem_load_1[1] * meta_scale))
                vals[2] = cutlass.Float32((_tmem_load_1[2] * meta_scale))
                vals[3] = cutlass.Float32((_tmem_load_1[3] * meta_scale))
                vals[4] = cutlass.Float32((_tmem_load_1[4] * meta_scale))
                vals[5] = cutlass.Float32((_tmem_load_1[5] * meta_scale))
                vals[6] = cutlass.Float32((_tmem_load_1[6] * meta_scale))
                vals[7] = cutlass.Float32((_tmem_load_1[7] * meta_scale))
                vals[8] = cutlass.Float32((_tmem_load_1[8] * meta_scale))
                vals[9] = cutlass.Float32((_tmem_load_1[9] * meta_scale))
                vals[10] = cutlass.Float32((_tmem_load_1[10] * meta_scale))
                vals[11] = cutlass.Float32((_tmem_load_1[11] * meta_scale))
                vals[12] = cutlass.Float32((_tmem_load_1[12] * meta_scale))
                vals[13] = cutlass.Float32((_tmem_load_1[13] * meta_scale))
                vals[14] = cutlass.Float32((_tmem_load_1[14] * meta_scale))
                vals[15] = cutlass.Float32((_tmem_load_1[15] * meta_scale))
                vals[16] = cutlass.Float32((_tmem_load_1[16] * meta_scale))
                vals[17] = cutlass.Float32((_tmem_load_1[17] * meta_scale))
                vals[18] = cutlass.Float32((_tmem_load_1[18] * meta_scale))
                vals[19] = cutlass.Float32((_tmem_load_1[19] * meta_scale))
                vals[20] = cutlass.Float32((_tmem_load_1[20] * meta_scale))
                vals[21] = cutlass.Float32((_tmem_load_1[21] * meta_scale))
                vals[22] = cutlass.Float32((_tmem_load_1[22] * meta_scale))
                vals[23] = cutlass.Float32((_tmem_load_1[23] * meta_scale))
                vals[24] = cutlass.Float32((_tmem_load_1[24] * meta_scale))
                vals[25] = cutlass.Float32((_tmem_load_1[25] * meta_scale))
                vals[26] = cutlass.Float32((_tmem_load_1[26] * meta_scale))
                vals[27] = cutlass.Float32((_tmem_load_1[27] * meta_scale))
                vals[28] = cutlass.Float32((_tmem_load_1[28] * meta_scale))
                vals[29] = cutlass.Float32((_tmem_load_1[29] * meta_scale))
                vals[30] = cutlass.Float32((_tmem_load_1[30] * meta_scale))
                vals[31] = cutlass.Float32((_tmem_load_1[31] * meta_scale))
                _bf16_pack_38 = prims.cvt_packfloat_f32(vals[1], vals[0], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[0] = cutlass.Uint32(_bf16_pack_38)
                _bf16_pack_39 = prims.cvt_packfloat_f32(vals[3], vals[2], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[1] = cutlass.Uint32(_bf16_pack_39)
                _bf16_pack_40 = prims.cvt_packfloat_f32(vals[5], vals[4], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[2] = cutlass.Uint32(_bf16_pack_40)
                _bf16_pack_41 = prims.cvt_packfloat_f32(vals[7], vals[6], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[3] = cutlass.Uint32(_bf16_pack_41)
                _bf16_pack_42 = prims.cvt_packfloat_f32(vals[9], vals[8], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[4] = cutlass.Uint32(_bf16_pack_42)
                _bf16_pack_43 = prims.cvt_packfloat_f32(vals[11], vals[10], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[5] = cutlass.Uint32(_bf16_pack_43)
                _bf16_pack_44 = prims.cvt_packfloat_f32(vals[13], vals[12], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[6] = cutlass.Uint32(_bf16_pack_44)
                _bf16_pack_45 = prims.cvt_packfloat_f32(vals[15], vals[14], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[7] = cutlass.Uint32(_bf16_pack_45)
                _bf16_pack_46 = prims.cvt_packfloat_f32(vals[17], vals[16], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[8] = cutlass.Uint32(_bf16_pack_46)
                _bf16_pack_47 = prims.cvt_packfloat_f32(vals[19], vals[18], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[9] = cutlass.Uint32(_bf16_pack_47)
                _bf16_pack_48 = prims.cvt_packfloat_f32(vals[21], vals[20], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[10] = cutlass.Uint32(_bf16_pack_48)
                _bf16_pack_49 = prims.cvt_packfloat_f32(vals[23], vals[22], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[11] = cutlass.Uint32(_bf16_pack_49)
                _bf16_pack_50 = prims.cvt_packfloat_f32(vals[25], vals[24], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[12] = cutlass.Uint32(_bf16_pack_50)
                _bf16_pack_51 = prims.cvt_packfloat_f32(vals[27], vals[26], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[13] = cutlass.Uint32(_bf16_pack_51)
                _bf16_pack_52 = prims.cvt_packfloat_f32(vals[29], vals[28], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[14] = cutlass.Uint32(_bf16_pack_52)
                _bf16_pack_53 = prims.cvt_packfloat_f32(vals[31], vals[30], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[15] = cutlass.Uint32(_bf16_pack_53)
                if (is_valid_row != 0):
                    _smem_store_vec_54 = cutlass.Vector.from_elements([cutlass.Uint32(packed[0]), cutlass.Uint32(packed[1]), cutlass.Uint32(packed[2]), cutlass.Uint32(packed[3])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_54.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 64)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_55 = cutlass.Vector.from_elements([cutlass.Uint32(packed[4]), cutlass.Uint32(packed[5]), cutlass.Uint32(packed[6]), cutlass.Uint32(packed[7])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_55.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 80)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_56 = cutlass.Vector.from_elements([cutlass.Uint32(packed[8]), cutlass.Uint32(packed[9]), cutlass.Uint32(packed[10]), cutlass.Uint32(packed[11])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_56.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 96)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_57 = cutlass.Vector.from_elements([cutlass.Uint32(packed[12]), cutlass.Uint32(packed[13]), cutlass.Uint32(packed[14]), cutlass.Uint32(packed[15])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_57.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 112)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                _tmem_load_2 = cute.make_rmem_tensor((32,), cutlass.Float32)
                _tmem_load_58_atom = cute.make_copy_atom(cute.nvgpu.tcgen05.Ld32x32bOp(cute.nvgpu.tcgen05.Repetition.x32), cutlass.Float32)
                _tmem_load_58_src = cute.make_tensor(cute.make_ptr(cutlass.Float32, cutlass.Uint32((((taddr + cutlass.Uint32(((epi_warp * 32) << 16))) + (acc_stage[0] * 128)) + 64)), mem_space=cutlass.AddressSpace.tmem, assumed_align=1), cute.make_layout((32,), stride=(1,)))
                _tmem_load_58_dst = cute.make_tensor(_tmem_load_2.iterator + 0, cute.make_layout((32,), stride=(1,)))
                cute.copy(_tmem_load_58_atom, _tmem_load_58_src, _tmem_load_58_dst)
                cute.arch.fence_view_async_tmem_load()
                vals[0] = cutlass.Float32((_tmem_load_2[0] * meta_scale))
                vals[1] = cutlass.Float32((_tmem_load_2[1] * meta_scale))
                vals[2] = cutlass.Float32((_tmem_load_2[2] * meta_scale))
                vals[3] = cutlass.Float32((_tmem_load_2[3] * meta_scale))
                vals[4] = cutlass.Float32((_tmem_load_2[4] * meta_scale))
                vals[5] = cutlass.Float32((_tmem_load_2[5] * meta_scale))
                vals[6] = cutlass.Float32((_tmem_load_2[6] * meta_scale))
                vals[7] = cutlass.Float32((_tmem_load_2[7] * meta_scale))
                vals[8] = cutlass.Float32((_tmem_load_2[8] * meta_scale))
                vals[9] = cutlass.Float32((_tmem_load_2[9] * meta_scale))
                vals[10] = cutlass.Float32((_tmem_load_2[10] * meta_scale))
                vals[11] = cutlass.Float32((_tmem_load_2[11] * meta_scale))
                vals[12] = cutlass.Float32((_tmem_load_2[12] * meta_scale))
                vals[13] = cutlass.Float32((_tmem_load_2[13] * meta_scale))
                vals[14] = cutlass.Float32((_tmem_load_2[14] * meta_scale))
                vals[15] = cutlass.Float32((_tmem_load_2[15] * meta_scale))
                vals[16] = cutlass.Float32((_tmem_load_2[16] * meta_scale))
                vals[17] = cutlass.Float32((_tmem_load_2[17] * meta_scale))
                vals[18] = cutlass.Float32((_tmem_load_2[18] * meta_scale))
                vals[19] = cutlass.Float32((_tmem_load_2[19] * meta_scale))
                vals[20] = cutlass.Float32((_tmem_load_2[20] * meta_scale))
                vals[21] = cutlass.Float32((_tmem_load_2[21] * meta_scale))
                vals[22] = cutlass.Float32((_tmem_load_2[22] * meta_scale))
                vals[23] = cutlass.Float32((_tmem_load_2[23] * meta_scale))
                vals[24] = cutlass.Float32((_tmem_load_2[24] * meta_scale))
                vals[25] = cutlass.Float32((_tmem_load_2[25] * meta_scale))
                vals[26] = cutlass.Float32((_tmem_load_2[26] * meta_scale))
                vals[27] = cutlass.Float32((_tmem_load_2[27] * meta_scale))
                vals[28] = cutlass.Float32((_tmem_load_2[28] * meta_scale))
                vals[29] = cutlass.Float32((_tmem_load_2[29] * meta_scale))
                vals[30] = cutlass.Float32((_tmem_load_2[30] * meta_scale))
                vals[31] = cutlass.Float32((_tmem_load_2[31] * meta_scale))
                _bf16_pack_59 = prims.cvt_packfloat_f32(vals[1], vals[0], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[0] = cutlass.Uint32(_bf16_pack_59)
                _bf16_pack_60 = prims.cvt_packfloat_f32(vals[3], vals[2], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[1] = cutlass.Uint32(_bf16_pack_60)
                _bf16_pack_61 = prims.cvt_packfloat_f32(vals[5], vals[4], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[2] = cutlass.Uint32(_bf16_pack_61)
                _bf16_pack_62 = prims.cvt_packfloat_f32(vals[7], vals[6], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[3] = cutlass.Uint32(_bf16_pack_62)
                _bf16_pack_63 = prims.cvt_packfloat_f32(vals[9], vals[8], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[4] = cutlass.Uint32(_bf16_pack_63)
                _bf16_pack_64 = prims.cvt_packfloat_f32(vals[11], vals[10], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[5] = cutlass.Uint32(_bf16_pack_64)
                _bf16_pack_65 = prims.cvt_packfloat_f32(vals[13], vals[12], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[6] = cutlass.Uint32(_bf16_pack_65)
                _bf16_pack_66 = prims.cvt_packfloat_f32(vals[15], vals[14], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[7] = cutlass.Uint32(_bf16_pack_66)
                _bf16_pack_67 = prims.cvt_packfloat_f32(vals[17], vals[16], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[8] = cutlass.Uint32(_bf16_pack_67)
                _bf16_pack_68 = prims.cvt_packfloat_f32(vals[19], vals[18], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[9] = cutlass.Uint32(_bf16_pack_68)
                _bf16_pack_69 = prims.cvt_packfloat_f32(vals[21], vals[20], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[10] = cutlass.Uint32(_bf16_pack_69)
                _bf16_pack_70 = prims.cvt_packfloat_f32(vals[23], vals[22], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[11] = cutlass.Uint32(_bf16_pack_70)
                _bf16_pack_71 = prims.cvt_packfloat_f32(vals[25], vals[24], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[12] = cutlass.Uint32(_bf16_pack_71)
                _bf16_pack_72 = prims.cvt_packfloat_f32(vals[27], vals[26], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[13] = cutlass.Uint32(_bf16_pack_72)
                _bf16_pack_73 = prims.cvt_packfloat_f32(vals[29], vals[28], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[14] = cutlass.Uint32(_bf16_pack_73)
                _bf16_pack_74 = prims.cvt_packfloat_f32(vals[31], vals[30], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[15] = cutlass.Uint32(_bf16_pack_74)
                if (is_valid_row != 0):
                    _smem_store_vec_75 = cutlass.Vector.from_elements([cutlass.Uint32(packed[0]), cutlass.Uint32(packed[1]), cutlass.Uint32(packed[2]), cutlass.Uint32(packed[3])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_75.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 128)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_76 = cutlass.Vector.from_elements([cutlass.Uint32(packed[4]), cutlass.Uint32(packed[5]), cutlass.Uint32(packed[6]), cutlass.Uint32(packed[7])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_76.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 144)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_77 = cutlass.Vector.from_elements([cutlass.Uint32(packed[8]), cutlass.Uint32(packed[9]), cutlass.Uint32(packed[10]), cutlass.Uint32(packed[11])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_77.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 160)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_78 = cutlass.Vector.from_elements([cutlass.Uint32(packed[12]), cutlass.Uint32(packed[13]), cutlass.Uint32(packed[14]), cutlass.Uint32(packed[15])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_78.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 176)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                _tmem_load_3 = cute.make_rmem_tensor((32,), cutlass.Float32)
                _tmem_load_79_atom = cute.make_copy_atom(cute.nvgpu.tcgen05.Ld32x32bOp(cute.nvgpu.tcgen05.Repetition.x32), cutlass.Float32)
                _tmem_load_79_src = cute.make_tensor(cute.make_ptr(cutlass.Float32, cutlass.Uint32((((taddr + cutlass.Uint32(((epi_warp * 32) << 16))) + (acc_stage[0] * 128)) + 96)), mem_space=cutlass.AddressSpace.tmem, assumed_align=1), cute.make_layout((32,), stride=(1,)))
                _tmem_load_79_dst = cute.make_tensor(_tmem_load_3.iterator + 0, cute.make_layout((32,), stride=(1,)))
                cute.copy(_tmem_load_79_atom, _tmem_load_79_src, _tmem_load_79_dst)
                cute.arch.fence_view_async_tmem_load()
                vals[0] = cutlass.Float32((_tmem_load_3[0] * meta_scale))
                vals[1] = cutlass.Float32((_tmem_load_3[1] * meta_scale))
                vals[2] = cutlass.Float32((_tmem_load_3[2] * meta_scale))
                vals[3] = cutlass.Float32((_tmem_load_3[3] * meta_scale))
                vals[4] = cutlass.Float32((_tmem_load_3[4] * meta_scale))
                vals[5] = cutlass.Float32((_tmem_load_3[5] * meta_scale))
                vals[6] = cutlass.Float32((_tmem_load_3[6] * meta_scale))
                vals[7] = cutlass.Float32((_tmem_load_3[7] * meta_scale))
                vals[8] = cutlass.Float32((_tmem_load_3[8] * meta_scale))
                vals[9] = cutlass.Float32((_tmem_load_3[9] * meta_scale))
                vals[10] = cutlass.Float32((_tmem_load_3[10] * meta_scale))
                vals[11] = cutlass.Float32((_tmem_load_3[11] * meta_scale))
                vals[12] = cutlass.Float32((_tmem_load_3[12] * meta_scale))
                vals[13] = cutlass.Float32((_tmem_load_3[13] * meta_scale))
                vals[14] = cutlass.Float32((_tmem_load_3[14] * meta_scale))
                vals[15] = cutlass.Float32((_tmem_load_3[15] * meta_scale))
                vals[16] = cutlass.Float32((_tmem_load_3[16] * meta_scale))
                vals[17] = cutlass.Float32((_tmem_load_3[17] * meta_scale))
                vals[18] = cutlass.Float32((_tmem_load_3[18] * meta_scale))
                vals[19] = cutlass.Float32((_tmem_load_3[19] * meta_scale))
                vals[20] = cutlass.Float32((_tmem_load_3[20] * meta_scale))
                vals[21] = cutlass.Float32((_tmem_load_3[21] * meta_scale))
                vals[22] = cutlass.Float32((_tmem_load_3[22] * meta_scale))
                vals[23] = cutlass.Float32((_tmem_load_3[23] * meta_scale))
                vals[24] = cutlass.Float32((_tmem_load_3[24] * meta_scale))
                vals[25] = cutlass.Float32((_tmem_load_3[25] * meta_scale))
                vals[26] = cutlass.Float32((_tmem_load_3[26] * meta_scale))
                vals[27] = cutlass.Float32((_tmem_load_3[27] * meta_scale))
                vals[28] = cutlass.Float32((_tmem_load_3[28] * meta_scale))
                vals[29] = cutlass.Float32((_tmem_load_3[29] * meta_scale))
                vals[30] = cutlass.Float32((_tmem_load_3[30] * meta_scale))
                vals[31] = cutlass.Float32((_tmem_load_3[31] * meta_scale))
                _bf16_pack_80 = prims.cvt_packfloat_f32(vals[1], vals[0], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[0] = cutlass.Uint32(_bf16_pack_80)
                _bf16_pack_81 = prims.cvt_packfloat_f32(vals[3], vals[2], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[1] = cutlass.Uint32(_bf16_pack_81)
                _bf16_pack_82 = prims.cvt_packfloat_f32(vals[5], vals[4], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[2] = cutlass.Uint32(_bf16_pack_82)
                _bf16_pack_83 = prims.cvt_packfloat_f32(vals[7], vals[6], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[3] = cutlass.Uint32(_bf16_pack_83)
                _bf16_pack_84 = prims.cvt_packfloat_f32(vals[9], vals[8], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[4] = cutlass.Uint32(_bf16_pack_84)
                _bf16_pack_85 = prims.cvt_packfloat_f32(vals[11], vals[10], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[5] = cutlass.Uint32(_bf16_pack_85)
                _bf16_pack_86 = prims.cvt_packfloat_f32(vals[13], vals[12], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[6] = cutlass.Uint32(_bf16_pack_86)
                _bf16_pack_87 = prims.cvt_packfloat_f32(vals[15], vals[14], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[7] = cutlass.Uint32(_bf16_pack_87)
                _bf16_pack_88 = prims.cvt_packfloat_f32(vals[17], vals[16], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[8] = cutlass.Uint32(_bf16_pack_88)
                _bf16_pack_89 = prims.cvt_packfloat_f32(vals[19], vals[18], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[9] = cutlass.Uint32(_bf16_pack_89)
                _bf16_pack_90 = prims.cvt_packfloat_f32(vals[21], vals[20], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[10] = cutlass.Uint32(_bf16_pack_90)
                _bf16_pack_91 = prims.cvt_packfloat_f32(vals[23], vals[22], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[11] = cutlass.Uint32(_bf16_pack_91)
                _bf16_pack_92 = prims.cvt_packfloat_f32(vals[25], vals[24], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[12] = cutlass.Uint32(_bf16_pack_92)
                _bf16_pack_93 = prims.cvt_packfloat_f32(vals[27], vals[26], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[13] = cutlass.Uint32(_bf16_pack_93)
                _bf16_pack_94 = prims.cvt_packfloat_f32(vals[29], vals[28], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[14] = cutlass.Uint32(_bf16_pack_94)
                _bf16_pack_95 = prims.cvt_packfloat_f32(vals[31], vals[30], 0, prims.CVTPackFloat.BF16X2, rnd=prims.FPRoundingMode.RN)
                packed[15] = cutlass.Uint32(_bf16_pack_95)
                if (is_valid_row != 0):
                    _smem_store_vec_96 = cutlass.Vector.from_elements([cutlass.Uint32(packed[0]), cutlass.Uint32(packed[1]), cutlass.Uint32(packed[2]), cutlass.Uint32(packed[3])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_96.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 192)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_97 = cutlass.Vector.from_elements([cutlass.Uint32(packed[4]), cutlass.Uint32(packed[5]), cutlass.Uint32(packed[6]), cutlass.Uint32(packed[7])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_97.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 208)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_98 = cutlass.Vector.from_elements([cutlass.Uint32(packed[8]), cutlass.Uint32(packed[9]), cutlass.Uint32(packed[10]), cutlass.Uint32(packed[11])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_98.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 224)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                    _smem_store_vec_99 = cutlass.Vector.from_elements([cutlass.Uint32(packed[12]), cutlass.Uint32(packed[13]), cutlass.Uint32(packed[14]), cutlass.Uint32(packed[15])], cutlass.Uint32)
                    prims.store_ext(_smem_store_vec_99.ir_value(), cute.make_ptr(cutlass.Uint32, cutlass.Uint32((sc_addr + cutlass.Uint32(((epi_tidx * 272) + 240)))), mem_space=cute.AddressSpace.smem, assumed_align=16))
                cute.arch.fence_proxy("async.shared", space="cta")
                prims.tcgen05_fence('before_thread_sync')
                cute.arch.mbarrier_arrive(acc_free_addr + acc_stage[0])
                _advanced_stage_100 = cutlass.Uint32(acc_stage[0] + 1)
                _stage_wrapped_101 = cutlass.Boolean(_advanced_stage_100 == 2)
                acc_stage[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_101, 0, _advanced_stage_100))
                _phase_acc_full[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_101, _phase_acc_full[0] ^ cutlass.Uint32(1), _phase_acc_full[0]))
                reduce_row[0] = cutlass.Int32(epi_tidx)
                if (is_partial != 0):
                    prims.barrier_cta_sync(2, thread_count=128)
                    reduce_row[0] = cutlass.Int32((((epi_tidx % 32) * 4) + cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(epi_tidx).ir_value(), cutlass.Int32(32).ir_value()))))
                reduce_ok = cutlass.Int32(cutlass.Int32((e_limit[0] > (row_base + reduce_row[0]))))
                reduce_tok = cutlass.Int32(_smeta_tok[((meta_stage[0] * 128) + cutlass.Uint32(reduce_row[0]))])
                if (reduce_ok != 0):
                    if (valid_cols > 0):
                        prims.cp_reduce_async_bulk_global_shared_cta(
                            out + ((reduce_tok * out_cols) + col_base),
                            cute.make_ptr(cutlass.Uint8, cutlass.Uint32((sc_addr + cutlass.Uint32((reduce_row[0] * 272)))), mem_space=cute.AddressSpace.smem, assumed_align=16),
                            cutlass.Int32((valid_cols * 2)),
                            op=prims.CpReduceOp.ADD,
                            type=prims.CpReduceType.BF16,
                            noftz=True,
                        )
                cute.arch.cp_async_bulk_commit_group()
                cute.arch.cp_async_bulk_wait_group(0, read=True)
                prims.barrier_cta_sync(2, thread_count=128)
                cute.arch.mbarrier_arrive(meta_free_addr + meta_stage[0])
                _advanced_stage_102 = cutlass.Uint32(meta_stage[0] + 1)
                _stage_wrapped_103 = cutlass.Boolean(_advanced_stage_102 == 2)
                meta_stage[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_103, 0, _advanced_stage_102))
                _phase_meta_full[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_103, _phase_meta_full[0] ^ cutlass.Uint32(1), _phase_meta_full[0]))
                while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage[0], _phase_tile_full[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                info[0] = cutlass.Int32(_sinfo[(tile_stage[0] * 5)])
                info[1] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 1)])
                info[2] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 2)])
                info[3] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 3)])
                info[4] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 4)])
                e_coord_m[0] = cutlass.Int32(_sinfo[(tile_stage[0] * 5)])
                e_coord_n[0] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 1)])
                e_limit[0] = cutlass.Int32(_sinfo[((tile_stage[0] * 5) + 4)])
                cute.arch.fence_proxy("async.shared", space="cta")
                cute.arch.mbarrier_arrive(tile_free_addr + tile_stage[0])
                _advanced_stage_104 = cutlass.Uint32(tile_stage[0] + 1)
                _stage_wrapped_105 = cutlass.Boolean(_advanced_stage_104 == 2)
                tile_stage[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_105, 0, _advanced_stage_104))
                _phase_tile_full[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_105, _phase_tile_full[0] ^ cutlass.Uint32(1), _phase_tile_full[0]))
            _break_loop_counter_15[0] += cutlass.Int32(1)
            if _break_loop_counter_15[0] >= cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)):
                _loop_active_14[0] = False
        cute.arch.cp_async_bulk_wait_group(0, read=True)
    elif warp == 4:
        sa = cute.make_rmem_tensor((1,), cutlass.Uint32)
        acc_stage_1 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        tile_stage_1 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        pha = cute.make_rmem_tensor((1,), cutlass.Uint32)
        ab_tok = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_tile_full_1 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_acc_free = cute.make_rmem_tensor((1,), cutlass.Uint32)
        sa[0] = cutlass.Uint32(0)
        acc_stage_1[0] = cutlass.Uint32(0)
        tile_stage_1[0] = cutlass.Uint32(0)
        pha[0] = cutlass.Uint32(0)
        ab_tok[0] = cutlass.Uint32(1)
        info_1 = cute.make_rmem_tensor((5,), cutlass.Int32)
        _phase_tile_full_1[0] = cutlass.Uint32(0)
        while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_1[0], _phase_tile_full_1[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
            pass
        info_1[0] = cutlass.Int32(_sinfo[(tile_stage_1[0] * 5)])
        info_1[1] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 1)])
        info_1[2] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 2)])
        info_1[3] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 3)])
        info_1[4] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 4)])
        cute.arch.fence_proxy("async.shared", space="cta")
        cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_1[0])
        _advanced_stage_106 = cutlass.Uint32(tile_stage_1[0] + 1)
        _stage_wrapped_107 = cutlass.Boolean(_advanced_stage_106 == 2)
        tile_stage_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_107, 0, _advanced_stage_106))
        _phase_tile_full_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_107, _phase_tile_full_1[0] ^ cutlass.Uint32(1), _phase_tile_full_1[0]))
        _phase_acc_free[0] = cutlass.Uint32(1)
        _loop_active_108 = cute.make_rmem_tensor((1,), cutlass.Boolean)
        _break_loop_counter_109 = cute.make_rmem_tensor((1,), cutlass.Int32)
        _break_loop_counter_109[0] = cutlass.Int32(cutlass.Int32(0))
        _loop_active_108[0] = cutlass.Boolean(_break_loop_counter_109[0] < cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)))
        while _loop_active_108[0]:
            _tile_1 = cutlass.Int32(_break_loop_counter_109[0])
            if (info_1[3] == 0):
                _loop_active_108[0] = False
            if _loop_active_108[0]:
                sfb_shift = 0
                _mbar_token_0 = cutlass.Uint32(prims.mbarrier_wait_parity(ab_full_addr + sa[0], pha[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE))
                ab_tok[0] = cutlass.Uint32(_mbar_token_0)
                while not prims.mbarrier_wait_parity(acc_free_addr + acc_stage_1[0], _phase_acc_free[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                prims.tcgen05_fence('after_thread_sync')
                if ab_tok[0] == 0:
                    while not prims.mbarrier_wait_parity(ab_full_addr + sa[0], pha[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                        pass
                _scale_copy_110_src_0 = cutlass.Uint64(cutlass.Uint32((sfa_addr + (sa[0] * 512))))
                _scale_copy_110_desc_0 = ((_scale_copy_110_src_0 >> 4) & cutlass.Uint64(0x3FFF)) | cutlass.Uint64(0x400800000000)
                _scale_copy_110_dst_0 = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_a), cutlass.Int32)
                with cute.arch.elect_one():
                    prims.tcgen05_cp(prims.Tcgen05CpShape.SHAPE_32X128B, _scale_copy_110_dst_0, _scale_copy_110_desc_0, group=prims.CTAGroup.CTA_1, multicast=prims.Tcgen05CpMulticast.WARPX4)
                _scale_copy_111_src_0 = cutlass.Uint64(cutlass.Uint32((sfb_addr + (sa[0] * 512))))
                _scale_copy_111_desc_0 = ((_scale_copy_111_src_0 >> 4) & cutlass.Uint64(0x3FFF)) | cutlass.Uint64(0x400800000000)
                _scale_copy_111_dst_0 = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_b), cutlass.Int32)
                with cute.arch.elect_one():
                    prims.tcgen05_cp(prims.Tcgen05CpShape.SHAPE_32X128B, _scale_copy_111_dst_0, _scale_copy_111_desc_0, group=prims.CTAGroup.CTA_1, multicast=prims.Tcgen05CpMulticast.WARPX4)
                _mma_a_lo_0 = cute.arch.make_warp_uniform(cutlass.Int32((((a_addr >> 4) & 0x3FFF) + sa[0] * 1024)))
                _mma_b_lo_0 = cute.arch.make_warp_uniform(cutlass.Int32((((b_addr >> 4) & 0x3FFF) + sa[0] * 1024)))
                _mma_mxf8f6f4_112_d = prims.make_tmem_ptr(cutlass.Int32((tmem_acc + (acc_stage_1[0] * 128))), cutlass.Int32)
                _mma_mxf8f6f4_112_sfa = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_a), cutlass.Int32)
                _mma_mxf8f6f4_112_sfb = prims.make_tmem_ptr(cutlass.Int32((tmem_sf_b + sfb_shift)), cutlass.Int32)
                _mma_mxf8f6f4_112_a = cutlass.Uint64(cutlass.Uint32(_mma_a_lo_0)) | (cutlass.Uint64(0x40004040) << 32)
                _mma_mxf8f6f4_112_b = cutlass.Uint64(cutlass.Uint32(_mma_b_lo_0)) | (cutlass.Uint64(0x40004040) << 32)
                if prims.elect_sync():
                    prims.tcgen05_mma_block_scale(
                        prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                        _mma_mxf8f6f4_112_d, _mma_mxf8f6f4_112_a + 0, _mma_mxf8f6f4_112_b + 0,
                        cutlass.Uint32(0x08A01400), cutlass.Boolean((1) == 0), _mma_mxf8f6f4_112_sfa, _mma_mxf8f6f4_112_sfb,
                        scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                    )
                    prims.tcgen05_mma_block_scale(
                        prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                        _mma_mxf8f6f4_112_d, _mma_mxf8f6f4_112_a + 2, _mma_mxf8f6f4_112_b + 2,
                        cutlass.Uint32(0x28A01410), True, _mma_mxf8f6f4_112_sfa, _mma_mxf8f6f4_112_sfb,
                        scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                    )
                    prims.tcgen05_mma_block_scale(
                        prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                        _mma_mxf8f6f4_112_d, _mma_mxf8f6f4_112_a + 4, _mma_mxf8f6f4_112_b + 4,
                        cutlass.Uint32(0x48A01420), True, _mma_mxf8f6f4_112_sfa, _mma_mxf8f6f4_112_sfb,
                        scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                    )
                    prims.tcgen05_mma_block_scale(
                        prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                        _mma_mxf8f6f4_112_d, _mma_mxf8f6f4_112_a + 6, _mma_mxf8f6f4_112_b + 6,
                        cutlass.Uint32(0x68A01430), True, _mma_mxf8f6f4_112_sfa, _mma_mxf8f6f4_112_sfb,
                        scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                    )
                with cute.arch.elect_one():
                    cute.nvgpu.tcgen05.commit(ab_free_addr + sa[0], None, cute.nvgpu.tcgen05.CtaGroup.ONE)
                _advanced_stage_113 = cutlass.Uint32(sa[0] + 1)
                _stage_wrapped_114 = cutlass.Boolean(_advanced_stage_113 == 5)
                sa[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_114, 0, _advanced_stage_113))
                pha[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_114, pha[0] ^ cutlass.Uint32(1), pha[0]))
                ab_tok[0] = cutlass.Uint32(1)
                if (k_tiles > 1):
                    _mbar_token_1 = cutlass.Uint32(prims.mbarrier_wait_parity(ab_full_addr + sa[0], pha[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE))
                    ab_tok[0] = cutlass.Uint32(_mbar_token_1)
                for k in cutlass.range(cutlass.Int32(1), cutlass.Int32(k_tiles), cutlass.Int32(1), unroll=1, unroll_full=False):
                    if ab_tok[0] == 0:
                        while not prims.mbarrier_wait_parity(ab_full_addr + sa[0], pha[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                            pass
                    _scale_copy_115_src_0 = cutlass.Uint64(cutlass.Uint32((sfa_addr + (sa[0] * 512))))
                    _scale_copy_115_desc_0 = ((_scale_copy_115_src_0 >> 4) & cutlass.Uint64(0x3FFF)) | cutlass.Uint64(0x400800000000)
                    _scale_copy_115_dst_0 = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_a), cutlass.Int32)
                    with cute.arch.elect_one():
                        prims.tcgen05_cp(prims.Tcgen05CpShape.SHAPE_32X128B, _scale_copy_115_dst_0, _scale_copy_115_desc_0, group=prims.CTAGroup.CTA_1, multicast=prims.Tcgen05CpMulticast.WARPX4)
                    _scale_copy_116_src_0 = cutlass.Uint64(cutlass.Uint32((sfb_addr + (sa[0] * 512))))
                    _scale_copy_116_desc_0 = ((_scale_copy_116_src_0 >> 4) & cutlass.Uint64(0x3FFF)) | cutlass.Uint64(0x400800000000)
                    _scale_copy_116_dst_0 = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_b), cutlass.Int32)
                    with cute.arch.elect_one():
                        prims.tcgen05_cp(prims.Tcgen05CpShape.SHAPE_32X128B, _scale_copy_116_dst_0, _scale_copy_116_desc_0, group=prims.CTAGroup.CTA_1, multicast=prims.Tcgen05CpMulticast.WARPX4)
                    _mma_a_lo_1 = cute.arch.make_warp_uniform(cutlass.Int32((((a_addr >> 4) & 0x3FFF) + sa[0] * 1024)))
                    _mma_b_lo_1 = cute.arch.make_warp_uniform(cutlass.Int32((((b_addr >> 4) & 0x3FFF) + sa[0] * 1024)))
                    _mma_mxf8f6f4_117_d = prims.make_tmem_ptr(cutlass.Int32((tmem_acc + (acc_stage_1[0] * 128))), cutlass.Int32)
                    _mma_mxf8f6f4_117_sfa = prims.make_tmem_ptr(cutlass.Int32(tmem_sf_a), cutlass.Int32)
                    _mma_mxf8f6f4_117_sfb = prims.make_tmem_ptr(cutlass.Int32((tmem_sf_b + sfb_shift)), cutlass.Int32)
                    _mma_mxf8f6f4_117_a = cutlass.Uint64(cutlass.Uint32(_mma_a_lo_1)) | (cutlass.Uint64(0x40004040) << 32)
                    _mma_mxf8f6f4_117_b = cutlass.Uint64(cutlass.Uint32(_mma_b_lo_1)) | (cutlass.Uint64(0x40004040) << 32)
                    if prims.elect_sync():
                        prims.tcgen05_mma_block_scale(
                            prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                            _mma_mxf8f6f4_117_d, _mma_mxf8f6f4_117_a + 0, _mma_mxf8f6f4_117_b + 0,
                            cutlass.Uint32(0x08A01400), cutlass.Boolean((0) == 0), _mma_mxf8f6f4_117_sfa, _mma_mxf8f6f4_117_sfb,
                            scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                        )
                        prims.tcgen05_mma_block_scale(
                            prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                            _mma_mxf8f6f4_117_d, _mma_mxf8f6f4_117_a + 2, _mma_mxf8f6f4_117_b + 2,
                            cutlass.Uint32(0x28A01410), True, _mma_mxf8f6f4_117_sfa, _mma_mxf8f6f4_117_sfb,
                            scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                        )
                        prims.tcgen05_mma_block_scale(
                            prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                            _mma_mxf8f6f4_117_d, _mma_mxf8f6f4_117_a + 4, _mma_mxf8f6f4_117_b + 4,
                            cutlass.Uint32(0x48A01420), True, _mma_mxf8f6f4_117_sfa, _mma_mxf8f6f4_117_sfb,
                            scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                        )
                        prims.tcgen05_mma_block_scale(
                            prims.Tcgen05MMAKind.MXF8F6F4, prims.CTAGroup.CTA_1,
                            _mma_mxf8f6f4_117_d, _mma_mxf8f6f4_117_a + 6, _mma_mxf8f6f4_117_b + 6,
                            cutlass.Uint32(0x68A01430), True, _mma_mxf8f6f4_117_sfa, _mma_mxf8f6f4_117_sfb,
                            scale_vec_size=prims.Tcgen05MMAScaleVecSize.X1,
                        )
                    with cute.arch.elect_one():
                        cute.nvgpu.tcgen05.commit(ab_free_addr + sa[0], None, cute.nvgpu.tcgen05.CtaGroup.ONE)
                    _advanced_stage_118 = cutlass.Uint32(sa[0] + 1)
                    _stage_wrapped_119 = cutlass.Boolean(_advanced_stage_118 == 5)
                    sa[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_119, 0, _advanced_stage_118))
                    pha[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_119, pha[0] ^ cutlass.Uint32(1), pha[0]))
                    ab_tok[0] = cutlass.Uint32(1)
                    if ((k + 1) < k_tiles):
                        _mbar_token_2 = cutlass.Uint32(prims.mbarrier_wait_parity(ab_full_addr + sa[0], pha[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE))
                        ab_tok[0] = cutlass.Uint32(_mbar_token_2)
                with cute.arch.elect_one():
                    cute.nvgpu.tcgen05.commit(acc_full_addr + acc_stage_1[0], None, cute.nvgpu.tcgen05.CtaGroup.ONE)
                _advanced_stage_120 = cutlass.Uint32(acc_stage_1[0] + 1)
                _stage_wrapped_121 = cutlass.Boolean(_advanced_stage_120 == 2)
                acc_stage_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_121, 0, _advanced_stage_120))
                _phase_acc_free[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_121, _phase_acc_free[0] ^ cutlass.Uint32(1), _phase_acc_free[0]))
                while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_1[0], _phase_tile_full_1[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                info_1[0] = cutlass.Int32(_sinfo[(tile_stage_1[0] * 5)])
                info_1[1] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 1)])
                info_1[2] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 2)])
                info_1[3] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 3)])
                info_1[4] = cutlass.Int32(_sinfo[((tile_stage_1[0] * 5) + 4)])
                cute.arch.fence_proxy("async.shared", space="cta")
                cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_1[0])
                _advanced_stage_122 = cutlass.Uint32(tile_stage_1[0] + 1)
                _stage_wrapped_123 = cutlass.Boolean(_advanced_stage_122 == 2)
                tile_stage_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_123, 0, _advanced_stage_122))
                _phase_tile_full_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_123, _phase_tile_full_1[0] ^ cutlass.Uint32(1), _phase_tile_full_1[0]))
            _break_loop_counter_109[0] += cutlass.Int32(1)
            if _break_loop_counter_109[0] >= cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)):
                _loop_active_108[0] = False
    elif warp == 5:
        stage = cute.make_rmem_tensor((1,), cutlass.Uint32)
        tile_stage_2 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_tile_full_2 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_ab_free = cute.make_rmem_tensor((1,), cutlass.Uint32)
        stage[0] = cutlass.Uint32(0)
        tile_stage_2[0] = cutlass.Uint32(0)
        rank_tma = 0
        rank_tma_n = 0
        info_2 = cute.make_rmem_tensor((5,), cutlass.Int32)
        _phase_tile_full_2[0] = cutlass.Uint32(0)
        while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_2[0], _phase_tile_full_2[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
            pass
        info_2[0] = cutlass.Int32(_sinfo[(tile_stage_2[0] * 5)])
        info_2[1] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 1)])
        info_2[2] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 2)])
        info_2[3] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 3)])
        info_2[4] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 4)])
        cute.arch.fence_proxy("async.shared", space="cta")
        cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_2[0])
        _advanced_stage_124 = cutlass.Uint32(tile_stage_2[0] + 1)
        _stage_wrapped_125 = cutlass.Boolean(_advanced_stage_124 == 2)
        tile_stage_2[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_125, 0, _advanced_stage_124))
        _phase_tile_full_2[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_125, _phase_tile_full_2[0] ^ cutlass.Uint32(1), _phase_tile_full_2[0]))
        _phase_ab_free[0] = cutlass.Uint32(1)
        _loop_active_126 = cute.make_rmem_tensor((1,), cutlass.Boolean)
        _break_loop_counter_127 = cute.make_rmem_tensor((1,), cutlass.Int32)
        _break_loop_counter_127[0] = cutlass.Int32(cutlass.Int32(0))
        _loop_active_126[0] = cutlass.Boolean(_break_loop_counter_127[0] < cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)))
        while _loop_active_126[0]:
            _tile_2 = cutlass.Int32(_break_loop_counter_127[0])
            if (info_2[3] == 0):
                _loop_active_126[0] = False
            if _loop_active_126[0]:
                row_base_tma = cutlass.Int32((info_2[0] * 128))
                col_base_tma = cutlass.Int32(((info_2[1] * 128) + (rank_tma * 128)))
                expert_tma = cutlass.Int32(info_2[2])
                sfb_atom = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32((info_2[1] * 2)).ir_value(), cutlass.Int32(2).ir_value())))
                for k_1 in cutlass.range(cutlass.Int32(0), cutlass.Int32(k_tiles), cutlass.Int32(1), unroll=1, unroll_full=False):
                    while not prims.mbarrier_wait_parity(ab_free_addr + stage[0], _phase_ab_free[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                        pass
                    if prims.elect_sync():
                        cute.arch.mbarrier_arrive_and_expect_tx(ab_full_addr + stage[0], 25600)
                        prims.cp_async_bulk_tensor_shared_cta_global(
                            cute.make_ptr(cutlass.Uint8, cutlass.Uint32((a_addr + (stage[0] * 16384))), mem_space=cute.AddressSpace.smem, assumed_align=16),
                            A.get_ptr(),
                            [cutlass.Int32((k_1 * 128)), cutlass.Int32(row_base_tma)],
                            ab_full_addr + stage[0],
                            mode=prims.TMALoadMode.TILE,
                        )
                        prims.cp_async_bulk_tensor_shared_cta_global(
                            cute.make_ptr(cutlass.Uint8, cutlass.Uint32((b_addr + (stage[0] * 16384))), mem_space=cute.AddressSpace.smem, assumed_align=16),
                            B.get_ptr(),
                            [cutlass.Int32((k_1 * 128)), cutlass.Int32(col_base_tma), cutlass.Int32(expert_tma)],
                            ab_full_addr + stage[0],
                            l2_cache_hint=0x12F0000000000000,
                            mode=prims.TMALoadMode.TILE,
                        )
                        prims.cp_async_bulk_tensor_shared_cta_global(
                            cute.make_ptr(cutlass.Uint8, cutlass.Uint32((sfa_addr + (stage[0] * 512))), mem_space=cute.AddressSpace.smem, assumed_align=16),
                            SFA.get_ptr(),
                            [cutlass.Int32(0), cutlass.Int32(0), cutlass.Int32(k_1), cutlass.Int32(info_2[0])],
                            ab_full_addr + stage[0],
                            mode=prims.TMALoadMode.TILE,
                        )
                        prims.cp_async_bulk_tensor_shared_cta_global(
                            cute.make_ptr(cutlass.Uint8, cutlass.Uint32((sfb_addr + (stage[0] * 512))), mem_space=cute.AddressSpace.smem, assumed_align=16),
                            SFB.get_ptr(),
                            [cutlass.Int32(0), cutlass.Int32(0), cutlass.Int32(k_1), cutlass.Int32(sfb_atom), cutlass.Int32(expert_tma)],
                            ab_full_addr + stage[0],
                            l2_cache_hint=0x12F0000000000000,
                            mode=prims.TMALoadMode.TILE,
                        )
                    _advanced_stage_128 = cutlass.Uint32(stage[0] + 1)
                    _stage_wrapped_129 = cutlass.Boolean(_advanced_stage_128 == 5)
                    stage[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_129, 0, _advanced_stage_128))
                    _phase_ab_free[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_129, _phase_ab_free[0] ^ cutlass.Uint32(1), _phase_ab_free[0]))
                while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_2[0], _phase_tile_full_2[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                info_2[0] = cutlass.Int32(_sinfo[(tile_stage_2[0] * 5)])
                info_2[1] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 1)])
                info_2[2] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 2)])
                info_2[3] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 3)])
                info_2[4] = cutlass.Int32(_sinfo[((tile_stage_2[0] * 5) + 4)])
                cute.arch.fence_proxy("async.shared", space="cta")
                cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_2[0])
                _advanced_stage_130 = cutlass.Uint32(tile_stage_2[0] + 1)
                _stage_wrapped_131 = cutlass.Boolean(_advanced_stage_130 == 2)
                tile_stage_2[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_131, 0, _advanced_stage_130))
                _phase_tile_full_2[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_131, _phase_tile_full_2[0] ^ cutlass.Uint32(1), _phase_tile_full_2[0]))
            _break_loop_counter_127[0] += cutlass.Int32(1)
            if _break_loop_counter_127[0] >= cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)):
                _loop_active_126[0] = False
    elif warp == 6:
        tile_stage_3 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_tile_free = cute.make_rmem_tensor((1,), cutlass.Uint32)
        tile_stage_3[0] = cutlass.Uint32(0)
        num_valid = cutlass.Int32(_num_non_exiting_tiles[0])
        n_units = cutlass.Int32(num_n_tiles)
        total_tiles = cutlass.Int32((num_m_tiles * n_units))
        first_item = cutlass.Int32(bid)
        item_stride = cutlass.Int32(num_bids)
        rank_sched = 0
        rank_n = 0
        _phase_tile_free[0] = cutlass.Uint32(1)
        _loop_active_132 = cute.make_rmem_tensor((1,), cutlass.Boolean)
        _break_loop_counter_133 = cute.make_rmem_tensor((1,), cutlass.Int32)
        _break_loop_counter_133[0] = cutlass.Int32(cutlass.Int32(first_item))
        _loop_active_132[0] = cutlass.Boolean(_break_loop_counter_133[0] < cutlass.Int32(total_tiles))
        while _loop_active_132[0]:
            item = cutlass.Int32(_break_loop_counter_133[0])
            m_tile = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(item).ir_value(), cutlass.Int32(n_units).ir_value())))
            n_tile = cutlass.Int32(((item - (m_tile * n_units)) + rank_n))
            if (m_tile >= num_valid):
                _loop_active_132[0] = False
            if _loop_active_132[0]:
                while not prims.mbarrier_wait_parity(tile_free_addr + tile_stage_3[0], _phase_tile_free[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                group = cutlass.Int32(m_tile)
                expert = cutlass.Int32(_tile_idx_to_expert_idx[group])
                mn_limit = cutlass.Int32(_tile_idx_to_mn_limit[group])
                if prims.elect_sync():
                    prims.store_ext(cutlass.Int32((group + rank_sched)).ir_value(), (sinfo + ((tile_stage_3[0] * 5))))
                    prims.store_ext(cutlass.Int32(n_tile).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 1))))
                    prims.store_ext(cutlass.Int32(expert).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 2))))
                    prims.store_ext(cutlass.Int32(1).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 3))))
                    prims.store_ext(cutlass.Int32(mn_limit).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 4))))
                cute.arch.fence_proxy("async.shared", space="cta")
                prims.barrier_cta_sync(4, thread_count=32)
                cute.arch.mbarrier_arrive(tile_full_addr + tile_stage_3[0])
                _advanced_stage_134 = cutlass.Uint32(tile_stage_3[0] + 1)
                _stage_wrapped_135 = cutlass.Boolean(_advanced_stage_134 == 2)
                tile_stage_3[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_135, 0, _advanced_stage_134))
                _phase_tile_free[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_135, _phase_tile_free[0] ^ cutlass.Uint32(1), _phase_tile_free[0]))
            _break_loop_counter_133[0] += cutlass.Int32(item_stride)
            if _break_loop_counter_133[0] >= cutlass.Int32(total_tiles):
                _loop_active_132[0] = False
        while not prims.mbarrier_wait_parity(tile_free_addr + tile_stage_3[0], _phase_tile_free[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
            pass
        if prims.elect_sync():
            prims.store_ext(cutlass.Int32(0).ir_value(), (sinfo + ((tile_stage_3[0] * 5))))
            prims.store_ext(cutlass.Int32(0).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 1))))
            prims.store_ext(cutlass.Int32(-1).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 2))))
            prims.store_ext(cutlass.Int32(0).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 3))))
            prims.store_ext(cutlass.Int32(0).ir_value(), (sinfo + (((tile_stage_3[0] * 5) + 4))))
        cute.arch.fence_proxy("async.shared", space="cta")
        prims.barrier_cta_sync(4, thread_count=32)
        cute.arch.mbarrier_arrive(tile_full_addr + tile_stage_3[0])
        _advanced_stage_136 = cutlass.Uint32(tile_stage_3[0] + 1)
        _stage_wrapped_137 = cutlass.Boolean(_advanced_stage_136 == 2)
        tile_stage_3[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_137, 0, _advanced_stage_136))
        _phase_tile_free[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_137, _phase_tile_free[0] ^ cutlass.Uint32(1), _phase_tile_free[0]))
    elif warp == 7:
        tile_stage_4 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        meta_stage_1 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_tile_full_3 = cute.make_rmem_tensor((1,), cutlass.Uint32)
        _phase_meta_free = cute.make_rmem_tensor((1,), cutlass.Uint32)
        tile_stage_4[0] = cutlass.Uint32(0)
        meta_stage_1[0] = cutlass.Uint32(0)
        info_3 = cute.make_rmem_tensor((5,), cutlass.Int32)
        _phase_tile_full_3[0] = cutlass.Uint32(0)
        while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_4[0], _phase_tile_full_3[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
            pass
        info_3[0] = cutlass.Int32(_sinfo[(tile_stage_4[0] * 5)])
        info_3[1] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 1)])
        info_3[2] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 2)])
        info_3[3] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 3)])
        info_3[4] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 4)])
        cute.arch.fence_proxy("async.shared", space="cta")
        cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_4[0])
        _advanced_stage_138 = cutlass.Uint32(tile_stage_4[0] + 1)
        _stage_wrapped_139 = cutlass.Boolean(_advanced_stage_138 == 2)
        tile_stage_4[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_139, 0, _advanced_stage_138))
        _phase_tile_full_3[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_139, _phase_tile_full_3[0] ^ cutlass.Uint32(1), _phase_tile_full_3[0]))
        lane_meta = cutlass.Int32(lane)
        _phase_meta_free[0] = cutlass.Uint32(1)
        _loop_active_140 = cute.make_rmem_tensor((1,), cutlass.Boolean)
        _break_loop_counter_141 = cute.make_rmem_tensor((1,), cutlass.Int32)
        _break_loop_counter_141[0] = cutlass.Int32(cutlass.Int32(0))
        _loop_active_140[0] = cutlass.Boolean(_break_loop_counter_141[0] < cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)))
        while _loop_active_140[0]:
            _tile_3 = cutlass.Int32(_break_loop_counter_141[0])
            if (info_3[3] == 0):
                _loop_active_140[0] = False
            if _loop_active_140[0]:
                while not prims.mbarrier_wait_parity(meta_free_addr + meta_stage_1[0], _phase_meta_free[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                expert_meta = cutlass.Int32(info_3[2])
                alpha_e = cutlass.Float32(_alpha[expert_meta])
                row_base_meta = cutlass.Int32((info_3[0] * 128))
                mn_limit_meta = cutlass.Int32(info_3[4])
                meta_row = cutlass.Int32(lane_meta)
                meta_prow = cutlass.Int32((row_base_meta + meta_row))
                meta_valid = cutlass.Int32(cutlass.Int32((meta_prow < mn_limit_meta)))
                meta_expanded = cutlass.Int32(_permuted_idx_to_expanded_idx[meta_prow])
                _max_0 = cutlass.max(meta_expanded, 0)
                meta_safe = cutlass.Int32(_max_0)
                meta_token = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(meta_safe).ir_value(), cutlass.Int32(top_k).ir_value())))
                meta_topk = cutlass.Int32((meta_safe - (meta_token * top_k)))
                meta_gather = cutlass.Int32((meta_token * meta_valid))
                meta_weight = cutlass.Float32(_token_final_scales[((meta_gather * top_k) + meta_topk)])
                prims.store_ext(cutlass.Float32((alpha_e * meta_weight)).ir_value(), (smeta_scale + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row)))))
                prims.store_ext(cutlass.Int32(meta_token).ir_value(), (smeta_tok + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row)))))
                meta_row_0 = cutlass.Int32((lane_meta + 32))
                meta_prow_1 = cutlass.Int32((row_base_meta + meta_row_0))
                meta_valid_2 = cutlass.Int32(cutlass.Int32((meta_prow_1 < mn_limit_meta)))
                meta_expanded_3 = cutlass.Int32(_permuted_idx_to_expanded_idx[meta_prow_1])
                _max_1 = cutlass.max(meta_expanded_3, 0)
                meta_safe_4 = cutlass.Int32(_max_1)
                meta_token_5 = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(meta_safe_4).ir_value(), cutlass.Int32(top_k).ir_value())))
                meta_topk_6 = cutlass.Int32((meta_safe_4 - (meta_token_5 * top_k)))
                meta_gather_7 = cutlass.Int32((meta_token_5 * meta_valid_2))
                meta_weight_8 = cutlass.Float32(_token_final_scales[((meta_gather_7 * top_k) + meta_topk_6)])
                prims.store_ext(cutlass.Float32((alpha_e * meta_weight_8)).ir_value(), (smeta_scale + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_0)))))
                prims.store_ext(cutlass.Int32(meta_token_5).ir_value(), (smeta_tok + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_0)))))
                meta_row_9 = cutlass.Int32((lane_meta + 64))
                meta_prow_10 = cutlass.Int32((row_base_meta + meta_row_9))
                meta_valid_11 = cutlass.Int32(cutlass.Int32((meta_prow_10 < mn_limit_meta)))
                meta_expanded_12 = cutlass.Int32(_permuted_idx_to_expanded_idx[meta_prow_10])
                _max_2 = cutlass.max(meta_expanded_12, 0)
                meta_safe_13 = cutlass.Int32(_max_2)
                meta_token_14 = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(meta_safe_13).ir_value(), cutlass.Int32(top_k).ir_value())))
                meta_topk_15 = cutlass.Int32((meta_safe_13 - (meta_token_14 * top_k)))
                meta_gather_16 = cutlass.Int32((meta_token_14 * meta_valid_11))
                meta_weight_17 = cutlass.Float32(_token_final_scales[((meta_gather_16 * top_k) + meta_topk_15)])
                prims.store_ext(cutlass.Float32((alpha_e * meta_weight_17)).ir_value(), (smeta_scale + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_9)))))
                prims.store_ext(cutlass.Int32(meta_token_14).ir_value(), (smeta_tok + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_9)))))
                meta_row_18 = cutlass.Int32((lane_meta + 96))
                meta_prow_19 = cutlass.Int32((row_base_meta + meta_row_18))
                meta_valid_20 = cutlass.Int32(cutlass.Int32((meta_prow_19 < mn_limit_meta)))
                meta_expanded_21 = cutlass.Int32(_permuted_idx_to_expanded_idx[meta_prow_19])
                _max_3 = cutlass.max(meta_expanded_21, 0)
                meta_safe_22 = cutlass.Int32(_max_3)
                meta_token_23 = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(meta_safe_22).ir_value(), cutlass.Int32(top_k).ir_value())))
                meta_topk_24 = cutlass.Int32((meta_safe_22 - (meta_token_23 * top_k)))
                meta_gather_25 = cutlass.Int32((meta_token_23 * meta_valid_20))
                meta_weight_26 = cutlass.Float32(_token_final_scales[((meta_gather_25 * top_k) + meta_topk_24)])
                prims.store_ext(cutlass.Float32((alpha_e * meta_weight_26)).ir_value(), (smeta_scale + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_18)))))
                prims.store_ext(cutlass.Int32(meta_token_23).ir_value(), (smeta_tok + (((meta_stage_1[0] * 128) + cutlass.Uint32(meta_row_18)))))
                cute.arch.mbarrier_arrive(meta_full_addr + meta_stage_1[0])
                _advanced_stage_142 = cutlass.Uint32(meta_stage_1[0] + 1)
                _stage_wrapped_143 = cutlass.Boolean(_advanced_stage_142 == 2)
                meta_stage_1[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_143, 0, _advanced_stage_142))
                _phase_meta_free[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_143, _phase_meta_free[0] ^ cutlass.Uint32(1), _phase_meta_free[0]))
                while not prims.mbarrier_wait_parity(tile_full_addr + tile_stage_4[0], _phase_tile_full_3[0], prims.MBarrierWait.TRY, scope=prims.MBarrierScope.CTA, order=prims.MemOrder.ACQUIRE):
                    pass
                info_3[0] = cutlass.Int32(_sinfo[(tile_stage_4[0] * 5)])
                info_3[1] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 1)])
                info_3[2] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 2)])
                info_3[3] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 3)])
                info_3[4] = cutlass.Int32(_sinfo[((tile_stage_4[0] * 5) + 4)])
                cute.arch.fence_proxy("async.shared", space="cta")
                cute.arch.mbarrier_arrive(tile_free_addr + tile_stage_4[0])
                _advanced_stage_144 = cutlass.Uint32(tile_stage_4[0] + 1)
                _stage_wrapped_145 = cutlass.Boolean(_advanced_stage_144 == 2)
                tile_stage_4[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_145, 0, _advanced_stage_144))
                _phase_tile_full_3[0] = cutlass.Uint32(cutlass.select_(_stage_wrapped_145, _phase_tile_full_3[0] ^ cutlass.Uint32(1), _phase_tile_full_3[0]))
            _break_loop_counter_141[0] += cutlass.Int32(1)
            if _break_loop_counter_141[0] >= cutlass.Int32(((num_m_tiles * num_n_tiles) + 1)):
                _loop_active_140[0] = False
    cute.arch.sync_threads()
    if warp == 0:
        cute.arch.dealloc_tmem(_tmem_base_ptr, 512, is_two_cta=False, arch='sm_100')
        cute.arch.relinquish_tmem_alloc_permit(is_two_cta=False)
    prims.griddepcontrol(kind=prims.GridDepAction.LAUNCH_DEPENDENTS)

@cute.jit
def launch_gemm2_dense_finalize_n128(A: cute.Tensor, _cake_tma_A_dim_0: cutlass.Int64, _cake_tma_A_dim_1: cutlass.Int64, _cake_tma_A_stride16_0: cutlass.Int64, B: cute.Tensor, _cake_tma_B_dim_0: cutlass.Int64, _cake_tma_B_dim_1: cutlass.Int64, _cake_tma_B_dim_2: cutlass.Int64, _cake_tma_B_stride16_0: cutlass.Int64, _cake_tma_B_stride16_1: cutlass.Int64, SFA: cute.Tensor, _cake_tma_SFA_dim_0: cutlass.Int64, _cake_tma_SFA_dim_1: cutlass.Int64, _cake_tma_SFA_dim_2: cutlass.Int64, _cake_tma_SFA_dim_3: cutlass.Int64, _cake_tma_SFA_stride16_0: cutlass.Int64, _cake_tma_SFA_stride16_1: cutlass.Int64, _cake_tma_SFA_stride16_2: cutlass.Int64, SFB: cute.Tensor, _cake_tma_SFB_dim_0: cutlass.Int64, _cake_tma_SFB_dim_1: cutlass.Int64, _cake_tma_SFB_dim_2: cutlass.Int64, _cake_tma_SFB_dim_3: cutlass.Int64, _cake_tma_SFB_dim_4: cutlass.Int64, _cake_tma_SFB_stride16_0: cutlass.Int64, _cake_tma_SFB_stride16_1: cutlass.Int64, _cake_tma_SFB_stride16_2: cutlass.Int64, _cake_tma_SFB_stride16_3: cutlass.Int64, out: cute.Tensor, tile_idx_to_expert_idx: cute.Tensor, tile_idx_to_mn_limit: cute.Tensor, num_non_exiting_tiles: cute.Tensor, alpha: cute.Tensor, permuted_idx_to_expanded_idx: cute.Tensor, token_final_scales: cute.Tensor, tile_idx_to_row_group: cute.Tensor, num_m_tiles: cutlass.Int32, num_n_tiles: cutlass.Int32, k_tiles: cutlass.Int32, out_cols: cutlass.Int32, top_k: cutlass.Int32, dbg: cute.Tensor, grid_x: cutlass.Int32, grid_y: cutlass.Int32, grid_z: cutlass.Int32, stream: cuda.CUstream):
    _tma_A = create_tensor_map_tiled(
        A.iterator.toint(),
        cutlass.Uint8,
        [_cake_tma_A_dim_0, _cake_tma_A_dim_1],
        [_cake_tma_A_stride16_0],
        [128, 128],
        swizzle=TensorMapSwizzle.s128b,
        l2_promotion=TensorMapL2Promotion.none,
        oob_fill=TensorMapFloatOOBFill.none,
    )
    _tma_B = create_tensor_map_tiled(
        B.iterator.toint(),
        cutlass.Float4E2M1FN,
        [_cake_tma_B_dim_0, _cake_tma_B_dim_1, _cake_tma_B_dim_2],
        [_cake_tma_B_stride16_0, _cake_tma_B_stride16_1],
        [128, 128, 1],
        swizzle=TensorMapSwizzle.s128b,
        l2_promotion=TensorMapL2Promotion.none,
        oob_fill=TensorMapFloatOOBFill.none,
    )
    _tma_SFA = create_tensor_map_tiled(
        SFA.iterator.toint(),
        cutlass.Uint8,
        [_cake_tma_SFA_dim_0, _cake_tma_SFA_dim_1, _cake_tma_SFA_dim_2, _cake_tma_SFA_dim_3],
        [_cake_tma_SFA_stride16_0, _cake_tma_SFA_stride16_1, _cake_tma_SFA_stride16_2],
        [128, 4, 1, 1],
        swizzle=TensorMapSwizzle.none,
        l2_promotion=TensorMapL2Promotion.none,
        oob_fill=TensorMapFloatOOBFill.none,
    )
    _tma_SFB = create_tensor_map_tiled(
        SFB.iterator.toint(),
        cutlass.Uint8,
        [_cake_tma_SFB_dim_0, _cake_tma_SFB_dim_1, _cake_tma_SFB_dim_2, _cake_tma_SFB_dim_3, _cake_tma_SFB_dim_4],
        [_cake_tma_SFB_stride16_0, _cake_tma_SFB_stride16_1, _cake_tma_SFB_stride16_2, _cake_tma_SFB_stride16_3],
        [128, 4, 1, 1, 1],
        swizzle=TensorMapSwizzle.none,
        l2_promotion=TensorMapL2Promotion.none,
        oob_fill=TensorMapFloatOOBFill.none,
    )
    kernel_cake_mxfp4_situ_moe_4e29554c5f9311bd563c(_tma_A, _tma_B, _tma_SFA, _tma_SFB, out.iterator, tile_idx_to_expert_idx.iterator, tile_idx_to_mn_limit.iterator, num_non_exiting_tiles.iterator, alpha.iterator, permuted_idx_to_expanded_idx.iterator, token_final_scales.iterator, tile_idx_to_row_group.iterator, num_m_tiles, num_n_tiles, k_tiles, out_cols, top_k, dbg.iterator).launch(
        grid=(grid_x, grid_y, grid_z),
        block=(256, 1, 1),
        smem=206976,
        use_pdl=True,
        stream=stream,
    )

def compile_program():
    return cute.compile(launch_gemm2_dense_finalize_n128,
        make_fake_tensor(cutlass.Uint8, (cute.sym_int64(symbol='A'),), (1,), assumed_align=16),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        make_fake_tensor(cutlass.Uint8, (cute.sym_int64(symbol='B'),), (1,), assumed_align=16),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        make_fake_tensor(cutlass.Uint8, (cute.sym_int64(symbol='SFA'),), (1,), assumed_align=16),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        make_fake_tensor(cutlass.Uint8, (cute.sym_int64(symbol='SFB'),), (1,), assumed_align=16),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        cutlass.Int64(0),
        make_fake_tensor(cutlass.BFloat16, (cute.sym_int64(symbol='out'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='tile_idx_to_expert_idx'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='tile_idx_to_mn_limit'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='num_non_exiting_tiles'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Float32, (cute.sym_int64(symbol='alpha'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='permuted_idx_to_expanded_idx'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Float32, (cute.sym_int64(symbol='token_final_scales'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='tile_idx_to_row_group'),), (1,), assumed_align=16),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='dbg'),), (1,), assumed_align=16),
        cutlass.Int32(1),
        cutlass.Int32(1),
        cutlass.Int32(1),
        make_fake_stream(use_tvm_ffi_env_stream=True),
        options='--enable-tvm-ffi --ptxas-options=--opt-level=2 --gpu-arch=sm_103a',
    )
