#
# Copyright (c) 2026 by FlashInfer team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Generated by Cake's CuTe DSL backend.  Do not edit."""
from __future__ import annotations

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
from cutlass._mlir import ir as cutlass_ir
from cutlass._mlir.dialects import arith as cutlass_arith
from cutlass._mlir.dialects import llvm as cutlass_llvm
from cutlass._mlir.dialects import nvvm as cutlass_nvvm
from cutlass._mlir.dialects import cuda as cutlass_cuda
from cutlass.cute.runtime import make_fake_stream, make_fake_tensor
from cutlass.experimental import primitives as prims
from cutlass.experimental.primitives import nvvm_wrapper as prims_nvvm
from cutlass.utils import blackwell_helpers as cutlass_blackwell
from cutlass.utils.layout import LayoutEnum as CutlassLayout
from cutlass.utils import blockscaled_layout as cutlass_blockscaled
from cutlass.experimental.cuda.tensor_map import (
    TensorMap,
    TensorMapDataFormat,
    TensorMapFloatOOBFill,
    TensorMapL2Promotion,
    TensorMapSwizzle,
    create_tensor_map_tiled,
)
from cutlass._mlir.dialects.nvvm import CTAGroupKind as DialectCTAGroup
from cutlass._mlir.dialects.nvvm import TMALoadMode as DialectTMALoadMode

NUM_MAIN_STAGES = 1
THREADS = 256
CAKE_TARGET_ARCH = 'sm_103a'
CAKE_SMEM_BYTES = 0

def _cake_ldparam_b32(addr, ptx_type):
    return cutlass.Int32(cutlass_llvm.inline_asm(
        cutlass.Int32.mlir_type,
        [cutlass.Uint64(addr).ir_value()],
        '{ .reg .u64 %pa; cvta.to.param::entry.u64 %pa, $1; ld.param::entry.' + ptx_type + ' $0, [%pa]; }', '=r,l',
        has_side_effects=False, is_align_stack=False,
        asm_dialect=cutlass_llvm.AsmDialect.AD_ATT,
    ))

def _cake_ldparam_b64(addr, ptx_type):
    return cutlass.Uint64(cutlass_llvm.inline_asm(
        cutlass.Uint64.mlir_type,
        [cutlass.Uint64(addr).ir_value()],
        '{ .reg .u64 %pa; cvta.to.param::entry.u64 %pa, $1; ld.param::entry.' + ptx_type + ' $0, [%pa]; }', '=l,l',
        has_side_effects=False, is_align_stack=False,
        asm_dialect=cutlass_llvm.AsmDialect.AD_ATT,
    ))

def _cake_ldg_nc_b32(addr):
    return cutlass.Int32(cutlass_llvm.inline_asm(
        cutlass.Int32.mlir_type,
        [cutlass.Uint64(addr).ir_value()],
        'ld.global.nc.b32 $0, [$1];', '=r,l',
        has_side_effects=False, is_align_stack=False,
        asm_dialect=cutlass_llvm.AsmDialect.AD_ATT,
    ))

@cute.kernel
def kernel_cake_mxfp4_situ_moe_2db9055c033d3772880a(ids_src: cute.Pointer, weights_src: cute.Pointer, ids_dst: cute.Pointer, weights_dst: cute.Pointer, output: cute.Pointer, num_routes: cutlass.Int32, top_k: cutlass.Int32, output_words: cutlass.Int32, ids_stride0: cutlass.Int32, ids_stride1: cutlass.Int32, w_stride0: cutlass.Int32, w_stride1: cutlass.Int32):
    tid = cutlass.Int32(cute.arch.thread_idx()[0])
    warp = cutlass.Int32(cute.arch.warp_idx())
    lane = cutlass.Int32(cute.arch.lane_idx())
    bid = cutlass.Int32(cute.arch.block_idx()[0])
    num_bids = cutlass.Int32(cute.arch.grid_dim()[0])
    blockIdx = cute.arch.block_idx()
    gridDim = cute.arch.grid_dim()
    _flat_layout = cute.make_layout((2147483647,), stride=(1,))
    _ids_src = cute.make_tensor(ids_src, _flat_layout)
    _weights_src = cute.make_tensor(weights_src, _flat_layout)
    _ids_dst = cute.make_tensor(ids_dst, _flat_layout)
    _weights_dst = cute.make_tensor(weights_dst, _flat_layout)
    _output = cute.make_tensor(output, _flat_layout)
    first = cutlass.Int32(((blockIdx[0] * 256) + tid))
    grid_x = cutlass.Int32(gridDim[0])
    task_stride = cutlass.Int32((grid_x * 256))
    _forward_loop_0 = cutlass.while_generate([cutlass.Int32(first)], lambda _forward_condition_1: _forward_condition_1 < cutlass.Int32(num_routes))
    _forward_loop_0.while_op.attributes["loop_annotation"] = cutlass.LoopUnroll(count=1)
    with _forward_loop_0 as _forward_values_2:
        route = _forward_values_2[0]
        token = cutlass.Int32(cutlass.Int32(cutlass_arith.divsi(cutlass.Int32(route).ir_value(), cutlass.Int32(top_k).ir_value())))
        slot = cutlass.Int32((route % top_k))
        prims.store_ext(cutlass.Float32(cutlass.Float32(_weights_src[((token * w_stride0) + (slot * w_stride1))])).ir_value(), (weights_dst + (route)))
        cutlass.yield_out([cutlass.Int32(route + (task_stride))])

@cute.jit
def launch_kimi_k3_mxfp4_situ_route_preprocess(ids_src: cute.Tensor, weights_src: cute.Tensor, ids_dst: cute.Tensor, weights_dst: cute.Tensor, output: cute.Tensor, num_routes: cutlass.Int32, top_k: cutlass.Int32, output_words: cutlass.Int32, ids_stride0: cutlass.Int32, ids_stride1: cutlass.Int32, w_stride0: cutlass.Int32, w_stride1: cutlass.Int32, grid_x: cutlass.Int32, grid_y: cutlass.Int32, grid_z: cutlass.Int32, stream: cuda.CUstream):
    kernel_cake_mxfp4_situ_moe_2db9055c033d3772880a(ids_src.iterator, weights_src.iterator, ids_dst.iterator, weights_dst.iterator, output.iterator, num_routes, top_k, output_words, ids_stride0, ids_stride1, w_stride0, w_stride1).launch(
        grid=(grid_x, grid_y, grid_z),
        block=(256, 1, 1),
        stream=stream,
    )

def compile_program():
    return cute.compile(launch_kimi_k3_mxfp4_situ_route_preprocess,
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='ids_src'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.BFloat16, (cute.sym_int64(symbol='weights_src'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Int32, (cute.sym_int64(symbol='ids_dst'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Float32, (cute.sym_int64(symbol='weights_dst'),), (1,), assumed_align=16),
        make_fake_tensor(cutlass.Uint32, (cute.sym_int64(symbol='output'),), (1,), assumed_align=16),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(0),
        cutlass.Int32(1),
        cutlass.Int32(1),
        cutlass.Int32(1),
        make_fake_stream(use_tvm_ffi_env_stream=True),
        options='--enable-tvm-ffi --ptxas-options=--opt-level=2 --gpu-arch=sm_103a',
    )
