"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the Kimi-K3
# serialized ``FP8_PB_WO`` projection GEMMs (SM100 / SM103).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host dispatcher resolves at preparation:
#
# * ``quant:u<units>``                 the per-token 1x128 E4M3 / UE8M0
#   quantization launch with ``units`` K blocks per half warp (1 for M <= 256,
#   2 / 4 for the large-M rows, chosen by ``cake_backend.quant_units``);
# * ``gemm``                            the persistent 2-CTA block-scaled
#   tcgen05 GEMM (256 output columns per CTA pair, M > 256);
# * ``decode:t<tok>_p<stages>[_fused][_res][_r<xb>][_q<lanes>]``   the swap-AB
#   split-K decode kernel for one token-tile width, TMA pipeline depth, in-CTA
#   quantization (``_fused``), resident token tiles (``_res``), a decoupled
#   ``xb``-deep BF16 token ring (``_r``) and narrow quantization units of
#   ``lanes`` lanes (``_q``; absent = half-warp units), as the measured dispatch
#   table selects per ``(N, K, M bucket)``.
#
# Every module is an exact-architecture program (tcgen05 / TMEM, ``cta_group::2``
# for the GEMM).  Both literals are populated verbatim by the generated-program
# export; do not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_fp8_projection_02efdc1c7ea31977bba6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_02efdc1c7ea31977bba6_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_02efdc1c7ea31977bba6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ec796df46f101e27c41ce8b5b4f0db4694baa96bf858874c2b80cf14a8ee3a7a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_03907eb3ed264f270f97": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_03907eb3ed264f270f97_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_03907eb3ed264f270f97_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c5f2dfb99ad854ae6948a2cc3642398835afae8eb5864e30cea98e5933da7b3f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_08b40b645a7ab67c2360": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_08b40b645a7ab67c2360_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_08b40b645a7ab67c2360_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f199aab6587fc0e5cc3063c0af2fb14b4e827bd9f205b304eaf33dcee6966588",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_0d6e372689f536829708": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_0d6e372689f536829708_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_0d6e372689f536829708_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6c914f455437314e76a69ff44b2d351b10e87b4621a80774dbbe6c6110c4553d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_12225ad4a7b116e13125": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_12225ad4a7b116e13125_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_12225ad4a7b116e13125_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5cae4537f4712707794446507738b79f42b3b2e4f5c7fbf61fb1fdaa53c4f3bc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0f245f61c801932edc902c632d26b4c99d175329b8fe9b9166e4d0d49bec59cc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_15f5fe144f1583c1ffd5": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_15f5fe144f1583c1ffd5_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_15f5fe144f1583c1ffd5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b4d45969e6635df9ce958b002348b2aadff9d093e30681418c5624da1e30f2a5",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2ccbefcc2338abd13571": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2ccbefcc2338abd13571_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2ccbefcc2338abd13571_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6ad56d81df7e05d71bcc5d7cf5d5a636c1336f57219d3379405646cb0fc3b83c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "68b1515d7ffaccc9dea1cf63f873308c918ad28e57285b641da2a4a636e8f8b0",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2d4792b887fd11182967": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2d4792b887fd11182967_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2d4792b887fd11182967_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2830e7a1102db82737173dfbaa0334591cf6d4009604517e84fa669d3f031ad7",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2fa80395173e55f493bb": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2fa80395173e55f493bb_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2fa80395173e55f493bb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "192125c3a7a59f2b4db9b706b4ba978247e084c1dac417624ae2dbaa22d26140",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_4ba833b35d5ca5cdf3eb": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_4ba833b35d5ca5cdf3eb_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_4ba833b35d5ca5cdf3eb_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bdb2b24ee7f0ce011aeeb2dffb37316e76dc5b935c51027b18690d6cb3c8517a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_4c378dd2e0e631f7b6ab": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_4c378dd2e0e631f7b6ab_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_4c378dd2e0e631f7b6ab_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "3d78bb322f5cc05f17a613ecc501a81cb60d4966442652bdb9bf6bc34b19b0f4",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_58c5d4ddd4613778fd5b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_58c5d4ddd4613778fd5b_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_58c5d4ddd4613778fd5b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e27d04a9db5d5beee1e4becd56f2de837082d7867f469888ee6de47feaa6afa2",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_671f6e8527b853cf3a0c": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_671f6e8527b853cf3a0c_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_671f6e8527b853cf3a0c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "45d660acea61cc3656cdef9ddd063378c6b1508af145df4e10f91935db81d15a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9e53942a8a8e8f11df2b457cfb1c11af7f7da8591fd82316a97180e1835c973d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_77dd92a92a3ee715240f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_77dd92a92a3ee715240f_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_77dd92a92a3ee715240f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "cf3ceeabdbf998a077fbc0c8705e1516e8319aeffaa764dbf5bb8154a9afc6f3",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8192b537d3e709b63ad2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8192b537d3e709b63ad2_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8192b537d3e709b63ad2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "86a8c15abc29509d8fe17468e2224a76db4a4cf40c8f2a875d4717be9b6f6b25",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8d2449a068b92354b0bc": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8d2449a068b92354b0bc_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8d2449a068b92354b0bc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9d67ac1660cff9b624b6413d03b6e78dce30a9f8032a3b3ab4aa1e2ed462a26b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8f414df7fef872f241ea": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8f414df7fef872f241ea_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8f414df7fef872f241ea_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6a624e41e09a26de233ba2333fdc69304e7e10f40e4f14751f77f7bd71fa63b9",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8f6b39413714926d59be": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8f6b39413714926d59be_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8f6b39413714926d59be_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "61f512f1d8f0fb43d13420b5274c31610531ef3f29370a3cd508aff8f0bfc387",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_93a7d211590430322d75": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_93a7d211590430322d75_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_93a7d211590430322d75_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "75272a3a7ba25fbcfdd236fc993cef5c40068877812b19991b46084a87fa2895",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_9942437c8e9e5e2a7ef5": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_9942437c8e9e5e2a7ef5_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_9942437c8e9e5e2a7ef5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b354f7d878ec74ba38943365cce9eec53d41d785085701b268c2f6e36a61be65",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_9afdfe82e56f89f6a9a7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_9afdfe82e56f89f6a9a7_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_9afdfe82e56f89f6a9a7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "626380de3e19aa4af9b45ac6a229043f89c294439802d328b9bbecfbbe35fa8c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_a1e32697b013ee166582": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_a1e32697b013ee166582_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_a1e32697b013ee166582_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "4841e6b9e3e6dbd9eec2441f469e070a3d857c81b5a439d24e9890650e3f364a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_a64f9619c0dd1ee17de9": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_a64f9619c0dd1ee17de9_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_a64f9619c0dd1ee17de9_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "cc61b8bd690a7e3a624fff4c4e60d13704c229667e7665637bdece9109e19363",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_aa9e86e8c5d975f372fd": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_aa9e86e8c5d975f372fd_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_aa9e86e8c5d975f372fd_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "edbbdfc5a9f6741f23b50a90e20cf64e78f20c98c06a84a732485a67448abd27",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_ada8d32600e57c228b66": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ada8d32600e57c228b66_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ada8d32600e57c228b66_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "97e0b164d3bf180979dea81440c83a25f51c8372f1e871de291126060a683495",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "05eb78cf99ae9f56043ce5007d85d3f93d2b12a92ebecc1bf213f758dcb5eeed",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_c0e552f5b3212c10a570": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_c0e552f5b3212c10a570_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_c0e552f5b3212c10a570_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "312e53aaf8f8bf9c32f8f8c89db0694308989841e6ea879c30d5f03cbeb8d7c1",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_c22359d10be557dd6aff": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c22359d10be557dd6aff_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c22359d10be557dd6aff_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b317ac9cc63dfbc8fa651fc7a8b4070cd9c723df18be9cdf853233a16f4f38ef",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_c7357484fd2ceafb8740": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c7357484fd2ceafb8740_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c7357484fd2ceafb8740_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "010bd1795fe88d5cbca13e08447ce5f60d65f8c141b2051463585549811c1c85",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_cc6daeb00a62e27fb94f": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_cc6daeb00a62e27fb94f_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_cc6daeb00a62e27fb94f_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7dbecdf7b18474bae7091096d04e869787839730512ae012fb42d6e166861c8b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_cc6dc85fd86b6ff3a3f1": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_cc6dc85fd86b6ff3a3f1_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_cc6dc85fd86b6ff3a3f1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9f2727fac7293b822780caec9c15c1568499adb4a3bdc9073db2614a7f790831",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_d524629d0ce1286e7476": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_d524629d0ce1286e7476_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_d524629d0ce1286e7476_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "88000243dc8dc5d86a2feae81dc75be52adea9efd18c4ee67c1ae677f6dd125f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "14c71a8e4413f10f1a2f230632082493f512fc7a9cf9d41e2339633996e90c8b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_e11487938ad75ec13498": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_e11487938ad75ec13498_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_e11487938ad75ec13498_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1132519a4a7a2f9d62550b1941df19385c48f240f08f9a36a1eeef5a9571fb1e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_ebe5570a1abb031149f7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ebe5570a1abb031149f7_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ebe5570a1abb031149f7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "f5406bfa305ca6b265ebc7b1809ba9b7d45835922bf8d152e4b38dc01f8d8e24",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_efbe28e677d5816dfd03": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_efbe28e677d5816dfd03_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_efbe28e677d5816dfd03_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "b7a5f836907a760e29aba08b92fd618efe92b5fb3188ebb9b3f9c281748dd658",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_f5dcc77cfb7deb20521b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_f5dcc77cfb7deb20521b_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_f5dcc77cfb7deb20521b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a27a2909d24a41d830ee1b75d6db94916d27ec4b060e197b18fad6c410b85ecb",
        "tma_workspace_bytes": 0,
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "decode:t128_p3": "cake_kimi_k3_fp8_projection_9afdfe82e56f89f6a9a7",
        "decode:t16_p4": "cake_kimi_k3_fp8_projection_f5dcc77cfb7deb20521b",
        "decode:t16_p4_fused": "cake_kimi_k3_fp8_projection_c0e552f5b3212c10a570",
        "decode:t16_p4_fused_cs2": "cake_kimi_k3_fp8_projection_77dd92a92a3ee715240f",
        "decode:t16_p4_fused_cs4": "cake_kimi_k3_fp8_projection_a64f9619c0dd1ee17de9",
        "decode:t32_p3_fused_cs8": "cake_kimi_k3_fp8_projection_03907eb3ed264f270f97",
        "decode:t32_p3_fused_r5_q4": "cake_kimi_k3_fp8_projection_d524629d0ce1286e7476",
        "decode:t32_p3_fused_res": "cake_kimi_k3_fp8_projection_aa9e86e8c5d975f372fd",
        "decode:t32_p4": "cake_kimi_k3_fp8_projection_9942437c8e9e5e2a7ef5",
        "decode:t32_p4_cs4": "cake_kimi_k3_fp8_projection_ebe5570a1abb031149f7",
        "decode:t32_p4_cs8": "cake_kimi_k3_fp8_projection_4ba833b35d5ca5cdf3eb",
        "decode:t64_p2_fused_r3_q4": "cake_kimi_k3_fp8_projection_2ccbefcc2338abd13571",
        "decode:t64_p2_fused_res": "cake_kimi_k3_fp8_projection_08b40b645a7ab67c2360",
        "decode:t64_p4": "cake_kimi_k3_fp8_projection_e11487938ad75ec13498",
        "gemm": "cake_kimi_k3_fp8_projection_ada8d32600e57c228b66",
        "gemm_rstaged": "cake_kimi_k3_fp8_projection_8d2449a068b92354b0bc",
        "gemm_tstore": "cake_kimi_k3_fp8_projection_671f6e8527b853cf3a0c",
        "quant:u1": "cake_kimi_k3_fp8_projection_8f6b39413714926d59be",
        "quant:u2": "cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f",
        "quant:u4": "cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363",
    },
    "sm_103a": {
        "decode:t128_p3": "cake_kimi_k3_fp8_projection_12225ad4a7b116e13125",
        "decode:t16_p4": "cake_kimi_k3_fp8_projection_2fa80395173e55f493bb",
        "decode:t16_p4_fused": "cake_kimi_k3_fp8_projection_4c378dd2e0e631f7b6ab",
        "decode:t16_p4_fused_cs2": "cake_kimi_k3_fp8_projection_efbe28e677d5816dfd03",
        "decode:t16_p4_fused_cs4": "cake_kimi_k3_fp8_projection_cc6daeb00a62e27fb94f",
        "decode:t32_p3_fused_cs8": "cake_kimi_k3_fp8_projection_c22359d10be557dd6aff",
        "decode:t32_p3_fused_r5_q4": "cake_kimi_k3_fp8_projection_c7357484fd2ceafb8740",
        "decode:t32_p3_fused_res": "cake_kimi_k3_fp8_projection_a1e32697b013ee166582",
        "decode:t32_p4": "cake_kimi_k3_fp8_projection_93a7d211590430322d75",
        "decode:t32_p4_cs4": "cake_kimi_k3_fp8_projection_58c5d4ddd4613778fd5b",
        "decode:t32_p4_cs8": "cake_kimi_k3_fp8_projection_0d6e372689f536829708",
        "decode:t64_p2_fused_r3_q4": "cake_kimi_k3_fp8_projection_8192b537d3e709b63ad2",
        "decode:t64_p2_fused_res": "cake_kimi_k3_fp8_projection_15f5fe144f1583c1ffd5",
        "decode:t64_p4": "cake_kimi_k3_fp8_projection_cc6dc85fd86b6ff3a3f1",
        "gemm": "cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8",
        "gemm_rstaged": "cake_kimi_k3_fp8_projection_02efdc1c7ea31977bba6",
        "gemm_tstore": "cake_kimi_k3_fp8_projection_8f414df7fef872f241ea",
        "quant:u1": "cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a",
        "quant:u2": "cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6",
        "quant:u4": "cake_kimi_k3_fp8_projection_2d4792b887fd11182967",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}

GEMM_KERNEL_KEY = "gemm"  # register epilogue (any even output row stride)
GEMM_RSTAGED_KERNEL_KEY = "gemm_rstaged"  # staged row-coalesced register epilogue (8-byte aligned output rows)
GEMM_TSTORE_KERNEL_KEY = (
    "gemm_tstore"  # TMA-store epilogue (16-byte output base, row stride, column edge)
)


def quant_kernel_key(units: int) -> str:
    return f"quant:u{int(units)}"


def decode_kernel_key(
    tok: int,
    stages: int,
    fused: bool,
    resident: bool,
    xb_stages: int = 0,
    qlanes: int = 16,
    csplit: int = 1,
    cs_alias: bool = False,
    epi_chunk: int = 0,
    pf: int = 0,
) -> str:
    key = f"decode:t{int(tok)}_p{int(stages)}"
    if fused:
        key += "_fused"
    if resident:
        key += "_res"
    if xb_stages:
        key += f"_r{int(xb_stages)}"
    if qlanes != 16:
        key += f"_q{int(qlanes)}"
    if epi_chunk and int(epi_chunk) != min(32, int(tok)):
        key += f"_c{int(epi_chunk)}"  # round 6: epilogue staging rows per flush (a 16-row chunk frees SMEM for a 5th stage)
    if int(csplit) > 1:
        key += f"_cs{int(csplit)}"  # round 5: K split across the CTAs of one cluster, DSM partial exchange
        if cs_alias:
            key += "a"  # the exchange inbox aliases the dead pipeline stages (one round; one work item per CTA)
    if int(pf) > 0:
        key += f"_pf{int(pf)}"  # round 6 (lever P): weight tiles prefetched into L2 pf stages ahead of their TMA load
    return key


def gemm_kernel_key(base: str, pf: int = 0) -> str:
    """``gemm`` / ``gemm_tstore`` / ``gemm_rstaged`` plus ``_pf<D>`` when the shape's table row prefetches the weight
    tiles ``D`` stages ahead (round 6, lever GP; table key ``gemm_pf``)."""
    return base + (f"_pf{int(pf)}" if int(pf) > 0 else "")


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 FP8 projection programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4568)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 FP8 projection kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4568)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_fp8_projection_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_fp8_projection_module(name: str):
    return gen_cake_kimi_k3_fp8_projection_module(name).build_and_load()
