"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs of the Kimi-K3
# serialized ``FP8_PB_WO`` projection GEMMs (SM100 / SM103).
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): translation units, compile flags, FFI entry, argument
# plan and closure identity.  ``KERNELS`` maps ``"<arch>"`` to the logical
# kernel key -> module assignment the host dispatcher resolves at preparation:
#
# * ``quant:u<units>``                 the per-token 1x128 E4M3 / UE8M0
#   quantization launch with ``units`` K blocks per half warp (1 for M <= 256,
#   2 / 4 for the large-M rows, chosen by ``cake_backend.quant_units``);
# * ``gemm``                            the persistent 2-CTA block-scaled
#   tcgen05 GEMM (256 output columns per CTA pair, M > 256);
# * ``decode:t<tok>_p<stages>[_fused][_res][_r<xb>][_q<lanes>]``   the swap-AB
#   split-K decode kernel for one token-tile width, TMA pipeline depth, in-CTA
#   quantization (``_fused``), resident token tiles (``_res``), a decoupled
#   ``xb``-deep BF16 token ring (``_r``) and narrow quantization units of
#   ``lanes`` lanes (``_q``; absent = half-warp units), as the measured dispatch
#   table selects per ``(N, K, M bucket)``.
#
# Every module is an exact-architecture program (tcgen05 / TMEM, ``cta_group::2``
# for the GEMM).  Both literals are populated verbatim by the generated-program
# export; do not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_kimi_k3_fp8_projection_00739ad64bc792e627df": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_00739ad64bc792e627df_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_00739ad64bc792e627df_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8ff4fba37c258215aa142d605594a1c68ed385fcb071b786069e0ccb98fb0fef",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_055d89bbf1c9a2ed23f6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_055d89bbf1c9a2ed23f6_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_055d89bbf1c9a2ed23f6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7a77b7cbc2f3d31f6464deaf3b5b1bcc33d3338142558d5b93208e70b25bbd2e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_07858805ef7c25803dbe": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_07858805ef7c25803dbe_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_07858805ef7c25803dbe_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6991efe08d6e2ef2e0012708744d3768fdccf8f0d675ccfb2910885927e14a9a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_0d1f3e1fce0542d045a7": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_0d1f3e1fce0542d045a7_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_0d1f3e1fce0542d045a7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "df97012f9bcb8fb30fb17d7184922e68deac775ff4087ebbe4aa7c66f11588bc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_10e9c8285c31ff891e3d": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_10e9c8285c31ff891e3d_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_10e9c8285c31ff891e3d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "310a2432570079688db81358633ecedcb814335cfd3f50fd881abd076f3fe8cb",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "0f245f61c801932edc902c632d26b4c99d175329b8fe9b9166e4d0d49bec59cc",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_1854b1b35222ad1788bf": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_1854b1b35222ad1788bf_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_1854b1b35222ad1788bf_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "6f7c1bd7246e20950b2815c2fc53d2f8d23c33a02a4453373ca3357e00732cd7",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_1c708dfcbfe9c984f9c1": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_1c708dfcbfe9c984f9c1_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_1c708dfcbfe9c984f9c1_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "74dfe2fb9ff0a41f43b8636b3f2ff419e330ebb27c9e836dd8d7c9ca2a82235b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "68b1515d7ffaccc9dea1cf63f873308c918ad28e57285b641da2a4a636e8f8b0",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_2d4792b887fd11182967": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2d4792b887fd11182967_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_2d4792b887fd11182967_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2830e7a1102db82737173dfbaa0334591cf6d4009604517e84fa669d3f031ad7",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_51111fd6e2d6560472d3": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_51111fd6e2d6560472d3_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_51111fd6e2d6560472d3_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "46394985cf5f5fb5387e55784db94ff6821bcb01971772f899259774d359bd8f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_56e0f36deb71d340ce0d": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_56e0f36deb71d340ce0d_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_56e0f36deb71d340ce0d_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8961db53b71b5aef8efcff3b95a24a564150cde0e3c0a6d97bc86f73309079f0",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_57561222edd2b892d6cc": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_57561222edd2b892d6cc_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_57561222edd2b892d6cc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2cebebce79faa2c629b9d6626f9b778460cb7b5cc866d44ff1a76876e74cdc7f",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_59eaf113c1017ac11185": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_59eaf113c1017ac11185_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_59eaf113c1017ac11185_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "fa14fe2bfac99001b7f0c3c9b8a4fa5d0257a954e2fb9d1b5fe976391b44cd8d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_614b479ad56eced96ef2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_614b479ad56eced96ef2_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_614b479ad56eced96ef2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "98468f8cacc456369b130ed2a14510bac1ba9e7d3c11cdc874875907b3a9ec3c",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_69dbd7f54be92e929682": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_69dbd7f54be92e929682_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_69dbd7f54be92e929682_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1bd9ce9d338cf556828ab3890a1345690c453d48d34bf538e9e18b6b5c7a0a3a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "9e53942a8a8e8f11df2b457cfb1c11af7f7da8591fd82316a97180e1835c973d",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_7596d4f5170c8d2b3517": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_7596d4f5170c8d2b3517_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_7596d4f5170c8d2b3517_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "ddaefb5fdb0fe04f4639769676611a4b5e334759560955d2fe8cdcf625899f4a",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8a3827518db03a3df438": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8a3827518db03a3df438_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8a3827518db03a3df438_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c3571fe58594712a4cba701c60a8ca63f522b298df9ed755ad920c113c5e70e2",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8d08ed15707e24cd6dac": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8d08ed15707e24cd6dac_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_8d08ed15707e24cd6dac_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7183436528d8ad76bb1cd90fb9664f71acb6ebe4f4932d66b52dffe5ae7e7eac",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_8f6b39413714926d59be": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8f6b39413714926d59be_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_8f6b39413714926d59be_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "61f512f1d8f0fb43d13420b5274c31610531ef3f29370a3cd508aff8f0bfc387",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_a7c4b9a2116fb996b2c4": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_a7c4b9a2116fb996b2c4_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_a7c4b9a2116fb996b2c4_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2a0866eb945de787499434157044f7e0becfb5b8d1b7589db432e4cae42b6cd5",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_ada8d32600e57c228b66": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ada8d32600e57c228b66_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_100a/cake_kimi_k3_fp8_projection_ada8d32600e57c228b66_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "97e0b164d3bf180979dea81440c83a25f51c8372f1e871de291126060a683495",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "SFA"],
            ["tma_buffer", "SFB"],
            ["buffer", "out"],
            ["tma_buffer", "OUT"],
            ["parameter", "M"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "store_vec"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "05eb78cf99ae9f56043ce5007d85d3f93d2b12a92ebecc1bf213f758dcb5eeed",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_bb073dff237d9efa1adc": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_bb073dff237d9efa1adc_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_bb073dff237d9efa1adc_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "dc4561e48d2e855305e6a7bdd4000a32addd5a995c9e32c8e3888cf4e9bf1d92",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_c4c3bf6737661af0248e": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c4c3bf6737661af0248e_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_c4c3bf6737661af0248e_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a20e3dc4b88d7f0c1bfd8b4b805130aa962d279c109c260e1fe77dab8a32f7aa",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_d7c1caa7b0f67ad250df": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_d7c1caa7b0f67ad250df_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_d7c1caa7b0f67ad250df_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7220803adee43616c452bffbe06e5c3938ee6fe084eafc7683f9d5116b96608e",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "x"],
            ["buffer", "a_q"],
            ["buffer", "a_sf"],
            ["parameter", "M"],
            ["parameter", "K"],
            ["parameter", "units_per_row"],
            ["parameter", "sf_k_sets"],
            ["parameter", "sf_rows"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "14c71a8e4413f10f1a2f230632082493f512fc7a9cf9d41e2339633996e90c8b",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_e4f401c8686b0a1990ec": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_e4f401c8686b0a1990ec_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_e4f401c8686b0a1990ec_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a922eaaadc5fc216f9f802bcf17f037e66a768560ea2d77f64f93818533a8555",
        "tma_workspace_bytes": 0,
    },
    "cake_kimi_k3_fp8_projection_f8a70558689c2bbf9c57": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_f8a70558689c2bbf9c57_kernel.cu",
            "cake_kimi_k3_fp8_projection/sm_103a/cake_kimi_k3_fp8_projection_f8a70558689c2bbf9c57_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "W"],
            ["tma_buffer", "X"],
            ["tma_buffer", "SFW"],
            ["tma_buffer", "SFX"],
            ["buffer", "out"],
            ["buffer", "partials"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "n_tiles"],
            ["parameter", "n_valid"],
            ["parameter", "ldo"],
            ["parameter", "num_k_iters"],
            ["parameter", "sf_k_tiles"],
            ["parameter", "split"],
            ["parameter", "tok_per_cta"],
            ["parameter", "total_work"],
            ["parameter", "store_vec"],
            ["buffer", "x"],
            ["parameter", "K"],
            ["tma_buffer", "XB"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "5e49837a99c49e6f10a49dd7fd7548c058032beba49ce6560fe2be3a24c22fc6",
        "tma_workspace_bytes": 0,
    },
}
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "decode:t128_p3": "cake_kimi_k3_fp8_projection_1c708dfcbfe9c984f9c1",
        "decode:t16_p4": "cake_kimi_k3_fp8_projection_59eaf113c1017ac11185",
        "decode:t16_p4_fused": "cake_kimi_k3_fp8_projection_00739ad64bc792e627df",
        "decode:t16_p4_fused_q8": "cake_kimi_k3_fp8_projection_69dbd7f54be92e929682",
        "decode:t32_p3_fused_r5_q4": "cake_kimi_k3_fp8_projection_07858805ef7c25803dbe",
        "decode:t32_p3_fused_res": "cake_kimi_k3_fp8_projection_0d1f3e1fce0542d045a7",
        "decode:t32_p4": "cake_kimi_k3_fp8_projection_1854b1b35222ad1788bf",
        "decode:t64_p2_fused_r3_q4": "cake_kimi_k3_fp8_projection_57561222edd2b892d6cc",
        "decode:t64_p2_fused_res": "cake_kimi_k3_fp8_projection_51111fd6e2d6560472d3",
        "decode:t64_p4": "cake_kimi_k3_fp8_projection_7596d4f5170c8d2b3517",
        "gemm": "cake_kimi_k3_fp8_projection_ada8d32600e57c228b66",
        "gemm_tstore": "cake_kimi_k3_fp8_projection_10e9c8285c31ff891e3d",
        "quant:u1": "cake_kimi_k3_fp8_projection_8f6b39413714926d59be",
        "quant:u2": "cake_kimi_k3_fp8_projection_2d05aaceaff566db5e6f",
        "quant:u4": "cake_kimi_k3_fp8_projection_74d5179e703e2a8fd363",
    },
    "sm_103a": {
        "decode:t128_p3": "cake_kimi_k3_fp8_projection_d7c1caa7b0f67ad250df",
        "decode:t16_p4": "cake_kimi_k3_fp8_projection_56e0f36deb71d340ce0d",
        "decode:t16_p4_fused": "cake_kimi_k3_fp8_projection_e4f401c8686b0a1990ec",
        "decode:t16_p4_fused_q8": "cake_kimi_k3_fp8_projection_a7c4b9a2116fb996b2c4",
        "decode:t32_p3_fused_r5_q4": "cake_kimi_k3_fp8_projection_bb073dff237d9efa1adc",
        "decode:t32_p3_fused_res": "cake_kimi_k3_fp8_projection_c4c3bf6737661af0248e",
        "decode:t32_p4": "cake_kimi_k3_fp8_projection_8d08ed15707e24cd6dac",
        "decode:t64_p2_fused_r3_q4": "cake_kimi_k3_fp8_projection_f8a70558689c2bbf9c57",
        "decode:t64_p2_fused_res": "cake_kimi_k3_fp8_projection_8a3827518db03a3df438",
        "decode:t64_p4": "cake_kimi_k3_fp8_projection_055d89bbf1c9a2ed23f6",
        "gemm": "cake_kimi_k3_fp8_projection_b0e896ab028b7e06cbd8",
        "gemm_tstore": "cake_kimi_k3_fp8_projection_614b479ad56eced96ef2",
        "quant:u1": "cake_kimi_k3_fp8_projection_138c7e2e869a32d57e0a",
        "quant:u2": "cake_kimi_k3_fp8_projection_dde80e626d9e542b79e6",
        "quant:u4": "cake_kimi_k3_fp8_projection_2d4792b887fd11182967",
    },
}

ARCHES = ("sm_100a", "sm_103a")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}

GEMM_KERNEL_KEY = "gemm"  # register epilogue (any even output row stride)
GEMM_TSTORE_KERNEL_KEY = (
    "gemm_tstore"  # TMA-store epilogue (16-byte output base, row stride, column edge)
)


def quant_kernel_key(units: int) -> str:
    return f"quant:u{int(units)}"


def decode_kernel_key(
    tok: int,
    stages: int,
    fused: bool,
    resident: bool,
    xb_stages: int = 0,
    qlanes: int = 16,
) -> str:
    key = f"decode:t{int(tok)}_p{int(stages)}"
    if fused:
        key += "_fused"
    if resident:
        key += "_res"
    if xb_stages:
        key += f"_r{int(xb_stages)}"
    if qlanes != 16:
        key += f"_q{int(qlanes)}"
    return key


def route_available(arch: str, required_keys: tuple[str, ...] = ()) -> bool:
    """True when ``arch`` is registered and carries every key in ``required_keys``."""
    table = KERNELS.get(arch)
    return table is not None and all(key in table for key in required_keys)


def kernel_module_name(arch: str, key: str) -> str:
    """Return the registered physical module for ``key`` on ``arch``."""
    table = KERNELS.get(arch)
    if table is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 FP8 projection programs for {arch} are not "
            "registered in this checkout yet (see flashinfer-ai/flashinfer#4568)"
        )
    name = table.get(key)
    if name is None:
        raise NotImplementedError(
            f"The generated Kimi-K3 FP8 projection kernel {key!r} for {arch} is not "
            "registered in this checkout (see flashinfer-ai/flashinfer#4568)"
        )
    record = MODULES[name]
    if record["arch"] != arch:
        raise RuntimeError(
            f"registered module {name!r} is an {record['arch']} program bound to {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_kimi_k3_fp8_projection_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_kimi_k3_fp8_projection_module(name: str):
    return gen_cake_kimi_k3_fp8_projection_module(name).build_and_load()
