/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by cake.codegen — do not edit.
// Shared device preamble of the sm_100a, sm_103a generated kernels: typedefs, tensor-map ABI
// and the union of their compiler helper libraries (128 modules); translation-unit-local
// includes (cooperative groups) stay in the kernels that use them.
#pragma once

typedef signed char        int8_t;
typedef unsigned char      uint8_t;
typedef unsigned short     uint16_t;
typedef unsigned int       uint32_t;
#if defined(__CUDACC_RTC__)
typedef unsigned long long uint64_t;
#else
typedef unsigned long      uint64_t;
#endif
static_assert(sizeof(uint64_t) == 8, "Cake requires an LP64 CUDA host ABI");
typedef signed int         int32_t;
typedef short int          int16_t;
struct __align__(64) CakeTensorMap64 { uint64_t opaque[16]; };
static_assert(sizeof(CakeTensorMap64) == 128, "64-aligned tensor-map ABI size");
static_assert(alignof(CakeTensorMap64) == 64, "64-aligned tensor-map ABI alignment");

#if defined(__CUDACC_RTC__)
typedef struct __align__(128) { uint64_t opaque[16]; } CUtensorMap;
#else
#include <cuda.h>
#endif

static_assert(sizeof(CUtensorMap) == 128, "CUtensorMap CUDA ABI must be 128 bytes");
#include <cuda_bf16.h>
#include <cuda_fp8.h>

#include "cake_device_helpers/cake_make_warp_uniform_15c3664d3e11e8cd.cuh"
#include <math_constants.h>
#include "cake_device_helpers/cake_elect_sync_1ee8cd91025d8932.cuh"
#include "cake_device_helpers/cake_mbarrier_init_15e581aef85ee586.cuh"
#include "cake_device_helpers/cake_mbarrier_wait_c93bf7e39b218733.cuh"
#include "cake_device_helpers/cake_tcgen05_mma_mxf8_bs_d9fb9a2cd9410ea1.cuh"
#include "cake_device_helpers/cake_desc_encode_a56f6347f8d37641.cuh"
union MmaSmemDesc {
    uint64_t u64;
    uint32_t u32[2];
};
#include "cake_device_helpers/cake_elect_commit_8131fdc67daf4d23.cuh"
#include "cake_device_helpers/cake_elect_commit_cg1_multicast_03e58d5b99c690fd.cuh"
#include "cake_device_helpers/cake_mbarrier_arrive_71ef360c3ac78eb7.cuh"
#include "cake_device_helpers/cake_mbarrier_arrive_expect_tx_54ce59d489f69526.cuh"
#include "cake_device_helpers/cake_make_sf_cp_desc_lo_sbo128_d7bc33f4814285f6.cuh"
#include "cake_device_helpers/cake_tcgen05_cp_32x128b_warpx4_889f02d6972847cb.cuh"
#include "cake_device_helpers/cake_tma_3d_gmem2smem_7df1e07811f83fc6.cuh"
#include "cake_device_helpers/cake_tma_store_2d_d8ce2704cc6b8732.cuh"
#include "cake_device_helpers/cake_mbarrier_wait_cluster_hint_bdb29a0e36dedbee.cuh"
#include "cake_device_helpers/cake_tcgen05_mma_mxf8_bs_cta2_6dfcd6345e880a14.cuh"
#include "cake_device_helpers/cake_elect_commit_cg2_multicast_18e7b4ad8e69c467.cuh"
#include "cake_device_helpers/cake_tcgen05_cp_32x128b_warpx4_cta2_d56d930686a205c4.cuh"
#include "cake_device_helpers/cake_tma_3d_gmem2smem_cta2_dcd29ed146891990.cuh"
#include "cake_device_helpers/cake_tmem_st_x16_f32_44948ad68a2365fa.cuh"
#include "cake_device_helpers/cake_max_noftz_a41d70352450a2c9.cuh"
#include "cake_device_helpers/cake_mul_f32x2_inplace_0f243a1e0030d755.cuh"
// ex2_emulation_f32x2 defined in softmax_frag_exp2_cast helper (or standalone)
#include "cake_device_helpers/cake_tmem_ld_x16_a9ed61940fdba296.cuh"
