// Generated by Cake — do not edit.
// tvm-ffi host launcher for Cake kernel 'kernel_factorized_packed_varlen_metadata'.
#include <cuda.h>
#include <cuda_runtime.h>
#include <tvm/ffi/container/tensor.h>
#include <tvm/ffi/error.h>
#include <tvm/ffi/extra/c_env_api.h>
#include <tvm/ffi/extra/cuda/cubin_launcher.h>
#include <tvm/ffi/function.h>

#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

TVM_FFI_EMBED_CUBIN(factorized_packed_varlen_metadata_984da5abcd);

namespace cake_host_shim {

using tvm::ffi::TensorView;

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(const TensorView& t, const TensorView& reference, const char* name,
                                const char* reference_name) {
  TVM_FFI_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id << " versus cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  TVM_FFI_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_CHECK(step > 0, ValueError) << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis) << ", expected "
          << expected;
    }
  }
}

void Run(TensorView arg_seq_idx_i32, TensorView arg_seq_idx_i64, TensorView arg_chunk_indices,
         TensorView arg_chunk_offsets, TensorView arg_segment_starts,
         TensorView arg_segment_lengths, TensorView arg_sequence_offsets, int64_t arg_num_segments,
         int64_t arg_num_sequences, int64_t arg_seqlen, int64_t arg_seq_idx_int64, int64_t grid_x,
         int64_t grid_y, int64_t grid_z) {
  CheckCudaTensor(arg_seq_idx_i32, "seq_idx_i32");
  CheckDtype(arg_seq_idx_i32, "seq_idx_i32", 0, 32, 1);
  CheckContiguous(arg_seq_idx_i32, "seq_idx_i32");
  CheckCudaTensor(arg_seq_idx_i64, "seq_idx_i64");
  CheckDtype(arg_seq_idx_i64, "seq_idx_i64", 0, 64, 1);
  CheckContiguous(arg_seq_idx_i64, "seq_idx_i64");
  CheckCudaTensor(arg_chunk_indices, "chunk_indices");
  CheckDtype(arg_chunk_indices, "chunk_indices", 0, 32, 1);
  CheckContiguous(arg_chunk_indices, "chunk_indices");
  CheckCudaTensor(arg_chunk_offsets, "chunk_offsets");
  CheckDtype(arg_chunk_offsets, "chunk_offsets", 0, 32, 1);
  CheckContiguous(arg_chunk_offsets, "chunk_offsets");
  CheckCudaTensor(arg_segment_starts, "segment_starts");
  CheckDtype(arg_segment_starts, "segment_starts", 0, 32, 1);
  CheckContiguous(arg_segment_starts, "segment_starts");
  CheckCudaTensor(arg_segment_lengths, "segment_lengths");
  CheckDtype(arg_segment_lengths, "segment_lengths", 0, 32, 1);
  CheckContiguous(arg_segment_lengths, "segment_lengths");
  CheckCudaTensor(arg_sequence_offsets, "sequence_offsets");
  CheckDtype(arg_sequence_offsets, "sequence_offsets", 0, 32, 1);
  CheckContiguous(arg_sequence_offsets, "sequence_offsets");
  TVM_FFI_CHECK(arg_num_segments >= -2147483648LL && arg_num_segments <= 2147483647LL, ValueError)
      << "scalar 'num_segments' value " << arg_num_segments
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_num_sequences >= -2147483648LL && arg_num_sequences <= 2147483647LL, ValueError)
      << "scalar 'num_sequences' value " << arg_num_sequences
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_seqlen >= -2147483648LL && arg_seqlen <= 2147483647LL, ValueError)
      << "scalar 'seqlen' value " << arg_seqlen
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_seq_idx_int64 >= -2147483648LL && arg_seq_idx_int64 <= 2147483647LL, ValueError)
      << "scalar 'seq_idx_int64' value " << arg_seq_idx_int64
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_seq_idx_i64, arg_seq_idx_i32, "seq_idx_i64", "seq_idx_i32");
  CheckSameCudaDevice(arg_chunk_indices, arg_seq_idx_i32, "chunk_indices", "seq_idx_i32");
  CheckSameCudaDevice(arg_chunk_offsets, arg_seq_idx_i32, "chunk_offsets", "seq_idx_i32");
  CheckSameCudaDevice(arg_segment_starts, arg_seq_idx_i32, "segment_starts", "seq_idx_i32");
  CheckSameCudaDevice(arg_segment_lengths, arg_seq_idx_i32, "segment_lengths", "seq_idx_i32");
  CheckSameCudaDevice(arg_sequence_offsets, arg_seq_idx_i32, "sequence_offsets", "seq_idx_i32");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y << ", "
      << grid_z << ")";

  DLDevice dev = arg_seq_idx_i32.device();
  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  void* p_seq_idx_i32 = arg_seq_idx_i32.data_ptr();
  void* p_seq_idx_i64 = arg_seq_idx_i64.data_ptr();
  void* p_chunk_indices = arg_chunk_indices.data_ptr();
  void* p_chunk_offsets = arg_chunk_offsets.data_ptr();
  void* p_segment_starts = arg_segment_starts.data_ptr();
  void* p_segment_lengths = arg_segment_lengths.data_ptr();
  void* p_sequence_offsets = arg_sequence_offsets.data_ptr();
  int32_t v_num_segments = (int32_t)arg_num_segments;
  int32_t v_num_sequences = (int32_t)arg_num_sequences;
  int32_t v_seqlen = (int32_t)arg_seqlen;
  int32_t v_seq_idx_int64 = (int32_t)arg_seq_idx_int64;
  void* kargs[] = {&p_seq_idx_i32,    &p_seq_idx_i64,     &p_chunk_indices,    &p_chunk_offsets,
                   &p_segment_starts, &p_segment_lengths, &p_sequence_offsets, &v_num_segments,
                   &v_num_sequences,  &v_seqlen,          &v_seq_idx_int64};

  static auto kernel = TVM_FFI_EMBED_CUBIN_GET_KERNEL(factorized_packed_varlen_metadata_984da5abcd,
                                                      "kernel_factorized_packed_varlen_metadata");
  tvm::ffi::dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  tvm::ffi::dim3 block(128u, 1u, 1u);

  TVM_FFI_CHECK_CUBIN_LAUNCHER_CUDA_ERROR(kernel.Launch(kargs, grid, block, stream, 0u));
}

}  // namespace cake_host_shim

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim::Run);
