/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_dsa_indexer_topk_219065b3049d18cbe817'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <cstdint>

extern "C" __global__ void kernel_cake_dsa_indexer_topk_219065b3049d18cbe817(int* __restrict__ Indices, float* __restrict__ Scores, int top_k);


namespace cake_host_shim_fe38f4dbd8b7abbe {

using tvm::ffi::TensorView;

void Run(TensorView arg_Indices, TensorView arg_Scores, int64_t arg_top_k, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_Indices.device();
  tvm::ffi::CUDADeviceGuard device_guard(dev.device_id);
  check_cuda_tensor(arg_Indices, "Indices");
  check_dtype(arg_Indices, DLDataType{kDLInt, 32, 1}, "Indices");
  check_contiguous(arg_Indices, "Indices");
  check_cuda_tensor(arg_Scores, "Scores");
  check_dtype(arg_Scores, DLDataType{kDLFloat, 32, 1}, "Scores");
  check_contiguous(arg_Scores, "Scores");
  TVM_FFI_CHECK(arg_top_k >= -2147483648LL && arg_top_k <= 2147483647LL, ValueError)
      << "scalar 'top_k' value " << arg_top_k
      << " is outside i32 range [-2147483648, 2147483647]";
  check_same_device(arg_Scores, arg_Indices, "Scores", "Indices");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  int* p_Indices = static_cast<int*>(arg_Indices.data_ptr());
  float* p_Scores = static_cast<float*>(arg_Scores.data_ptr());
  int32_t v_top_k = (int32_t)arg_top_k;
  void* kargs[] = {&p_Indices, &p_Scores, &v_top_k};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaError_t launch_status = cudaLaunchKernel(
      reinterpret_cast<const void*>(kernel_cake_dsa_indexer_topk_219065b3049d18cbe817), grid, block, kargs, 40960u, stream);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernel for kernel_cake_dsa_indexer_topk_219065b3049d18cbe817 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_fe38f4dbd8b7abbe

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_fe38f4dbd8b7abbe::Run);
