# Copyright (c) 2026 by FlashInfer team.
# Generated sources retain uniform imports and DSL SSA temporaries.
# ruff: noqa: F401, F841
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generated by Cake's CuTe DSL backend.  Do not edit."""

from __future__ import annotations

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
from cutlass._mlir import ir as cutlass_ir
from cutlass._mlir.dialects import arith as cutlass_arith
from cutlass._mlir.dialects import llvm as cutlass_llvm
from cutlass._mlir.dialects import nvvm as cutlass_nvvm
from cutlass._mlir.dialects import cuda as cutlass_cuda
from cutlass.cute.runtime import make_fake_stream, make_fake_tensor
from cutlass.experimental import primitives as prims
from cutlass.experimental.primitives import nvvm_wrapper as prims_nvvm
from cutlass.utils import blackwell_helpers as cutlass_blackwell
from cutlass.utils import hopper_helpers as cutlass_hopper
from cutlass.utils.layout import LayoutEnum as CutlassLayout
from cutlass.utils import blockscaled_layout as cutlass_blockscaled
from cutlass.experimental.cuda.tensor_map import (
    TensorMap,
    TensorMapDataFormat,
    TensorMapFloatOOBFill,
    TensorMapL2Promotion,
    TensorMapSwizzle,
    create_tensor_map_tiled,
)
from cutlass._mlir.dialects.nvvm import CTAGroupKind as DialectCTAGroup
from cutlass._mlir.dialects.nvvm import TMALoadMode as DialectTMALoadMode

NUM_MAIN_STAGES = 1
THREADS = 128
CAKE_TARGET_ARCH = "sm_103a"
CAKE_SMEM_BYTES = 0


@cute.kernel
def kernel_cake_mxfp8_megamoe_ep16_topk_reduce(
    route_terms_bf16: cute.Pointer,
    output_bf16: cute.Pointer,
    tokens_per_rank: cutlass.Int32,
):
    tid = cutlass.Int32(cute.arch.thread_idx()[0])
    warp = cutlass.Int32(cute.arch.warp_idx())
    lane = cutlass.Int32(cute.arch.lane_idx())
    bid = cutlass.Int32(cute.arch.block_idx()[0])
    num_bids = cutlass.Int32(cute.arch.grid_dim()[0])
    blockIdx = cute.arch.block_idx()
    gridDim = cute.arch.grid_dim()
    _flat_layout = cute.make_layout((2147483647,), stride=(1,))
    _route_terms_bf16 = cute.make_tensor(route_terms_bf16, _flat_layout)
    _output_bf16 = cute.make_tensor(output_bf16, _flat_layout)
    worker = cutlass.Int32(((bid * 128) + tid))
    total_workers = cutlass.Int32((tokens_per_rank * 384))
    if worker < total_workers:
        token = cutlass.Int32(
            cutlass.Int32(
                cutlass_arith.divsi(
                    cutlass.Int32(worker).ir_value(), cutlass.Int32(384).ir_value()
                )
            )
        )
        hidden_tile = cutlass.Int32((worker - (token * 384)))
        column = cutlass.Int32((hidden_tile * 8))
        route_base = cutlass.Uint64(
            (((cutlass.Uint64(token) * 8) * 3072) + cutlass.Uint64(column))
        )
        _gmem_load_0 = prims.load_ext(
            route_terms_bf16 + route_base, dtype=cutlass.Int16, count=8
        )
        _gmem_load_f32_1 = _gmem_load_0.bitcast(cutlass.BFloat16).to(cutlass.Float32)
        _vec_load_0 = cute.make_rmem_tensor((8,), cutlass.Float32)
        _vec_load_0[0] = _gmem_load_f32_1[0]
        _vec_load_0[1] = _gmem_load_f32_1[1]
        _vec_load_0[2] = _gmem_load_f32_1[2]
        _vec_load_0[3] = _gmem_load_f32_1[3]
        _vec_load_0[4] = _gmem_load_f32_1[4]
        _vec_load_0[5] = _gmem_load_f32_1[5]
        _vec_load_0[6] = _gmem_load_f32_1[6]
        _vec_load_0[7] = _gmem_load_f32_1[7]
        accum = cute.make_rmem_tensor((8,), cutlass.Float32)
        for element in cutlass.range_constexpr(0, 8, 1):
            accum[element] = cutlass.Float32(_vec_load_0[element])
        for route_slot in cutlass.range_constexpr(1, 8, 1):
            _gmem_load_2 = prims.load_ext(
                route_terms_bf16 + (route_base + cutlass.Uint64((route_slot * 3072))),
                dtype=cutlass.Int16,
                count=8,
            )
            _gmem_load_f32_3 = _gmem_load_2.bitcast(cutlass.BFloat16).to(
                cutlass.Float32
            )
            _vec_load_1 = cute.make_rmem_tensor((8,), cutlass.Float32)
            _vec_load_1[0] = _gmem_load_f32_3[0]
            _vec_load_1[1] = _gmem_load_f32_3[1]
            _vec_load_1[2] = _gmem_load_f32_3[2]
            _vec_load_1[3] = _gmem_load_f32_3[3]
            _vec_load_1[4] = _gmem_load_f32_3[4]
            _vec_load_1[5] = _gmem_load_f32_3[5]
            _vec_load_1[6] = _gmem_load_f32_3[6]
            _vec_load_1[7] = _gmem_load_f32_3[7]
            for element_1 in cutlass.range_constexpr(0, 8, 1):
                accum[element_1] = cutlass.Float32(
                    (accum[element_1] + _vec_load_1[element_1])
                )
        _gmem_store_f32_4 = cutlass.Vector.from_elements(
            [
                cutlass.Float32(accum[0]),
                cutlass.Float32(accum[1]),
                cutlass.Float32(accum[2]),
                cutlass.Float32(accum[3]),
                cutlass.Float32(accum[4]),
                cutlass.Float32(accum[5]),
                cutlass.Float32(accum[6]),
                cutlass.Float32(accum[7]),
            ],
            cutlass.Float32,
        )
        _gmem_store_f16x2_5 = _gmem_store_f32_4.to(cutlass.BFloat16).bitcast(
            cutlass.Int16
        )
        prims.store_ext(
            _gmem_store_f16x2_5.ir_value(),
            cute.recast_ptr(
                output_bf16 + ((cutlass.Uint64(token) * 3072) + cutlass.Uint64(column)),
                dtype=cutlass.Int16,
            )
            + (0)
            + 0,
        )


@cute.jit
def launch_cake_mxfp8_megamoe_ep16_topk_reduce(
    route_terms_bf16: cute.Tensor,
    output_bf16: cute.Tensor,
    tokens_per_rank: cutlass.Int32,
    grid_x: cutlass.Int32,
    grid_y: cutlass.Int32,
    grid_z: cutlass.Int32,
    stream: cuda.CUstream,
):
    kernel_cake_mxfp8_megamoe_ep16_topk_reduce(
        route_terms_bf16.iterator, output_bf16.iterator, tokens_per_rank
    ).launch(
        grid=(grid_x, grid_y, grid_z),
        block=(128, 1, 1),
        stream=stream,
    )


def compile_program():
    return cute.compile(
        launch_cake_mxfp8_megamoe_ep16_topk_reduce,
        make_fake_tensor(
            cutlass.BFloat16,
            (cute.sym_int64(symbol="route_terms_bf16"),),
            (1,),
            assumed_align=16,
        ),
        make_fake_tensor(
            cutlass.BFloat16,
            (cute.sym_int64(symbol="output_bf16"),),
            (1,),
            assumed_align=16,
        ),
        cutlass.Int32(0),
        cutlass.Int32(1),
        cutlass.Int32(1),
        cutlass.Int32(1),
        make_fake_stream(use_tvm_ffi_env_stream=True),
        options="--enable-tvm-ffi --ptxas-options=--opt-level=3 --gpu-arch=sm_103a",
    )
