# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Shared fixtures for the mamba test suite.

Pre-compiles the ``checkpointing_ssu`` JIT variants the tests exercise in a
single batched ninja invocation. ``checkpointing_ssu`` is not part of the AOT
``flashinfer-jit-cache`` package, so a fresh CI container otherwise compiles
each variant serially on first touch (~60s each x ~40 variants dominates the
suite's wall time). Batch-building lets ninja schedule all of them in
parallel across cores, and is a near-free no-op when the modules are already
present in the JIT disk cache.
"""

import torch

# Every (state_dtype, input_dtype, dt_dtype, weight_dtype, matrixA_dtype,
# stateIndex_dtype, state_scale_dtype, dim, dstate, npredicted, max_window,
# heads_per_group, philox_rounds, enable_pdl) combination requested by
# tests/mamba/test_checkpointing_ssu.py, captured by instrumenting
# flashinfer.mamba.checkpointing_ssu._get_module over a full run of the file.
# Keep in sync when adding parametrizations: a missing entry is harmless (the
# test falls back to a serial first-touch compile), just slower.
_CHECKPOINTING_SSU_VARIANTS = [
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        10,
        16,
        16,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        16,
        16,
        16,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        16,
        16,
        8,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        16,
        16,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        8,
        16,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        6,
        6,
        16,
        0,
        False,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        6,
        6,
        16,
        0,
        True,
    ),
    (
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        8,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        10,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        10,
        16,
        16,
        10,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        14,
        16,
        16,
        10,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        16,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        16,
        16,
        16,
        10,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        8,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        8,
        16,
        10,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        6,
        6,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        6,
        6,
        16,
        10,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        8,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float16,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        8,
        16,
        64,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        10,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        16,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        4,
        8,
        16,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        6,
        6,
        16,
        0,
        False,
    ),
    (
        torch.float32,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        None,
        64,
        128,
        8,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        16,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        16,
        16,
        16,
        10,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        4,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        0,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        10,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        5,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        5,
        True,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        8,
        16,
        16,
        0,
        False,
    ),
    (
        torch.float8_e4m3fn,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        8,
        16,
        64,
        0,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        1,
        1,
        16,
        0,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        1,
        1,
        16,
        5,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        16,
        16,
        16,
        0,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        16,
        16,
        16,
        10,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        4,
        16,
        16,
        0,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        0,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        6,
        6,
        16,
        10,
        False,
    ),
    (
        torch.int8,
        torch.bfloat16,
        torch.bfloat16,
        torch.bfloat16,
        torch.float32,
        torch.int32,
        torch.float32,
        64,
        128,
        8,
        16,
        16,
        0,
        False,
    ),
]

# Only prewarm when a substantial chunk of the checkpointing suite is about to
# run; a developer running one or two tests should not wait for 43 modules.
_PREWARM_MIN_TESTS = 8


def pytest_collection_modifyitems(config, items):
    n_checkpointing = sum(
        1 for item in items if "test_checkpointing_ssu" in item.nodeid
    )
    if n_checkpointing < _PREWARM_MIN_TESTS:
        return

    import concurrent.futures
    import contextlib
    import os
    import warnings

    from flashinfer.jit.mamba.checkpointing_ssu import gen_checkpointing_ssu_module

    # The prewarm is purely an optimization: any failure below degrades to
    # the normal serial first-touch JIT compile at test time (where a real
    # build error will surface attributed to the test that needs the module),
    # and must never abort collection.
    try:
        # Skip variants whose .so already exists (warm JIT cache / AOT package).
        specs = [
            spec
            for spec in (
                gen_checkpointing_ssu_module(*variant)
                for variant in _CHECKPOINTING_SSU_VARIANTS
            )
            if not spec.get_library_path().exists()
        ]
    except Exception as exc:  # noqa: BLE001 — best-effort prewarm
        warnings.warn(
            f"checkpointing_ssu prewarm skipped (spec generation failed): {exc}",
            stacklevel=2,
        )
        return
    if not specs:
        return

    # Build missing modules through the standard per-module path (spec.build),
    # parallelized with a thread pool. Do NOT use build_jit_specs() here: its
    # single batched ninja invocation records commands in the cache root's
    # .ninja_log, while each module's build.ninja sets builddir to the module
    # directory — so the per-test build_and_load() would find no log entries
    # for the batch-built outputs and recompile every module serially again.
    #
    # Concurrency: total concurrent compiler processes ~= pool workers x
    # per-module ninja jobs (MAX_JOBS). Scale both from the core count so
    # small CI runners are not oversubscribed, and treat a pre-set MAX_JOBS
    # (the documented total ninja-job budget) as a cap.
    prev_max_jobs = os.environ.get("MAX_JOBS")
    total_jobs = os.cpu_count() or 4
    if prev_max_jobs:
        with contextlib.suppress(ValueError):
            total_jobs = min(total_jobs, max(1, int(prev_max_jobs)))
    max_workers = max(1, total_jobs // 2)
    os.environ["MAX_JOBS"] = str(max(1, total_jobs // max_workers))
    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {pool.submit(spec.build, verbose=False): spec for spec in specs}
            for fut in concurrent.futures.as_completed(futures):
                try:
                    fut.result()
                except Exception as exc:  # noqa: BLE001 — best-effort prewarm
                    warnings.warn(
                        f"checkpointing_ssu prewarm build failed for "
                        f"{futures[fut].name}; affected tests fall back to "
                        f"serial first-touch JIT: {exc}",
                        stacklevel=2,
                    )
    finally:
        if prev_max_jobs is None:
            os.environ.pop("MAX_JOBS", None)
        else:
            os.environ["MAX_JOBS"] = prev_max_jobs
