"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import (
    gen_jit_spec,
    sm100a_nvcc_flags,
    sm103a_nvcc_flags,
    sm107a_nvcc_flags,
)

# Explicit target-owned registration of the generated GEMM programs.  One
# record per physical module = one traced kernel instance (``template``) per
# architecture.  A record carries ``arch``, the instance ``template`` (the
# symbol the host planner derives from the operand layouts, the tile width,
# the output kind, the epilogue path and the TMA L2 eviction hints -- see
# ``cake_backend.instance_symbol`` and ``cake_backend.router_symbol``; the
# prefetch / L2-promotion / stage-count knobs are part of the symbol too but
# sit at their defaults in every registered instance), the kernel symbol, the JIT cache name,
# the translation units, compile flags, the FFI entry, the argument plan the
# host binds by keyword, the caller-owned descriptor workspace size, the
# closure identity and the launch geometry baked into the module (block,
# cluster).  Populated verbatim by the generated-program export; do not edit
# by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_dense_projection_gemm_037abba0775871119206": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256_m256_g8",
        "kernel": "kernel_cake_dense_projection_gemm_037abba0775871119206",
        "cache_name": "cake_dense_projection_gemm_037abba0775871119206_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_037abba0775871119206_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_037abba0775871119206_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "ac0a137eca71248e9fcdd778f4d685af5d36537db0c2d8fa4c58d4551cb187f3",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_0f2e64f049da5daaeaab": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n128_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_0f2e64f049da5daaeaab",
        "cache_name": "cake_dense_projection_gemm_0f2e64f049da5daaeaab_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_0f2e64f049da5daaeaab_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_0f2e64f049da5daaeaab_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "3d8e8b2b7ee68b153b075b2387597bb93d259f366128cbfbf750eaa6e9238a40",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_10aae20b3f6c9e9abaad": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256",
        "kernel": "kernel_cake_dense_projection_gemm_10aae20b3f6c9e9abaad",
        "cache_name": "cake_dense_projection_gemm_10aae20b3f6c9e9abaad_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_10aae20b3f6c9e9abaad_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_10aae20b3f6c9e9abaad_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "7da9bd0f7ace415e4cab432e8e83ec012a198c8af7ec54b68e9184e1d902b333",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_14ca631112bde96fb49d": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_g8_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_14ca631112bde96fb49d",
        "cache_name": "cake_dense_projection_gemm_14ca631112bde96fb49d_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_14ca631112bde96fb49d_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_14ca631112bde96fb49d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "09e0bd5df8697910f11568789c575e5dc265a51133093ab7ec8baa8dd738f767",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_198be1c48e2c0cf6cab1": {
        "arch": "sm_100a",
        "template": "router_fp32_gemm_kn",
        "kernel": "kernel_cake_dense_projection_gemm_198be1c48e2c0cf6cab1",
        "cache_name": "cake_dense_projection_gemm_198be1c48e2c0cf6cab1_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_198be1c48e2c0cf6cab1_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_198be1c48e2c0cf6cab1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "cb28b43e3099d3eadba82a86a913055bf39b2b5e24716f27f1a52090fef3f00d",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_1c158d5e905f05e1c7de": {
        "arch": "sm_100a",
        "template": "router_fp32_gemm_kk",
        "kernel": "kernel_cake_dense_projection_gemm_1c158d5e905f05e1c7de",
        "cache_name": "cake_dense_projection_gemm_1c158d5e905f05e1c7de_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_1c158d5e905f05e1c7de_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_1c158d5e905f05e1c7de_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "e3d5d992f208c5a2b2c6286028f88334617ce175848a785ec25f7f6f934be616",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_1f9e164aad352c8dbb2d": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_1f9e164aad352c8dbb2d",
        "cache_name": "cake_dense_projection_gemm_1f9e164aad352c8dbb2d_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_1f9e164aad352c8dbb2d_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_1f9e164aad352c8dbb2d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "30aa1828dce9fae7a6db24765c71ecd272fab9c11197182b7d8199d98693af21",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_2339d2580e93b0d7afbb": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n128",
        "kernel": "kernel_cake_dense_projection_gemm_2339d2580e93b0d7afbb",
        "cache_name": "cake_dense_projection_gemm_2339d2580e93b0d7afbb_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_2339d2580e93b0d7afbb_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_2339d2580e93b0d7afbb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "c0b78171ea20e829b0ba257d6ef8ecf840718cb8e2fcc30e88c1c8da1eee3ff7",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_237d70b3b0008ff14a95": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_g32_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_237d70b3b0008ff14a95",
        "cache_name": "cake_dense_projection_gemm_237d70b3b0008ff14a95_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_237d70b3b0008ff14a95_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_237d70b3b0008ff14a95_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "6687a2edb0af06aef8ea6c6c88b6b1a026f2eb327a16f14d4a82dc1fae559a8a",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_256faf70a4552c580334": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n128_hen_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_256faf70a4552c580334",
        "cache_name": "cake_dense_projection_gemm_256faf70a4552c580334_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_256faf70a4552c580334_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_256faf70a4552c580334_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "9d2b940cfd3fa4da03ab68090a0f8bff4de7e16547d85650ab5c8dba8548b57e",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_2692ea1874dcba0f1bf1": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kk_n128",
        "kernel": "kernel_cake_dense_projection_gemm_2692ea1874dcba0f1bf1",
        "cache_name": "cake_dense_projection_gemm_2692ea1874dcba0f1bf1_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_2692ea1874dcba0f1bf1_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_2692ea1874dcba0f1bf1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "afe7c2938c1619ba345c36ee6f3e416328952f19f945c71274bbeda88710c03c",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_320bdc3905b3e481edf0": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n128_hen",
        "kernel": "kernel_cake_dense_projection_gemm_320bdc3905b3e481edf0",
        "cache_name": "cake_dense_projection_gemm_320bdc3905b3e481edf0_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_320bdc3905b3e481edf0_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_320bdc3905b3e481edf0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "cf1664988321355724182c5a9081253d07a692654c64601b205ff8bf57427887",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_4753c1d0b0bf457f9f4f": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256_g8",
        "kernel": "kernel_cake_dense_projection_gemm_4753c1d0b0bf457f9f4f",
        "cache_name": "cake_dense_projection_gemm_4753c1d0b0bf457f9f4f_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_4753c1d0b0bf457f9f4f_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_4753c1d0b0bf457f9f4f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "75d0e7a64bff55b2070a6fd723b90685fe09c19110e2a1f38a64e5d68a55d0e4",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_49a4e857ad292f1d8783": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_49a4e857ad292f1d8783",
        "cache_name": "cake_dense_projection_gemm_49a4e857ad292f1d8783_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_49a4e857ad292f1d8783_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_49a4e857ad292f1d8783_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "2e69b2d08339f5426a0f72a38228c4a00e0b4618a9e4b56a3be65d86ae3eb515",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_4acb28f3e94830b20e44": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_4acb28f3e94830b20e44",
        "cache_name": "cake_dense_projection_gemm_4acb28f3e94830b20e44_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_4acb28f3e94830b20e44_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_4acb28f3e94830b20e44_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "2a74041a81c085be5ed0d23f2118825cc389181ccbfd7788997fb0bc1a213e61",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_569e99278d9e5847f1ef": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kn_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_569e99278d9e5847f1ef",
        "cache_name": "cake_dense_projection_gemm_569e99278d9e5847f1ef_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_569e99278d9e5847f1ef_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_569e99278d9e5847f1ef_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "ac9a5d6a90a92e3a5e950fdefe0efff7935be1fc278ae7f7986ca0b8a6caf177",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_571821beb881bd498fba": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n128_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_571821beb881bd498fba",
        "cache_name": "cake_dense_projection_gemm_571821beb881bd498fba_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_571821beb881bd498fba_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_571821beb881bd498fba_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "dffbe79d2936779c07dafd80985788e032d450eb13cbdc022cd476a6ca66daf8",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_5cbd4982d30c70f8f49d": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n128_t",
        "kernel": "kernel_cake_dense_projection_gemm_5cbd4982d30c70f8f49d",
        "cache_name": "cake_dense_projection_gemm_5cbd4982d30c70f8f49d_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5cbd4982d30c70f8f49d_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5cbd4982d30c70f8f49d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "216686696eaba7d024f55737e61c2d5fbb30b23a47df983b323a00ea569f3c07",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_5ce01f0a1d31f78e535f": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_m256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_5ce01f0a1d31f78e535f",
        "cache_name": "cake_dense_projection_gemm_5ce01f0a1d31f78e535f_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5ce01f0a1d31f78e535f_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5ce01f0a1d31f78e535f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "766ada447eeb0878b8928b4df2b89fe9944853418c15f5e7d034d07eb748a270",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_5e16f8d63324490f7843": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kk_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_5e16f8d63324490f7843",
        "cache_name": "cake_dense_projection_gemm_5e16f8d63324490f7843_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_5e16f8d63324490f7843_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_5e16f8d63324490f7843_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "21402c469b1274ed435bf742764ee40eef6a7c5f307b3ad1e579ccdf60e18b91",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_5e3e3be440f3cc598ee3": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_5e3e3be440f3cc598ee3",
        "cache_name": "cake_dense_projection_gemm_5e3e3be440f3cc598ee3_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5e3e3be440f3cc598ee3_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5e3e3be440f3cc598ee3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "87f9d298b64d9d8c6d7c46be4c18905eef139a8e76704066ba5a6e059a64fa10",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_5e407b1e668e2a88744a": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n128_hen_t",
        "kernel": "kernel_cake_dense_projection_gemm_5e407b1e668e2a88744a",
        "cache_name": "cake_dense_projection_gemm_5e407b1e668e2a88744a_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5e407b1e668e2a88744a_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_5e407b1e668e2a88744a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "3ac7fcf1903c69e4818e64a0a2f12c5cd701dd7cb31d050f2075e471913b32a8",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_61e307d1404119637be9": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_61e307d1404119637be9",
        "cache_name": "cake_dense_projection_gemm_61e307d1404119637be9_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_61e307d1404119637be9_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_61e307d1404119637be9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "507f33235d1ae924e26f4b99455fa3f5af272f2bc9cac868826e30fbfe522639",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_646f26aa480af3ae73b8": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_m256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_646f26aa480af3ae73b8",
        "cache_name": "cake_dense_projection_gemm_646f26aa480af3ae73b8_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_646f26aa480af3ae73b8_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_646f26aa480af3ae73b8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "a35ef06b38d6dabd8ff24753052dac2c9e4c05c7ad5ad5cc3376386a39493568",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_655f3db3a9dac9eccd7f": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_g8_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_655f3db3a9dac9eccd7f",
        "cache_name": "cake_dense_projection_gemm_655f3db3a9dac9eccd7f_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_655f3db3a9dac9eccd7f_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_655f3db3a9dac9eccd7f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "eacc9613f3e70d659045856a6ba7b1a596c90d56a89762d0dbc972111be8ab54",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_6f0a761f21e7816084e6": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_m256_g8",
        "kernel": "kernel_cake_dense_projection_gemm_6f0a761f21e7816084e6",
        "cache_name": "cake_dense_projection_gemm_6f0a761f21e7816084e6_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_6f0a761f21e7816084e6_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_6f0a761f21e7816084e6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "1aa352edb9407af6b9f6481f9944f85f83eebcabb88d701f96653c92af9b04f9",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_79a6dfb1bd30afef2f90": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_79a6dfb1bd30afef2f90",
        "cache_name": "cake_dense_projection_gemm_79a6dfb1bd30afef2f90_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_79a6dfb1bd30afef2f90_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_79a6dfb1bd30afef2f90_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "4a0dcde6d329bea64286e4d874492480fb47d89012f2630755eee2fa3dd71b5c",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_7bc116c164a4780a91f8": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_7bc116c164a4780a91f8",
        "cache_name": "cake_dense_projection_gemm_7bc116c164a4780a91f8_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_7bc116c164a4780a91f8_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_7bc116c164a4780a91f8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "739e6a481ce89a758a0ed833d2f3d17d7bf5752a91f78ab4de7ac6b6a56cdc0c",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_7d0e7b1e86b036f9e169": {
        "arch": "sm_107a",
        "template": "router_fp32_gemm_nn_t",
        "kernel": "kernel_cake_dense_projection_gemm_7d0e7b1e86b036f9e169",
        "cache_name": "cake_dense_projection_gemm_7d0e7b1e86b036f9e169_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_7d0e7b1e86b036f9e169_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_7d0e7b1e86b036f9e169_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "056ada449e9352177a8c3ef12c1041a0f9e60b18f5e25f7d7b426b1d003cfcc7",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_7f431317df8e387aba36": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n128_hen_t",
        "kernel": "kernel_cake_dense_projection_gemm_7f431317df8e387aba36",
        "cache_name": "cake_dense_projection_gemm_7f431317df8e387aba36_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_7f431317df8e387aba36_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_7f431317df8e387aba36_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "99518aa4a27d0034b7d605808f19db8b0620bff800d1c3e9150b4453ac409e4f",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_8549d9785079ec66bce6": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n128_hen_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_8549d9785079ec66bce6",
        "cache_name": "cake_dense_projection_gemm_8549d9785079ec66bce6_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_8549d9785079ec66bce6_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_8549d9785079ec66bce6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "38dfb6151299a016facfcf94d6d182095dd0ad58b5aa0819fb2834ed6aa77282",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_89365ab74287536812ed": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_89365ab74287536812ed",
        "cache_name": "cake_dense_projection_gemm_89365ab74287536812ed_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_89365ab74287536812ed_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_89365ab74287536812ed_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "e17b4afb03289a98d0900670ac1579a51ffe7fa6bc6150785f4d9e2a673c4314",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_8cc57a37d91a4350ba7e": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_m256_t",
        "kernel": "kernel_cake_dense_projection_gemm_8cc57a37d91a4350ba7e",
        "cache_name": "cake_dense_projection_gemm_8cc57a37d91a4350ba7e_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_8cc57a37d91a4350ba7e_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_8cc57a37d91a4350ba7e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "d004a32547813f3cf0fedee7c4a6964b9dfb204d7b4adc3c4dc159259c0aad37",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_98e3827cd311e5a61581": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_98e3827cd311e5a61581",
        "cache_name": "cake_dense_projection_gemm_98e3827cd311e5a61581_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_98e3827cd311e5a61581_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_98e3827cd311e5a61581_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "0c114ace996d86f1917a44cb4171874a4fab59f0a0ede20f6c59d3b6a99ad487",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_a18aed8888505d2fde5d": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_g4",
        "kernel": "kernel_cake_dense_projection_gemm_a18aed8888505d2fde5d",
        "cache_name": "cake_dense_projection_gemm_a18aed8888505d2fde5d_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_a18aed8888505d2fde5d_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_a18aed8888505d2fde5d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "b9da66057e09decfbf32074ca1526efd30f8ffba1bc90e18bb7f84eea780a07a",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_a66d29304d002e6fedce": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256_g32",
        "kernel": "kernel_cake_dense_projection_gemm_a66d29304d002e6fedce",
        "cache_name": "cake_dense_projection_gemm_a66d29304d002e6fedce_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_a66d29304d002e6fedce_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_a66d29304d002e6fedce_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "148e884817d84d9c112f6e2cf8fd137175765df134b5be15a8736c57bc78fb92",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_ab84324a35238a2caec3": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kk_n256",
        "kernel": "kernel_cake_dense_projection_gemm_ab84324a35238a2caec3",
        "cache_name": "cake_dense_projection_gemm_ab84324a35238a2caec3_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_ab84324a35238a2caec3_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_ab84324a35238a2caec3_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "3a4d40457c8cd4dd6419e53e819a3978bee8f971524a0ab869f5650bd0342215",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_ae13b96e9d15c1aff3ad": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_m256_g8",
        "kernel": "kernel_cake_dense_projection_gemm_ae13b96e9d15c1aff3ad",
        "cache_name": "cake_dense_projection_gemm_ae13b96e9d15c1aff3ad_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_ae13b96e9d15c1aff3ad_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_ae13b96e9d15c1aff3ad_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "978c7b286d2705f995d8fe8735ac8e1f0d5deada1742cdd47e4718c06c364072",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_b1a93c14a58efb2a4f76": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_b1a93c14a58efb2a4f76",
        "cache_name": "cake_dense_projection_gemm_b1a93c14a58efb2a4f76_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_b1a93c14a58efb2a4f76_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_b1a93c14a58efb2a4f76_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "ddddb91885da199c81fd943217be7ad2d4ae76a2929a15dd2b2723423ff6011b",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf": {
        "arch": "sm_107a",
        "template": "router_fp32_gemm_kn",
        "kernel": "kernel_cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf",
        "cache_name": "cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "1388f98aecda8ac85460345f4cb35b6eb8ef2d91a75b469388ae3d4fd0114649",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_b6b1c7b42f2b36674119": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n256_t",
        "kernel": "kernel_cake_dense_projection_gemm_b6b1c7b42f2b36674119",
        "cache_name": "cake_dense_projection_gemm_b6b1c7b42f2b36674119_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_b6b1c7b42f2b36674119_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_b6b1c7b42f2b36674119_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "778335a1ebc92d93bb479f2597c90a707ef0dfa1659dd544068d09b5892fc2b5",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_b6c3f896fa56a87d4c31": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256_m256",
        "kernel": "kernel_cake_dense_projection_gemm_b6c3f896fa56a87d4c31",
        "cache_name": "cake_dense_projection_gemm_b6c3f896fa56a87d4c31_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_b6c3f896fa56a87d4c31_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_b6c3f896fa56a87d4c31_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "39fe212b51e23722705d3315911f18f9bad373407a05a66005ae03978824b542",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_cd5ce4605f5f6e3e1080": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_cd5ce4605f5f6e3e1080",
        "cache_name": "cake_dense_projection_gemm_cd5ce4605f5f6e3e1080_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_cd5ce4605f5f6e3e1080_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_cd5ce4605f5f6e3e1080_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "86cbf2dedbdd2a2ad070eba300c5b861590375dbfd6431b67d0ba7743adbe00f",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_d8727e03addb48546763": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_kk_n128_hen",
        "kernel": "kernel_cake_dense_projection_gemm_d8727e03addb48546763",
        "cache_name": "cake_dense_projection_gemm_d8727e03addb48546763_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_d8727e03addb48546763_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_d8727e03addb48546763_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "031f7a41cb9962e1bf742e5e577605d9c4a331d7863a495ff0a23704b36de8ea",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_d9a22f555edc76f8a094": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_m256",
        "kernel": "kernel_cake_dense_projection_gemm_d9a22f555edc76f8a094",
        "cache_name": "cake_dense_projection_gemm_d9a22f555edc76f8a094_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_d9a22f555edc76f8a094_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_d9a22f555edc76f8a094_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "7539963c3c7896ad62c8d2b9ee8760aa3126be0f93b445131c8e7fcba38c1370",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_e1369c96009f04986c9b": {
        "arch": "sm_100a",
        "template": "router_fp32_gemm_nn_t",
        "kernel": "kernel_cake_dense_projection_gemm_e1369c96009f04986c9b",
        "cache_name": "cake_dense_projection_gemm_e1369c96009f04986c9b_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e1369c96009f04986c9b_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e1369c96009f04986c9b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "be17f7d37d1576f775f722d772d3764b7c3413c93456a05ea23d107678acb76f",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_e354a38002b3ab988950": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kk_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_e354a38002b3ab988950",
        "cache_name": "cake_dense_projection_gemm_e354a38002b3ab988950_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e354a38002b3ab988950_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e354a38002b3ab988950_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "2112e658252e15d4b939843897c33df4b04f4ef294c0074c9a26a53ab08403d1",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_e472c4481ac708e0cd8c": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_g8_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_e472c4481ac708e0cd8c",
        "cache_name": "cake_dense_projection_gemm_e472c4481ac708e0cd8c_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e472c4481ac708e0cd8c_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_e472c4481ac708e0cd8c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "d5f47813f6882c672cf6af2f86b6415a234f840f16c7f3c4ff9da12a79a16163",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_e800e0912bc944f95ad8": {
        "arch": "sm_107a",
        "template": "router_fp32_gemm_kk",
        "kernel": "kernel_cake_dense_projection_gemm_e800e0912bc944f95ad8",
        "cache_name": "cake_dense_projection_gemm_e800e0912bc944f95ad8_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_e800e0912bc944f95ad8_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_e800e0912bc944f95ad8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 256,
        "closure_sha256": "eb014459a23ccd8988aa18e90d88363997dabea48e0a7cad5c93f2fe33733f74",
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_ed5f28d89c5e46e2fe56": {
        "arch": "sm_107a",
        "template": "dense_proj_gemm_nn_n128_t",
        "kernel": "kernel_cake_dense_projection_gemm_ed5f28d89c5e46e2fe56",
        "cache_name": "cake_dense_projection_gemm_ed5f28d89c5e46e2fe56_sm_107a",
        "sources": [
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_ed5f28d89c5e46e2fe56_kernel.cu",
            "cake_dense_projection_gemm/sm_107a/cake_dense_projection_gemm_ed5f28d89c5e46e2fe56_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "0739338e5b36ce3a80cbac57808abcf9e8e5c609787e4e6ff70400a596cb6151",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n256_g8",
        "kernel": "kernel_cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0",
        "cache_name": "cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "246f8a606991ce6d004d95ba73ba309cd684a50df7cefc642bb0e71cbd564909",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_f3dd3abb8883fb05fb60": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_kn_n128_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_f3dd3abb8883fb05fb60",
        "cache_name": "cake_dense_projection_gemm_f3dd3abb8883fb05fb60_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_f3dd3abb8883fb05fb60_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_f3dd3abb8883fb05fb60_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "19ff4a33c563e6e19397defaa966e5e1166bdd92b9d8c8cc4fb17ec3bcb0d5c3",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
    "cake_dense_projection_gemm_f961229de54a9e8bda49": {
        "arch": "sm_100a",
        "template": "dense_proj_gemm_nn_n256_m256_g8_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_f961229de54a9e8bda49",
        "cache_name": "cake_dense_projection_gemm_f961229de54a9e8bda49_sm_100a",
        "sources": [
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_f961229de54a9e8bda49_kernel.cu",
            "cake_dense_projection_gemm/sm_100a/cake_dense_projection_gemm_f961229de54a9e8bda49_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["workspace", "tma_descriptor_workspace"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "tma_workspace_bytes": 512,
        "closure_sha256": "f59af3a79a213f62238f19424608f8f1ff66caa58e3bbfe1b3b3e0718f13913e",
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
    },
}

# ``arch -> template -> module name``: the instance table the host planner
# resolves a launch through.  Populated by the generated-program export next to
# ``MODULES``; do not edit by hand.
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "dense_proj_gemm_kk_n128": "cake_dense_projection_gemm_2339d2580e93b0d7afbb",
        "dense_proj_gemm_kk_n128_hen": "cake_dense_projection_gemm_320bdc3905b3e481edf0",
        "dense_proj_gemm_kk_n256": "cake_dense_projection_gemm_10aae20b3f6c9e9abaad",
        "dense_proj_gemm_kk_n256_g32": "cake_dense_projection_gemm_a66d29304d002e6fedce",
        "dense_proj_gemm_kk_n256_g8": "cake_dense_projection_gemm_4753c1d0b0bf457f9f4f",
        "dense_proj_gemm_kk_n256_m256": "cake_dense_projection_gemm_b6c3f896fa56a87d4c31",
        "dense_proj_gemm_kk_n256_m256_g8": "cake_dense_projection_gemm_037abba0775871119206",
        "dense_proj_gemm_kk_n256_tma1": "cake_dense_projection_gemm_e354a38002b3ab988950",
        "dense_proj_gemm_kn_n128_f32_tma1": "cake_dense_projection_gemm_f3dd3abb8883fb05fb60",
        "dense_proj_gemm_kn_n256": "cake_dense_projection_gemm_49a4e857ad292f1d8783",
        "dense_proj_gemm_kn_n256_f32_tma1": "cake_dense_projection_gemm_b1a93c14a58efb2a4f76",
        "dense_proj_gemm_kn_n256_f32_v8": "cake_dense_projection_gemm_61e307d1404119637be9",
        "dense_proj_gemm_kn_n256_g8": "cake_dense_projection_gemm_ee97b5fe6d54e7e3b0f0",
        "dense_proj_gemm_kn_n256_g8_f32_v8": "cake_dense_projection_gemm_14ca631112bde96fb49d",
        "dense_proj_gemm_kn_n256_g8_tma1": "cake_dense_projection_gemm_e472c4481ac708e0cd8c",
        "dense_proj_gemm_kn_n256_m256_g8": "cake_dense_projection_gemm_ae13b96e9d15c1aff3ad",
        "dense_proj_gemm_kn_n256_m256_tma1": "cake_dense_projection_gemm_5ce01f0a1d31f78e535f",
        "dense_proj_gemm_kn_n256_tma1": "cake_dense_projection_gemm_7bc116c164a4780a91f8",
        "dense_proj_gemm_nn_n128_f32_t": "cake_dense_projection_gemm_571821beb881bd498fba",
        "dense_proj_gemm_nn_n128_hen_f32_t": "cake_dense_projection_gemm_8549d9785079ec66bce6",
        "dense_proj_gemm_nn_n128_hen_t": "cake_dense_projection_gemm_5e407b1e668e2a88744a",
        "dense_proj_gemm_nn_n128_t": "cake_dense_projection_gemm_5cbd4982d30c70f8f49d",
        "dense_proj_gemm_nn_n256": "cake_dense_projection_gemm_5e3e3be440f3cc598ee3",
        "dense_proj_gemm_nn_n256_f32_tma1": "cake_dense_projection_gemm_89365ab74287536812ed",
        "dense_proj_gemm_nn_n256_g32_f32_v8": "cake_dense_projection_gemm_237d70b3b0008ff14a95",
        "dense_proj_gemm_nn_n256_g4": "cake_dense_projection_gemm_a18aed8888505d2fde5d",
        "dense_proj_gemm_nn_n256_g8_f32_v8": "cake_dense_projection_gemm_655f3db3a9dac9eccd7f",
        "dense_proj_gemm_nn_n256_m256": "cake_dense_projection_gemm_d9a22f555edc76f8a094",
        "dense_proj_gemm_nn_n256_m256_f32_tma1": "cake_dense_projection_gemm_646f26aa480af3ae73b8",
        "dense_proj_gemm_nn_n256_m256_g8": "cake_dense_projection_gemm_6f0a761f21e7816084e6",
        "dense_proj_gemm_nn_n256_m256_g8_tma1": "cake_dense_projection_gemm_f961229de54a9e8bda49",
        "dense_proj_gemm_nn_n256_m256_t": "cake_dense_projection_gemm_8cc57a37d91a4350ba7e",
        "router_fp32_gemm_kk": "cake_dense_projection_gemm_1c158d5e905f05e1c7de",
        "router_fp32_gemm_kn": "cake_dense_projection_gemm_198be1c48e2c0cf6cab1",
        "router_fp32_gemm_nn_t": "cake_dense_projection_gemm_e1369c96009f04986c9b",
    },
    "sm_107a": {
        "dense_proj_gemm_kk_n128": "cake_dense_projection_gemm_2692ea1874dcba0f1bf1",
        "dense_proj_gemm_kk_n128_hen": "cake_dense_projection_gemm_d8727e03addb48546763",
        "dense_proj_gemm_kk_n256": "cake_dense_projection_gemm_ab84324a35238a2caec3",
        "dense_proj_gemm_kk_n256_tma1": "cake_dense_projection_gemm_5e16f8d63324490f7843",
        "dense_proj_gemm_kn_n256": "cake_dense_projection_gemm_4acb28f3e94830b20e44",
        "dense_proj_gemm_kn_n256_f32_tma1": "cake_dense_projection_gemm_98e3827cd311e5a61581",
        "dense_proj_gemm_kn_n256_tma1": "cake_dense_projection_gemm_569e99278d9e5847f1ef",
        "dense_proj_gemm_nn_n128_f32_t": "cake_dense_projection_gemm_0f2e64f049da5daaeaab",
        "dense_proj_gemm_nn_n128_hen_f32_t": "cake_dense_projection_gemm_256faf70a4552c580334",
        "dense_proj_gemm_nn_n128_hen_t": "cake_dense_projection_gemm_7f431317df8e387aba36",
        "dense_proj_gemm_nn_n128_t": "cake_dense_projection_gemm_ed5f28d89c5e46e2fe56",
        "dense_proj_gemm_nn_n256": "cake_dense_projection_gemm_1f9e164aad352c8dbb2d",
        "dense_proj_gemm_nn_n256_f32_tma1": "cake_dense_projection_gemm_79a6dfb1bd30afef2f90",
        "dense_proj_gemm_nn_n256_t": "cake_dense_projection_gemm_b6b1c7b42f2b36674119",
        "dense_proj_gemm_nn_n256_tma1": "cake_dense_projection_gemm_cd5ce4605f5f6e3e1080",
        "router_fp32_gemm_kk": "cake_dense_projection_gemm_e800e0912bc944f95ad8",
        "router_fp32_gemm_kn": "cake_dense_projection_gemm_b2a0d33bf7580b7ddeaf",
        "router_fp32_gemm_nn_t": "cake_dense_projection_gemm_7d0e7b1e86b036f9e169",
    },
}

# PLACEHOLDER (generated file list): the device / binding translation units of
# every registered module live under ``csrc/cake_dense_projection_gemm/<arch>/``
# next to this file and are named in each record's ``sources``.  They are
# written by the Cake exporter together with the two registries above; this
# checkout registers no program until that delivery lands.

ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
    "sm_107a": sm107a_nvcc_flags,
}
TRACKING_ISSUE = "flashinfer-ai/flashinfer#5677"


@functools.cache
def toolchain_supports(arch: str) -> bool:
    """Can the nvcc this checkout invokes emit ``arch``?  (SM100 / SM103 / SM107 only.)

    ``compute_107a`` (Rubin) needs a CUDA toolkit that lists it; a toolkit without it
    must decline the sm_107a programs up front instead of failing inside the JIT build,
    so a checkout that registers sm_107a programs stays importable and testable on a
    toolkit that only knows 10.0 / 10.3 (same rule as ``msa_nvfp4_decode.cake_jit``).
    """
    if arch not in ARCH_NVCC_FLAGS:
        return False
    if arch == "sm_107a":
        from ...compilation_context import _nvcc_supports_sm107

        return bool(_nvcc_supports_sm107())
    return True


def registered_templates(arch: str) -> tuple[str, ...]:
    """Instance templates registered for ``arch``, sorted."""
    return tuple(sorted(KERNELS.get(arch, {})))


def select_module(arch: str, template: str) -> str:
    """Return the registered module name serving ``template`` on ``arch``."""
    name = KERNELS.get(arch, {}).get(template)
    if name is None:
        registered = registered_templates(arch)
        raise NotImplementedError(
            f"The generated dense projection GEMM instance {template!r} for {arch} is "
            f"not registered in this checkout (registered: {list(registered) or 'none'}; "
            f"see {TRACKING_ISSUE})"
        )
    record = MODULES.get(name)
    if (
        record is None
        or record.get("arch") != arch
        or record.get("template") != template
    ):
        raise ValueError(
            f"registry record {name!r} does not serve template {template!r} on {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_dense_projection_gemm_module(name: str):
    record = MODULES[name]
    if not toolchain_supports(record["arch"]):
        raise RuntimeError(
            f"generated dense projection GEMM module {name!r} targets {record['arch']}, "
            "which this checkout cannot compile"
        )
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{record['cache_name']}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_dense_projection_gemm_module(name: str):
    return gen_cake_dense_projection_gemm_module(name).build_and_load()
