"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import (
    gen_jit_spec,
    sm100a_nvcc_flags,
    sm103a_nvcc_flags,
    sm107a_nvcc_flags,
)

# Explicit target-owned registration of the generated GEMM programs.  One
# record per delivered program = one traced kernel instance (``template``);
# a program is architecture-neutral (one source pair, compiled per device
# architecture).  A record carries ``arches``, the instance ``template`` (the
# symbol the host planner derives from the operand layouts, the tile width,
# the output kind, the epilogue path and the TMA L2 eviction hints -- see
# ``cake_backend.instance_symbol`` and ``cake_backend.router_symbol``; the
# prefetch / L2-promotion / stage-count knobs are part of the symbol too but
# sit at their defaults in every registered instance), the kernel symbol, the JIT cache name,
# the translation units, compile flags, the FFI entry, the argument plan the
# host binds by keyword, the
# closure identity and the launch geometry baked into the module (block,
# cluster).  Populated verbatim by the generated-program export; do not edit
# by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_dense_projection_gemm_066af859590e9aee7a11": {
        "template": "dense_proj_gemm_kn_n256_q_s6",
        "kernel": "kernel_cake_dense_projection_gemm_066af859590e9aee7a11",
        "cache_name": "cake_dense_projection_gemm_066af859590e9aee7a11",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_066af859590e9aee7a11_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_066af859590e9aee7a11_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "9062eab72c529a54d8551cb2e87f0db976ab51d32847eb1e3bbc4648acb09bec",
    },
    "cake_dense_projection_gemm_06dcd760459d9480ffb7": {
        "template": "dense_proj_gemm_kn_n256_m256_tma2",
        "kernel": "kernel_cake_dense_projection_gemm_06dcd760459d9480ffb7",
        "cache_name": "cake_dense_projection_gemm_06dcd760459d9480ffb7",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_06dcd760459d9480ffb7_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_06dcd760459d9480ffb7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "73699459db5ff346ea170e084c7f4993bbbc3c933024948fd5e7872d3da964c0",
    },
    "cake_dense_projection_gemm_0803c48454af80623231": {
        "template": "dense_proj_gemm_nn_n128_hen_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_0803c48454af80623231",
        "cache_name": "cake_dense_projection_gemm_0803c48454af80623231",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0803c48454af80623231_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0803c48454af80623231_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "4a51dcf5a83ee4ea2dd91f2300cc4fb08f09c8196139a7ef5eb361a57f6c6916",
    },
    "cake_dense_projection_gemm_0850908ea2dbc27ce781": {
        "template": "dense_proj_gemm_nn_n128_m64_hen_t",
        "kernel": "kernel_cake_dense_projection_gemm_0850908ea2dbc27ce781",
        "cache_name": "cake_dense_projection_gemm_0850908ea2dbc27ce781",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0850908ea2dbc27ce781_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0850908ea2dbc27ce781_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "a26a1f8f456a82ea9b7cbfe8352b1cc013f60b3422a47a3303a550304f1339c1",
    },
    "cake_dense_projection_gemm_0b42fd8a7c007cde97ad": {
        "template": "dense_proj_gemm_kk_n256_q",
        "kernel": "kernel_cake_dense_projection_gemm_0b42fd8a7c007cde97ad",
        "cache_name": "cake_dense_projection_gemm_0b42fd8a7c007cde97ad",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0b42fd8a7c007cde97ad_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0b42fd8a7c007cde97ad_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "5ca52fc5781fcdb19c3046f0aa8eae97daeeacefbda9c396392bb201ca1f1998",
    },
    "cake_dense_projection_gemm_0d8ac8cda346d79d4bdf": {
        "template": "dense_proj_gemm_nk_n256_t",
        "kernel": "kernel_cake_dense_projection_gemm_0d8ac8cda346d79d4bdf",
        "cache_name": "cake_dense_projection_gemm_0d8ac8cda346d79d4bdf",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0d8ac8cda346d79d4bdf_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_0d8ac8cda346d79d4bdf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "37ab3f3c558ce593794cbee2928e47ffbc0f4d31cb7d3c285e3b90de26a81283",
    },
    "cake_dense_projection_gemm_126a56433ecb5f1043d0": {
        "template": "dense_proj_gemm_nn_n128_t",
        "kernel": "kernel_cake_dense_projection_gemm_126a56433ecb5f1043d0",
        "cache_name": "cake_dense_projection_gemm_126a56433ecb5f1043d0",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_126a56433ecb5f1043d0_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_126a56433ecb5f1043d0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "65fe4c13bb5f832f0e60ab6dab35e90dc083158f5cd5db9a5e10166c6db68be0",
    },
    "cake_dense_projection_gemm_1413d3b9c02b6945a1cf": {
        "template": "dense_proj_gemm_kn_n256_m256",
        "kernel": "kernel_cake_dense_projection_gemm_1413d3b9c02b6945a1cf",
        "cache_name": "cake_dense_projection_gemm_1413d3b9c02b6945a1cf",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1413d3b9c02b6945a1cf_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1413d3b9c02b6945a1cf_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "aedf5849f50c8fa1c6c02903600a796558b9fc5f0dd06435c5902167606967b0",
    },
    "cake_dense_projection_gemm_1ab088290b3c67039673": {
        "template": "dense_proj_gemm_nn_n160_m256",
        "kernel": "kernel_cake_dense_projection_gemm_1ab088290b3c67039673",
        "cache_name": "cake_dense_projection_gemm_1ab088290b3c67039673",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1ab088290b3c67039673_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1ab088290b3c67039673_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "4437aa799cfbad394f3c640747d3fb28d9d8d02ab451325c756377a92b590627",
    },
    "cake_dense_projection_gemm_1e978afde39024480a3c": {
        "template": "dense_proj_gemm_nn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_1e978afde39024480a3c",
        "cache_name": "cake_dense_projection_gemm_1e978afde39024480a3c",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1e978afde39024480a3c_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_1e978afde39024480a3c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "b2ed266239aab64eef5100eaf887d1c35c7183cd404b6506c83d07e1de10982b",
    },
    "cake_dense_projection_gemm_28ff8edb6f8a05e36ae0": {
        "template": "router_fp32_gemm_kn",
        "kernel": "kernel_cake_dense_projection_gemm_28ff8edb6f8a05e36ae0",
        "cache_name": "cake_dense_projection_gemm_28ff8edb6f8a05e36ae0",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_28ff8edb6f8a05e36ae0_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_28ff8edb6f8a05e36ae0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "25c919c80b5aa53250f7476579e58064788708d79f94ad2368a029a6b799442e",
    },
    "cake_dense_projection_gemm_2de6fa410246e7879b5f": {
        "template": "dense_proj_gemm_kn_n256_tma2",
        "kernel": "kernel_cake_dense_projection_gemm_2de6fa410246e7879b5f",
        "cache_name": "cake_dense_projection_gemm_2de6fa410246e7879b5f",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_2de6fa410246e7879b5f_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_2de6fa410246e7879b5f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "702e0d84ae49935b073b03f65c3186cb97371ce9b2ee3d9f8bfe299f8ff47e0d",
    },
    "cake_dense_projection_gemm_3091734cf7182b0e661e": {
        "template": "dense_proj_gemm_nn_n256_m256_t",
        "kernel": "kernel_cake_dense_projection_gemm_3091734cf7182b0e661e",
        "cache_name": "cake_dense_projection_gemm_3091734cf7182b0e661e",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_3091734cf7182b0e661e_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_3091734cf7182b0e661e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "200f805b28c7063f9ace778782a758d6051c97a5a1088dd559cc8bbfb7988f69",
    },
    "cake_dense_projection_gemm_35674bf6a89e7f2043b1": {
        "template": "dense_proj_gemm_kk_n256",
        "kernel": "kernel_cake_dense_projection_gemm_35674bf6a89e7f2043b1",
        "cache_name": "cake_dense_projection_gemm_35674bf6a89e7f2043b1",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_35674bf6a89e7f2043b1_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_35674bf6a89e7f2043b1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "6d729487e73b1366e2fd1fb317eca33b8641e3e6a2262695754e76abea524b21",
    },
    "cake_dense_projection_gemm_41def5ce888a2f676ca7": {
        "template": "dense_proj_gemm_kn_n256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_41def5ce888a2f676ca7",
        "cache_name": "cake_dense_projection_gemm_41def5ce888a2f676ca7",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_41def5ce888a2f676ca7_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_41def5ce888a2f676ca7_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "a15660d675c5c31b5bab112d84a7ab4588e160e30b183e866f6f7fa4710fd358",
    },
    "cake_dense_projection_gemm_435a4e07c002dcf7d895": {
        "template": "dense_proj_gemm_kn_n256_hne",
        "kernel": "kernel_cake_dense_projection_gemm_435a4e07c002dcf7d895",
        "cache_name": "cake_dense_projection_gemm_435a4e07c002dcf7d895",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_435a4e07c002dcf7d895_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_435a4e07c002dcf7d895_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "c103c233542dcdf93e3242f96240e5b80bbdcd2f2e8e6b4fbb94456767bf9eac",
    },
    "cake_dense_projection_gemm_456bed7bdad8bfcbc7b9": {
        "template": "dense_proj_gemm_kk_n192_hee_s8",
        "kernel": "kernel_cake_dense_projection_gemm_456bed7bdad8bfcbc7b9",
        "cache_name": "cake_dense_projection_gemm_456bed7bdad8bfcbc7b9",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_456bed7bdad8bfcbc7b9_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_456bed7bdad8bfcbc7b9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "51b7fbec743896011453d8ec1750e15147e826c05fc65779ecdc3a458408f770",
    },
    "cake_dense_projection_gemm_57eaa9343ab9d81e4eba": {
        "template": "router_fp32_gemm_nn_t",
        "kernel": "kernel_cake_dense_projection_gemm_57eaa9343ab9d81e4eba",
        "cache_name": "cake_dense_projection_gemm_57eaa9343ab9d81e4eba",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_57eaa9343ab9d81e4eba_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_57eaa9343ab9d81e4eba_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "7a9a7a6513ef918551c946f1656b9c7432a9c89c489461ecc3621b92d1b88007",
    },
    "cake_dense_projection_gemm_5e19961befd1ab82aa72": {
        "template": "dense_proj_gemm_nn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_5e19961befd1ab82aa72",
        "cache_name": "cake_dense_projection_gemm_5e19961befd1ab82aa72",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_5e19961befd1ab82aa72_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_5e19961befd1ab82aa72_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "319b7444333f055c748074c5b50fae869dd753e57836066dd315d6699e8d3957",
    },
    "cake_dense_projection_gemm_60f77c497aa4efa25a17": {
        "template": "dense_proj_gemm_nn_n192_hee_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_60f77c497aa4efa25a17",
        "cache_name": "cake_dense_projection_gemm_60f77c497aa4efa25a17",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_60f77c497aa4efa25a17_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_60f77c497aa4efa25a17_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "364ec5c2b16abd78c69e3f715a567f2ced415a8ab8032ce1452be795a24c34de",
    },
    "cake_dense_projection_gemm_6a3513b2ff1269ba2727": {
        "template": "dense_proj_gemm_nn_n256_m256",
        "kernel": "kernel_cake_dense_projection_gemm_6a3513b2ff1269ba2727",
        "cache_name": "cake_dense_projection_gemm_6a3513b2ff1269ba2727",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6a3513b2ff1269ba2727_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6a3513b2ff1269ba2727_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "129331b9364c59e7206cbf74eaafb1ae789730c1d8f386c037c4c9d351d06808",
    },
    "cake_dense_projection_gemm_6cedaf1e44497cb1de4f": {
        "template": "dense_proj_gemm_nn_n256_m256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_6cedaf1e44497cb1de4f",
        "cache_name": "cake_dense_projection_gemm_6cedaf1e44497cb1de4f",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6cedaf1e44497cb1de4f_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6cedaf1e44497cb1de4f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "0349ff7086a8645175269b73dd45a4fbbe2504cae27ff51460313119fdf41c2b",
    },
    "cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9": {
        "template": "dense_proj_gemm_kk_n128_hen",
        "kernel": "kernel_cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9",
        "cache_name": "cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "12e6acefab21fceb36814b083df0c25451e0111eaf82720882cf1fc259da880c",
    },
    "cake_dense_projection_gemm_733315e1e7ccec79a47d": {
        "template": "dense_proj_gemm_kk_n192",
        "kernel": "kernel_cake_dense_projection_gemm_733315e1e7ccec79a47d",
        "cache_name": "cake_dense_projection_gemm_733315e1e7ccec79a47d",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_733315e1e7ccec79a47d_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_733315e1e7ccec79a47d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "1209adfc0e6af4e35a11c646a12798efef571615aab26c46b072ab781f1cdc10",
    },
    "cake_dense_projection_gemm_79d1e0218a3bd17a355e": {
        "template": "dense_proj_gemm_nn_n192_hee_t",
        "kernel": "kernel_cake_dense_projection_gemm_79d1e0218a3bd17a355e",
        "cache_name": "cake_dense_projection_gemm_79d1e0218a3bd17a355e",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_79d1e0218a3bd17a355e_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_79d1e0218a3bd17a355e_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "6b3dd941e154773fcba6a40aad38e3198437462fc71163a5cee67f017fa0f4d3",
    },
    "cake_dense_projection_gemm_84f34147a58bd2254ac0": {
        "template": "dense_proj_gemm_kn_n128_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_84f34147a58bd2254ac0",
        "cache_name": "cake_dense_projection_gemm_84f34147a58bd2254ac0",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_84f34147a58bd2254ac0_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_84f34147a58bd2254ac0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "6f45a8c09ec97fae9c03697806433823001d7ed109c02b1a8198cb0f3f068f5a",
    },
    "cake_dense_projection_gemm_86ca4ae13cf7c4436c4b": {
        "template": "dense_proj_gemm_nn_n256_m256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_86ca4ae13cf7c4436c4b",
        "cache_name": "cake_dense_projection_gemm_86ca4ae13cf7c4436c4b",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_86ca4ae13cf7c4436c4b_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_86ca4ae13cf7c4436c4b_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "c91022f6de6ee5f667ccedfd54ed78d7534c067a4c46beabe735d8ca16fc1993",
    },
    "cake_dense_projection_gemm_8ce0e050d9f6b49105d6": {
        "template": "dense_proj_gemm_kn_n256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_8ce0e050d9f6b49105d6",
        "cache_name": "cake_dense_projection_gemm_8ce0e050d9f6b49105d6",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_8ce0e050d9f6b49105d6_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_8ce0e050d9f6b49105d6_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "fdf9e2f09b3123d3c71d3d628083113be239050204f410eda4cb5b62fc0c7a20",
    },
    "cake_dense_projection_gemm_9ae37c3d7960707ca7ed": {
        "template": "dense_proj_gemm_nn_n192_m256_t",
        "kernel": "kernel_cake_dense_projection_gemm_9ae37c3d7960707ca7ed",
        "cache_name": "cake_dense_projection_gemm_9ae37c3d7960707ca7ed",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_9ae37c3d7960707ca7ed_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_9ae37c3d7960707ca7ed_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "c7fb1809de0c3b00c8034545a8f2dfc2d644f51d25f698d1e06afa003b3b425e",
    },
    "cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8": {
        "template": "dense_proj_gemm_kn_n256",
        "kernel": "kernel_cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8",
        "cache_name": "cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "ff8f10669e34f5f3c5cd63cd0cfc7c126a7da73452e827d9a72817cf439482ab",
    },
    "cake_dense_projection_gemm_ab6f52bebd5d4f2354bc": {
        "template": "dense_proj_gemm_nn_n192_m256_hee_t",
        "kernel": "kernel_cake_dense_projection_gemm_ab6f52bebd5d4f2354bc",
        "cache_name": "cake_dense_projection_gemm_ab6f52bebd5d4f2354bc",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_ab6f52bebd5d4f2354bc_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_ab6f52bebd5d4f2354bc_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "2bfe471e54ec96c28975389de96cb0f9a6ddcd2933b9c7325b7f2290dbbfd576",
    },
    "cake_dense_projection_gemm_abb485347529949426bb": {
        "template": "dense_proj_gemm_nn_n256_m256_hee_t",
        "kernel": "kernel_cake_dense_projection_gemm_abb485347529949426bb",
        "cache_name": "cake_dense_projection_gemm_abb485347529949426bb",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_abb485347529949426bb_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_abb485347529949426bb_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "4d04937a97783cd1a51bf3c72a2af5559f0bdc75690384817ce12aeba220237b",
    },
    "cake_dense_projection_gemm_ad39ccfa7d3f8f48197f": {
        "template": "dense_proj_gemm_nn_n128_m64_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_ad39ccfa7d3f8f48197f",
        "cache_name": "cake_dense_projection_gemm_ad39ccfa7d3f8f48197f",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_ad39ccfa7d3f8f48197f_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_ad39ccfa7d3f8f48197f_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "b0ece4aa09aba6c15682cd02e2e444858cbb5963a0d0ce0b8d03ea0e11104526",
    },
    "cake_dense_projection_gemm_aea591402b89e66b97e0": {
        "template": "dense_proj_gemm_kn_n256_q",
        "kernel": "kernel_cake_dense_projection_gemm_aea591402b89e66b97e0",
        "cache_name": "cake_dense_projection_gemm_aea591402b89e66b97e0",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_aea591402b89e66b97e0_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_aea591402b89e66b97e0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "1e64e5c603ea484028e25f521a20d93257c7e2e3aa7bfa5f94173cc55903d812",
    },
    "cake_dense_projection_gemm_b7ff52b97418b2b95107": {
        "template": "dense_proj_gemm_kn_n256_m256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_b7ff52b97418b2b95107",
        "cache_name": "cake_dense_projection_gemm_b7ff52b97418b2b95107",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_b7ff52b97418b2b95107_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_b7ff52b97418b2b95107_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "d58a8bf454cc358f2d2d763b89b9488e9c63c271ca8c3e5e305576fb6b795e1a",
    },
    "cake_dense_projection_gemm_bfd7b5f9dc6d7575b882": {
        "template": "dense_proj_gemm_kn_n256_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_bfd7b5f9dc6d7575b882",
        "cache_name": "cake_dense_projection_gemm_bfd7b5f9dc6d7575b882",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_bfd7b5f9dc6d7575b882_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_bfd7b5f9dc6d7575b882_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "3f88be8f6123205e0a152a216df901597f67adcddf82a268d59f85d4ffbbe2db",
    },
    "cake_dense_projection_gemm_c1bc27ef7de8313bbcc0": {
        "template": "dense_proj_gemm_kk_n128",
        "kernel": "kernel_cake_dense_projection_gemm_c1bc27ef7de8313bbcc0",
        "cache_name": "cake_dense_projection_gemm_c1bc27ef7de8313bbcc0",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_c1bc27ef7de8313bbcc0_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_c1bc27ef7de8313bbcc0_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "dbc41df47209ba850fc38227148c80ee564f8dcf55689bfd6b60f233683dd7f8",
    },
    "cake_dense_projection_gemm_cae078a17b7a4abbd9e4": {
        "template": "dense_proj_gemm_nn_n160_m256_f32",
        "kernel": "kernel_cake_dense_projection_gemm_cae078a17b7a4abbd9e4",
        "cache_name": "cake_dense_projection_gemm_cae078a17b7a4abbd9e4",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_cae078a17b7a4abbd9e4_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_cae078a17b7a4abbd9e4_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "fc24579343d3026555ba986da061e2807722e4375ab5a9c649853ffcf5f1fc48",
    },
    "cake_dense_projection_gemm_d53898d15d7e7de6757c": {
        "template": "router_fp32_gemm_kk",
        "kernel": "kernel_cake_dense_projection_gemm_d53898d15d7e7de6757c",
        "cache_name": "cake_dense_projection_gemm_d53898d15d7e7de6757c",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_d53898d15d7e7de6757c_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_d53898d15d7e7de6757c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["buffer", "out32"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "k_iters_split"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [448, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "a0c045142efaca516b48de9c432176f1d95ce68071f0c09feba9402a12e955f7",
    },
    "cake_dense_projection_gemm_d9c9c7319a972bc4a5e2": {
        "template": "dense_proj_gemm_kk_n192_m256_hen_s5",
        "kernel": "kernel_cake_dense_projection_gemm_d9c9c7319a972bc4a5e2",
        "cache_name": "cake_dense_projection_gemm_d9c9c7319a972bc4a5e2",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_d9c9c7319a972bc4a5e2_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_d9c9c7319a972bc4a5e2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "694bce2ea3837cd3d516aab01b5ebd65dea39de978263ea75925f3a8dadc08e6",
    },
    "cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8": {
        "template": "dense_proj_gemm_kk_n256_m256",
        "kernel": "kernel_cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8",
        "cache_name": "cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "57a9c22b88debfa1bf9b03c1c9c4e6d8998710410fd7f7094a364eb12c7582aa",
    },
    "cake_dense_projection_gemm_e53504f37ad4cfc5a25c": {
        "template": "dense_proj_gemm_nn_n256_f32_v8",
        "kernel": "kernel_cake_dense_projection_gemm_e53504f37ad4cfc5a25c",
        "cache_name": "cake_dense_projection_gemm_e53504f37ad4cfc5a25c",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e53504f37ad4cfc5a25c_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e53504f37ad4cfc5a25c_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "04a2c9bbe7dc2aa9004531d225ce33d086794789546f255c371f5c6598215730",
    },
    "cake_dense_projection_gemm_e7776d59c0b526d4f799": {
        "template": "dense_proj_gemm_nn_n128_hen_t",
        "kernel": "kernel_cake_dense_projection_gemm_e7776d59c0b526d4f799",
        "cache_name": "cake_dense_projection_gemm_e7776d59c0b526d4f799",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e7776d59c0b526d4f799_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_e7776d59c0b526d4f799_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "23c6b3ddfd739341cb5e9e27cebf8e434450712135874c643d1ba62ca7621f0f",
    },
    "cake_dense_projection_gemm_f01266f2a1193a02d7b2": {
        "template": "dense_proj_gemm_nn_n128_m64_t",
        "kernel": "kernel_cake_dense_projection_gemm_f01266f2a1193a02d7b2",
        "cache_name": "cake_dense_projection_gemm_f01266f2a1193a02d7b2",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f01266f2a1193a02d7b2_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f01266f2a1193a02d7b2_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a"],
        "closure_sha256": "844b12e6c4e8ef180695d56c908d496591546a53e67e3edc3145622019d3ed65",
    },
    "cake_dense_projection_gemm_f07ceffa3ad4f1016ce1": {
        "template": "dense_proj_gemm_kn_n256_m256_f32_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_f07ceffa3ad4f1016ce1",
        "cache_name": "cake_dense_projection_gemm_f07ceffa3ad4f1016ce1",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f07ceffa3ad4f1016ce1_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f07ceffa3ad4f1016ce1_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "04be69723bab04a952832058596fd3b997ace34f0cf7b9fb413ed2274e812b29",
    },
    "cake_dense_projection_gemm_f300509a1df5faeac09a": {
        "template": "dense_proj_gemm_kn_n128_m256_tma1",
        "kernel": "kernel_cake_dense_projection_gemm_f300509a1df5faeac09a",
        "cache_name": "cake_dense_projection_gemm_f300509a1df5faeac09a",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f300509a1df5faeac09a_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f300509a1df5faeac09a_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "51100c61356845c2337de3f4b3515246833d5878637119eff46b4b17b02a0063",
    },
    "cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d": {
        "template": "dense_proj_gemm_nn_n128_m64_hen_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d",
        "cache_name": "cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_100a", "sm_107a"],
        "closure_sha256": "3f0265c70b61bff4ebe1a905fc2e9a7a821dfc23094041c9992940d9a741440a",
    },
    "cake_dense_projection_gemm_fae5998b6daa1ed20dbe": {
        "template": "dense_proj_gemm_nn_n128_f32_t",
        "kernel": "kernel_cake_dense_projection_gemm_fae5998b6daa1ed20dbe",
        "cache_name": "cake_dense_projection_gemm_fae5998b6daa1ed20dbe",
        "sources": [
            "cake_dense_projection_gemm/cake_dense_projection_gemm_fae5998b6daa1ed20dbe_kernel.cu",
            "cake_dense_projection_gemm/cake_dense_projection_gemm_fae5998b6daa1ed20dbe_binding.cu",
        ],
        "compile_flags": [],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "A"],
            ["tma_buffer", "B"],
            ["tma_buffer", "OUT32"],
            ["tma_buffer", "OUT16"],
            ["buffer", "out"],
            ["buffer", "out32"],
            ["buffer", "ws"],
            ["buffer", "counters"],
            ["parameter", "M"],
            ["parameter", "N"],
            ["parameter", "m_tiles"],
            ["parameter", "n_tiles"],
            ["parameter", "group_m"],
            ["parameter", "promo_code"],
            ["parameter", "k_iters"],
            ["parameter", "ldo"],
            ["parameter", "out_l"],
            ["parameter", "num_cluster_tiles"],
            ["parameter", "num_l"],
            ["parameter", "num_full"],
            ["parameter", "iters_per_unit"],
            ["parameter", "sk_iters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "launch": {"block": [320, 1, 1], "cluster": [2, 1, 1]},
        "arches": ["sm_107a"],
        "closure_sha256": "a5829126693940bf0ef793f9d89815b0402a15076b24557ae745927aaaaf686d",
    },
}

# ``arch -> template -> module name``: the instance table the host planner
# resolves a launch through.  Populated by the generated-program export next to
# ``MODULES``; do not edit by hand.
KERNELS: dict[str, dict[str, str]] = {
    "sm_100a": {
        "dense_proj_gemm_kk_n128": "cake_dense_projection_gemm_c1bc27ef7de8313bbcc0",
        "dense_proj_gemm_kk_n128_hen": "cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9",
        "dense_proj_gemm_kk_n192": "cake_dense_projection_gemm_733315e1e7ccec79a47d",
        "dense_proj_gemm_kk_n192_hee_s8": "cake_dense_projection_gemm_456bed7bdad8bfcbc7b9",
        "dense_proj_gemm_kk_n256": "cake_dense_projection_gemm_35674bf6a89e7f2043b1",
        "dense_proj_gemm_kk_n256_m256": "cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8",
        "dense_proj_gemm_kk_n256_q": "cake_dense_projection_gemm_0b42fd8a7c007cde97ad",
        "dense_proj_gemm_kn_n128_f32_tma1": "cake_dense_projection_gemm_84f34147a58bd2254ac0",
        "dense_proj_gemm_kn_n128_m256_tma1": "cake_dense_projection_gemm_f300509a1df5faeac09a",
        "dense_proj_gemm_kn_n256": "cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8",
        "dense_proj_gemm_kn_n256_f32_tma1": "cake_dense_projection_gemm_41def5ce888a2f676ca7",
        "dense_proj_gemm_kn_n256_f32_v8": "cake_dense_projection_gemm_bfd7b5f9dc6d7575b882",
        "dense_proj_gemm_kn_n256_m256": "cake_dense_projection_gemm_1413d3b9c02b6945a1cf",
        "dense_proj_gemm_kn_n256_m256_tma1": "cake_dense_projection_gemm_b7ff52b97418b2b95107",
        "dense_proj_gemm_kn_n256_m256_tma2": "cake_dense_projection_gemm_06dcd760459d9480ffb7",
        "dense_proj_gemm_kn_n256_q_s6": "cake_dense_projection_gemm_066af859590e9aee7a11",
        "dense_proj_gemm_kn_n256_tma1": "cake_dense_projection_gemm_8ce0e050d9f6b49105d6",
        "dense_proj_gemm_nk_n256_t": "cake_dense_projection_gemm_0d8ac8cda346d79d4bdf",
        "dense_proj_gemm_nn_n128_m64_f32_t": "cake_dense_projection_gemm_ad39ccfa7d3f8f48197f",
        "dense_proj_gemm_nn_n128_m64_hen_f32_t": "cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d",
        "dense_proj_gemm_nn_n128_m64_hen_t": "cake_dense_projection_gemm_0850908ea2dbc27ce781",
        "dense_proj_gemm_nn_n128_m64_t": "cake_dense_projection_gemm_f01266f2a1193a02d7b2",
        "dense_proj_gemm_nn_n192_hee_f32_t": "cake_dense_projection_gemm_60f77c497aa4efa25a17",
        "dense_proj_gemm_nn_n192_hee_t": "cake_dense_projection_gemm_79d1e0218a3bd17a355e",
        "dense_proj_gemm_nn_n192_m256_t": "cake_dense_projection_gemm_9ae37c3d7960707ca7ed",
        "dense_proj_gemm_nn_n256": "cake_dense_projection_gemm_5e19961befd1ab82aa72",
        "dense_proj_gemm_nn_n256_f32_v8": "cake_dense_projection_gemm_e53504f37ad4cfc5a25c",
        "dense_proj_gemm_nn_n256_m256": "cake_dense_projection_gemm_6a3513b2ff1269ba2727",
        "dense_proj_gemm_nn_n256_m256_f32_tma1": "cake_dense_projection_gemm_6cedaf1e44497cb1de4f",
        "dense_proj_gemm_nn_n256_m256_t": "cake_dense_projection_gemm_3091734cf7182b0e661e",
        "dense_proj_gemm_nn_n256_m256_tma1": "cake_dense_projection_gemm_86ca4ae13cf7c4436c4b",
        "router_fp32_gemm_kk": "cake_dense_projection_gemm_d53898d15d7e7de6757c",
        "router_fp32_gemm_kn": "cake_dense_projection_gemm_28ff8edb6f8a05e36ae0",
        "router_fp32_gemm_nn_t": "cake_dense_projection_gemm_57eaa9343ab9d81e4eba",
    },
    "sm_107a": {
        "dense_proj_gemm_kk_n128": "cake_dense_projection_gemm_c1bc27ef7de8313bbcc0",
        "dense_proj_gemm_kk_n128_hen": "cake_dense_projection_gemm_6e7bc9fac8bb406dd3e9",
        "dense_proj_gemm_kk_n192": "cake_dense_projection_gemm_733315e1e7ccec79a47d",
        "dense_proj_gemm_kk_n192_m256_hen_s5": "cake_dense_projection_gemm_d9c9c7319a972bc4a5e2",
        "dense_proj_gemm_kk_n256": "cake_dense_projection_gemm_35674bf6a89e7f2043b1",
        "dense_proj_gemm_kk_n256_m256": "cake_dense_projection_gemm_e2d1d5eb0deb5cfa61d8",
        "dense_proj_gemm_kk_n256_q": "cake_dense_projection_gemm_0b42fd8a7c007cde97ad",
        "dense_proj_gemm_kn_n128_f32_tma1": "cake_dense_projection_gemm_84f34147a58bd2254ac0",
        "dense_proj_gemm_kn_n128_m256_tma1": "cake_dense_projection_gemm_f300509a1df5faeac09a",
        "dense_proj_gemm_kn_n256": "cake_dense_projection_gemm_a6c6e3e388ef1c21b9d8",
        "dense_proj_gemm_kn_n256_f32_tma1": "cake_dense_projection_gemm_41def5ce888a2f676ca7",
        "dense_proj_gemm_kn_n256_f32_v8": "cake_dense_projection_gemm_bfd7b5f9dc6d7575b882",
        "dense_proj_gemm_kn_n256_hne": "cake_dense_projection_gemm_435a4e07c002dcf7d895",
        "dense_proj_gemm_kn_n256_m256": "cake_dense_projection_gemm_1413d3b9c02b6945a1cf",
        "dense_proj_gemm_kn_n256_m256_f32_tma1": "cake_dense_projection_gemm_f07ceffa3ad4f1016ce1",
        "dense_proj_gemm_kn_n256_q": "cake_dense_projection_gemm_aea591402b89e66b97e0",
        "dense_proj_gemm_kn_n256_tma1": "cake_dense_projection_gemm_8ce0e050d9f6b49105d6",
        "dense_proj_gemm_kn_n256_tma2": "cake_dense_projection_gemm_2de6fa410246e7879b5f",
        "dense_proj_gemm_nk_n256_t": "cake_dense_projection_gemm_0d8ac8cda346d79d4bdf",
        "dense_proj_gemm_nn_n128_f32_t": "cake_dense_projection_gemm_fae5998b6daa1ed20dbe",
        "dense_proj_gemm_nn_n128_hen_f32_t": "cake_dense_projection_gemm_0803c48454af80623231",
        "dense_proj_gemm_nn_n128_hen_t": "cake_dense_projection_gemm_e7776d59c0b526d4f799",
        "dense_proj_gemm_nn_n128_m64_hen_f32_t": "cake_dense_projection_gemm_f3e4a0c29ae3dfcd481d",
        "dense_proj_gemm_nn_n128_m64_hen_t": "cake_dense_projection_gemm_0850908ea2dbc27ce781",
        "dense_proj_gemm_nn_n128_t": "cake_dense_projection_gemm_126a56433ecb5f1043d0",
        "dense_proj_gemm_nn_n160_m256": "cake_dense_projection_gemm_1ab088290b3c67039673",
        "dense_proj_gemm_nn_n160_m256_f32": "cake_dense_projection_gemm_cae078a17b7a4abbd9e4",
        "dense_proj_gemm_nn_n192_hee_f32_t": "cake_dense_projection_gemm_60f77c497aa4efa25a17",
        "dense_proj_gemm_nn_n192_hee_t": "cake_dense_projection_gemm_79d1e0218a3bd17a355e",
        "dense_proj_gemm_nn_n192_m256_hee_t": "cake_dense_projection_gemm_ab6f52bebd5d4f2354bc",
        "dense_proj_gemm_nn_n256": "cake_dense_projection_gemm_5e19961befd1ab82aa72",
        "dense_proj_gemm_nn_n256_f32_tma1": "cake_dense_projection_gemm_1e978afde39024480a3c",
        "dense_proj_gemm_nn_n256_f32_v8": "cake_dense_projection_gemm_e53504f37ad4cfc5a25c",
        "dense_proj_gemm_nn_n256_m256": "cake_dense_projection_gemm_6a3513b2ff1269ba2727",
        "dense_proj_gemm_nn_n256_m256_f32_tma1": "cake_dense_projection_gemm_6cedaf1e44497cb1de4f",
        "dense_proj_gemm_nn_n256_m256_hee_t": "cake_dense_projection_gemm_abb485347529949426bb",
        "dense_proj_gemm_nn_n256_m256_tma1": "cake_dense_projection_gemm_86ca4ae13cf7c4436c4b",
        "router_fp32_gemm_kk": "cake_dense_projection_gemm_d53898d15d7e7de6757c",
        "router_fp32_gemm_kn": "cake_dense_projection_gemm_28ff8edb6f8a05e36ae0",
        "router_fp32_gemm_nn_t": "cake_dense_projection_gemm_57eaa9343ab9d81e4eba",
    },
}

# Generated file list: the device / binding translation units of every registered
# module live flat under ``csrc/cake_dense_projection_gemm/`` next to this file
# (``<module>_kernel.cu`` / ``<module>_binding.cu``, one architecture-neutral pair
# per program; each record's ``sources`` names them and ``arches`` lists the
# architectures it is compiled for).  They are written by the Cake exporter
# together with the two registries above.

ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
    "sm_107a": sm107a_nvcc_flags,
}
TRACKING_ISSUE = "flashinfer-ai/flashinfer#5677"


@functools.cache
def toolchain_supports(arch: str) -> bool:
    """Can the nvcc this checkout invokes emit ``arch``?  (SM100 / SM103 / SM107 only.)

    ``compute_107a`` (Rubin) needs a CUDA toolkit that lists it; a toolkit without it
    must decline the sm_107a programs up front instead of failing inside the JIT build,
    so a checkout that registers sm_107a programs stays importable and testable on a
    toolkit that only knows 10.0 / 10.3 (same rule as ``msa_nvfp4_decode.cake_jit``).
    """
    if arch not in ARCH_NVCC_FLAGS:
        return False
    if arch == "sm_107a":
        from ...compilation_context import _nvcc_supports_sm107

        return bool(_nvcc_supports_sm107())
    return True


def registered_templates(arch: str) -> tuple[str, ...]:
    """Instance templates registered for ``arch``, sorted."""
    return tuple(sorted(KERNELS.get(arch, {})))


def select_module(arch: str, template: str) -> str:
    """Return the registered module name serving ``template`` on ``arch``."""
    name = KERNELS.get(arch, {}).get(template)
    if name is None:
        registered = registered_templates(arch)
        raise NotImplementedError(
            f"The generated dense projection GEMM instance {template!r} for {arch} is "
            f"not registered in this checkout (registered: {list(registered) or 'none'}; "
            f"see {TRACKING_ISSUE})"
        )
    record = MODULES.get(name)
    if (
        record is None
        or arch not in record.get("arches", ())
        or record.get("template") != template
    ):
        raise ValueError(
            f"registry record {name!r} does not serve template {template!r} on {arch}"
        )
    return name


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_dense_projection_gemm_module(name: str, arch: str):
    """JIT spec of program ``name`` compiled for ``arch`` (one architecture-neutral source pair
    per program; the device architecture selects the nvcc flags and the cache entry)."""
    record = MODULES[name]
    if arch not in record["arches"]:
        raise ValueError(
            f"generated dense projection GEMM module {name!r} is not registered for {arch} "
            f"(registered: {list(record['arches'])})"
        )
    if not toolchain_supports(arch):
        raise RuntimeError(
            f"generated dense projection GEMM module {name!r} targets {arch}, "
            "which this checkout cannot compile"
        )
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{record['cache_name']}_{arch}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[arch],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_dense_projection_gemm_module(name: str, arch: str):
    return gen_cake_dense_projection_gemm_module(name, arch).build_and_load()
