"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

from ...jit import env as jit_env
from ...jit.core import gen_jit_spec, sm100a_nvcc_flags, sm103a_nvcc_flags

# Explicit target-owned registration of the generated programs.
#
# ``MODULES`` holds one record per physical generated module (a kernel plus
# its host binding): architecture, role, translation units, compile flags,
# FFI entry, argument plan and closure identity.
#
# ``ROUTES`` maps ``"<dtype>_p<page_size>_g<item_groups>_pm<partition_mode>__<arch>"``
# to the physical *main* (persistent decode) module of that variant.  The
# main kernel is traced per (KV dtype, page size, scheduler item-group
# capacity, partition mode); the host plan (``cake_backend.plan_varq_dcp_decode``)
# selects the variant from host-known scalars only.
#
# ``MERGE_MODULES`` maps an architecture to its split-KV merge kernel
# (``mla_varq_dcp_merge``), launched programmatically behind the main kernel
# by the ticket-scheduler variants whose plan can split an item.
#
# All three literals are populated verbatim by the generated-program export;
# do not edit them by hand.
MODULES: dict[str, dict[str, Any]] = {
    "cake_mla_varq_dcp_decode_151fa207eae09b6acf4c": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_151fa207eae09b6acf4c_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_151fa207eae09b6acf4c_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "bcf0835649dcfd02f5fa8510baded031d023f68f86948e1263770560cd565ba3",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_1d9c4091b5b5be58ac17": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_1d9c4091b5b5be58ac17_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_1d9c4091b5b5be58ac17_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7492c9daaed1c551afc2cbbdd2a6e2e879e9c9b059e44714bd007c43ac80a762",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_21887aef96de2fe1072b": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_21887aef96de2fe1072b_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_21887aef96de2fe1072b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "957a8b29fd6eff4501bab2930e2e9228725528019171b5babb4f98cff7dc1654",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_231353abd6b556678996": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_231353abd6b556678996_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_231353abd6b556678996_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "d4ac351a2791ef29d974d75d6c4d1ccac11f788932dee39e94b03688db1b6b61",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_252672ef0d898f524376": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_252672ef0d898f524376_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_252672ef0d898f524376_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a38ea6294e6e4473526eb0fc2711865176c644a108e5e82ced1e828fe1d3b10a",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_2bf7383af34e3992d465": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_2bf7383af34e3992d465_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_2bf7383af34e3992d465_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "43a683da1f42892aa35938a5c5546fb2149a7b6ba2817956b3bcbb8d72d524f4",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_2db15bd8b3f55f014cd2": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_2db15bd8b3f55f014cd2_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_2db15bd8b3f55f014cd2_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8f6748d151f2167cfdfb306786ef6de5eb36a64af92b8b257cfaa126c3c0e7ae",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_3dce533f439187b2ba94": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_3dce533f439187b2ba94_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_3dce533f439187b2ba94_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "e81dfa1793aa69c8c8a3a6943dcde71a549955cd0da3dd890ad29aa61a987e57",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_40856d47a0d677ff3995": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_40856d47a0d677ff3995_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_40856d47a0d677ff3995_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "1e2c754a469f1433ec7838019b410538f7c4795c2408569dd25b6e182d980e80",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_4e94141393551a162838": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_4e94141393551a162838_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_4e94141393551a162838_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "38f72cb5d54f7a9558f861a39b950f0918ab3ef988837a748e16d424c1387031",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_55f942c0fd73976256b7": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_55f942c0fd73976256b7_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_55f942c0fd73976256b7_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "2bf86596ef94e2ccbe09997c1ee10f621ac79308f9427b71ea74cc1e9ee4fd31",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_79a964f6e6f6d83fa856": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_79a964f6e6f6d83fa856_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_79a964f6e6f6d83fa856_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "8c65a8142c4a6c0d039eb0f572e1092c5c21905819987775c1e31b256d41cb39",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_8681b1169cbf8bfa80c0": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_8681b1169cbf8bfa80c0_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_8681b1169cbf8bfa80c0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "c2c705a27d713d40fdcd31a666a35e9390c961c914b324fcb2d99068bb64e587",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_871774c686ce52af84b0": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_871774c686ce52af84b0_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_871774c686ce52af84b0_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "09d79fc94ef68f542ffc34363d41b1713fad1ed5c4c95d5d34a7189e621744c2",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_8a18ba249996045a7426": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_8a18ba249996045a7426_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_8a18ba249996045a7426_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["buffer", "cum_seq_lens_q"],
            ["parameter", "num_heads"],
            ["parameter", "tiles_max"],
            ["parameter", "max_records"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "07c704ded0148fdbae0cce4bcdbd665a39790d0c8d8c89da4c5e7756c6735dd4",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_98b03fefa040cdc3d38b": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_98b03fefa040cdc3d38b_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_98b03fefa040cdc3d38b_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "a678288937e7838c95c5abb01e703c32de3e08bb0f5280d7d4f679753e5df2aa",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_bd9a8b80a732b73de2a5": {
        "arch": "sm_100a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_bd9a8b80a732b73de2a5_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_100a/cake_mla_varq_dcp_decode_bd9a8b80a732b73de2a5_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["buffer", "cum_seq_lens_q"],
            ["parameter", "num_heads"],
            ["parameter", "tiles_max"],
            ["parameter", "max_records"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "319ac5f7da5162c92fad056c6ef7f1431802e6aba31788ac7c8419015c1f6797",
        "tma_workspace_bytes": 0,
    },
    "cake_mla_varq_dcp_decode_d0514cfa6f6541a12cb6": {
        "arch": "sm_103a",
        "role": "kernel",
        "sources": [
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_d0514cfa6f6541a12cb6_kernel.cu",
            "cake_mla_varq_dcp_decode/sm_103a/cake_mla_varq_dcp_decode_d0514cfa6f6541a12cb6_binding.cu",
        ],
        "compile_flags": ["--use_fast_math"],
        "ffi_entry": "run",
        "arg_plan": [
            ["tma_buffer", "tmap_q"],
            ["tma_buffer", "tmap_k"],
            ["tma_buffer", "tmap_v"],
            ["tma_buffer", "tmap_o"],
            ["tma_buffer", "tmap_po"],
            ["buffer", "O"],
            ["buffer", "LSE"],
            ["buffer", "partial_O"],
            ["buffer", "partial_lse"],
            ["buffer", "page_table"],
            ["buffer", "seq_lens"],
            ["buffer", "cum_seq_lens_q"],
            ["buffer", "causal_global"],
            ["buffer", "sched_counters"],
            ["buffer", "unit_flags"],
            ["buffer", "split_meta"],
            ["buffer", "merge_ctl"],
            ["parameter", "softmax_scale_log2"],
            ["parameter", "tiles_max"],
            ["parameter", "num_heads"],
            ["parameter", "max_pages"],
            ["parameter", "cp_world"],
            ["parameter", "cp_rank"],
            ["parameter", "num_items"],
            ["parameter", "unit_min"],
            ["parameter", "static_tiles"],
            ["parameter", "unit_num"],
            ["parameter", "unit_den"],
            ["parameter", "max_units"],
            ["parameter", "static_only"],
            ["buffer", "dbg"],
            ["parameter", "partial_slots"],
            ["parameter", "fd_tiles_max"],
            ["parameter", "fd_num_heads"],
            ["parameter", "fd_cp_world"],
            ["parameter", "fd_num_items"],
            ["parameter", "fd_unit_min"],
            ["parameter", "fd_static_tiles"],
            ["parameter", "fd_unit_den"],
            ["parameter", "fd_clusters"],
            ["grid", "grid_x"],
            ["grid", "grid_y"],
            ["grid", "grid_z"],
        ],
        "closure_sha256": "7f4de180a886366dd488a23db3ee5485d149dccfe096ffb4d49251e61c3d22b1",
        "tma_workspace_bytes": 0,
    },
}
ROUTES: dict[str, dict[str, Any]] = {
    "bf16_p32_g4_pm1__sm_100a": {
        "arch": "sm_100a",
        "dtype": "bf16",
        "page_size": 32,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_98b03fefa040cdc3d38b",
    },
    "bf16_p32_g4_pm1__sm_103a": {
        "arch": "sm_103a",
        "dtype": "bf16",
        "page_size": 32,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_3dce533f439187b2ba94",
    },
    "bf16_p64_g16_pm0__sm_100a": {
        "arch": "sm_100a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 16,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_79a964f6e6f6d83fa856",
    },
    "bf16_p64_g16_pm0__sm_103a": {
        "arch": "sm_103a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 16,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_40856d47a0d677ff3995",
    },
    "bf16_p64_g4_pm0__sm_100a": {
        "arch": "sm_100a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_151fa207eae09b6acf4c",
    },
    "bf16_p64_g4_pm0__sm_103a": {
        "arch": "sm_103a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_d0514cfa6f6541a12cb6",
    },
    "bf16_p64_g4_pm1__sm_100a": {
        "arch": "sm_100a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_8681b1169cbf8bfa80c0",
    },
    "bf16_p64_g4_pm1__sm_103a": {
        "arch": "sm_103a",
        "dtype": "bf16",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_21887aef96de2fe1072b",
    },
    "fp8_p128_g4_pm1__sm_100a": {
        "arch": "sm_100a",
        "dtype": "fp8",
        "page_size": 128,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_2bf7383af34e3992d465",
    },
    "fp8_p128_g4_pm1__sm_103a": {
        "arch": "sm_103a",
        "dtype": "fp8",
        "page_size": 128,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_55f942c0fd73976256b7",
    },
    "fp8_p64_g16_pm0__sm_100a": {
        "arch": "sm_100a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 16,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_4e94141393551a162838",
    },
    "fp8_p64_g16_pm0__sm_103a": {
        "arch": "sm_103a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 16,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_871774c686ce52af84b0",
    },
    "fp8_p64_g4_pm0__sm_100a": {
        "arch": "sm_100a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_252672ef0d898f524376",
    },
    "fp8_p64_g4_pm0__sm_103a": {
        "arch": "sm_103a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 0,
        "main": "cake_mla_varq_dcp_decode_231353abd6b556678996",
    },
    "fp8_p64_g4_pm1__sm_100a": {
        "arch": "sm_100a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_1d9c4091b5b5be58ac17",
    },
    "fp8_p64_g4_pm1__sm_103a": {
        "arch": "sm_103a",
        "dtype": "fp8",
        "page_size": 64,
        "item_groups": 4,
        "partition_mode": 1,
        "main": "cake_mla_varq_dcp_decode_2db15bd8b3f55f014cd2",
    },
}
MERGE_MODULES: dict[str, str] = {
    "sm_100a": "cake_mla_varq_dcp_decode_bd9a8b80a732b73de2a5",
    "sm_103a": "cake_mla_varq_dcp_decode_8a18ba249996045a7426",
}

STAGES = ("main", "merge")
ARCH_NVCC_FLAGS = {
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}
TRACKING_ISSUE = "flashinfer-ai/flashinfer#4658"


def route_name(
    arch: str, dtype: str, page_size: int, item_groups: int, partition_mode: int
) -> str:
    return f"{dtype}_p{int(page_size)}_g{int(item_groups)}_pm{int(bool(partition_mode))}__{arch}"


def main_route_available(
    arch: str, dtype: str, page_size: int, item_groups: int, partition_mode: int
) -> bool:
    return route_name(arch, dtype, page_size, item_groups, partition_mode) in ROUTES


def select_main_module(
    arch: str, dtype: str, page_size: int, item_groups: int, partition_mode: int
) -> str:
    """Return the registered main-kernel module of one physical variant."""
    name = route_name(arch, dtype, page_size, item_groups, partition_mode)
    record = ROUTES.get(name)
    if record is None:
        raise NotImplementedError(
            "The generated Cake MLA var-Q DCP decode program "
            f"{name!r} (dtype={dtype}, page_size={page_size}, "
            f"item_groups={item_groups}, partition_mode={int(bool(partition_mode))}) "
            f"is not registered in this checkout (see {TRACKING_ISSUE})"
        )
    module = record["main"]
    if module not in MODULES or MODULES[module]["arch"] != arch:
        raise RuntimeError(
            f"route {name!r} names an unregistered main module {module!r}"
        )
    return module


def select_merge_module(arch: str) -> str:
    """Return the registered split-KV merge kernel module for ``arch``."""
    module = MERGE_MODULES.get(arch)
    if module is None:
        raise NotImplementedError(
            "The generated Cake MLA var-Q DCP merge kernel for "
            f"{arch} is not registered in this checkout (see {TRACKING_ISSUE})"
        )
    if module not in MODULES or MODULES[module]["arch"] != arch:
        raise RuntimeError(f"merge module {module!r} for {arch} is not registered")
    return module


def _header_dirs():
    installed = [jit_env.FLASHINFER_CSRC_DIR, jit_env.FLASHINFER_INCLUDE_DIR]
    if (installed[0] / "tvm_ffi_utils.h").is_file() and (
        installed[1] / "flashinfer/layout.cuh"
    ).is_file():
        return installed
    checkout = Path(__file__).resolve().parents[3]
    source = [checkout / "csrc", checkout / "include"]
    if (source[0] / "tvm_ffi_utils.h").is_file() and (
        source[1] / "flashinfer/layout.cuh"
    ).is_file():
        return source
    raise FileNotFoundError("FlashInfer binding headers were not found")


@functools.cache
def gen_cake_mla_varq_dcp_decode_module(name: str):
    record = MODULES[name]
    root = Path(__file__).resolve().parent / "csrc"
    sources = [root / relative for relative in record["sources"]]
    return gen_jit_spec(
        name=f"{name}_" + record["closure_sha256"][:20],
        sources=sources,
        extra_cuda_cflags=[
            *ARCH_NVCC_FLAGS[record["arch"]],
            *record["compile_flags"],
        ],
        extra_ldflags=["-lcuda"],
        extra_include_paths=[root, *[p.parent for p in sources], *_header_dirs()],
        use_fast_math=False,
    )


@functools.cache
def load_cake_mla_varq_dcp_decode_module(name: str):
    return gen_cake_mla_varq_dcp_decode_module(name).build_and_load()
