/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8'.
#include "cake_kda_prefill_host_shim.cuh"

struct CakeTensorMap;
extern "C" __global__ void kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8(float* __restrict__ ws_qd, CakeTensorMap const* ws_qd_tma, float* __restrict__ ws_kd, CakeTensorMap const* ws_kd_tma, float* __restrict__ ws_w, CakeTensorMap const* ws_w_tma, float* __restrict__ ws_qk, CakeTensorMap const* ws_qk_tma, float* __restrict__ ws_diag, CakeTensorMap const* ws_diag_tma, __nv_bfloat16* __restrict__ v, CakeTensorMap const* v_tma, long long* __restrict__ cu_seqlens, int* __restrict__ cu_chunks, int* __restrict__ seq_order, __nv_bfloat16* __restrict__ initial_state, __nv_bfloat16* __restrict__ out, CakeTensorMap const* out_tma, __nv_bfloat16* __restrict__ final_state, int num_heads, int use_initial_state, int store_final_state, float scale, unsigned long long state_indices_addr, long long state_slot_stride, int use_state_indices, float* __restrict__ initial_state_f32, float* __restrict__ final_state_f32, __nv_bfloat16* __restrict__ state_checkpoints, long long* __restrict__ checkpoint_cu_starts, int checkpoint_every_n_tokens);

namespace cake_host_shim_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8 {

using namespace cake_kda_prefill_shim;
using tvm::ffi::Optional;
using tvm::ffi::TensorView;

void RunWithDescriptors(TensorView arg_ws_qd, TensorView arg_ws_qd_tma, TensorView arg_ws_kd, TensorView arg_ws_kd_tma, TensorView arg_ws_w, TensorView arg_ws_w_tma, TensorView arg_ws_qk, TensorView arg_ws_qk_tma, TensorView arg_ws_diag, TensorView arg_ws_diag_tma, TensorView arg_v, TensorView arg_v_tma, TensorView arg_cu_seqlens, TensorView arg_cu_chunks, TensorView arg_seq_order, TensorView arg_initial_state, TensorView arg_out, TensorView arg_out_tma, TensorView arg_final_state, int64_t arg_num_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, double arg_scale, int64_t arg_state_indices_addr, int64_t arg_state_slot_stride, int64_t arg_use_state_indices, TensorView arg_initial_state_f32, TensorView arg_final_state_f32, TensorView arg_state_checkpoints, TensorView arg_checkpoint_cu_starts, int64_t arg_checkpoint_every_n_tokens, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z, int descriptor_action) {
  DLDevice dev = arg_ws_qd.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_ws_qd, "ws_qd");
  CheckDtype(arg_ws_qd, "ws_qd", 2, 32, 1);
  CheckContiguous(arg_ws_qd, "ws_qd");
  CheckCudaTensor(arg_ws_qd_tma, "ws_qd_tma");
  CheckDtype(arg_ws_qd_tma, "ws_qd_tma", 2, 32, 1);
  CheckContiguous(arg_ws_qd_tma, "ws_qd_tma");
  CheckCudaTensor(arg_ws_kd, "ws_kd");
  CheckDtype(arg_ws_kd, "ws_kd", 2, 32, 1);
  CheckContiguous(arg_ws_kd, "ws_kd");
  CheckCudaTensor(arg_ws_kd_tma, "ws_kd_tma");
  CheckDtype(arg_ws_kd_tma, "ws_kd_tma", 2, 32, 1);
  CheckContiguous(arg_ws_kd_tma, "ws_kd_tma");
  CheckCudaTensor(arg_ws_w, "ws_w");
  CheckDtype(arg_ws_w, "ws_w", 2, 32, 1);
  CheckContiguous(arg_ws_w, "ws_w");
  CheckCudaTensor(arg_ws_w_tma, "ws_w_tma");
  CheckDtype(arg_ws_w_tma, "ws_w_tma", 2, 32, 1);
  CheckContiguous(arg_ws_w_tma, "ws_w_tma");
  CheckCudaTensor(arg_ws_qk, "ws_qk");
  CheckDtype(arg_ws_qk, "ws_qk", 2, 32, 1);
  CheckContiguous(arg_ws_qk, "ws_qk");
  CheckCudaTensor(arg_ws_qk_tma, "ws_qk_tma");
  CheckDtype(arg_ws_qk_tma, "ws_qk_tma", 2, 32, 1);
  CheckContiguous(arg_ws_qk_tma, "ws_qk_tma");
  CheckCudaTensor(arg_ws_diag, "ws_diag");
  CheckDtype(arg_ws_diag, "ws_diag", 2, 32, 1);
  CheckContiguous(arg_ws_diag, "ws_diag");
  CheckCudaTensor(arg_ws_diag_tma, "ws_diag_tma");
  CheckDtype(arg_ws_diag_tma, "ws_diag_tma", 2, 32, 1);
  CheckContiguous(arg_ws_diag_tma, "ws_diag_tma");
  CheckCudaTensor(arg_v, "v");
  CheckDtype(arg_v, "v", 4, 16, 1);
  CheckContiguous(arg_v, "v");
  CheckCudaTensor(arg_v_tma, "v_tma");
  CheckDtype(arg_v_tma, "v_tma", 4, 16, 1);
  CheckContiguous(arg_v_tma, "v_tma");
  CheckCudaTensor(arg_cu_seqlens, "cu_seqlens");
  CheckDtype(arg_cu_seqlens, "cu_seqlens", 0, 64, 1);
  CheckContiguous(arg_cu_seqlens, "cu_seqlens");
  CheckCudaTensor(arg_cu_chunks, "cu_chunks");
  CheckDtype(arg_cu_chunks, "cu_chunks", 0, 32, 1);
  CheckContiguous(arg_cu_chunks, "cu_chunks");
  CheckCudaTensor(arg_seq_order, "seq_order");
  CheckDtype(arg_seq_order, "seq_order", 0, 32, 1);
  CheckContiguous(arg_seq_order, "seq_order");
  CheckCudaTensor(arg_initial_state, "initial_state");
  CheckDtype(arg_initial_state, "initial_state", 4, 16, 1);
  CheckContiguous(arg_initial_state, "initial_state");
  CheckCudaTensor(arg_out, "out");
  CheckDtype(arg_out, "out", 4, 16, 1);
  CheckContiguous(arg_out, "out");
  CheckCudaTensor(arg_out_tma, "out_tma");
  CheckDtype(arg_out_tma, "out_tma", 4, 16, 1);
  CheckContiguous(arg_out_tma, "out_tma");
  CheckCudaTensor(arg_final_state, "final_state");
  CheckDtype(arg_final_state, "final_state", 4, 16, 1);
  CheckContiguous(arg_final_state, "final_state");
  TVM_FFI_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_use_initial_state >= -2147483648LL && arg_use_initial_state <= 2147483647LL, ValueError)
      << "scalar 'use_initial_state' value " << arg_use_initial_state
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_store_final_state >= -2147483648LL && arg_store_final_state <= 2147483647LL, ValueError)
      << "scalar 'store_final_state' value " << arg_store_final_state
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_state_indices_addr >= 0LL && arg_state_indices_addr <= 9223372036854775807LL, ValueError)
      << "scalar 'state_indices_addr' value " << arg_state_indices_addr
      << " is outside u64 range [0, 9223372036854775807]";
  TVM_FFI_CHECK(arg_use_state_indices >= -2147483648LL && arg_use_state_indices <= 2147483647LL, ValueError)
      << "scalar 'use_state_indices' value " << arg_use_state_indices
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckCudaTensor(arg_initial_state_f32, "initial_state_f32");
  CheckDtype(arg_initial_state_f32, "initial_state_f32", 2, 32, 1);
  CheckContiguous(arg_initial_state_f32, "initial_state_f32");
  CheckCudaTensor(arg_final_state_f32, "final_state_f32");
  CheckDtype(arg_final_state_f32, "final_state_f32", 2, 32, 1);
  CheckContiguous(arg_final_state_f32, "final_state_f32");
  CheckCudaTensor(arg_state_checkpoints, "state_checkpoints");
  CheckDtype(arg_state_checkpoints, "state_checkpoints", 4, 16, 1);
  CheckContiguous(arg_state_checkpoints, "state_checkpoints");
  CheckCudaTensor(arg_checkpoint_cu_starts, "checkpoint_cu_starts");
  CheckDtype(arg_checkpoint_cu_starts, "checkpoint_cu_starts", 0, 64, 1);
  CheckContiguous(arg_checkpoint_cu_starts, "checkpoint_cu_starts");
  TVM_FFI_CHECK(arg_checkpoint_every_n_tokens >= -2147483648LL && arg_checkpoint_every_n_tokens <= 2147483647LL, ValueError)
      << "scalar 'checkpoint_every_n_tokens' value " << arg_checkpoint_every_n_tokens
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_ws_qd_tma, arg_ws_qd, "ws_qd_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_kd, arg_ws_qd, "ws_kd", "ws_qd");
  CheckSameCudaDevice(arg_ws_kd_tma, arg_ws_qd, "ws_kd_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_w, arg_ws_qd, "ws_w", "ws_qd");
  CheckSameCudaDevice(arg_ws_w_tma, arg_ws_qd, "ws_w_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_qk, arg_ws_qd, "ws_qk", "ws_qd");
  CheckSameCudaDevice(arg_ws_qk_tma, arg_ws_qd, "ws_qk_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_diag, arg_ws_qd, "ws_diag", "ws_qd");
  CheckSameCudaDevice(arg_ws_diag_tma, arg_ws_qd, "ws_diag_tma", "ws_qd");
  CheckSameCudaDevice(arg_v, arg_ws_qd, "v", "ws_qd");
  CheckSameCudaDevice(arg_v_tma, arg_ws_qd, "v_tma", "ws_qd");
  CheckSameCudaDevice(arg_cu_seqlens, arg_ws_qd, "cu_seqlens", "ws_qd");
  CheckSameCudaDevice(arg_cu_chunks, arg_ws_qd, "cu_chunks", "ws_qd");
  CheckSameCudaDevice(arg_seq_order, arg_ws_qd, "seq_order", "ws_qd");
  CheckSameCudaDevice(arg_initial_state, arg_ws_qd, "initial_state", "ws_qd");
  CheckSameCudaDevice(arg_out, arg_ws_qd, "out", "ws_qd");
  CheckSameCudaDevice(arg_out_tma, arg_ws_qd, "out_tma", "ws_qd");
  CheckSameCudaDevice(arg_final_state, arg_ws_qd, "final_state", "ws_qd");
  CheckSameCudaDevice(arg_initial_state_f32, arg_ws_qd, "initial_state_f32", "ws_qd");
  CheckSameCudaDevice(arg_final_state_f32, arg_ws_qd, "final_state_f32", "ws_qd");
  CheckSameCudaDevice(arg_state_checkpoints, arg_ws_qd, "state_checkpoints", "ws_qd");
  CheckSameCudaDevice(arg_checkpoint_cu_starts, arg_ws_qd, "checkpoint_cu_starts", "ws_qd");
  CheckCurrentCudaDevice(arg_ws_qd, "ws_qd");
  CheckCudaTensor(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckSameCudaDevice(arg_tma_descriptor_workspace, arg_ws_qd, "tma_descriptor_workspace", "ws_qd");
  CheckContiguous(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckDtype(arg_tma_descriptor_workspace, "tma_descriptor_workspace", 1, 8, 1);
  TVM_FFI_CHECK(arg_tma_descriptor_workspace.numel() >= 896, ValueError)
      << "tma_descriptor_workspace requires at least 896 bytes";
  TVM_FFI_CHECK(
      reinterpret_cast<uintptr_t>(arg_tma_descriptor_workspace.data_ptr()) % 128 == 0,
      ValueError)
      << "tma_descriptor_workspace must be 128-byte aligned";
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  float* p_ws_qd = static_cast<float*>(arg_ws_qd.data_ptr());
  CUtensorMap h_ws_qd_tma = EncodeTma_ws_qd_tma_0(arg_ws_qd_tma);
  CakeTensorMap const* p_ws_qd_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 0u));
  float* p_ws_kd = static_cast<float*>(arg_ws_kd.data_ptr());
  CUtensorMap h_ws_kd_tma = EncodeTma_ws_kd_tma_0(arg_ws_kd_tma);
  CakeTensorMap const* p_ws_kd_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 1u));
  float* p_ws_w = static_cast<float*>(arg_ws_w.data_ptr());
  CUtensorMap h_ws_w_tma = EncodeTma_ws_w_tma_0(arg_ws_w_tma);
  CakeTensorMap const* p_ws_w_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 2u));
  float* p_ws_qk = static_cast<float*>(arg_ws_qk.data_ptr());
  CUtensorMap h_ws_qk_tma = EncodeTma_ws_qk_tma_0(arg_ws_qk_tma);
  CakeTensorMap const* p_ws_qk_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 3u));
  float* p_ws_diag = static_cast<float*>(arg_ws_diag.data_ptr());
  CUtensorMap h_ws_diag_tma = EncodeTma_ws_diag_tma_0(arg_ws_diag_tma);
  CakeTensorMap const* p_ws_diag_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 4u));
  __nv_bfloat16* p_v = static_cast<__nv_bfloat16*>(arg_v.data_ptr());
  CUtensorMap h_v_tma = EncodeTma_v_tma_0(arg_v_tma);
  CakeTensorMap const* p_v_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 5u));
  long long* p_cu_seqlens = static_cast<long long*>(arg_cu_seqlens.data_ptr());
  int* p_cu_chunks = static_cast<int*>(arg_cu_chunks.data_ptr());
  int* p_seq_order = static_cast<int*>(arg_seq_order.data_ptr());
  __nv_bfloat16* p_initial_state = static_cast<__nv_bfloat16*>(arg_initial_state.data_ptr());
  __nv_bfloat16* p_out = static_cast<__nv_bfloat16*>(arg_out.data_ptr());
  CUtensorMap h_out_tma = EncodeTma_out_tma_4(arg_out_tma);
  CakeTensorMap const* p_out_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 6u));
  __nv_bfloat16* p_final_state = static_cast<__nv_bfloat16*>(arg_final_state.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_use_initial_state = (int32_t)arg_use_initial_state;
  int32_t v_store_final_state = (int32_t)arg_store_final_state;
  float v_scale = (float)arg_scale;
  uint64_t v_state_indices_addr = (uint64_t)arg_state_indices_addr;
  int64_t v_state_slot_stride = (int64_t)arg_state_slot_stride;
  int32_t v_use_state_indices = (int32_t)arg_use_state_indices;
  float* p_initial_state_f32 = static_cast<float*>(arg_initial_state_f32.data_ptr());
  float* p_final_state_f32 = static_cast<float*>(arg_final_state_f32.data_ptr());
  __nv_bfloat16* p_state_checkpoints = static_cast<__nv_bfloat16*>(arg_state_checkpoints.data_ptr());
  long long* p_checkpoint_cu_starts = static_cast<long long*>(arg_checkpoint_cu_starts.data_ptr());
  int32_t v_checkpoint_every_n_tokens = (int32_t)arg_checkpoint_every_n_tokens;
  void* kargs[] = {&p_ws_qd, &p_ws_qd_tma, &p_ws_kd, &p_ws_kd_tma, &p_ws_w, &p_ws_w_tma, &p_ws_qk, &p_ws_qk_tma, &p_ws_diag, &p_ws_diag_tma, &p_v, &p_v_tma, &p_cu_seqlens, &p_cu_chunks, &p_seq_order, &p_initial_state, &p_out, &p_out_tma, &p_final_state, &v_num_heads, &v_use_initial_state, &v_store_final_state, &v_scale, &v_state_indices_addr, &v_state_slot_stride, &v_use_state_indices, &p_initial_state_f32, &p_final_state_f32, &p_state_checkpoints, &p_checkpoint_cu_starts, &v_checkpoint_every_n_tokens};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = EnsureMaxDynamicSharedMemory(
      smem_mu, *smem_status_by_device, dev.device_id,
      reinterpret_cast<const void*>(kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8), 177152);
  TVM_FFI_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(512u, 1u, 1u);
  if (descriptor_action != 0) {
  const CUtensorMap workspace_maps[] = {h_ws_qd_tma, h_ws_kd_tma, h_ws_w_tma, h_ws_qk_tma, h_ws_diag_tma, h_v_tma, h_out_tma};
  UploadCallerTmaWorkspace(arg_tma_descriptor_workspace.data_ptr(), workspace_maps, stream);
  }
  if (descriptor_action == 1) return;

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 177152u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8), kargs);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kda_tf32_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8 failed: "
      << cudaGetErrorString(launch_status);
}

void Run(TensorView arg_ws_qd, TensorView arg_ws_qd_tma, TensorView arg_ws_kd, TensorView arg_ws_kd_tma, TensorView arg_ws_w, TensorView arg_ws_w_tma, TensorView arg_ws_qk, TensorView arg_ws_qk_tma, TensorView arg_ws_diag, TensorView arg_ws_diag_tma, TensorView arg_v, TensorView arg_v_tma, TensorView arg_cu_seqlens, TensorView arg_cu_chunks, TensorView arg_seq_order, TensorView arg_initial_state, TensorView arg_out, TensorView arg_out_tma, TensorView arg_final_state, int64_t arg_num_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, double arg_scale, int64_t arg_state_indices_addr, int64_t arg_state_slot_stride, int64_t arg_use_state_indices, TensorView arg_initial_state_f32, TensorView arg_final_state_f32, TensorView arg_state_checkpoints, TensorView arg_checkpoint_cu_starts, int64_t arg_checkpoint_every_n_tokens, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_ws_qd, arg_ws_qd_tma, arg_ws_kd, arg_ws_kd_tma, arg_ws_w, arg_ws_w_tma, arg_ws_qk, arg_ws_qk_tma, arg_ws_diag, arg_ws_diag_tma, arg_v, arg_v_tma, arg_cu_seqlens, arg_cu_chunks, arg_seq_order, arg_initial_state, arg_out, arg_out_tma, arg_final_state, arg_num_heads, arg_use_initial_state, arg_store_final_state, arg_scale, arg_state_indices_addr, arg_state_slot_stride, arg_use_state_indices, arg_initial_state_f32, arg_final_state_f32, arg_state_checkpoints, arg_checkpoint_cu_starts, arg_checkpoint_every_n_tokens, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 2);
}

void PrepareTma(TensorView arg_ws_qd, TensorView arg_ws_qd_tma, TensorView arg_ws_kd, TensorView arg_ws_kd_tma, TensorView arg_ws_w, TensorView arg_ws_w_tma, TensorView arg_ws_qk, TensorView arg_ws_qk_tma, TensorView arg_ws_diag, TensorView arg_ws_diag_tma, TensorView arg_v, TensorView arg_v_tma, TensorView arg_cu_seqlens, TensorView arg_cu_chunks, TensorView arg_seq_order, TensorView arg_initial_state, TensorView arg_out, TensorView arg_out_tma, TensorView arg_final_state, int64_t arg_num_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, double arg_scale, int64_t arg_state_indices_addr, int64_t arg_state_slot_stride, int64_t arg_use_state_indices, TensorView arg_initial_state_f32, TensorView arg_final_state_f32, TensorView arg_state_checkpoints, TensorView arg_checkpoint_cu_starts, int64_t arg_checkpoint_every_n_tokens, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_ws_qd, arg_ws_qd_tma, arg_ws_kd, arg_ws_kd_tma, arg_ws_w, arg_ws_w_tma, arg_ws_qk, arg_ws_qk_tma, arg_ws_diag, arg_ws_diag_tma, arg_v, arg_v_tma, arg_cu_seqlens, arg_cu_chunks, arg_seq_order, arg_initial_state, arg_out, arg_out_tma, arg_final_state, arg_num_heads, arg_use_initial_state, arg_store_final_state, arg_scale, arg_state_indices_addr, arg_state_slot_stride, arg_use_state_indices, arg_initial_state_f32, arg_final_state_f32, arg_state_checkpoints, arg_checkpoint_cu_starts, arg_checkpoint_every_n_tokens, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 1);
}

void RunPrepared(TensorView arg_ws_qd, TensorView arg_ws_qd_tma, TensorView arg_ws_kd, TensorView arg_ws_kd_tma, TensorView arg_ws_w, TensorView arg_ws_w_tma, TensorView arg_ws_qk, TensorView arg_ws_qk_tma, TensorView arg_ws_diag, TensorView arg_ws_diag_tma, TensorView arg_v, TensorView arg_v_tma, TensorView arg_cu_seqlens, TensorView arg_cu_chunks, TensorView arg_seq_order, TensorView arg_initial_state, TensorView arg_out, TensorView arg_out_tma, TensorView arg_final_state, int64_t arg_num_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, double arg_scale, int64_t arg_state_indices_addr, int64_t arg_state_slot_stride, int64_t arg_use_state_indices, TensorView arg_initial_state_f32, TensorView arg_final_state_f32, TensorView arg_state_checkpoints, TensorView arg_checkpoint_cu_starts, int64_t arg_checkpoint_every_n_tokens, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  RunWithDescriptors(arg_ws_qd, arg_ws_qd_tma, arg_ws_kd, arg_ws_kd_tma, arg_ws_w, arg_ws_w_tma, arg_ws_qk, arg_ws_qk_tma, arg_ws_diag, arg_ws_diag_tma, arg_v, arg_v_tma, arg_cu_seqlens, arg_cu_chunks, arg_seq_order, arg_initial_state, arg_out, arg_out_tma, arg_final_state, arg_num_heads, arg_use_initial_state, arg_store_final_state, arg_scale, arg_state_indices_addr, arg_state_slot_stride, arg_use_state_indices, arg_initial_state_f32, arg_final_state_f32, arg_state_checkpoints, arg_checkpoint_cu_starts, arg_checkpoint_every_n_tokens, arg_tma_descriptor_workspace, grid_x, grid_y, grid_z, 0);
}

}  // namespace cake_host_shim_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8::Run);
TVM_FFI_DLL_EXPORT_TYPED_FUNC(run_prepare_tma, cake_host_shim_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8::PrepareTma);
TVM_FFI_DLL_EXPORT_TYPED_FUNC(run_prepared, cake_host_shim_dd0f76773ac27a364fcf5df27f69697e3b1af22c2f77595b41b23945752e90f8::RunPrepared);
