// Generated by cuda.runtime.host_shim — do not edit.
// tvm-ffi host launcher for generated kernel 'kernel_flashkda_bf16_bt16_chain_m64'.
#include <cuda.h>
#include <cuda_runtime_api.h>

#include <tvm/ffi/container/tensor.h>
#include <tvm/ffi/error.h>
#include <tvm/ffi/extra/c_env_api.h>
#include <tvm/ffi/extra/cuda/cubin_launcher.h>
#include <tvm/ffi/function.h>

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

TVM_FFI_EMBED_CUBIN(flashkda_bf16_bt16_chain_m64_d3d65ffa34);

namespace cuda_host_shim_3bead515fefbe0ea {

using tvm::ffi::TensorView;

inline int64_t CudaDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  TVM_FFI_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  TVM_FFI_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  TVM_FFI_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  TVM_FFI_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  TVM_FFI_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

// CUDA 13.4 adds an oversized shared-memory mode (function/launch attribute
// SHARED_MEMORY_MODE = 3) that lets a kernel exceed the standard
// MaxSharedMemoryPerBlockOptin ceiling up to device attribute 150
// (OversizedSharedMemoryPerBlock), at the cost of an 8 KiB L1 carveout.
#if (TVM_FFI_CUBIN_LAUNCHER_USE_DRIVER_API && defined(CUDA_VERSION) && CUDA_VERSION >= 13040) || \
    (!TVM_FFI_CUBIN_LAUNCHER_USE_DRIVER_API && defined(CUDART_VERSION) && CUDART_VERSION >= 13040)
#define CUDA_HAS_OVERSIZED_SMEM 1
#else
#define CUDA_HAS_OVERSIZED_SMEM 0
#endif

// Per-device dynamic-SMEM opt-in. Returns true when launches on this device
// must carry the ALLOW_OVERSIZED shared-memory-mode launch attribute: the
// request exceeds the device's standard opt-in ceiling
// (MaxSharedMemoryPerBlockOptin, attribute 97) but fits the oversized ceiling
// (OversizedSharedMemoryPerBlock, attribute 150). Within the standard ceiling
// it sets MAX_DYNAMIC_SHARED_SIZE_BYTES for the device, mirroring
// CubinKernel::SetMaxDynamicSharedMemory. cache: 0 = unresolved,
// 1 = standard opt-in done, 2 = oversized mode required.
inline bool CudaConfigureDynamicSmem(tvm::ffi::CubinKernel& kernel, int device_id,
                                     int smem_bytes, signed char* cache, int cache_len) {
  namespace cuda_api = tvm::ffi::cuda_api;
  TVM_FFI_CHECK(device_id >= 0 && device_id < cache_len, RuntimeError)
      << "dynamic-SMEM opt-in cache does not cover cuda:" << device_id;
  if (cache[device_id] != 0) {
    return cache[device_id] == 2;
  }
  auto device = cuda_api::GetDeviceHandle(device_id);
  int optin_max = 0;
  cuda_api::ResultType err = cuda_api::GetDeviceAttribute(
      &optin_max,
      /* CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN /
         cudaDevAttrMaxSharedMemoryPerBlockOptin */
      cuda_api::DeviceAttrType(97), device);
  TVM_FFI_CHECK(err == cuda_api::kSuccess, RuntimeError)
      << "querying MaxSharedMemoryPerBlockOptin failed for cuda:" << device_id;
  if (smem_bytes <= optin_max) {
    err = cuda_api::SetKernelMaxDynamicSharedMem(kernel.GetHandle(), smem_bytes, device);
    TVM_FFI_CHECK(err == cuda_api::kSuccess, RuntimeError)
        << "MAX_DYNAMIC_SHARED_SIZE_BYTES=" << smem_bytes << " rejected for cuda:" << device_id;
    cache[device_id] = 1;
    return false;
  }
#if CUDA_HAS_OVERSIZED_SMEM
  int oversized_max = 0;
  err = cuda_api::GetDeviceAttribute(
      &oversized_max,
      /* CU_DEVICE_ATTRIBUTE_MAX_OVERSIZED_SHARED_MEMORY_PER_BLOCK /
         cudaDevAttrOversizedSharedMemoryPerBlock */
      cuda_api::DeviceAttrType(150), device);
  TVM_FFI_CHECK(err == cuda_api::kSuccess && oversized_max >= smem_bytes, RuntimeError)
      << "dynamic smem " << smem_bytes << " B exceeds the standard opt-in ceiling ("
      << optin_max << " B) on cuda:" << device_id << " and the oversized ceiling is "
      << oversized_max << " B";
  cache[device_id] = 2;
  return true;
#else
  TVM_FFI_THROW(RuntimeError)
      << "dynamic smem " << smem_bytes << " B exceeds the standard opt-in ceiling ("
      << optin_max << " B) on cuda:" << device_id
      << " and this CUDA toolkit predates the 13.4 oversized shared-memory mode";
#endif
}

struct TmaDeviceArena {
  static constexpr size_t kSlotsPerChunk = 256;
  static constexpr size_t kMaxSlots = 4096;
  std::vector<CUdeviceptr> chunks;
  size_t used = 0;
};

// Immutable, process-lifetime device tensor-map slots for the pointer ABI.
// A slot is never rewritten: different descriptor bytes always get a new
// address, so concurrent streams cannot observe a partially updated map. The
// chunked arena caps storage at 512 KiB per CUDA context in this host module.
static inline void* TmaDeviceSlot(
    const CUtensorMap& tm,
    int device_id,
    cudaStream_t stream) {
  static std::mutex mu;
  static auto* slots = new std::unordered_map<std::string, void*>();
  static auto* arenas = new std::unordered_map<CUcontext, TmaDeviceArena>();

  // Device allocations are context-owned. Resolve and validate the active
  // context before cache lookup so a warm entry can never bypass the same
  // checks as a cold entry or leak a pointer across contexts on one device.
  CUcontext current_context = nullptr;
  CUresult result = cuCtxGetCurrent(&current_context);
  TVM_FFI_CHECK(result == CUDA_SUCCESS && current_context != nullptr, RuntimeError)
      << "pointer TMA ABI requires an active CUDA context: CUresult="
      << static_cast<int>(result);
  CUdevice current_device = -1;
  result = cuCtxGetDevice(&current_device);
  TVM_FFI_CHECK(result == CUDA_SUCCESS && current_device == device_id, RuntimeError)
      << "TMA descriptor device mismatch: current=" << current_device
      << ", tensor=" << device_id;

  std::string key =
      std::to_string(reinterpret_cast<uintptr_t>(current_context));
  key.push_back(':');
  key.append(reinterpret_cast<const char*>(&tm), sizeof(CUtensorMap));
  std::lock_guard<std::mutex> lock(mu);

  // CUcontext is an opaque, recyclable handle.  Before trusting a warm arena,
  // prove that its first allocation still belongs to this live context.  A
  // destroyed context makes the pointer query fail; a subsequently reused
  // handle must therefore discard the stale pointer and descriptor entries.
  auto arena_it = arenas->find(current_context);
  if (arena_it != arenas->end() && !arena_it->second.chunks.empty()) {
    CUcontext allocation_context = nullptr;
    result = cuPointerGetAttribute(
        &allocation_context,
        CU_POINTER_ATTRIBUTE_CONTEXT,
        arena_it->second.chunks.front());
    if (result != CUDA_SUCCESS || allocation_context != current_context) {
      const std::string prefix =
          std::to_string(reinterpret_cast<uintptr_t>(current_context)) + ":";
      for (auto slot_it = slots->begin(); slot_it != slots->end();) {
        if (slot_it->first.compare(0, prefix.size(), prefix) == 0) {
          slot_it = slots->erase(slot_it);
        } else {
          ++slot_it;
        }
      }
      arenas->erase(arena_it);
    }
  }

  auto it = slots->find(key);
  if (it != slots->end()) return it->second;

  CUstreamCaptureStatus capture_status = CU_STREAM_CAPTURE_STATUS_NONE;
  result = cuStreamIsCapturing(
      reinterpret_cast<CUstream>(stream), &capture_status);
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuStreamIsCapturing for TMA descriptor slot failed: CUresult="
      << static_cast<int>(result);
  TVM_FFI_CHECK(capture_status == CU_STREAM_CAPTURE_STATUS_NONE, RuntimeError)
      << "pointer TMA ABI cannot create a new device descriptor slot inside "
         "CUDA Graph capture; prewarm this exact tensor/layout binding or "
         "compile with tma_abi='grid_constant'";

  TmaDeviceArena& arena = (*arenas)[current_context];
  TVM_FFI_CHECK(arena.used < TmaDeviceArena::kMaxSlots, RuntimeError)
      << "pointer TMA ABI exhausted its immutable descriptor arena in CUDA "
         "context " << current_context << " on device " << device_id
      << " (capacity=" << TmaDeviceArena::kMaxSlots
      << "); reuse tensor/layout bindings or compile with tma_abi='grid_constant'";
  if (arena.used % TmaDeviceArena::kSlotsPerChunk == 0) {
    CUdeviceptr chunk = 0;
    result = cuMemAlloc(
        &chunk,
        TmaDeviceArena::kSlotsPerChunk * sizeof(CUtensorMap));
    TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
        << "cuMemAlloc for TMA descriptor arena failed: CUresult="
        << static_cast<int>(result);
    arena.chunks.push_back(chunk);
  }
  size_t chunk_index = arena.used / TmaDeviceArena::kSlotsPerChunk;
  size_t slot_index = arena.used % TmaDeviceArena::kSlotsPerChunk;
  CUdeviceptr dev = arena.chunks[chunk_index] +
                    slot_index * sizeof(CUtensorMap);
  result = cuMemcpyHtoD(dev, &tm, sizeof(CUtensorMap));
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuMemcpyHtoD for TMA descriptor slot failed: CUresult="
      << static_cast<int>(result);
  ++arena.used;
  void* pointer = reinterpret_cast<void*>(static_cast<uintptr_t>(dev));
  (*slots)[key] = pointer;
  return pointer;
}

// 4D TMA descriptor for buffer 'ws_qd_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_ws_qd_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 3, ValueError)
      << "TMA source 'ws_qd_tma' must have at least 3 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'ws_qd_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0, ValueError)
      << "TMA source 'ws_qd_tma' trailing dims must be positive";
  TVM_FFI_CHECK(d1 % 64 == 0, ValueError)
      << "TMA source 'ws_qd_tma' extent " << d1
      << " must divide exactly by " << 64;
  uint64_t global_dim[4] = {(uint64_t)(64), (uint64_t)(d2), (uint64_t)(d3), (uint64_t)((d1 / 64))};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'ws_qd_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 16u <= global_dim[1] && 1u <= global_dim[2] && 2u <= global_dim[3], ValueError)
      << "TMA box (64, 16, 1, 2) exceeds resolved global dims for 'ws_qd_tma'";
  uint64_t global_strides[3] = {
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)(((d2 * d1) * 16) / 8),
      (uint64_t)((64 * 16) / 8),
  };
  uint32_t box_dim[4] = {64u, 16u, 1u, 2u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'ws_qd_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 4D TMA descriptor for buffer 'ws_kd_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_ws_kd_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 3, ValueError)
      << "TMA source 'ws_kd_tma' must have at least 3 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'ws_kd_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0, ValueError)
      << "TMA source 'ws_kd_tma' trailing dims must be positive";
  TVM_FFI_CHECK(d1 % 64 == 0, ValueError)
      << "TMA source 'ws_kd_tma' extent " << d1
      << " must divide exactly by " << 64;
  uint64_t global_dim[4] = {(uint64_t)(64), (uint64_t)(d2), (uint64_t)(d3), (uint64_t)((d1 / 64))};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'ws_kd_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 16u <= global_dim[1] && 1u <= global_dim[2] && 2u <= global_dim[3], ValueError)
      << "TMA box (64, 16, 1, 2) exceeds resolved global dims for 'ws_kd_tma'";
  uint64_t global_strides[3] = {
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)(((d2 * d1) * 16) / 8),
      (uint64_t)((64 * 16) / 8),
  };
  uint32_t box_dim[4] = {64u, 16u, 1u, 2u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'ws_kd_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 4D TMA descriptor for buffer 'ws_w_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_ws_w_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 3, ValueError)
      << "TMA source 'ws_w_tma' must have at least 3 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'ws_w_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0, ValueError)
      << "TMA source 'ws_w_tma' trailing dims must be positive";
  TVM_FFI_CHECK(d1 % 64 == 0, ValueError)
      << "TMA source 'ws_w_tma' extent " << d1
      << " must divide exactly by " << 64;
  uint64_t global_dim[4] = {(uint64_t)(64), (uint64_t)(d2), (uint64_t)(d3), (uint64_t)((d1 / 64))};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'ws_w_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 16u <= global_dim[1] && 1u <= global_dim[2] && 2u <= global_dim[3], ValueError)
      << "TMA box (64, 16, 1, 2) exceeds resolved global dims for 'ws_w_tma'";
  uint64_t global_strides[3] = {
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)(((d2 * d1) * 16) / 8),
      (uint64_t)((64 * 16) / 8),
  };
  uint32_t box_dim[4] = {64u, 16u, 1u, 2u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'ws_w_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 5D TMA descriptor for buffer 'ws_qk_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_ws_qk_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 5, ValueError)
      << "TMA source 'ws_qk_tma' must have at least 5 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'ws_qk_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  int64_t d4 = t.size(t.ndim() - 4);
  int64_t d5 = t.size(t.ndim() - 5);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0 && d4 > 0 && d5 > 0, ValueError)
      << "TMA source 'ws_qk_tma' trailing dims must be positive";
  uint64_t global_dim[5] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(d3), (uint64_t)(d4), (uint64_t)(d5)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0 && global_dim[4] > 0, ValueError)
      << "TMA descriptor for 'ws_qk_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(16u <= global_dim[0] && 16u <= global_dim[1] && 1u <= global_dim[2] && 1u <= global_dim[3] && 1u <= global_dim[4], ValueError)
      << "TMA box (16, 16, 1, 1, 1) exceeds resolved global dims for 'ws_qk_tma'";
  uint64_t global_strides[4] = {
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)(((d2 * d1) * 16) / 8),
      (uint64_t)((((d3 * d2) * d1) * 16) / 8),
      (uint64_t)(((((d4 * d3) * d2) * d1) * 16) / 8),
  };
  uint32_t box_dim[5] = {16u, 16u, 1u, 1u, 1u};
  uint32_t elem_strides[5] = {1u, 1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 5, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_32B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (5D, 'ws_qk_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 4D TMA descriptor for buffer 'ws_diag_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_ws_diag_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 4, ValueError)
      << "TMA source 'ws_diag_tma' must have at least 4 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'ws_diag_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  int64_t d3 = t.size(t.ndim() - 3);
  int64_t d4 = t.size(t.ndim() - 4);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0 && d3 > 0 && d4 > 0, ValueError)
      << "TMA source 'ws_diag_tma' trailing dims must be positive";
  uint64_t global_dim[4] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(d3), (uint64_t)(d4)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'ws_diag_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(128u <= global_dim[0] && 1u <= global_dim[1] && 1u <= global_dim[2] && 1u <= global_dim[3], ValueError)
      << "TMA box (128, 1, 1, 1) exceeds resolved global dims for 'ws_diag_tma'";
  uint64_t global_strides[3] = {
      (uint64_t)((d1 * 32) / 8),
      (uint64_t)(((d2 * d1) * 32) / 8),
      (uint64_t)((((d3 * d2) * d1) * 32) / 8),
  };
  uint32_t box_dim[4] = {128u, 1u, 1u, 1u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_FLOAT32, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_NONE, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'ws_diag_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'v_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_v_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'v_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'v_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'v_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'v_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 1u <= global_dim[1], ValueError)
      << "TMA box (64, 1, 16) exceeds resolved global dims for 'v_tma'";
  uint64_t global_strides[2] = {
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)(((d1 * d2) * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 16u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'v_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 4D TMA descriptor for buffer 'out_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_out_tma(const TensorView& t) {
  TVM_FFI_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'out_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  TVM_FFI_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'out_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  TVM_FFI_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'out_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  TVM_FFI_CHECK(d1 % 64 == 0, ValueError)
      << "TMA source 'out_tma' extent " << d1
      << " must divide exactly by " << 64;
  uint64_t global_dim[4] = {(uint64_t)(64), (uint64_t)(outer2), (uint64_t)(d2), (uint64_t)((d1 / 64))};
  TVM_FFI_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0, ValueError)
      << "TMA descriptor for 'out_tma' resolved a non-positive global dim";
  TVM_FFI_CHECK(64u <= global_dim[0] && 1u <= global_dim[2] && 1u <= global_dim[3], ValueError)
      << "TMA box (64, 16, 1, 1) exceeds resolved global dims for 'out_tma'";
  uint64_t global_strides[3] = {
      (uint64_t)(((d2 * d1) * 16) / 8),
      (uint64_t)((d1 * 16) / 8),
      (uint64_t)((64 * 16) / 8),
  };
  uint32_t box_dim[4] = {64u, 16u, 1u, 1u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm{};
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 4, t.data_ptr(), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (4D, 'out_tma') failed: CUresult=" << (int)r;
  return tm;
}

void Run(TensorView arg_ws_qd, TensorView arg_ws_qd_tma, TensorView arg_ws_kd, TensorView arg_ws_kd_tma, TensorView arg_ws_w, TensorView arg_ws_w_tma, TensorView arg_ws_qk, TensorView arg_ws_qk_tma, TensorView arg_ws_diag, TensorView arg_ws_diag_tma, TensorView arg_v, TensorView arg_v_tma, TensorView arg_cu_seqlens, TensorView arg_cu_chunks, TensorView arg_seq_order, TensorView arg_initial_state, TensorView arg_out, TensorView arg_out_tma, TensorView arg_final_state, int64_t arg_num_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, double arg_scale, int64_t arg_state_indices_addr, int64_t arg_state_slot_stride, int64_t arg_use_state_indices, TensorView arg_initial_state_f32, TensorView arg_final_state_f32, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  CheckCudaTensor(arg_ws_qd, "ws_qd");
  CheckDtype(arg_ws_qd, "ws_qd", 4, 16, 1);
  CheckContiguous(arg_ws_qd, "ws_qd");
  CheckCudaTensor(arg_ws_qd_tma, "ws_qd_tma");
  CheckDtype(arg_ws_qd_tma, "ws_qd_tma", 4, 16, 1);
  CheckContiguous(arg_ws_qd_tma, "ws_qd_tma");
  CheckCudaTensor(arg_ws_kd, "ws_kd");
  CheckDtype(arg_ws_kd, "ws_kd", 4, 16, 1);
  CheckContiguous(arg_ws_kd, "ws_kd");
  CheckCudaTensor(arg_ws_kd_tma, "ws_kd_tma");
  CheckDtype(arg_ws_kd_tma, "ws_kd_tma", 4, 16, 1);
  CheckContiguous(arg_ws_kd_tma, "ws_kd_tma");
  CheckCudaTensor(arg_ws_w, "ws_w");
  CheckDtype(arg_ws_w, "ws_w", 4, 16, 1);
  CheckContiguous(arg_ws_w, "ws_w");
  CheckCudaTensor(arg_ws_w_tma, "ws_w_tma");
  CheckDtype(arg_ws_w_tma, "ws_w_tma", 4, 16, 1);
  CheckContiguous(arg_ws_w_tma, "ws_w_tma");
  CheckCudaTensor(arg_ws_qk, "ws_qk");
  CheckDtype(arg_ws_qk, "ws_qk", 4, 16, 1);
  CheckContiguous(arg_ws_qk, "ws_qk");
  CheckCudaTensor(arg_ws_qk_tma, "ws_qk_tma");
  CheckDtype(arg_ws_qk_tma, "ws_qk_tma", 4, 16, 1);
  CheckContiguous(arg_ws_qk_tma, "ws_qk_tma");
  CheckCudaTensor(arg_ws_diag, "ws_diag");
  CheckDtype(arg_ws_diag, "ws_diag", 2, 32, 1);
  CheckContiguous(arg_ws_diag, "ws_diag");
  CheckCudaTensor(arg_ws_diag_tma, "ws_diag_tma");
  CheckDtype(arg_ws_diag_tma, "ws_diag_tma", 2, 32, 1);
  CheckContiguous(arg_ws_diag_tma, "ws_diag_tma");
  CheckCudaTensor(arg_v, "v");
  CheckDtype(arg_v, "v", 4, 16, 1);
  CheckContiguous(arg_v, "v");
  CheckCudaTensor(arg_v_tma, "v_tma");
  CheckDtype(arg_v_tma, "v_tma", 4, 16, 1);
  CheckContiguous(arg_v_tma, "v_tma");
  CheckCudaTensor(arg_cu_seqlens, "cu_seqlens");
  CheckDtype(arg_cu_seqlens, "cu_seqlens", 0, 64, 1);
  CheckContiguous(arg_cu_seqlens, "cu_seqlens");
  CheckCudaTensor(arg_cu_chunks, "cu_chunks");
  CheckDtype(arg_cu_chunks, "cu_chunks", 0, 32, 1);
  CheckContiguous(arg_cu_chunks, "cu_chunks");
  CheckCudaTensor(arg_seq_order, "seq_order");
  CheckDtype(arg_seq_order, "seq_order", 0, 32, 1);
  CheckContiguous(arg_seq_order, "seq_order");
  CheckCudaTensor(arg_initial_state, "initial_state");
  CheckDtype(arg_initial_state, "initial_state", 4, 16, 1);
  CheckContiguous(arg_initial_state, "initial_state");
  CheckCudaTensor(arg_out, "out");
  CheckDtype(arg_out, "out", 4, 16, 1);
  CheckContiguous(arg_out, "out");
  CheckCudaTensor(arg_out_tma, "out_tma");
  CheckDtype(arg_out_tma, "out_tma", 4, 16, 1);
  CheckContiguous(arg_out_tma, "out_tma");
  CheckCudaTensor(arg_final_state, "final_state");
  CheckDtype(arg_final_state, "final_state", 4, 16, 1);
  CheckContiguous(arg_final_state, "final_state");
  TVM_FFI_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_use_initial_state >= -2147483648LL && arg_use_initial_state <= 2147483647LL, ValueError)
      << "scalar 'use_initial_state' value " << arg_use_initial_state
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_store_final_state >= -2147483648LL && arg_store_final_state <= 2147483647LL, ValueError)
      << "scalar 'store_final_state' value " << arg_store_final_state
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_state_indices_addr >= 0LL && arg_state_indices_addr <= 9223372036854775807LL, ValueError)
      << "scalar 'state_indices_addr' value " << arg_state_indices_addr
      << " is outside u64 range [0, 9223372036854775807]";
  TVM_FFI_CHECK(arg_use_state_indices >= -2147483648LL && arg_use_state_indices <= 2147483647LL, ValueError)
      << "scalar 'use_state_indices' value " << arg_use_state_indices
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckCudaTensor(arg_initial_state_f32, "initial_state_f32");
  CheckDtype(arg_initial_state_f32, "initial_state_f32", 2, 32, 1);
  CheckContiguous(arg_initial_state_f32, "initial_state_f32");
  CheckCudaTensor(arg_final_state_f32, "final_state_f32");
  CheckDtype(arg_final_state_f32, "final_state_f32", 2, 32, 1);
  CheckContiguous(arg_final_state_f32, "final_state_f32");
  CheckSameCudaDevice(arg_ws_qd_tma, arg_ws_qd, "ws_qd_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_kd, arg_ws_qd, "ws_kd", "ws_qd");
  CheckSameCudaDevice(arg_ws_kd_tma, arg_ws_qd, "ws_kd_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_w, arg_ws_qd, "ws_w", "ws_qd");
  CheckSameCudaDevice(arg_ws_w_tma, arg_ws_qd, "ws_w_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_qk, arg_ws_qd, "ws_qk", "ws_qd");
  CheckSameCudaDevice(arg_ws_qk_tma, arg_ws_qd, "ws_qk_tma", "ws_qd");
  CheckSameCudaDevice(arg_ws_diag, arg_ws_qd, "ws_diag", "ws_qd");
  CheckSameCudaDevice(arg_ws_diag_tma, arg_ws_qd, "ws_diag_tma", "ws_qd");
  CheckSameCudaDevice(arg_v, arg_ws_qd, "v", "ws_qd");
  CheckSameCudaDevice(arg_v_tma, arg_ws_qd, "v_tma", "ws_qd");
  CheckSameCudaDevice(arg_cu_seqlens, arg_ws_qd, "cu_seqlens", "ws_qd");
  CheckSameCudaDevice(arg_cu_chunks, arg_ws_qd, "cu_chunks", "ws_qd");
  CheckSameCudaDevice(arg_seq_order, arg_ws_qd, "seq_order", "ws_qd");
  CheckSameCudaDevice(arg_initial_state, arg_ws_qd, "initial_state", "ws_qd");
  CheckSameCudaDevice(arg_out, arg_ws_qd, "out", "ws_qd");
  CheckSameCudaDevice(arg_out_tma, arg_ws_qd, "out_tma", "ws_qd");
  CheckSameCudaDevice(arg_final_state, arg_ws_qd, "final_state", "ws_qd");
  CheckSameCudaDevice(arg_initial_state_f32, arg_ws_qd, "initial_state_f32", "ws_qd");
  CheckSameCudaDevice(arg_final_state_f32, arg_ws_qd, "final_state_f32", "ws_qd");
  CheckCurrentCudaDevice(arg_ws_qd, "ws_qd");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  DLDevice dev = arg_ws_qd.device();
  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  void* p_ws_qd = arg_ws_qd.data_ptr();
  CUtensorMap h_ws_qd_tma = EncodeTma_ws_qd_tma(arg_ws_qd_tma);
  void* p_ws_qd_tma = TmaDeviceSlot(h_ws_qd_tma, arg_ws_qd_tma.device().device_id, stream);
  void* p_ws_kd = arg_ws_kd.data_ptr();
  CUtensorMap h_ws_kd_tma = EncodeTma_ws_kd_tma(arg_ws_kd_tma);
  void* p_ws_kd_tma = TmaDeviceSlot(h_ws_kd_tma, arg_ws_kd_tma.device().device_id, stream);
  void* p_ws_w = arg_ws_w.data_ptr();
  CUtensorMap h_ws_w_tma = EncodeTma_ws_w_tma(arg_ws_w_tma);
  void* p_ws_w_tma = TmaDeviceSlot(h_ws_w_tma, arg_ws_w_tma.device().device_id, stream);
  void* p_ws_qk = arg_ws_qk.data_ptr();
  CUtensorMap h_ws_qk_tma = EncodeTma_ws_qk_tma(arg_ws_qk_tma);
  void* p_ws_qk_tma = TmaDeviceSlot(h_ws_qk_tma, arg_ws_qk_tma.device().device_id, stream);
  void* p_ws_diag = arg_ws_diag.data_ptr();
  CUtensorMap h_ws_diag_tma = EncodeTma_ws_diag_tma(arg_ws_diag_tma);
  void* p_ws_diag_tma = TmaDeviceSlot(h_ws_diag_tma, arg_ws_diag_tma.device().device_id, stream);
  void* p_v = arg_v.data_ptr();
  CUtensorMap h_v_tma = EncodeTma_v_tma(arg_v_tma);
  void* p_v_tma = TmaDeviceSlot(h_v_tma, arg_v_tma.device().device_id, stream);
  void* p_cu_seqlens = arg_cu_seqlens.data_ptr();
  void* p_cu_chunks = arg_cu_chunks.data_ptr();
  void* p_seq_order = arg_seq_order.data_ptr();
  void* p_initial_state = arg_initial_state.data_ptr();
  void* p_out = arg_out.data_ptr();
  CUtensorMap h_out_tma = EncodeTma_out_tma(arg_out_tma);
  void* p_out_tma = TmaDeviceSlot(h_out_tma, arg_out_tma.device().device_id, stream);
  void* p_final_state = arg_final_state.data_ptr();
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_use_initial_state = (int32_t)arg_use_initial_state;
  int32_t v_store_final_state = (int32_t)arg_store_final_state;
  float v_scale = (float)arg_scale;
  uint64_t v_state_indices_addr = (uint64_t)arg_state_indices_addr;
  int64_t v_state_slot_stride = (int64_t)arg_state_slot_stride;
  int32_t v_use_state_indices = (int32_t)arg_use_state_indices;
  void* p_initial_state_f32 = arg_initial_state_f32.data_ptr();
  void* p_final_state_f32 = arg_final_state_f32.data_ptr();
  void* kargs[] = {&p_ws_qd, &p_ws_qd_tma, &p_ws_kd, &p_ws_kd_tma, &p_ws_w, &p_ws_w_tma, &p_ws_qk, &p_ws_qk_tma, &p_ws_diag, &p_ws_diag_tma, &p_v, &p_v_tma, &p_cu_seqlens, &p_cu_chunks, &p_seq_order, &p_initial_state, &p_out, &p_out_tma, &p_final_state, &v_num_heads, &v_use_initial_state, &v_store_final_state, &v_scale, &v_state_indices_addr, &v_state_slot_stride, &v_use_state_indices, &p_initial_state_f32, &p_final_state_f32};

  static auto kernel = EmbedCubinModule_flashkda_bf16_bt16_chain_m64_d3d65ffa34::Global()->mod.GetKernel("kernel_flashkda_bf16_bt16_chain_m64");
  static signed char cuda_smem_mode_cache[64] = {0};
  const bool use_oversized_smem = CudaConfigureDynamicSmem(
      kernel, (int)arg_ws_qd.device().device_id, 138240,
      cuda_smem_mode_cache, 64);
  tvm::ffi::dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  tvm::ffi::dim3 block(512u, 1u, 1u);

  TVM_FFI_CHECK(!use_oversized_smem, RuntimeError)
      << "oversized dynamic shared memory requires the extended (cluster) launch path";
  TVM_FFI_CHECK_CUBIN_LAUNCHER_CUDA_ERROR(kernel.Launch(kargs, grid, block, stream, 138240u));
}

}  // namespace cuda_host_shim_3bead515fefbe0ea

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cuda_host_shim_3bead515fefbe0ea::Run);
