/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// tvm-ffi direct-source launcher for Cake kernel 'kernel_cake_lm_head_loss_eadb84f9fd90929a2ed2'.
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "tvm_ffi_utils.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_lm_head_loss_eadb84f9fd90929a2ed2(float* __restrict__ stats, __nv_bfloat16* __restrict__ z, long long* __restrict__ labels, float* __restrict__ infer_logp, float* __restrict__ loss_weights, float* __restrict__ d_in, float* __restrict__ lse, float* __restrict__ logp, float* __restrict__ d, float* __restrict__ term, int rows_c, int row0, int V, int num_tiles, int mode, float loss_div);


namespace cake_host_shim_9f7795315a148f5a {

using tvm::ffi::Optional;
using tvm::ffi::TensorView;

// Every entry of this translation unit does driver-API work on the calling
// thread -- tensor-map encoding, the descriptor-slot arena, the embedded
// cubin launch -- and the driver serves it from that thread's current
// context. The CUDA runtime binds a device's primary context lazily, on the
// first runtime call that performs work, so a thread that only received
// tensors and whose first CUDA work is this launch (PyTorch's autograd worker
// running a Function.backward under torch.autograd.grad: allocations come
// from the caching allocator and cudaGetDevice does not bind) reaches Run with
// cuCtxGetCurrent() == nullptr and the encoder fails with
// CUDA_ERROR_INVALID_CONTEXT. Bind the tensor device's primary context in
// that case: it is the context the runtime and PyTorch use, so allocation
// ownership is unchanged. The retained handle is cached per device for the
// process lifetime and never released (the runtime owns the primary
// context); the per-thread state is the driver's own current-context slot.
// A thread that already has a current context is left untouched.
inline void EnsureCurrentCudaContext(int device_id) {
  CUcontext current = nullptr;
  CUresult result = cuCtxGetCurrent(&current);
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuCtxGetCurrent failed before host-shim launch for cuda:" << device_id
      << ": CUresult=" << static_cast<int>(result);
  if (current != nullptr) return;
  constexpr int kMaxCachedCudaDevices = 64;
  TVM_FFI_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "primary-context cache does not cover cuda:" << device_id;
  static std::mutex mu;
  static CUcontext primary_by_device[kMaxCachedCudaDevices] = {};
  CUcontext primary = nullptr;
  {
    std::lock_guard<std::mutex> lock(mu);
    primary = primary_by_device[device_id];
    if (primary == nullptr) {
      result = cuInit(0);
      TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
          << "cuInit failed while binding the CUDA context for cuda:" << device_id
          << ": CUresult=" << static_cast<int>(result);
      CUdevice device = -1;
      result = cuDeviceGet(&device, device_id);
      TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
          << "cuDeviceGet failed while binding the CUDA context for cuda:" << device_id
          << ": CUresult=" << static_cast<int>(result);
      result = cuDevicePrimaryCtxRetain(&primary, device);
      TVM_FFI_CHECK(result == CUDA_SUCCESS && primary != nullptr, RuntimeError)
          << "cuDevicePrimaryCtxRetain failed while binding the CUDA context for cuda:"
          << device_id << ": CUresult=" << static_cast<int>(result);
      primary_by_device[device_id] = primary;
    }
  }
  result = cuCtxSetCurrent(primary);
  TVM_FFI_CHECK(result == CUDA_SUCCESS, RuntimeError)
      << "cuCtxSetCurrent failed while binding the primary context of cuda:" << device_id
      << ": CUresult=" << static_cast<int>(result);
}

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
    // The device is selected; make sure this thread also has a driver context
    // before the encoders, slot arena and launch below run on it.
    EnsureCurrentCudaContext(device_id);
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  TVM_FFI_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  TVM_FFI_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  TVM_FFI_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  TVM_FFI_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  TVM_FFI_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  TVM_FFI_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  TVM_FFI_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

void Run(TensorView arg_stats, TensorView arg_z, TensorView arg_labels, TensorView arg_infer_logp, TensorView arg_loss_weights, TensorView arg_d_in, TensorView arg_lse, TensorView arg_logp, TensorView arg_d, TensorView arg_term, int64_t arg_rows_c, int64_t arg_row0, int64_t arg_V, int64_t arg_num_tiles, int64_t arg_mode, double arg_loss_div, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_stats.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_stats, "stats");
  CheckDtype(arg_stats, "stats", 2, 32, 1);
  CheckContiguous(arg_stats, "stats");
  CheckCudaTensor(arg_z, "z");
  CheckDtype(arg_z, "z", 4, 16, 1);
  CheckContiguous(arg_z, "z");
  CheckCudaTensor(arg_labels, "labels");
  CheckDtype(arg_labels, "labels", 0, 64, 1);
  CheckContiguous(arg_labels, "labels");
  CheckCudaTensor(arg_infer_logp, "infer_logp");
  CheckDtype(arg_infer_logp, "infer_logp", 2, 32, 1);
  CheckContiguous(arg_infer_logp, "infer_logp");
  CheckCudaTensor(arg_loss_weights, "loss_weights");
  CheckDtype(arg_loss_weights, "loss_weights", 2, 32, 1);
  CheckContiguous(arg_loss_weights, "loss_weights");
  CheckCudaTensor(arg_d_in, "d_in");
  CheckDtype(arg_d_in, "d_in", 2, 32, 1);
  CheckContiguous(arg_d_in, "d_in");
  CheckCudaTensor(arg_lse, "lse");
  CheckDtype(arg_lse, "lse", 2, 32, 1);
  CheckContiguous(arg_lse, "lse");
  CheckCudaTensor(arg_logp, "logp");
  CheckDtype(arg_logp, "logp", 2, 32, 1);
  CheckContiguous(arg_logp, "logp");
  CheckCudaTensor(arg_d, "d");
  CheckDtype(arg_d, "d", 2, 32, 1);
  CheckContiguous(arg_d, "d");
  CheckCudaTensor(arg_term, "term");
  CheckDtype(arg_term, "term", 2, 32, 1);
  CheckContiguous(arg_term, "term");
  TVM_FFI_CHECK(arg_rows_c >= -2147483648LL && arg_rows_c <= 2147483647LL, ValueError)
      << "scalar 'rows_c' value " << arg_rows_c
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_row0 >= -2147483648LL && arg_row0 <= 2147483647LL, ValueError)
      << "scalar 'row0' value " << arg_row0
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_V >= -2147483648LL && arg_V <= 2147483647LL, ValueError)
      << "scalar 'V' value " << arg_V
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_num_tiles >= -2147483648LL && arg_num_tiles <= 2147483647LL, ValueError)
      << "scalar 'num_tiles' value " << arg_num_tiles
      << " is outside i32 range [-2147483648, 2147483647]";
  TVM_FFI_CHECK(arg_mode >= -2147483648LL && arg_mode <= 2147483647LL, ValueError)
      << "scalar 'mode' value " << arg_mode
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_z, arg_stats, "z", "stats");
  CheckSameCudaDevice(arg_labels, arg_stats, "labels", "stats");
  CheckSameCudaDevice(arg_infer_logp, arg_stats, "infer_logp", "stats");
  CheckSameCudaDevice(arg_loss_weights, arg_stats, "loss_weights", "stats");
  CheckSameCudaDevice(arg_d_in, arg_stats, "d_in", "stats");
  CheckSameCudaDevice(arg_lse, arg_stats, "lse", "stats");
  CheckSameCudaDevice(arg_logp, arg_stats, "logp", "stats");
  CheckSameCudaDevice(arg_d, arg_stats, "d", "stats");
  CheckSameCudaDevice(arg_term, arg_stats, "term", "stats");
  TVM_FFI_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)TVMFFIEnvGetStream(dev.device_type, dev.device_id);
  float* p_stats = static_cast<float*>(arg_stats.data_ptr());
  __nv_bfloat16* p_z = static_cast<__nv_bfloat16*>(arg_z.data_ptr());
  long long* p_labels = static_cast<long long*>(arg_labels.data_ptr());
  float* p_infer_logp = static_cast<float*>(arg_infer_logp.data_ptr());
  float* p_loss_weights = static_cast<float*>(arg_loss_weights.data_ptr());
  float* p_d_in = static_cast<float*>(arg_d_in.data_ptr());
  float* p_lse = static_cast<float*>(arg_lse.data_ptr());
  float* p_logp = static_cast<float*>(arg_logp.data_ptr());
  float* p_d = static_cast<float*>(arg_d.data_ptr());
  float* p_term = static_cast<float*>(arg_term.data_ptr());
  int32_t v_rows_c = (int32_t)arg_rows_c;
  int32_t v_row0 = (int32_t)arg_row0;
  int32_t v_V = (int32_t)arg_V;
  int32_t v_num_tiles = (int32_t)arg_num_tiles;
  int32_t v_mode = (int32_t)arg_mode;
  float v_loss_div = (float)arg_loss_div;
  void* kargs[] = {&p_stats, &p_z, &p_labels, &p_infer_logp, &p_loss_weights, &p_d_in, &p_lse, &p_logp, &p_d, &p_term, &v_rows_c, &v_row0, &v_V, &v_num_tiles, &v_mode, &v_loss_div};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaError_t launch_status = cudaLaunchKernel(
      reinterpret_cast<const void*>(kernel_cake_lm_head_loss_eadb84f9fd90929a2ed2), grid, block, kargs, 0u, stream);
  TVM_FFI_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernel for kernel_cake_lm_head_loss_eadb84f9fd90929a2ed2 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_9f7795315a148f5a

TVM_FFI_DLL_EXPORT_TYPED_FUNC(run, cake_host_shim_9f7795315a148f5a::Run);
