name: Publish sdist to PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (e.g., v1.2.3) to build and publish'
        required: true
        type: string

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build & upload tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*.tar.gz
