/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by tools/export-generated-programs (device kernel), laid out as a
// single translation unit following the csrc/tinygemm2_sm100.cu convention
// (one TU = generated kernel + TVM-FFI binding).
//
// Provenance: generated Loom schedule 'alpha_moe_w8a8_up_down' — SM100/SM103
// fused W8A8 block-scale MoE megakernel: routed gate/up projection, SwiGLU +
// per-token FP8 requant, down projection, and asynchronous BF16 reduce-add
// into a caller-owned output accumulator.
//
// The generated TU is embedded by a mechanical transform that does not touch
// kernel code:
//   1. the fixed-width typedefs and the opaque CUtensorMap typedef of the
//      generated prelude are dropped (the host headers below supply them);
//   2. the generated #define block is kept verbatim; SMEM_TOTAL/THREADS are
//      captured into constexprs for the launcher, then every generated macro
//      is #undef'd after the kernel.
// The kernel body is byte-identical to the generated output.

#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_runtime.h>
#include <math_constants.h>

#include <cstdint>
#include <cstring>
#include <limits>

#include "tvm_ffi_utils.h"

// clang-format off

struct __align__(128) LoomTensorMap { uint64_t opaque[16]; };



#define LOOM_INF CUDART_INF_F
#define TMEM_NCOLS 72
#define TMEM_UP_ACC_OFFSET 0
#define TMEM_DOWN_ACC_OFFSET 48
#define NUM_UP_PIPE_STAGES 3
#define NUM_DOWN_PIPE_STAGES 3
#define SMEM_SMEM_W1_OFF 1024
#define SMEM_SMEM_W1_STAGE_BYTES 32768
#define SMEM_SMEM_W1_STRIDE 33792
#define SMEM_SMEM_X_OFF 33792
#define SMEM_SMEM_X_STAGE_BYTES 1024
#define SMEM_SMEM_X_STRIDE 33792
#define SMEM_SMEM_W2_OFF 102400
#define SMEM_SMEM_W2_STAGE_BYTES 16384
#define SMEM_SMEM_W2_STRIDE 16384
#define SMEM_SMEM_ACT_OFF 151552
#define SMEM_SMEM_ACT_STAGE_BYTES 1024
#define SMEM_SMEM_ACT_STRIDE 1024
#define SMEM_SMEM_AMAX_OFF 152576
#define SMEM_SMEM_AMAX_STAGE_BYTES 32
#define SMEM_SMEM_AMAX_STRIDE 32
#define SMEM_SMEM_ACT_SCALE_OFF 152608
#define SMEM_SMEM_ACT_SCALE_STAGE_BYTES 32
#define SMEM_SMEM_ACT_SCALE_STRIDE 32
#define SMEM_SMEM_OUT_OFF 152640
#define SMEM_SMEM_OUT_STAGE_BYTES 2048
#define SMEM_SMEM_OUT_STRIDE 2048
#define SMEM_TOTAL 154752
#define THREADS 192


__device__ __forceinline__ uint32_t elect_sync() {
    uint32_t pred = 0;
    asm volatile(
        "{\n\t"
        ".reg .pred %%px;\n\t"
        "elect.sync _|%%px, %1;\n\t"
        "@%%px mov.s32 %0, 1;\n\t"
        "}\n"
        : "+r"(pred)
        : "r"(0xFFFFFFFF));
    return pred;
}


__device__ __forceinline__ void mbarrier_init(int mbar_addr, int count) {
    asm volatile("mbarrier.init.shared::cta.b64 [%0], %1;"
        :: "r"(mbar_addr), "r"(count));
}


__device__ __forceinline__ uint32_t mbarrier_try_wait(int mbar_addr, int phase) {
    uint32_t token;
    asm volatile(
        "{\n\t"
        ".reg .pred P1;\n\t"
        "mbarrier.try_wait.parity.acquire.cta.shared::cta.b64"
        " P1, [%1], %2;\n\t"
        "selp.u32 %0, 1, 0, P1;\n\t"
        "}\n"
        : "=r"(token)
        : "r"(mbar_addr), "r"(phase) : "memory");
    return token;
}

__device__ __forceinline__ uint32_t mbarrier_try_wait_cluster(int mbar_addr, int phase) {
    uint32_t token;
    asm volatile(
        "{\n\t"
        ".reg .pred P1;\n\t"
        "mbarrier.try_wait.parity.acquire.cluster.shared::cta.b64"
        " P1, [%1], %2;\n\t"
        "selp.u32 %0, 1, 0, P1;\n\t"
        "}\n"
        : "=r"(token)
        : "r"(mbar_addr), "r"(phase) : "memory");
    return token;
}

__device__ __forceinline__ void mbarrier_wait(int mbar_addr, int phase) {
    uint32_t ticks = 0x989680;
    asm volatile(
        "{\n\t"
        ".reg .pred P1;\n\t"
        "LAB_WAIT:\n\t"
        "mbarrier.try_wait.parity.acquire.cta.shared::cta.b64"
        " P1, [%0], %1, %2;\n\t"
        "@P1 bra.uni DONE;\n\t"
        "bra.uni LAB_WAIT;\n\t"
        "DONE:\n\t"
        "}\n"
        :: "r"(mbar_addr), "r"(phase), "r"(ticks) : "memory");
}

__device__ __forceinline__ void mbarrier_wait_cluster(int mbar_addr, int phase) {
    uint32_t ticks = 0x989680;
    asm volatile(
        "{\n\t"
        ".reg .pred P1;\n\t"
        "LAB_WAIT_CLUSTER:\n\t"
        "mbarrier.try_wait.parity.acquire.cluster.shared::cta.b64"
        " P1, [%0], %1, %2;\n\t"
        "@P1 bra.uni DONE_CLUSTER;\n\t"
        "bra.uni LAB_WAIT_CLUSTER;\n\t"
        "DONE_CLUSTER:\n\t"
        "}\n"
        :: "r"(mbar_addr), "r"(phase), "r"(ticks) : "memory");
}

__device__ __forceinline__ void mbarrier_wait_token(int mbar_addr, int phase, uint32_t token) {
    if (token == 0) {
        mbarrier_wait(mbar_addr, phase);
    }
}

__device__ __forceinline__ void mbarrier_wait_token_cluster(int mbar_addr, int phase, uint32_t token) {
    if (token == 0) {
        mbarrier_wait_cluster(mbar_addr, phase);
    }
}


__device__ __forceinline__ void tcgen05_mma_f8f6f4(
    int taddr, uint64_t a_desc, uint64_t b_desc,
    uint32_t i_desc, int enable_input_d) {
    asm volatile(
        "{\n\t"
        ".reg .pred p;\n\t"
        "setp.ne.b32 p, %4, 0;\n\t"
        "tcgen05.mma.cta_group::1.kind::f8f6f4 [%0], %1, %2, %3, p;\n\t"
        "}\n"
        :: "r"(taddr), "l"(a_desc), "l"(b_desc),
           "r"(i_desc), "r"(enable_input_d));
}


__device__ __forceinline__ uint64_t desc_encode(uint64_t x) {
    return (x & 0x3FFFFULL) >> 4ULL;
}


__device__ __forceinline__ void mma_ss_step(
    int a_lo, int b_lo, int taddr, uint32_t i_desc, int enable_d,
    uint32_t a_dhi, uint32_t b_dhi) {
    asm volatile(
        "{\n\t"
        ".reg .pred leader, p;\n\t"
        ".reg .b32 adhi, bdhi;\n\t"
        ".reg .b64 da, db;\n\t"
        "elect.sync _|leader, 0xFFFFFFFF;\n\t"
        "setp.ne.b32 p, %4, 0;\n\t"
        "mov.b32 adhi, %5;\n\t"
        "mov.b32 bdhi, %6;\n\t"
        "mov.b64 da, {%0, adhi};\n\t"
        "mov.b64 db, {%1, bdhi};\n\t"
        "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, %3, p;\n\t"
        "}\n"
        :: "r"(a_lo), "r"(b_lo), "r"(taddr), "r"(i_desc), "r"(enable_d), "r"(a_dhi), "r"(b_dhi));
}


__device__ __forceinline__ void elect_commit(int mbar_addr) {
    asm volatile(
        "{\n\t"
        ".reg .pred leader;\n\t"
        "elect.sync _|leader, 0xFFFFFFFF;\n\t"
        "@leader tcgen05.commit.cta_group::1.mbarrier::arrive::one"
        ".shared::cluster.b64 [%0];\n\t"
        "}\n"
        :: "r"(mbar_addr));
}


__device__ __forceinline__ void mbarrier_arrive(int mbar_addr) {
    asm volatile(
        "mbarrier.arrive.release.cta.shared::cta.b64 _, [%0];"
        :: "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void mbarrier_arrive_expect_tx(int mbar_addr, uint32_t bytes) {
    asm volatile(
        "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 _, [%0], %1;"
        :: "r"(mbar_addr), "r"(bytes) : "memory");
}


__device__ __forceinline__ void mbarrier_init_pred(int mbar_addr, uint32_t count, uint32_t pred) {
    asm volatile(
        "{\n\t"
        ".reg .pred p;\n\t"
        "setp.ne.b32 p, %2, 0;\n\t"
        "@p mbarrier.init.shared::cta.b64 [%0], %1;\n\t"
        "}\n" :: "r"(mbar_addr), "r"(count), "r"(pred));
}


__device__ __forceinline__ float max_noftz(float a, float b) {
    float c;
    asm("max.f32 %0, %1, %2;" : "=f"(c) : "f"(a), "f"(b));
    return c;
}


__device__ __forceinline__ void fence_async_shared() {
    asm volatile("fence.proxy.async.shared::cta;" ::: "memory");
}


__device__ __forceinline__ uint64_t make_smem_desc(int addr) {
    const int SBO = 1024;
    return desc_encode(addr)
         | (desc_encode(SBO) << 32ULL)
         | (1ULL << 46ULL)
         | (2ULL << 61ULL);
}


__device__ __forceinline__ void tma_3d_gmem2smem(
    int dst, const void *tmap_ptr, int x, int y, int z, int mbar_addr) {
    asm volatile(
        "cp.async.bulk.tensor.3d.shared::cta.global"
        ".mbarrier::complete_tx::bytes"
        " [%0], [%1, {%2, %3, %4}], [%5];"
        :: "r"(dst), "l"(tmap_ptr), "r"(x), "r"(y), "r"(z),
           "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void tma_2d_gmem2smem(
    int dst, const void *tmap_ptr, int x, int y, int mbar_addr) {
    asm volatile(
        "cp.async.bulk.tensor.2d.shared::cta.global"
        ".mbarrier::complete_tx::bytes"
        " [%0], [%1, {%2, %3}], [%4];"
        :: "r"(dst), "l"(tmap_ptr), "r"(x), "r"(y),
           "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void tma_4d_gmem2smem(
    int dst, const void *tmap_ptr, int x, int y, int z, int w, int mbar_addr) {
    asm volatile(
        "cp.async.bulk.tensor.4d.shared::cta.global"
        ".mbarrier::complete_tx::bytes"
        " [%0], [%1, {%2, %3, %4, %5}], [%6];"
        :: "r"(dst), "l"(tmap_ptr), "r"(x), "r"(y), "r"(z), "r"(w),
           "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void tma_gather4_gmem2smem(
    int dst, const void *tmap_ptr,
    int col_idx, int row0, int row1, int row2, int row3,
    int mbar_addr) {
    // Canonical .shared::cta form for non-multicast gather4, matching
    // trtllm-gen / cuda_ptx and the PTX ISA qualifier order
    // (dim.dst.src.load_mode.completion_mechanism). Per the PTX grammar,
    // .shared::cluster is reserved for the multicast variant (ctaMask).
    asm volatile(
        "cp.async.bulk.tensor.2d.shared::cta.global.tile::gather4"
        ".mbarrier::complete_tx::bytes"
        " [%0], [%1, {%2, %3, %4, %5, %6}], [%7];"
        :: "r"(dst), "l"(tmap_ptr), "r"(col_idx),
           "r"(row0), "r"(row1), "r"(row2), "r"(row3),
           "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void tcgen05_commit(int mbar_addr) {
    asm volatile(
        "tcgen05.commit.cta_group::1.mbarrier::arrive::one"
        ".shared::cluster.b64 [%0];"
        :: "r"(mbar_addr) : "memory");
}


__device__ __forceinline__ void tmem_ld_x8(float* dst, int tmem_addr) {
    asm volatile(
        "tcgen05.ld.sync.aligned.32x32b.x8.b32"
        " {%0, %1, %2, %3, %4, %5, %6, %7}, [%8];"
        : "=f"(dst[0]), "=f"(dst[1]), "=f"(dst[2]), "=f"(dst[3]),
          "=f"(dst[4]), "=f"(dst[5]), "=f"(dst[6]), "=f"(dst[7])
        : "r"(tmem_addr));
}


__device__ __forceinline__ void tmem_ld_x8_wait(float* dst, int addr) {
    tmem_ld_x8(dst, addr);
    asm volatile("tcgen05.wait::ld.sync.aligned;");
}


__device__ __forceinline__ uint32_t make_warp_uniform(uint32_t val) {
    uint32_t result;
    asm volatile("shfl.sync.idx.b32 %0, %1, 0, 0x1f, 0xffffffff;"
        : "=r"(result) : "r"(val));
    return result;
}

extern "C" {

__global__ __launch_bounds__(192, 1) void
kernel_alpha_moe_w8a8_up_down(__grid_constant__ LoomTensorMap const x, __grid_constant__ LoomTensorMap const W1, float* __restrict__ x_scale, float* __restrict__ w1_scale, __grid_constant__ LoomTensorMap const W2, float* __restrict__ w2_scale, int* __restrict__ sorted_token_ids, int* __restrict__ expert_ids, int* __restrict__ num_tokens_post_padded, float* __restrict__ topk_weights, __nv_bfloat16* __restrict__ out, int M, int K, int top_k, int route_block_m, float scaling_factor)
{
    const int tid = threadIdx.x;
    const int warp = make_warp_uniform(tid / 32);
    const int lane = tid % 32;

    extern __shared__ __align__(1024) char smem_raw[];
    int smem;
    smem = (int)(unsigned long long)__cvta_generic_to_shared(smem_raw);

    const int bid = blockIdx.x;
    const int num_bids = gridDim.x;

    // Kernel setup ops
    uint8_t* smem_w1 = reinterpret_cast<uint8_t*>(smem_raw + 1024);
    const int smem_w1_addr = smem + 1024;
    uint8_t* smem_x = reinterpret_cast<uint8_t*>(smem_raw + 33792);
    const int smem_x_addr = smem + 33792;
    uint8_t* smem_w2 = reinterpret_cast<uint8_t*>(smem_raw + 102400);
    const int smem_w2_addr = smem + 102400;
    uint8_t* smem_act = reinterpret_cast<uint8_t*>(smem_raw + 151552);
    const int smem_act_addr = smem + 151552;
    unsigned int* smem_amax = reinterpret_cast<unsigned int*>(smem_raw + 152576);
    const int smem_amax_addr = smem + 152576;
    float* smem_act_scale = reinterpret_cast<float*>(smem_raw + 152608);
    const int smem_act_scale_addr = smem + 152608;
    __nv_bfloat16* smem_out = reinterpret_cast<__nv_bfloat16*>(smem_raw + 152640);
    const int smem_out_addr = smem + 152640;

    // Mbarrier init (6 groups, 18 barriers)
    // Mbarriers at smem_raw[0..144)

    if (warp == 0) {
        uint32_t leader = elect_sync();
        // --- pipeline 'up_pipe' ---
        // up_full: 3 barriers, init_count=1
        mbarrier_init_pred(smem + 0, 1, leader);
        mbarrier_init_pred(smem + 8, 1, leader);
        mbarrier_init_pred(smem + 16, 1, leader);
        // up_ready: 3 barriers, init_count=1
        mbarrier_init_pred(smem + 24, 1, leader);
        mbarrier_init_pred(smem + 32, 1, leader);
        mbarrier_init_pred(smem + 40, 1, leader);
        // up_free: 3 barriers, init_count=4
        mbarrier_init_pred(smem + 48, 4, leader);
        mbarrier_init_pred(smem + 56, 4, leader);
        mbarrier_init_pred(smem + 64, 4, leader);
        // --- pipeline 'down_pipe' ---
        // down_full: 3 barriers, init_count=1
        mbarrier_init_pred(smem + 72, 1, leader);
        mbarrier_init_pred(smem + 80, 1, leader);
        mbarrier_init_pred(smem + 88, 1, leader);
        // down_ready: 3 barriers, init_count=1
        mbarrier_init_pred(smem + 96, 1, leader);
        mbarrier_init_pred(smem + 104, 1, leader);
        mbarrier_init_pred(smem + 112, 1, leader);
        // down_free: 3 barriers, init_count=4
        mbarrier_init_pred(smem + 120, 4, leader);
        mbarrier_init_pred(smem + 128, 4, leader);
        mbarrier_init_pred(smem + 136, 4, leader);
        asm volatile("fence.mbarrier_init.release.cluster;");
    }

    __syncthreads();

    // TMEM alloc (128 columns, 72 used)
    volatile int* tmem_addr_storage = (volatile int*)(smem_raw + 144);
    if (warp == 0) {
        int _tmem_hold = smem + 144;
        asm volatile("tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;" :: "r"(_tmem_hold), "r"(128) : "memory");
    }

    __syncthreads();
    asm volatile("tcgen05.fence::after_thread_sync;");

    const int mbar_base = smem;
    #define up_full_addr (mbar_base + 0)
    #define up_ready_addr (mbar_base + 24)
    #define up_free_addr (mbar_base + 48)
    #define down_full_addr (mbar_base + 72)
    #define down_ready_addr (mbar_base + 96)
    #define down_free_addr (mbar_base + 120)
    const int taddr = tmem_addr_storage[0];

    // Kernel post-init ops
    const int tmem_up_acc = taddr;
    const int tmem_down_acc = taddr + 48;

    // ---- Role: load ----
    if (warp == 0) {
        { // load_main
            int plan_extent_l = num_tokens_post_padded[0];
            unsigned int _phase_up_free = 1;
            unsigned int _phase_down_free = 1;
            if (plan_extent_l > blockIdx.x * 8) {
                int route_work = blockIdx.x;
                int intermediate_block = blockIdx.y;
                int subtiles_per_route_block = route_block_m / 8;
                int route_block = route_work / subtiles_per_route_block;
                int route_subtile = route_work % subtiles_per_route_block;
                int route_base = route_block * route_block_m + route_subtile * 8;
                int expert = expert_ids[route_block];
                int k_blocks = K / 128;
                unsigned int stage = 0;
                #pragma unroll 1
                for (int kb = 0; kb < k_blocks; kb++) {
                    mbarrier_wait(up_free_addr + (stage) * 8, _phase_up_free);
                    if (elect_sync()) {
                        int pair0 = sorted_token_ids[route_base];
                        int pair1 = sorted_token_ids[route_base + 1];
                        int pair2 = sorted_token_ids[route_base + 2];
                        int pair3 = sorted_token_ids[route_base + 3];
                        int pair4 = sorted_token_ids[route_base + 4];
                        int pair5 = sorted_token_ids[route_base + 5];
                        int pair6 = sorted_token_ids[route_base + 6];
                        int pair7 = sorted_token_ids[route_base + 7];
                        int _min_0 = ((pair0 / top_k) < (M - 1) ? (pair0 / top_k) : (M - 1));
                        int row0 = _min_0;
                        int _min_1 = ((pair1 / top_k) < (M - 1) ? (pair1 / top_k) : (M - 1));
                        int row1 = _min_1;
                        int _min_2 = ((pair2 / top_k) < (M - 1) ? (pair2 / top_k) : (M - 1));
                        int row2 = _min_2;
                        int _min_3 = ((pair3 / top_k) < (M - 1) ? (pair3 / top_k) : (M - 1));
                        int row3 = _min_3;
                        int _min_4 = ((pair4 / top_k) < (M - 1) ? (pair4 / top_k) : (M - 1));
                        int row4 = _min_4;
                        int _min_5 = ((pair5 / top_k) < (M - 1) ? (pair5 / top_k) : (M - 1));
                        int row5 = _min_5;
                        int _min_6 = ((pair6 / top_k) < (M - 1) ? (pair6 / top_k) : (M - 1));
                        int row6 = _min_6;
                        int _min_7 = ((pair7 / top_k) < (M - 1) ? (pair7 / top_k) : (M - 1));
                        int row7 = _min_7;
                        mbarrier_arrive_expect_tx(up_full_addr + (stage) * 8, 33792);
                        tma_gather4_gmem2smem(smem_x_addr + stage * 33792, (&x), kb * 128, row0, row1, row2, row3, up_full_addr + (stage) * 8);
                        tma_gather4_gmem2smem(smem_x_addr + stage * 33792 + 512, (&x), kb * 128, row4, row5, row6, row7, up_full_addr + (stage) * 8);
                        tma_4d_gmem2smem(smem_w1_addr + stage * 33792, (&W1), 0, intermediate_block * 256, kb, expert, up_full_addr + (stage) * 8);
                        tma_4d_gmem2smem(smem_w1_addr + stage * 33792 + 16384, (&W1), 0, intermediate_block * 256 + 128, kb, expert, up_full_addr + (stage) * 8);
                    }
                    stage += 1;
                    if (stage == 3) { stage = 0; _phase_up_free ^= 1; }
                }
                asm volatile("barrier.sync 14, %0;" :: "r"(192));
                stage = 0;
                int out_blocks = K / 128;
                if (elect_sync()) {
                    #pragma unroll 1
                    for (int ob = 0; ob < out_blocks; ob++) {
                        mbarrier_wait(down_free_addr + (stage) * 8, _phase_down_free);
                        mbarrier_arrive_expect_tx(down_full_addr + (stage) * 8, 16384);
                        tma_3d_gmem2smem(smem_w2_addr + stage * 16384, (&W2), intermediate_block * 128, ob * 128, expert, down_full_addr + (stage) * 8);
                        stage += 1;
                        if (stage == 3) { stage = 0; _phase_down_free ^= 1; }
                    }
                }
            }
        }
    // ---- Role: mma ----
    } else if (warp == 1) {
        { // mma_main
            int plan_extent_m = num_tokens_post_padded[0];
            unsigned int _phase_up_free_1 = 1;
            unsigned int _phase_up_full = 0;
            unsigned int _phase_down_free_1 = 1;
            unsigned int _phase_down_full = 0;
            if (plan_extent_m > blockIdx.x * 8) {
                int k_blocks_mma = K / 128;
                unsigned int up_stage = 0;
                #pragma unroll 1
                for (int kb_mma = 0; kb_mma < k_blocks_mma; kb_mma++) {
                    mbarrier_wait(up_free_addr + (up_stage) * 8, _phase_up_free_1);
                    mbarrier_wait(up_full_addr + (up_stage) * 8, _phase_up_full);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    int _mma_a_lo_0 = make_warp_uniform((((smem_w1_addr) >> 4) & 0x3FFF) + (up_stage) * 2112);
                    int _mma_b_lo_0 = make_warp_uniform((((smem_x_addr) >> 4) & 0x3FFF) + (up_stage) * 2112);
                    asm volatile(
                    "{\n\t"
                    ".reg .pred leader, p0, p1;\n\t"
                    ".reg .b32 adhi, bdhi, alo, blo, id;\n\t"
                    ".reg .b64 da, db;\n\t"
                    "elect.sync _|leader, 0xFFFFFFFF;\n\t"
                    "setp.ne.b32 p0, %3, 0;\n\t"
                    "setp.ne.b32 p1, 1, 0;\n\t"
                    ""
                    "mov.b32 adhi, 0x40004040;\n\t"
                    "mov.b32 bdhi, 0x40004040;\n\t"
                    "mov.b32 id, 134348816;\n\t"
                    "mov.b32 alo, %0;\n\t"
                    "mov.b32 blo, %1;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p0;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "}\n"
                    :: "r"(_mma_a_lo_0), "r"(_mma_b_lo_0), "r"((tmem_up_acc + (up_stage * 16))), "r"(0));
                    int _mma_a_lo_1 = make_warp_uniform((((smem_w1_addr + 16384) >> 4) & 0x3FFF) + (up_stage) * 2112);
                    int _mma_b_lo_1 = make_warp_uniform((((smem_x_addr) >> 4) & 0x3FFF) + (up_stage) * 2112);
                    asm volatile(
                    "{\n\t"
                    ".reg .pred leader, p0, p1;\n\t"
                    ".reg .b32 adhi, bdhi, alo, blo, id;\n\t"
                    ".reg .b64 da, db;\n\t"
                    "elect.sync _|leader, 0xFFFFFFFF;\n\t"
                    "setp.ne.b32 p0, %3, 0;\n\t"
                    "setp.ne.b32 p1, 1, 0;\n\t"
                    ""
                    "mov.b32 adhi, 0x40004040;\n\t"
                    "mov.b32 bdhi, 0x40004040;\n\t"
                    "mov.b32 id, 134348816;\n\t"
                    "mov.b32 alo, %0;\n\t"
                    "mov.b32 blo, %1;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p0;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "}\n"
                    :: "r"(_mma_a_lo_1), "r"(_mma_b_lo_1), "r"((tmem_up_acc + (up_stage * 16 + 8))), "r"(0));
                    elect_commit(up_ready_addr + (up_stage) * 8);
                    up_stage += 1;
                    if (up_stage == 3) { up_stage = 0; _phase_up_free_1 ^= 1; _phase_up_full ^= 1; }
                }
                asm volatile("barrier.sync 14, %0;" :: "r"(192));
                int out_blocks_mma = K / 128;
                unsigned int down_stage = 0;
                #pragma unroll 1
                for (int ob_mma = 0; ob_mma < out_blocks_mma; ob_mma++) {
                    mbarrier_wait(down_free_addr + (down_stage) * 8, _phase_down_free_1);
                    mbarrier_wait(down_full_addr + (down_stage) * 8, _phase_down_full);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    int _mma_a_lo_2 = make_warp_uniform((((smem_w2_addr) >> 4) & 0x3FFF) + (down_stage) * 1024);
                    int _mma_b_lo_2 = make_warp_uniform(((smem_act_addr) >> 4) & 0x3FFF);
                    asm volatile(
                    "{\n\t"
                    ".reg .pred leader, p0, p1;\n\t"
                    ".reg .b32 adhi, bdhi, alo, blo, id;\n\t"
                    ".reg .b64 da, db;\n\t"
                    "elect.sync _|leader, 0xFFFFFFFF;\n\t"
                    "setp.ne.b32 p0, %3, 0;\n\t"
                    "setp.ne.b32 p1, 1, 0;\n\t"
                    ""
                    "mov.b32 adhi, 0x40004040;\n\t"
                    "mov.b32 bdhi, 0x40004040;\n\t"
                    "mov.b32 id, 134348816;\n\t"
                    "mov.b32 alo, %0;\n\t"
                    "mov.b32 blo, %1;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p0;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "add.u32 alo, alo, 2;\n\t"
                    "add.u32 blo, blo, 2;\n\t"
                    "mov.b64 da, {alo, adhi};\n\t"
                    "mov.b64 db, {blo, bdhi};\n\t"
                    "@leader tcgen05.mma.cta_group::1.kind::f8f6f4 [%2], da, db, id, p1;\n\t"
                    "}\n"
                    :: "r"(_mma_a_lo_2), "r"(_mma_b_lo_2), "r"((tmem_down_acc + (down_stage * 8))), "r"(0));
                    elect_commit(down_ready_addr + (down_stage) * 8);
                    down_stage += 1;
                    if (down_stage == 3) { down_stage = 0; _phase_down_free_1 ^= 1; _phase_down_full ^= 1; }
                }
            }
        }
    // ---- Role: consumer ----
    } else if (warp >= 2 && warp <= 5) {
        { // consumer_main
            int plan_extent_c = num_tokens_post_padded[0];
            unsigned int _phase_up_ready = 0;
            unsigned int _phase_down_ready = 0;
            if (plan_extent_c > blockIdx.x * 8) {
                int route_work_c = blockIdx.x;
                int intermediate_blocks_c = gridDim.y;
                int intermediate_block_c = blockIdx.y;
                int subtiles_per_route_block_c = route_block_m / 8;
                int route_block_c = route_work_c / subtiles_per_route_block_c;
                int route_subtile_c = route_work_c % subtiles_per_route_block_c;
                int route_base_c = route_block_c * route_block_m + route_subtile_c * 8;
                int expert_c = expert_ids[route_block_c];
                int k_blocks_c = K / 128;
                const int consumer_warp = warp % 4;
                const int consumer_tid = consumer_warp * 32 + lane;
                const int physical_row = consumer_warp * 32 + lane;
                const int scale_row = physical_row / 8 % 2;
                int lane_pair = M * top_k;
                int lane_token = M - 1;
                float lane_route_weight = 0.0f;
                if (lane < 8) {
                    lane_pair = sorted_token_ids[route_base_c + lane];
                    int _min_8 = ((lane_pair / top_k) < (M - 1) ? (lane_pair / top_k) : (M - 1));
                    lane_token = _min_8;
                    if (lane_pair < M * top_k) {
                        lane_route_weight = topk_weights[lane_pair];
                    }
                }
                int route_pairs[8];
                float route_weights[8];
                #pragma unroll
                for (int token_slot_route = 0; token_slot_route < 8; token_slot_route++) {
                    int _shfl_0 = __shfl_sync(0xFFFFFFFF, lane_pair, token_slot_route);
                    route_pairs[token_slot_route] = _shfl_0;
                    float _shfl_1 = __shfl_sync(0xFFFFFFFF, lane_route_weight, token_slot_route);
                    route_weights[token_slot_route] = _shfl_1;
                }
                float panel0[8];
                float panel1[8];
                #pragma unroll
                for (int token_slot_init = 0; token_slot_init < 8; token_slot_init++) {
                    panel0[token_slot_init] = 0.0f;
                    panel1[token_slot_init] = 0.0f;
                }
                unsigned int up_stage_c = 0;
                #pragma unroll 1
                for (int kb_c = 0; kb_c < k_blocks_c; kb_c++) {
                    mbarrier_wait(up_ready_addr + (up_stage_c) * 8, _phase_up_ready);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    int row_base = consumer_warp * 32;
                    int panel0_addr = taddr + (unsigned int)(row_base << 16) + up_stage_c * 16;
                    int panel1_addr = panel0_addr + 8;
                    float _tmem_load_0[8];
                    tmem_ld_x8(&_tmem_load_0[0], panel0_addr);
                    asm volatile("tcgen05.wait::ld.sync.aligned;");
                    float _tmem_load_1[8];
                    tmem_ld_x8(&_tmem_load_1[0], panel1_addr);
                    asm volatile("tcgen05.wait::ld.sync.aligned;");
                    float wscale_lane = 0.0f;
                    if (lane < 2) {
                        wscale_lane = w1_scale[(expert_c * intermediate_blocks_c * 2 + intermediate_block_c * 2 + lane) * k_blocks_c + kb_c];
                    }
                    float _shfl_2 = __shfl_sync(0xFFFFFFFF, wscale_lane, scale_row);
                    float wscale = _shfl_2;
                    float xscale_lane = 0.0f;
                    if (lane < 8) {
                        xscale_lane = x_scale[lane_token * k_blocks_c + kb_c];
                    }
                    #pragma unroll
                    for (int token_slot_acc = 0; token_slot_acc < 8; token_slot_acc++) {
                        float _shfl_3 = __shfl_sync(0xFFFFFFFF, xscale_lane, token_slot_acc);
                        float xscale = _shfl_3;
                        float scale = xscale * wscale;
                        panel0[token_slot_acc] = panel0[token_slot_acc] + _tmem_load_0[token_slot_acc] * scale;
                        panel1[token_slot_acc] = panel1[token_slot_acc] + _tmem_load_1[token_slot_acc] * scale;
                    }
                    if (elect_sync()) {
                        mbarrier_arrive(up_free_addr + (up_stage_c) * 8);
                    }
                    up_stage_c += 1;
                    if (up_stage_c == 3) { up_stage_c = 0; _phase_up_ready ^= 1; }
                }
                if (consumer_tid < 8) {
                    smem_amax[consumer_tid] = 0;
                }
                asm volatile("barrier.sync 15, %0;" :: "r"(128));
                float act0[8];
                float act1[8];
                bool gate_lane = lane % 16 < 8;
                #pragma unroll
                for (int token_slot_act = 0; token_slot_act < 8; token_slot_act++) {
                    float _shfl_xor_0 = __shfl_xor_sync(0xFFFFFFFF, panel0[token_slot_act], 8);
                    float peer0 = _shfl_xor_0;
                    float _shfl_xor_1 = __shfl_xor_sync(0xFFFFFFFF, panel1[token_slot_act], 8);
                    float peer1 = _shfl_xor_1;
                    float gate0 = panel0[token_slot_act];
                    float gate1 = panel1[token_slot_act];
                    float _expf_0 = __expf(-gate0);
                    float sig0 = 1.0f / (1.0f + _expf_0);
                    float _expf_1 = __expf(-gate1);
                    float sig1 = 1.0f / (1.0f + _expf_1);
                    act0[token_slot_act] = gate0 * sig0 * peer0;
                    act1[token_slot_act] = gate1 * sig1 * peer1;
                    if (gate_lane) {
                        float _fabs_0 = fabsf(act0[token_slot_act]);
                        float abs0 = _fabs_0;
                        float _fabs_1 = fabsf(act1[token_slot_act]);
                        float abs1 = _fabs_1;
                        float _max_0 = max_noftz(abs0, abs1);
                        float local_max = _max_0;
                        uint32_t _amf_u_0 = __float_as_uint(local_max);
                        uint32_t _amf_mask_0 = -int32_t(_amf_u_0 >> 31) | 0x80000000u;
                        unsigned int _amf_enc_0 = _amf_u_0 ^ _amf_mask_0;
                        atomicMax(&smem_amax[token_slot_act], _amf_enc_0);
                    }
                }
                asm volatile("barrier.sync 15, %0;" :: "r"(128));
                if (consumer_tid < 8) {
                    uint32_t _amf_u_1 = smem_amax[consumer_tid];
                    uint32_t _amf_mask_1 = ((_amf_u_1 >> 31) - 1u) | 0x80000000u;
                    float _amf_dec_0 = __uint_as_float(_amf_u_1 ^ _amf_mask_1);
                    smem_act_scale[consumer_tid] = _amf_dec_0 / 448.0f;
                }
                asm volatile("barrier.sync 15, %0;" :: "r"(128));
                const int feature_in_half = physical_row / 16 * 8 + physical_row % 8;
                bool even_feature_lane = gate_lane && lane % 2 == 0;
                #pragma unroll
                for (int token_slot_quant = 0; token_slot_quant < 8; token_slot_quant++) {
                    float inv_scale = 1.0f / smem_act_scale[token_slot_quant];
                    float _shfl_xor_2 = __shfl_xor_sync(0xFFFFFFFF, act0[token_slot_quant], 1);
                    float peer_feature0 = _shfl_xor_2;
                    float _shfl_xor_3 = __shfl_xor_sync(0xFFFFFFFF, act1[token_slot_quant], 1);
                    float peer_feature1 = _shfl_xor_3;
                    if (even_feature_lane) {
                        {
                            uint16_t _fp8_pair_1407612528;
                            asm("cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;"
                                : "=h"(_fp8_pair_1407612528) : "f"(0.0f), "f"(act0[token_slot_quant] * inv_scale));
                            uint32_t _byte_1407612528 = (uint32_t)(_fp8_pair_1407612528 & 0xFF);
                            uint32_t _addr_1407612528 = static_cast<uint32_t>((smem_act_addr + (unsigned int)(token_slot_quant * 128 + feature_in_half ^ (token_slot_quant * 128 + feature_in_half >> 7 & 7) << 4)));
                            asm volatile("st.shared.u8 [%0], %1;" :: "r"(_addr_1407612528), "r"(_byte_1407612528) : "memory");
                        }
                        {
                            uint16_t _fp8_pair_1407613008;
                            asm("cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;"
                                : "=h"(_fp8_pair_1407613008) : "f"(0.0f), "f"(peer_feature0 * inv_scale));
                            uint32_t _byte_1407613008 = (uint32_t)(_fp8_pair_1407613008 & 0xFF);
                            uint32_t _addr_1407613008 = static_cast<uint32_t>((smem_act_addr + (unsigned int)(token_slot_quant * 128 + (feature_in_half + 1) ^ (token_slot_quant * 128 + (feature_in_half + 1) >> 7 & 7) << 4)));
                            asm volatile("st.shared.u8 [%0], %1;" :: "r"(_addr_1407613008), "r"(_byte_1407613008) : "memory");
                        }
                        {
                            uint16_t _fp8_pair_1407613152;
                            asm("cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;"
                                : "=h"(_fp8_pair_1407613152) : "f"(0.0f), "f"(act1[token_slot_quant] * inv_scale));
                            uint32_t _byte_1407613152 = (uint32_t)(_fp8_pair_1407613152 & 0xFF);
                            uint32_t _addr_1407613152 = static_cast<uint32_t>((smem_act_addr + (unsigned int)(token_slot_quant * 128 + (64 + feature_in_half) ^ (token_slot_quant * 128 + (64 + feature_in_half) >> 7 & 7) << 4)));
                            asm volatile("st.shared.u8 [%0], %1;" :: "r"(_addr_1407613152), "r"(_byte_1407613152) : "memory");
                        }
                        {
                            uint16_t _fp8_pair_1407613296;
                            asm("cvt.rn.satfinite.e4m3x2.f32 %0, %1, %2;"
                                : "=h"(_fp8_pair_1407613296) : "f"(0.0f), "f"(peer_feature1 * inv_scale));
                            uint32_t _byte_1407613296 = (uint32_t)(_fp8_pair_1407613296 & 0xFF);
                            uint32_t _addr_1407613296 = static_cast<uint32_t>((smem_act_addr + (unsigned int)(token_slot_quant * 128 + (64 + feature_in_half + 1) ^ (token_slot_quant * 128 + (64 + feature_in_half + 1) >> 7 & 7) << 4)));
                            asm volatile("st.shared.u8 [%0], %1;" :: "r"(_addr_1407613296), "r"(_byte_1407613296) : "memory");
                        }
                    }
                }
                asm volatile("fence.proxy.async.shared::cta;" ::: "memory");
                asm volatile("barrier.sync 15, %0;" :: "r"(128));
                asm volatile("barrier.sync 14, %0;" :: "r"(192));
                int out_blocks_c = K / 128;
                unsigned int down_stage_c = 0;
                #pragma unroll 1
                for (int ob_c = 0; ob_c < out_blocks_c; ob_c++) {
                    mbarrier_wait(down_ready_addr + (down_stage_c) * 8, _phase_down_ready);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    int down_addr = taddr + 48 + (unsigned int)(consumer_warp * 32 << 16) + down_stage_c * 8;
                    float _tmem_load_2[8];
                    tmem_ld_x8(&_tmem_load_2[0], down_addr);
                    asm volatile("tcgen05.wait::ld.sync.aligned;");
                    float w2s = w2_scale[(expert_c * out_blocks_c + ob_c) * intermediate_blocks_c + intermediate_block_c];
                    #pragma unroll
                    for (int token_slot_out = 0; token_slot_out < 8; token_slot_out++) {
                        int pair_out = route_pairs[token_slot_out];
                        bool valid_out = pair_out < M * top_k;
                        float route_weight = 0.0f;
                        if (valid_out) {
                            route_weight = route_weights[token_slot_out];
                        }
                        float out_scale = smem_act_scale[token_slot_out] * w2s * route_weight * scaling_factor;
                        smem_out[token_slot_out * 128 + physical_row] = _tmem_load_2[token_slot_out] * out_scale;
                    }
                    asm volatile("fence.proxy.async.shared::cta;" ::: "memory");
                    asm volatile("barrier.sync 15, %0;" :: "r"(128));
                    if (warp == 2) {
                        if (elect_sync()) {
                            #pragma unroll
                            for (int token_slot_reduce = 0; token_slot_reduce < 8; token_slot_reduce++) {
                                int pair_reduce = route_pairs[token_slot_reduce];
                                if (pair_reduce < M * top_k) {
                                    int token_reduce = pair_reduce / top_k;
                                    {
                                        void* _cpred_dst_2 = reinterpret_cast<void*>(out + (token_reduce * K + ob_c * 128));
                                        asm volatile("cp.reduce.async.bulk.global.shared::cta.bulk_group.add.noftz.bf16"
                                            " [%0], [%1], %2;"
                                            :: "l"(_cpred_dst_2), "r"(smem_out_addr + (unsigned int)(token_slot_reduce * 128 * 2)), "r"((uint32_t)(256))
                                            : "memory");
                                    }
                                }
                            }
                            asm volatile("cp.async.bulk.commit_group;");
                            asm volatile("cp.async.bulk.wait_group 0;");
                        }
                    }
                    asm volatile("barrier.sync 15, %0;" :: "r"(128));
                    if (elect_sync()) {
                        mbarrier_arrive(down_free_addr + (down_stage_c) * 8);
                    }
                    down_stage_c += 1;
                    if (down_stage_c == 3) { down_stage_c = 0; _phase_down_ready ^= 1; }
                }
            }
        }
    }

    // Cleanup
    __syncthreads(); // barrier before TMEM dealloc

    if (warp == 0) {
        asm volatile("tcgen05.dealloc.cta_group::1.sync.aligned.b32 %0, %1;" :: "r"(tmem_addr_storage[0]), "r"(128));
        asm volatile("tcgen05.relinquish_alloc_permit.cta_group::1.sync.aligned;");
    }
}

} // extern "C"

// End of generated section: capture the launch metadata, then unscope the
// generated macros.
namespace flashinfer {
namespace alphamoe_sm100 {
constexpr int kGeneratedThreads = THREADS;
constexpr int kGeneratedSmemTotal = SMEM_TOTAL;
}  // namespace alphamoe_sm100
}  // namespace flashinfer
#undef LOOM_INF
#undef NUM_DOWN_PIPE_STAGES
#undef NUM_UP_PIPE_STAGES
#undef SMEM_SMEM_ACT_OFF
#undef SMEM_SMEM_ACT_SCALE_OFF
#undef SMEM_SMEM_ACT_SCALE_STAGE_BYTES
#undef SMEM_SMEM_ACT_SCALE_STRIDE
#undef SMEM_SMEM_ACT_STAGE_BYTES
#undef SMEM_SMEM_ACT_STRIDE
#undef SMEM_SMEM_AMAX_OFF
#undef SMEM_SMEM_AMAX_STAGE_BYTES
#undef SMEM_SMEM_AMAX_STRIDE
#undef SMEM_SMEM_OUT_OFF
#undef SMEM_SMEM_OUT_STAGE_BYTES
#undef SMEM_SMEM_OUT_STRIDE
#undef SMEM_SMEM_W1_OFF
#undef SMEM_SMEM_W1_STAGE_BYTES
#undef SMEM_SMEM_W1_STRIDE
#undef SMEM_SMEM_W2_OFF
#undef SMEM_SMEM_W2_STAGE_BYTES
#undef SMEM_SMEM_W2_STRIDE
#undef SMEM_SMEM_X_OFF
#undef SMEM_SMEM_X_STAGE_BYTES
#undef SMEM_SMEM_X_STRIDE
#undef SMEM_TOTAL
#undef THREADS
#undef TMEM_DOWN_ACC_OFFSET
#undef TMEM_NCOLS
#undef TMEM_UP_ACC_OFFSET

// clang-format on

namespace flashinfer {
namespace alphamoe_sm100 {

using tvm::ffi::TensorView;

// Fixed geometry of the generated schedule. The kernel owns one 8-row route
// subtile x one 128-wide intermediate block per CTA; gate/up weight rows are
// consumed as two 128-row TMA boxes (256 interleaved rows) per intermediate
// block, and every FP8 scale is a 128-group block scale.
constexpr int kThreads = kGeneratedThreads;
constexpr int kSmemTotal = kGeneratedSmemTotal;
constexpr int kRouteSubtile = 8;    // route rows owned by one CTA
constexpr int kGroup = 128;         // FP8 scale group / TMA box edge
constexpr int kRowsPerInter = 256;  // interleaved gate+up rows per 128 intermediate columns

struct ProblemDims {
  int m;                     // number of tokens
  int k;                     // hidden size
  int n;                     // gate+up rows per expert (2 * intermediate)
  int intermediate;          // n / 2
  int top_k;                 // routes per token
  int block_m;               // routing-plan block size (route_block_m)
  int64_t num_route_blocks;  // expert_ids.numel()
};

inline void CheckCuda(cudaError_t status, const char* operation) {
  TVM_FFI_ICHECK(status == cudaSuccess) << operation << " failed: " << cudaGetErrorString(status);
}

inline void CheckSm100Family(int device_id) {
  int major = 0;
  int minor = 0;
  CheckCuda(cudaDeviceGetAttribute(&major, cudaDevAttrComputeCapabilityMajor, device_id),
            "cudaDeviceGetAttribute(compute capability major)");
  CheckCuda(cudaDeviceGetAttribute(&minor, cudaDevAttrComputeCapabilityMinor, device_id),
            "cudaDeviceGetAttribute(compute capability minor)");
  TVM_FFI_ICHECK(major == 10 && (minor == 0 || minor == 3))
      << "alphamoe_sm100 requires an SM100/SM103 (B200/B300 class) device, got sm_" << major
      << minor;
}

inline void CheckDtypeIs(const TensorView& t, DLDataType want, const char* name,
                         const char* want_name) {
  const DLDataType d = t.dtype();
  TVM_FFI_ICHECK(d.code == want.code && d.bits == want.bits && d.lanes == want.lanes)
      << name << " must be " << want_name << ", got (code=" << int(d.code)
      << ", bits=" << int(d.bits) << ", lanes=" << int(d.lanes) << ")";
}

inline void CheckCudaTensor(const TensorView& t, DLDataType want, int ndim, bool contiguous,
                            const char* name, const char* want_name) {
  TVM_FFI_ICHECK(t.device().device_type == kDLCUDA) << name << " must be a CUDA tensor";
  TVM_FFI_ICHECK(t.ndim() == ndim) << name << " must be " << ndim << "D, got ndim=" << t.ndim();
  if (contiguous) {
    TVM_FFI_ICHECK(t.IsContiguous()) << name << " must be contiguous";
  }
  CheckDtypeIs(t, want, name, want_name);
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)]. (Verbatim from the Loom host
// shim; a no-op for the 2D hidden_states tensor.)
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  TVM_FFI_ICHECK(trailing > 0 && t.ndim() >= trailing)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = static_cast<int>(t.ndim()) - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  TVM_FFI_ICHECK(step > 0) << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      TVM_FFI_ICHECK(t.stride(axis) == expected)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis) << ", expected "
          << expected;
    }
  }
}

// 2D TMA descriptor for hidden_states (the shim's buffer 'x') —
// field-for-field the descriptor the Loom host shim encodes: raw UINT8 view,
// box (128, 1) for the gather4 row loads, 128B swizzle, no L2 promotion, no
// OOB fill. Only the innermost stride must be 1; the row stride may exceed K
// (row-sliced activations are valid).
inline CUtensorMap EncodeHiddenStatesTma(const TensorView& t) {
  TVM_FFI_ICHECK(t.ndim() >= 2) << "TMA source 'hidden_states' must have at least 2 dimensions, "
                                   "got ndim="
                                << t.ndim();
  TVM_FFI_ICHECK(t.stride(-1) == 1)
      << "TMA source 'hidden_states' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  TVM_FFI_ICHECK(d1 > 0) << "TMA source 'hidden_states' trailing dims must be positive";
  int64_t outer1 = t.numel() / (d1);
  CheckDenseLeadingFold(t, 1, "hidden_states");
  int64_t s2 = t.stride(t.ndim() - 2) * 1;
  TVM_FFI_ICHECK(s2 > 0) << "TMA source 'hidden_states' physical strides must be positive";
  uint64_t global_dim[2] = {(uint64_t)(d1), (uint64_t)(outer1)};
  TVM_FFI_ICHECK(global_dim[0] > 0 && global_dim[1] > 0)
      << "TMA descriptor for 'hidden_states' resolved a non-positive global dim";
  TVM_FFI_ICHECK(128u <= global_dim[0] && 1u <= global_dim[1])
      << "TMA box (128, 1) exceeds resolved global dims for 'hidden_states'";
  uint64_t global_strides[1] = {
      (uint64_t)((s2 * 8) / 8),
  };
  uint32_t box_dim[2] = {128u, 1u};
  uint32_t elem_strides[2] = {1u, 1u};
  CUtensorMap tm;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_UINT8, 2, t.data_ptr(), global_dim, global_strides, box_dim,
      elem_strides, CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B,
      CU_TENSOR_MAP_L2_PROMOTION_NONE, CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_ICHECK(r == CUDA_SUCCESS)
      << "cuTensorMapEncodeTiled (2D, 'hidden_states') failed: CUresult=" << int(r);
  return tm;
}

// 4D TMA descriptor for gemm1_weights (the shim's buffer 'W1') — the logical
// (E, N, K) tensor is presented to TMA as (128, N, K/128, E) so one box is a
// 128x128 K-major tile of interleaved gate/up rows.
inline CUtensorMap EncodeGemm1WeightsTma(const TensorView& t) {
  TVM_FFI_ICHECK(t.ndim() >= 2) << "TMA source 'gemm1_weights' must have at least 2 dimensions, "
                                   "got ndim="
                                << t.ndim();
  TVM_FFI_ICHECK(t.stride(-1) == 1)
      << "TMA source 'gemm1_weights' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  TVM_FFI_ICHECK(d1 > 0 && d2 > 0) << "TMA source 'gemm1_weights' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  TVM_FFI_ICHECK(d1 % 128 == 0) << "TMA source 'gemm1_weights' extent " << d1
                                << " must divide exactly by " << 128;
  uint64_t global_dim[4] = {(uint64_t)(128), (uint64_t)(d2), (uint64_t)((d1 / 128)),
                            (uint64_t)(outer2)};
  TVM_FFI_ICHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0 && global_dim[3] > 0)
      << "TMA descriptor for 'gemm1_weights' resolved a non-positive global dim";
  TVM_FFI_ICHECK(128u <= global_dim[0] && 128u <= global_dim[1] && 1u <= global_dim[2] &&
                 1u <= global_dim[3])
      << "TMA box (128, 128, 1, 1) exceeds resolved global dims for 'gemm1_weights'";
  uint64_t global_strides[3] = {
      (uint64_t)((d1 * 8) / 8),
      (uint64_t)((128 * 8) / 8),
      (uint64_t)(((d2 * d1) * 8) / 8),
  };
  uint32_t box_dim[4] = {128u, 128u, 1u, 1u};
  uint32_t elem_strides[4] = {1u, 1u, 1u, 1u};
  CUtensorMap tm;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_UINT8, 4, t.data_ptr(), global_dim, global_strides, box_dim,
      elem_strides, CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B,
      CU_TENSOR_MAP_L2_PROMOTION_NONE, CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_ICHECK(r == CUDA_SUCCESS)
      << "cuTensorMapEncodeTiled (4D, 'gemm1_weights') failed: CUresult=" << int(r);
  return tm;
}

// 3D TMA descriptor for gemm2_weights (the shim's buffer 'W2') — the logical
// (E, K, N/2) tensor maps directly to (N/2, K, E) with 128x128 boxes.
inline CUtensorMap EncodeGemm2WeightsTma(const TensorView& t) {
  TVM_FFI_ICHECK(t.ndim() >= 2) << "TMA source 'gemm2_weights' must have at least 2 dimensions, "
                                   "got ndim="
                                << t.ndim();
  TVM_FFI_ICHECK(t.stride(-1) == 1)
      << "TMA source 'gemm2_weights' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  TVM_FFI_ICHECK(d1 > 0 && d2 > 0) << "TMA source 'gemm2_weights' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  TVM_FFI_ICHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0)
      << "TMA descriptor for 'gemm2_weights' resolved a non-positive global dim";
  TVM_FFI_ICHECK(128u <= global_dim[0] && 128u <= global_dim[1] && 1u <= global_dim[2])
      << "TMA box (128, 128, 1) exceeds resolved global dims for 'gemm2_weights'";
  uint64_t global_strides[2] = {
      (uint64_t)((d1 * 8) / 8),
      (uint64_t)(((d2 * d1) * 8) / 8),
  };
  uint32_t box_dim[3] = {128u, 128u, 1u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_UINT8, 3, t.data_ptr(), global_dim, global_strides, box_dim,
      elem_strides, CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B,
      CU_TENSOR_MAP_L2_PROMOTION_NONE, CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  TVM_FFI_ICHECK(r == CUDA_SUCCESS)
      << "cuTensorMapEncodeTiled (3D, 'gemm2_weights') failed: CUresult=" << int(r);
  return tm;
}

// Validate the public contract. Dtype/contiguity requirements mirror the Loom
// host shim (the shim types FP8 tensors as raw uint8 views; here they carry
// their real float8_e4m3fn dtype); the shape/divisibility constraints are the
// generated schedule's coverage guards: K and N/2 positive multiples of 128
// (N % 256 == 0), block_m a positive multiple of the 8-row route subtile.
inline ProblemDims CheckInputs(
    const TensorView& hidden_states, const TensorView& hidden_states_scale,
    const TensorView& gemm1_weights, const TensorView& gemm1_weights_scale,
    const TensorView& gemm2_weights, const TensorView& gemm2_weights_scale,
    const TensorView& sorted_token_ids, const TensorView& expert_ids,
    const TensorView& num_tokens_post_padded, const TensorView& topk_weights, const TensorView& out,
    int64_t top_k, int64_t block_m) {
  // hidden_states deliberately skips the contiguity check: the TMA descriptor
  // reads the row stride, so row-sliced activations are valid.
  CheckCudaTensor(hidden_states, dl_float8_e4m3fn, 2, /*contiguous=*/false, "hidden_states",
                  "float8_e4m3fn");
  CheckCudaTensor(hidden_states_scale, dl_float32, 2, /*contiguous=*/true, "hidden_states_scale",
                  "float32");
  CheckCudaTensor(gemm1_weights, dl_float8_e4m3fn, 3, /*contiguous=*/true, "gemm1_weights",
                  "float8_e4m3fn");
  CheckCudaTensor(gemm1_weights_scale, dl_float32, 3, /*contiguous=*/true, "gemm1_weights_scale",
                  "float32");
  CheckCudaTensor(gemm2_weights, dl_float8_e4m3fn, 3, /*contiguous=*/true, "gemm2_weights",
                  "float8_e4m3fn");
  CheckCudaTensor(gemm2_weights_scale, dl_float32, 3, /*contiguous=*/true, "gemm2_weights_scale",
                  "float32");
  CheckCudaTensor(sorted_token_ids, dl_int32, 1, /*contiguous=*/true, "sorted_token_ids", "int32");
  CheckCudaTensor(expert_ids, dl_int32, 1, /*contiguous=*/true, "expert_ids", "int32");
  CheckCudaTensor(num_tokens_post_padded, dl_int32, 1, /*contiguous=*/true,
                  "num_tokens_post_padded", "int32");
  CheckCudaTensor(topk_weights, dl_float32, 2, /*contiguous=*/true, "topk_weights", "float32");
  CheckCudaTensor(out, dl_bfloat16, 2, /*contiguous=*/true, "out", "bfloat16");

  const int device_id = hidden_states.device().device_id;
  const TensorView* views[] = {&hidden_states_scale, &gemm1_weights,
                               &gemm1_weights_scale, &gemm2_weights,
                               &gemm2_weights_scale, &sorted_token_ids,
                               &expert_ids,          &num_tokens_post_padded,
                               &topk_weights,        &out};
  for (const TensorView* view : views) {
    TVM_FFI_ICHECK(view->device().device_id == device_id)
        << "all alphamoe_sm100 tensors must live on the same CUDA device";
  }
  CheckSm100Family(device_id);

  const int64_t m = hidden_states.size(0);
  const int64_t k = hidden_states.size(1);
  const int64_t num_experts = gemm1_weights.size(0);
  const int64_t n = gemm1_weights.size(1);
  TVM_FFI_ICHECK(m > 0) << "hidden_states must have at least one token, got M=" << m;
  TVM_FFI_ICHECK(k >= kGroup && k % kGroup == 0)
      << "K (" << k << ") must be a positive multiple of " << kGroup << " and at least " << kGroup;
  TVM_FFI_ICHECK(n >= kRowsPerInter && n % kRowsPerInter == 0)
      << "gemm1_weights.shape[1] (" << n << ") must be a positive multiple of " << kRowsPerInter
      << " (gate+up rows per 128-wide intermediate block)";
  TVM_FFI_ICHECK(gemm1_weights.size(2) == k)
      << "gemm1_weights.shape[2] (" << gemm1_weights.size(2) << ") must equal K (" << k << ")";
  const int64_t intermediate = n / 2;

  TVM_FFI_ICHECK(hidden_states_scale.size(0) == m && hidden_states_scale.size(1) == k / kGroup)
      << "hidden_states_scale must have shape (" << m << ", " << k / kGroup << "), got ("
      << hidden_states_scale.size(0) << ", " << hidden_states_scale.size(1) << ")";
  TVM_FFI_ICHECK(gemm1_weights_scale.size(0) == num_experts &&
                 gemm1_weights_scale.size(1) == n / kGroup &&
                 gemm1_weights_scale.size(2) == k / kGroup)
      << "gemm1_weights_scale must have shape (" << num_experts << ", " << n / kGroup << ", "
      << k / kGroup << "), got (" << gemm1_weights_scale.size(0) << ", "
      << gemm1_weights_scale.size(1) << ", " << gemm1_weights_scale.size(2) << ")";
  TVM_FFI_ICHECK(gemm2_weights.size(0) == num_experts && gemm2_weights.size(1) == k &&
                 gemm2_weights.size(2) == intermediate)
      << "gemm2_weights must have shape (" << num_experts << ", " << k << ", " << intermediate
      << "), got (" << gemm2_weights.size(0) << ", " << gemm2_weights.size(1) << ", "
      << gemm2_weights.size(2) << ")";
  TVM_FFI_ICHECK(gemm2_weights_scale.size(0) == num_experts &&
                 gemm2_weights_scale.size(1) == k / kGroup &&
                 gemm2_weights_scale.size(2) == intermediate / kGroup)
      << "gemm2_weights_scale must have shape (" << num_experts << ", " << k / kGroup << ", "
      << intermediate / kGroup << "), got (" << gemm2_weights_scale.size(0) << ", "
      << gemm2_weights_scale.size(1) << ", " << gemm2_weights_scale.size(2) << ")";

  TVM_FFI_ICHECK(top_k >= 1) << "top_k must be positive, got " << top_k;
  TVM_FFI_ICHECK(block_m >= kRouteSubtile && block_m % kRouteSubtile == 0)
      << "block_m (" << block_m << ") must be a positive multiple of " << kRouteSubtile;
  TVM_FFI_ICHECK(num_tokens_post_padded.numel() == 1)
      << "num_tokens_post_padded must be a device int32 tensor with exactly one element, got "
      << num_tokens_post_padded.numel();
  TVM_FFI_ICHECK(expert_ids.numel() > 0) << "expert_ids must not be empty";
  TVM_FFI_ICHECK(topk_weights.size(0) == m && topk_weights.size(1) == top_k)
      << "topk_weights must have shape (" << m << ", " << top_k << "), got ("
      << topk_weights.size(0) << ", " << topk_weights.size(1) << ")";
  TVM_FFI_ICHECK(out.size(0) == m && out.size(1) == k)
      << "out must have shape (" << m << ", " << k << "), got (" << out.size(0) << ", "
      << out.size(1) << ")";

  // The kernel receives M/K/top_k/block_m as i32 scalars and uses M * top_k
  // as the routing-plan padding sentinel; all must fit in i32.
  TVM_FFI_ICHECK(m <= std::numeric_limits<int>::max() && k <= std::numeric_limits<int>::max() &&
                 m * top_k <= std::numeric_limits<int>::max())
      << "problem dimensions exceed the kernel's i32 scalar range";

  return ProblemDims{static_cast<int>(m),     static_cast<int>(k),
                     static_cast<int>(n),     static_cast<int>(intermediate),
                     static_cast<int>(top_k), static_cast<int>(block_m),
                     expert_ids.numel()};
}

// Launch the generated kernel. TMap is the generated TU's by-value
// __grid_constant__ tensor-map parameter type (loomCUtensorMap); it is
// layout-compatible with CUtensorMap. The launch configuration mirrors the
// Loom host shim: block (192, 1, 1), 154752 B dynamic smem, and the grid the
// Loom launcher passes — one CTA per (8-row route subtile, 128-wide
// intermediate block): grid = (expert_ids.numel() * block_m / 8, N / 256, 1).
template <typename TMap>
inline void LaunchKernel(void (*kernel)(TMap, TMap, float*, float*, TMap, float*, int*, int*, int*,
                                        float*, __nv_bfloat16*, int, int, int, int, float),
                         const CUtensorMap& hidden_states_map, const CUtensorMap& gemm1_map,
                         const CUtensorMap& gemm2_map, float* hidden_states_scale,
                         float* gemm1_weights_scale, float* gemm2_weights_scale,
                         int* sorted_token_ids, int* expert_ids, int* num_tokens_post_padded,
                         float* topk_weights, __nv_bfloat16* out, const ProblemDims& dims,
                         float scaling_factor, cudaStream_t stream) {
  static_assert(sizeof(TMap) == sizeof(CUtensorMap),
                "generated tensor-map parameter must be layout-compatible with CUtensorMap");
  TMap x_param, w1_param, w2_param;
  std::memcpy(&x_param, &hidden_states_map, sizeof(TMap));
  std::memcpy(&w1_param, &gemm1_map, sizeof(TMap));
  std::memcpy(&w2_param, &gemm2_map, sizeof(TMap));

  CheckCuda(cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, kSmemTotal),
            "cudaFuncSetAttribute(alphamoe_sm100 dynamic smem)");

  const int64_t grid_x = dims.num_route_blocks * (dims.block_m / kRouteSubtile);
  const int64_t grid_y = dims.n / kRowsPerInter;
  TVM_FFI_ICHECK(grid_x > 0 && grid_x <= std::numeric_limits<int>::max())
      << "launch grid.x (" << grid_x << ") out of range";
  TVM_FFI_ICHECK(grid_y > 0 && grid_y <= 65535) << "launch grid.y (" << grid_y << ") out of range";
  const dim3 grid(static_cast<unsigned int>(grid_x), static_cast<unsigned int>(grid_y), 1u);
  const dim3 block(kThreads);

  kernel<<<grid, block, kSmemTotal, stream>>>(
      x_param, w1_param, hidden_states_scale, gemm1_weights_scale, w2_param, gemm2_weights_scale,
      sorted_token_ids, expert_ids, num_tokens_post_padded, topk_weights, out, dims.m, dims.k,
      dims.top_k, dims.block_m, scaling_factor);
  CheckCuda(cudaGetLastError(), "alphamoe_sm100 kernel launch");
}

}  // namespace alphamoe_sm100
}  // namespace flashinfer

namespace flashinfer {
namespace alphamoe_sm100 {

// Fused W8A8 block-scale MoE (gate/up + SwiGLU + per-token FP8 requant +
// down) over a moe_align_block_size routing plan. `out` is a caller-owned
// BF16 accumulator: the kernel asynchronously reduce-adds every routed
// expert contribution into it, so it must be zeroed (or hold the intended
// initial values) before launch.
void Run(TensorView hidden_states, TensorView hidden_states_scale, TensorView gemm1_weights,
         TensorView gemm1_weights_scale, TensorView gemm2_weights, TensorView gemm2_weights_scale,
         TensorView sorted_token_ids, TensorView expert_ids, TensorView num_tokens_post_padded,
         TensorView topk_weights, TensorView out, int64_t top_k, int64_t block_m,
         double routed_scaling_factor) {
  const ProblemDims dims =
      CheckInputs(hidden_states, hidden_states_scale, gemm1_weights, gemm1_weights_scale,
                  gemm2_weights, gemm2_weights_scale, sorted_token_ids, expert_ids,
                  num_tokens_post_padded, topk_weights, out, top_k, block_m);
  const CUtensorMap hidden_states_map = EncodeHiddenStatesTma(hidden_states);
  const CUtensorMap gemm1_map = EncodeGemm1WeightsTma(gemm1_weights);
  const CUtensorMap gemm2_map = EncodeGemm2WeightsTma(gemm2_weights);
  const cudaStream_t stream = get_stream(hidden_states.device());
  LaunchKernel(&kernel_alpha_moe_w8a8_up_down, hidden_states_map, gemm1_map, gemm2_map,
               static_cast<float*>(hidden_states_scale.data_ptr()),
               static_cast<float*>(gemm1_weights_scale.data_ptr()),
               static_cast<float*>(gemm2_weights_scale.data_ptr()),
               static_cast<int*>(sorted_token_ids.data_ptr()),
               static_cast<int*>(expert_ids.data_ptr()),
               static_cast<int*>(num_tokens_post_padded.data_ptr()),
               static_cast<float*>(topk_weights.data_ptr()),
               reinterpret_cast<__nv_bfloat16*>(out.data_ptr()), dims,
               static_cast<float>(routed_scaling_factor), stream);
}

}  // namespace alphamoe_sm100
}  // namespace flashinfer

TVM_FFI_DLL_EXPORT_TYPED_FUNC(fp8_block_scale_aligned_moe_op, flashinfer::alphamoe_sm100::Run);
